EN ESTE NOTEBOOK:
- Hacemos clustering con K-prototypes (agrupa conjuntos de datos que contienen una mezcla de variables numéricas y categóricas nominales). Para ello, tratamos 'ant_obstetrico' y 'ant_medico' como nominales.
- Hacemos clustering con K-Medoids.
- Hacemos clustering con HDBSCAN con distancia Gower (agrupa puntos de datos basados en la densidad de su distribución).
- Hacemos la descripción de los grupos en función de las variables Ecocardiografía | TA, carótida y oftálmica | Analítica | Scores categóricos | Antecedentes

In [23]:
import pandas as pd
import numpy as np

# Obtención de los datos

## Datos para clustering

In [24]:
df = pd.read_csv('imputado.csv')

In [25]:
df.columns

Index(['Unnamed: 0', 'id', 'peso_ini_gest', 'peso_fin_gest',
       'aumento_peso_gest', 'talla', 'imc_ini_gest', 'peso_rn', 'apgar_1min',
       'apgar_5min', 'apgar_10min', 'eg_parto', 'valor_sflt1',
       'eg_deter_sflt1_plgf', 'tas_1tri', 'tad_1tri', 'edad_materna_gest',
       'eg_eco_1tri', 'valor_plgf', 'ratio_sflt1_plgf', 'nivel_estudios',
       'riesgo_pe_1tri', 'ant_medico', 'ant_obstetrico', 'covid',
       'edema_agudo_pulmon', 'hemorragia_pospart_transfusion',
       'ini_trabajo_parto_espontaneo', 'parto_previo_mayor37_pre',
       'estudio_inicial_Angiocor', 'estudio_inicial_BiSC',
       'estudio_inicial_EUROPE', 'estudio_inicial_Ninguno',
       'etnia_Asia_Oriental', 'etnia_Blanca', 'etnia_Latina', 'etnia_Mixto',
       'etnia_Negra', 'etnia_Sureste_asiatico', 'concepcion_Espontanea',
       'concepcion_FIV', 'concepcion_FIV_ovodonacion',
       'concepcion_Inseminacion', 'tipo_parto_Cesarea', 'tipo_parto_Eutocico',
       'tipo_parto_Instrumentado', 'sexo_rn_Masculino', 'tomo_Aspirina',
       'tomo_Heparina', 'tomo_Antihipertensivo', 'tomo_Ninguna',
       'trastorno_hipertensivo', 'comp_placentaria', 'comp_maternaGrave',
       'comp_metabolica'],
      dtype='object')

## Datos para descripción de los grupos

In [26]:
# Gestación y biomarcadores (hay que crear las variables MoM)
# El df que se usará para el clustering es df_modelo

def calcular_mom_variables(df):
    df = df.copy()
    # Definimos las condiciones basadas en 'eg_deter_sflt1_plgf'
    condiciones = [
        (df['eg_deter_sflt1_plgf'] >= 10) & (df['eg_deter_sflt1_plgf'] < 15), # 10 a 14.99
        (df['eg_deter_sflt1_plgf'] >= 15) & (df['eg_deter_sflt1_plgf'] < 20), # 15 a 19.99
        (df['eg_deter_sflt1_plgf'] >= 20) & (df['eg_deter_sflt1_plgf'] < 24),
        (df['eg_deter_sflt1_plgf'] >= 24) & (df['eg_deter_sflt1_plgf'] < 29),
        (df['eg_deter_sflt1_plgf'] >= 29) & (df['eg_deter_sflt1_plgf'] < 34),
        (df['eg_deter_sflt1_plgf'] >= 34) & (df['eg_deter_sflt1_plgf'] < 37),
        (df['eg_deter_sflt1_plgf'] >= 37)
]

    # Divisores para cada columna
    div_ratio = [24.8, 10.5, 4.92, 3.06, 3.75, 9.03, 19.6]
    div_sflt1 = [1328, 1355, 1299, 1355, 1742, 2552, 3485]
    div_plgf  = [52.6, 135, 264, 465, 471, 284, 191]

    # Aplicamos np.select para obtener el divisor correspondiente a cada fila
    # Si no cumple ninguna condición, devuelve NaN (np.nan)
    df['ratio_MoM'] = df['ratio_sflt1_plgf'] / np.select(condiciones, div_ratio, default=np.nan)
    df['sflt1_MoM'] = df['valor_sflt1'] / np.select(condiciones, div_sflt1, default=np.nan)
    df['plgf_MoM']  = df['valor_plgf'] / np.select(condiciones, div_plgf, default=np.nan)

    return df

df_modelo = calcular_mom_variables(df)

variables_a_borrar = ['ratio_sflt1_plgf', 'valor_sflt1', 'valor_plgf']
df_modelo = df_modelo.drop(columns=variables_a_borrar, errors='ignore')

In [27]:
# Ecocardiografía | TA, carótida y oftálmica | Analítica (df_comparacion)
df_clust2 = pd.read_csv('datos.csv')

In [28]:
# Scores categóricos (df_cat)

df_cat = pd.read_excel('variables_CARDIOMOM.xlsx')

scl_mapping = {
    'Nada': 0, 'Muy poco': 1, 'Poco': 2, 'Bastante': 3, 'Mucho': 4
}

# Funciones de categorización

def cat_regicor_dieta(score):
    if pd.isna(score): return np.nan
    if score < 23: return "Baja adherencia"
    elif 23 <= score <= 29: return "Adherencia moderada"
    else: return "Alta adherencia"

def cat_regicor_actividad(met):
    if pd.isna(met): return np.nan
    if met < 500: return "Actividad física baja"
    elif 500 <= met <= 1000: return "Actividad física moderada"
    else: return "Actividad física alta"

def cat_pss14(score):
    if pd.isna(score): return np.nan
    if score <= 13: return "Nivel de estrés bajo"
    elif 14 <= score <= 26: return "Nivel de estrés moderado"
    elif 27 <= score <= 40: return "Nivel de estrés alto"
    else: return "Nivel de estrés muy alto"

def cat_mfe30(score):
    if pd.isna(score): return np.nan
    if score < 8: return "Rendimiento de memoria óptimo"
    elif 9 <= score <= 35: return "Función normal (lapsus leves)"
    elif 36 <= score <= 50: return "Deterioro leve"
    else: return "Disfunción moderada-grave"

def cat_scl90r(t_score):
    if pd.isna(t_score): return np.nan
    if t_score >= 80: return "Patología severa"
    elif t_score >= 65: return "EN RIESGO"
    else: return "Normal / Sin riesgo"


df_cat['Cat_Dieta'] = df_cat['Score total'].apply(cat_regicor_dieta)
df_cat['Cat_Actividad'] = df_cat['Act física TOTAL (MET/semana)'].apply(cat_regicor_actividad)
df_cat['Cat_Estres'] = df_cat['Score'].apply(cat_pss14)
df_cat['Cat_Memoria'] = df_cat['Score.1'].apply(cat_mfe30)

# Procesamiento SCL-90-R
scl_items_cols = df_cat.loc[:, "Dolores de cabeza":"Pensar que en mi cabeza hay algo que no funciona bien"].columns
df_scl_numeric = df_cat[scl_items_cols].replace(scl_mapping).apply(pd.to_numeric, errors='coerce')
df_cat['SCL90_IGS_Raw'] = df_scl_numeric.mean(axis=1)

def calcular_t_score(row):
    raw = row['SCL90_IGS_Raw']
    if pd.isna(raw): return np.nan
    # Baremo Mujer (Media 0.17, DT 0.11) basado en el PDF
    return 50 + 10 * ((raw - 0.17) / 0.11)

df_cat['SCL90_T_Score'] = df_cat.apply(calcular_t_score, axis=1)
df_cat['Cat_SCL90R'] = df_cat['SCL90_T_Score'].apply(cat_scl90r)


cols_to_show = ['ID', 'Cat_Dieta', 'Cat_Actividad', 'Cat_Estres', 'Cat_Memoria', 'Cat_SCL90R']

print(df_cat[cols_to_show].head(20).to_string(index=False))

 ID           Cat_Dieta             Cat_Actividad               Cat_Estres                   Cat_Memoria          Cat_SCL90R
  1 Adherencia moderada     Actividad física alta     Nivel de estrés alto Función normal (lapsus leves)    Patología severa
  2 Adherencia moderada     Actividad física alta Nivel de estrés moderado Rendimiento de memoria óptimo    Patología severa
  3     Baja adherencia     Actividad física alta Nivel de estrés moderado                           NaN                 NaN
  4 Adherencia moderada                       NaN Nivel de estrés moderado                Deterioro leve    Patología severa
  5 Adherencia moderada                       NaN     Nivel de estrés alto Función normal (lapsus leves)    Patología severa
  6     Baja adherencia     Actividad física alta     Nivel de estrés alto                           NaN                 NaN
  7     Baja adherencia     Actividad física alta Nivel de estrés moderado                           NaN                 NaN
  8 Adherencia moderada     Actividad física alta Nivel de estrés muy alto Rendimiento de memoria óptimo    Patología severa
  9 Adherencia moderada     Actividad física alta Nivel de estrés moderado                           NaN                 NaN
 10 Adherencia moderada                       NaN Nivel de estrés moderado Función normal (lapsus leves)    Patología severa
 11 Adherencia moderada     Actividad física alta Nivel de estrés moderado Función normal (lapsus leves)    Patología severa
 12 Adherencia moderada     Actividad física alta Nivel de estrés moderado                           NaN                 NaN
 13 Adherencia moderada                       NaN Nivel de estrés moderado                Deterioro leve    Patología severa
 14 Adherencia moderada                       NaN Nivel de estrés moderado Rendimiento de memoria óptimo Normal / Sin riesgo
 15 Adherencia moderada     Actividad física alta     Nivel de estrés alto Función normal (lapsus leves)    Patología severa
 16 Adherencia moderada     Actividad física alta Nivel de estrés moderado                           NaN                 NaN
 17     Baja adherencia     Actividad física alta Nivel de estrés muy alto Función normal (lapsus leves)                 NaN
 18 Adherencia moderada     Actividad física alta     Nivel de estrés alto Función normal (lapsus leves)    Patología severa
 19 Adherencia moderada     Actividad física alta Nivel de estrés moderado                Deterioro leve    Patología severa
 20     Baja adherencia Actividad física moderada     Nivel de estrés alto     Disfunción moderada-grave                 NaN

/var/folders/h2/lk1h3scx0p3cs7sk_k_sxylh0000gn/T/ipykernel_12371/459520726.py:51: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_scl_numeric = df_cat[scl_items_cols].replace(scl_mapping).apply(pd.to_numeric, errors='coerce')

In [29]:
# Antecedentes (df_clust2n)
# Nota: las variables 'ant_medico' y 'ant_obstetrico' ya están como nominales

cols_ant_obstetrico = [
    'parto_previo_menor37_pre', 'aborto_menor20', 
    'ant_cir', 'ant_peg', 'ant_obito', 'ant_pe', 'ant_hellp'
]
# Calculamos la suma y convertimos a 1 si es >= 1
df_clust2['ant_obstetrico'] = (df_clust2[cols_ant_obstetrico].sum(axis=1) >= 1).astype(int)

cols_ant_medico = [
    'ant_cesarea', 'ant_diabetes_pregest', 'hta_pregest', 'sindr_antifosfolipido', 
    'enf_autoinm', 'fuma', 'alcohol', 'drogas'
]
# Calculamos la suma y convertimos a 1 si es >= 1
df_clust2['ant_medico'] = (df_clust2[cols_ant_medico].sum(axis=1) >= 1).astype(int)

# Trastorno hipertensivo: 1 si pe, sd_hellp o 'hipertension_gest' vs 0 si no tiene ninguna. 
cols_hipertension = ['pe', 'sd_hellp', 'hipertension_gest']
df_clust2['trastorno_hipertensivo'] = df_clust2[cols_hipertension].max(axis=1)

# Complicación placentaria: 'cir', 'peg', 'desprendimiento_placenta'
cols_placentaria = ['cir', 'peg', 'desprendimiento_placenta']
df_clust2['comp_placentaria'] = df_clust2[cols_placentaria].max(axis=1)

# Complicación materna grave: 'uci_materna_ucoi', 'hemocerebral_ictus', 'trombosis_venosa_prof'
cols_materna_grave = ['uci_materna_ucoi', 'hemocerebral_ictus', 'trombosis_venosa_prof']
df_clust2['comp_maternaGrave'] = df_clust2[cols_materna_grave].max(axis=1)

# Complicación metabólica: 'diabetes_gest', 'colestasis_intrahepatica'
cols_metabolica = ['diabetes_gest', 'colestasis_intrahepatica']
df_clust2['comp_metabolica'] = df_clust2[cols_metabolica].max(axis=1)

In [30]:
df_clust2['ant_medico'].unique()

array([0, 1])

In [31]:
df_clust2['ant_obstetrico'].unique()

array([0, 1])

# Clustering con K-prototypes (numéricas + categóricas)

Las variables consideradas en el clustering son ['peso_ini_gest', 'peso_fin_gest', 'aumento_peso_gest', 'talla', 'imc_ini_gest', 'peso_rn', 'apgar_1min', 'apgar_5min', 'apgar_10min', 'eg_parto', 'sflt1_MoM', 'tas_1tri', 'tad_1tri', 'edad_materna_gest', 'plgf_MoM', 'ratio_MoM', 'ant_obstetrico', 'ant_medico', 'trastorno_hipertensivo', 
'comp_placentaria', 'comp_maternaGrave', 'comp_metabolica']

In [32]:
pip install kmodes

Requirement already satisfied: kmodes in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.12.2)
Requirement already satisfied: numpy>=1.10.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kmodes) (1.26.4)
Requirement already satisfied: scikit-learn>=0.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kmodes) (1.7.2)
Requirement already satisfied: scipy>=0.13.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kmodes) (1.16.3)
Requirement already satisfied: joblib>=0.11 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from kmodes) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn>=0.22.0->kmodes) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [33]:
pip install gower

Requirement already satisfied: gower in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.1.2)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gower) (1.26.4)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from gower) (1.16.3)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [34]:
from kmodes.kprototypes import KPrototypes
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, davies_bouldin_score
import gower
import matplotlib.pyplot as plt

In [35]:
# Definición de variables
variables_numericas = [
    'peso_ini_gest', 'peso_fin_gest', 'aumento_peso_gest', 'talla', 'imc_ini_gest',
    'peso_rn', 'apgar_1min', 'apgar_5min', 'apgar_10min', 'eg_parto',
    'sflt1_MoM', 'tas_1tri', 'tad_1tri', 'edad_materna_gest', 'plgf_MoM', 'ratio_MoM'
]

variables_categoricas = [
    'ant_obstetrico', 'ant_medico', 'trastorno_hipertensivo',
    'comp_placentaria', 'comp_maternaGrave', 'comp_metabolica'
]

todas_variables = variables_numericas + variables_categoricas

# Candidatas (todas menos 'id')
candidatas_num = list(variables_numericas)
candidatas_cat = list(variables_categoricas)


# Función de evaluación MODIFICADA para devolver n
def evaluar_kproto(vars_num, vars_cat, k, df_modelo):
    todas = vars_num + vars_cat

    X_num_loc = StandardScaler().fit_transform(df_modelo[vars_num]) if vars_num else np.empty((len(df_modelo), 0))
    X_cat_loc = df_modelo[vars_cat].values.astype(str) if vars_cat else np.empty((len(df_modelo), 0))
    X_loc = np.concatenate([X_num_loc, X_cat_loc], axis=1)
    cat_cols_loc = list(range(len(vars_num), len(todas)))

    X_gow = df_modelo[todas].copy()
    if vars_cat:
        X_gow[vars_cat] = X_gow[vars_cat].astype(int)
    dist_loc = gower.gower_matrix(X_gow)

    kp = KPrototypes(n_clusters=k, init='Cao', n_init=3, random_state=42)
    labels = kp.fit_predict(X_loc, categorical=cat_cols_loc)
    
    # Calcular tamaños de los grupos
    counts = pd.Series(labels).value_counts().sort_index().tolist()
    
    sil = silhouette_score(dist_loc, labels, metric='precomputed')
    return sil, counts


# Forward selection para K-prototypes
def find_top3_kproto(df_modelo, k_range):
    all_k_results = []

    for k in k_range:
        print(f"\nBuscando mejores combinaciones para k={k}...")
        combinations_tested = []
        current_num = []
        current_cat = []
        remaining_num = list(candidatas_num)
        remaining_cat = list(candidatas_cat)

        while remaining_num or remaining_cat:
            step_scores = []

            # Probar añadir cada variable candidata (numérica o categórica)
            candidatas_paso = (
                [('num', v) for v in remaining_num] +
                [('cat', v) for v in remaining_cat]
            )

            for tipo, var in candidatas_paso:
                vars_num_tmp = current_num + ([var] if tipo == 'num' else [])
                vars_cat_tmp = current_cat + ([var] if tipo == 'cat' else [])

                # Necesitamos al menos 2 variables para calcular Silhouette
                if len(vars_num_tmp) + len(vars_cat_tmp) < 2:
                    step_scores.append((None, var, tipo))
                    continue

                try:
                    sil, counts = evaluar_kproto(vars_num_tmp, vars_cat_tmp, k, df_modelo)
                    combinations_tested.append({
                        'k': k,
                        'silhouette': sil,
                        'num_variables': len(vars_num_tmp) + len(vars_cat_tmp),
                        'variables': vars_num_tmp + vars_cat_tmp,
                        'n_grupos': counts # Guardamos los tamaños
                    })
                    step_scores.append((sil, var, tipo))
                except Exception:
                    step_scores.append((None, var, tipo))

            # Elegir la mejor variable del paso
            step_scores_validos = [(s, v, t) for s, v, t in step_scores if s is not None]

            if not step_scores_validos:
                tipo, var = candidatas_paso[0][0], candidatas_paso[0][1]
                if tipo == 'num':
                    current_num.append(var)
                    remaining_num.remove(var)
                else:
                    current_cat.append(var)
                    remaining_cat.remove(var)
                continue

            step_scores_validos.sort(key=lambda x: x[0], reverse=True)
            best_sil, best_var, best_tipo = step_scores_validos[0]

            if best_tipo == 'num':
                current_num.append(best_var)
                remaining_num.remove(best_var)
            else:
                current_cat.append(best_var)
                remaining_cat.remove(best_var)

            print(f"  Paso {len(current_num)+len(current_cat)}: +{best_var:<30} → Sil = {best_sil:.4f}")

        # Top 3 para este k
        if combinations_tested:
            df_k = pd.DataFrame(combinations_tested)
            top3 = df_k.sort_values('silhouette', ascending=False).head(3)
            all_k_results.append(top3)
            print(f"\n  Top 3 para k={k}:")
            for _, r in top3.iterrows():
                print(f"    Sil={r['silhouette']:.4f} | Grupos: {r['n_grupos']} | {r['num_variables']} vars: {r['variables']}")

    return pd.concat(all_k_results, ignore_index=True)


# Ejecutar
top3_results_mixto = find_top3_kproto(df_modelo, range(2, 6)) # Rango reducido para ejemplo

print("\n" + "="*70)
print("RESUMEN: Top 3 combinaciones por k")
print("="*70)
pd.set_option('display.max_colwidth', None)
display(top3_results_mixto[['k', 'silhouette', 'n_grupos', 'variables']])

Buscando mejores combinaciones para k=2...
  Paso 2: +ant_medico                     → Sil = 0.4497
  Paso 3: +apgar_10min                    → Sil = 0.6822
  Paso 4: +apgar_5min                     → Sil = 0.7149
  Paso 5: +apgar_1min                     → Sil = 0.7222
  Paso 6: +eg_parto                       → Sil = 0.7075
  Paso 7: +comp_maternaGrave              → Sil = 0.7057
  Paso 8: +peso_rn                        → Sil = 0.6811
  Paso 9: +comp_placentaria               → Sil = 0.6544
  Paso 10: +tad_1tri                       → Sil = 0.6324
  Paso 11: +aumento_peso_gest              → Sil = 0.6090
  Paso 12: +imc_ini_gest                   → Sil = 0.5812
  Paso 13: +tas_1tri                       → Sil = 0.5607
  Paso 14: +talla                          → Sil = 0.5367
  Paso 15: +peso_fin_gest                  → Sil = 0.5189
  Paso 16: +comp_metabolica                → Sil = 0.4948
  Paso 17: +trastorno_hipertensivo         → Sil = 0.4728
  Paso 18: +ant_obstetrico                 → Sil = 0.4577
  Paso 19: +edad_materna_gest              → Sil = 0.2447

  Top 3 para k=2:
    Sil=0.7222 | Grupos: [37, 422] | 5 vars: ['peso_ini_gest', 'apgar_10min', 'apgar_5min', 'apgar_1min', 'ant_medico']
    Sil=0.7149 | Grupos: [35, 424] | 4 vars: ['peso_ini_gest', 'apgar_10min', 'apgar_5min', 'ant_medico']
    Sil=0.7075 | Grupos: [31, 428] | 6 vars: ['peso_ini_gest', 'apgar_10min', 'apgar_5min', 'apgar_1min', 'eg_parto', 'ant_medico']

Buscando mejores combinaciones para k=3...
  Paso 2: +comp_maternaGrave              → Sil = 0.3089
  Paso 3: +apgar_10min                    → Sil = 0.4356
  Paso 4: +imc_ini_gest                   → Sil = 0.4986
  Paso 5: +apgar_5min                     → Sil = 0.4885
  Paso 6: +peso_fin_gest                  → Sil = 0.4822
  Paso 7: +apgar_1min                     → Sil = 0.4570
  Paso 8: +ant_medico                     → Sil = 0.4144
  Paso 9: +eg_parto                       → Sil = 0.3806
  Paso 10: +comp_metabolica                → Sil = 0.3511
  Paso 11: +tas_1tri                       → Sil = 0.3280
  Paso 12: +tad_1tri                       → Sil = 0.3121
  Paso 13: +aumento_peso_gest              → Sil = 0.2962
  Paso 14: +trastorno_hipertensivo         → Sil = 0.2740
  Paso 15: +talla                          → Sil = 0.2604
  Paso 16: +ant_obstetrico                 → Sil = 0.2432
  Paso 17: +edad_materna_gest              → Sil = 0.2217
  Paso 18: +comp_placentaria               → Sil = 0.2007
  Paso 19: +peso_rn                        → Sil = 0.1753

  Top 3 para k=3:
    Sil=0.4986 | Grupos: [103, 33, 323] | 4 vars: ['peso_ini_gest', 'apgar_10min', 'imc_ini_gest', 'comp_maternaGrave']
    Sil=0.4885 | Grupos: [103, 322, 34] | 5 vars: ['peso_ini_gest', 'apgar_10min', 'imc_ini_gest', 'apgar_5min', 'comp_maternaGrave']
    Sil=0.4866 | Grupos: [111, 315, 33] | 5 vars: ['peso_ini_gest', 'apgar_10min', 'imc_ini_gest', 'peso_fin_gest', 'comp_maternaGrave']

Buscando mejores combinaciones para k=4...
  Paso 2: +ant_medico                     → Sil = 0.2937
  Paso 3: +peso_fin_gest                  → Sil = 0.3617
  Paso 4: +imc_ini_gest                   → Sil = 0.3514
  Paso 5: +apgar_10min                    → Sil = 0.3602
  Paso 6: +apgar_5min                     → Sil = 0.3602
  Paso 7: +apgar_1min                     → Sil = 0.4660
  Paso 8: +comp_metabolica                → Sil = 0.4173
  Paso 9: +comp_maternaGrave              → Sil = 0.3768
  Paso 10: +ant_obstetrico                 → Sil = 0.3304
  Paso 11: +comp_placentaria               → Sil = 0.2796
  Paso 12: +eg_parto                       → Sil = 0.1458
  Paso 13: +peso_rn                        → Sil = 0.2472
  Paso 14: +trastorno_hipertensivo         → Sil = 0.2251
  Paso 15: +tad_1tri                       → Sil = 0.1928
  Paso 16: +edad_materna_gest              → Sil = 0.1432
  Paso 17: +tas_1tri                       → Sil = 0.1305
  Paso 18: +talla                          → Sil = 0.1390
  Paso 19: +aumento_peso_gest              → Sil = 0.0953

  Top 3 para k=4:
    Sil=0.4660 | Grupos: [10, 27, 313, 109] | 7 vars: ['peso_ini_gest', 'peso_fin_gest', 'imc_ini_gest', 'apgar_10min', 'apgar_5min', 'apgar_1min', 'ant_medico']
    Sil=0.4173 | Grupos: [10, 27, 313, 109] | 8 vars: ['peso_ini_gest', 'peso_fin_gest', 'imc_ini_gest', 'apgar_10min', 'apgar_5min', 'apgar_1min', 'ant_medico', 'comp_metabolica']
    Sil=0.4151 | Grupos: [10, 27, 313, 109] | 8 vars: ['peso_ini_gest', 'peso_fin_gest', 'imc_ini_gest', 'apgar_10min', 'apgar_5min', 'apgar_1min', 'ant_medico', 'comp_maternaGrave']

Buscando mejores combinaciones para k=5...
  Paso 2: +ant_medico                     → Sil = 0.3991
  Paso 3: +peso_fin_gest                  → Sil = 0.3056
  Paso 4: +apgar_10min                    → Sil = 0.3520
  Paso 5: +imc_ini_gest                   → Sil = 0.3415
  Paso 6: +apgar_5min                     → Sil = 0.3341
  Paso 7: +apgar_1min                     → Sil = 0.3439
  Paso 8: +eg_parto                       → Sil = 0.2897
  Paso 9: +comp_maternaGrave              → Sil = 0.2610
  Paso 10: +peso_rn                        → Sil = 0.2592
  Paso 11: +comp_placentaria               → Sil = 0.2708
  Paso 12: +comp_metabolica                → Sil = 0.2521
  Paso 13: +trastorno_hipertensivo         → Sil = 0.2286
  Paso 14: +ant_obstetrico                 → Sil = 0.2094
  Paso 15: +tas_1tri                       → Sil = 0.0811
  Paso 16: +talla                          → Sil = 0.0584
  Paso 17: +edad_materna_gest              → Sil = 0.0798
  Paso 18: +aumento_peso_gest              → Sil = 0.0588
  Paso 19: +tad_1tri                       → Sil = 0.0427

  Top 3 para k=5:
    Sil=0.3991 | Grupos: [92, 59, 152, 135, 21] | 2 vars: ['peso_ini_gest', 'ant_medico']
    Sil=0.3940 | Grupos: [22, 26, 170, 93, 148] | 2 vars: ['peso_ini_gest', 'comp_maternaGrave']
    Sil=0.3757 | Grupos: [141, 72, 68, 131, 47] | 2 vars: ['peso_ini_gest', 'trastorno_hipertensivo']

======================================================================
RESUMEN: Top 3 combinaciones por k
======================================================================

,k,silhouette,n_grupos,variables
0,2,0.722224,"[37, 422]","[peso_ini_gest, apgar_10min, apgar_5min, apgar_1min, ant_medico]"
1,2,0.714869,"[35, 424]","[peso_ini_gest, apgar_10min, apgar_5min, ant_medico]"
2,2,0.707450,"[31, 428]","[peso_ini_gest, apgar_10min, apgar_5min, apgar_1min, eg_parto, ant_medico]"
3,3,0.498643,"[103, 33, 323]","[peso_ini_gest, apgar_10min, imc_ini_gest, comp_maternaGrave]"
4,3,0.488487,"[103, 322, 34]","[peso_ini_gest, apgar_10min, imc_ini_gest, apgar_5min, comp_maternaGrave]"
5,3,0.486609,"[111, 315, 33]","[peso_ini_gest, apgar_10min, imc_ini_gest, peso_fin_gest, comp_maternaGrave]"
6,4,0.466029,"[10, 27, 313, 109]","[peso_ini_gest, peso_fin_gest, imc_ini_gest, apgar_10min, apgar_5min, apgar_1min, ant_medico]"
7,4,0.417299,"[10, 27, 313, 109]","[peso_ini_gest, peso_fin_gest, imc_ini_gest, apgar_10min, apgar_5min, apgar_1min, ant_medico, comp_metabolica]"
8,4,0.415081,"[10, 27, 313, 109]","[peso_ini_gest, peso_fin_gest, imc_ini_gest, apgar_10min, apgar_5min, apgar_1min, ant_medico, comp_maternaGrave]"
9,5,0.399129,"[92, 59, 152, 135, 21]","[peso_ini_gest, ant_medico]"
10,5,0.393963,"[22, 26, 170, 93, 148]","[peso_ini_gest, comp_maternaGrave]"
11,5,0.375659,"[141, 72, 68, 131, 47]","[peso_ini_gest, trastorno_hipertensivo]"

# Descripción de los grupos

In [36]:
from scipy import stats
from itertools import combinations

In [37]:
vars_embarazo = [c for c in [
    'peso_ini_gest', 'peso_fin_gest', 'aumento_peso_gest', 'talla', 'imc_ini_gest',
    'edad_materna_gest', 'tas_1tri', 'tad_1tri', 'eg_eco_1tri', 'eg_parto',
    'peso_rn', 'apgar_1min', 'apgar_5min', 'apgar_10min'
] if c in df_modelo.columns]

vars_biomarcadores = [c for c in ['ratio_MoM', 'sflt1_MoM', 'plgf_MoM'] if c in df_modelo.columns]

vars_eco = [c for c in [
    'diam_telediastolico', 'diam_telesistolico', 'dtsvi_indexado', 'septo_iv_diastole',
    'pared_posterior_vi_diastole', 'diam_ai', 'ai_volumen', 'ad_volumen', 'tapse',
    'e_mitral', 'e_e', 'gc_tsvi', 'urato_acidourico'
] if c in df_clust2.columns]

vars_ta_car_oft = [c for c in [
    'ta_sistolica', 'ta_diastolica', 'frec_cardiaca',
    'right_1peak_systolic_velocity', 'right_2peak_systolic_velocity',
    'right_pulsatility_index', 'right_psv_ratio',
    'left_1peak_systolic_velocity', 'left_2peak_systolic_velocity',
    'left_pulsatility_index', 'left_psv_ratio', 'right_mean', 'left_mean'
] if c in df_clust2.columns]

vars_analitica = [c for c in [
    'plgf_pg', 'troponina_t', 'nt_probnp', 'hemoglobina', 'hematocrito',
    'leucocitos', 'plaquetas', 'glucosa', 'sodio', 'potasio',
    'urato_acidourico', 'creatinina', 'hemoglobina_glicada', 'ast', 'alt',
    'bilirubina_total', 'ldh', 'vldl', 'ldl', 'hdl', 'colesterol_total',
    'trigliceridos', 'prote_totales_orina', 'albumina_orina',
    'ratio_albumina_creatinina', 'tirotropina', 'prolactina'
] if c in df_clust2.columns]

vars_antecedentes = [c for c in [
    'trastorno_hipertensivo', 'comp_placentaria', 'comp_maternaGrave',
    'comp_metabolica', 'ant_obstetrico', 'ant_medico'
] if c in df_clust2.columns]

cols_cat_scores = ['ID', 'Cat_Dieta', 'Cat_Actividad', 'Cat_Estres', 'Cat_Memoria', 'Cat_SCL90R']

grupos_informe = {
    "GESTACIÓN Y BIOMARCADORES": vars_embarazo + vars_biomarcadores,
    "ECOCARDIOGRAFÍA":           vars_eco,
    "TA, CARÓTIDA Y OFTÁLMICA":  vars_ta_car_oft,
    "ANALÍTICA":                 vars_analitica,
    "SCORES CATEGÓRICOS":        [c for c in cols_cat_scores if c != 'ID' and c in df_cat.columns],
    "ANTECEDENTES":              vars_antecedentes,
}

# Construcción del dataframe maestro

# Asegurar tipos consistentes
df_modelo['id'] = df_modelo['id'].astype(float)
df_clust2['id'] = df_clust2['id'].astype(float)
df_cat['ID']    = df_cat['ID'].astype(float)

# Eliminación de duplicados
df_clust_dedup  = df_modelo.drop_duplicates(subset='id', keep='first')
df_clust2_dedup = df_clust2.drop_duplicates(subset='id', keep='first')
df_cat_dedup    = df_cat.drop_duplicates(subset='ID', keep='first')

# Iniciamos df_maestro
df_maestro = df_clust_dedup.copy()

# MERGE 1: Unir variables de df_clust2 (EVITANDO DUPLICADOS QUE CAUSAN MERGEERROR)
cols_interes_clust2 = vars_eco + vars_ta_car_oft + vars_analitica + vars_antecedentes
# Solo traemos columnas que NO existan ya en df_maestro para evitar colisiones
cols_nuevas_clust2 = [c for c in cols_interes_clust2 if c in df_clust2_dedup.columns and c not in df_maestro.columns]

df_maestro = pd.merge(
    df_maestro, 
    df_clust2_dedup[['id'] + cols_nuevas_clust2], 
    on='id', 
    how='left'
)

# MERGE 2: Unir variables de scores categóricos
cols_cat_existentes = [c for c in cols_cat_scores if c in df_cat_dedup.columns]
cols_cat_nuevas = [c for c in cols_cat_existentes if c != 'ID' and c not in df_maestro.columns]

df_maestro = pd.merge(
    df_maestro,
    df_cat_dedup[['ID'] + cols_cat_nuevas],
    left_on='id', right_on='ID',
    how='left'
).drop(columns=['ID'], errors='ignore')

# Asegurar que los antecedentes sean tratados como categorías
vars_antecedentes = [v for v in vars_antecedentes if v in df_maestro.columns]
for v in vars_antecedentes:
    df_maestro[v] = df_maestro[v].astype(str).replace('nan', np.nan).astype('category')

grupos_informe["ANTECEDENTES"] = vars_antecedentes
assert len(df_maestro) == len(df_clust_dedup), "ERROR: df_maestro tiene duplicados inesperados"

# Funciones auxiliares

def describir_clusters(df, variables_num, variables_cat):
    partes = []
    if variables_num:
        # Mejora: Manejo de grupos con n=1 para evitar errores en std()
        res_num = df.groupby('cluster')[variables_num].agg(
            lambda x: f"{x.mean():.2f} ± {x.std():.2f}" if len(x.dropna()) > 1 else f"{x.mean():.2f} ± 0.00"
        ).T
        res_num.columns = [f"Grupo {i}" for i in res_num.columns]
        partes.append(res_num)

    if variables_cat:
        cat_list = []
        for col in variables_cat:
            valid = df[[col, 'cluster']].dropna(subset=[col]).copy()
            valid[col] = valid[col].astype(str)
            try:
                ct_n   = pd.crosstab(valid[col], valid['cluster'])
                ct_pct = pd.crosstab(valid[col], valid['cluster'], normalize='columns') * 100
                ct_fmt = ct_n.astype(str).copy()
                for r in ct_n.index:
                    for c in ct_n.columns:
                        ct_fmt.loc[r, c] = f"{int(ct_n.loc[r, c])} ({ct_pct.loc[r, c]:.1f}%)"
                ct_fmt.index = [f"{col}: {idx}" for idx in ct_fmt.index]
                cat_list.append(ct_fmt)
            except Exception as e:
                print(f"  [AVISO] No se pudo tabular '{col}': {e}")
        if cat_list:
            res_cat = pd.concat(cat_list)
            res_cat.columns = [f"Grupo {i}" for i in res_cat.columns]
            partes.append(res_cat)
    return pd.concat(partes) if partes else pd.DataFrame()

def realizar_analisis_avanzado(df, var, grupo_col):
    serie = df[var]
    if hasattr(serie, 'values') and serie.values.ndim > 1:
        df = df.copy()
        df[var] = serie.values[:, 0]

    grupos_ids = sorted(df[grupo_col].unique())
    dict_datos = {g: df[df[grupo_col] == g][var].dropna() for g in grupos_ids}
    n_grupos = len(grupos_ids)

    datos_validos = [d for d in dict_datos.values() if len(d) > 0]
    if len(datos_validos) < 2:
        return [var, "N/A", "N/A", "N/A"] + ["-"] * n_grupos

    es_numerica = pd.api.types.is_numeric_dtype(df[var]) and not set(df[var].dropna().unique()).issubset({0, 1, '0', '1', '0.0', '1.0'})

    if es_numerica:
        p_shapiro = stats.shapiro(df[var].dropna())[1] if len(df[var].dropna()) > 3 else 0
        skew = df[var].skew()
        kurt = df[var].kurtosis()
        es_normal = (p_shapiro > 0.05) and (abs(skew) < 1) and (abs(kurt) < 3)
        
        # Levene requiere al menos 2 datos por grupo
        datos_levene = [d for d in datos_validos if len(d) > 1]
        p_levene = stats.levene(*datos_levene)[1] if len(datos_levene) > 1 else 1
        homogeneas = p_levene > 0.05

        if n_grupos == 2:
            test_name = "Prueba T" if es_normal else "U Mann-Whitney"
            g1, g2 = list(dict_datos.values())[0], list(dict_datos.values())[1]
            if es_normal:
                _, p_val_total = stats.ttest_ind(g1, g2, equal_var=homogeneas)
            else:
                _, p_val_total = stats.mannwhitneyu(g1, g2)
        else:
            if es_normal:
                test_name = "ANOVA" if homogeneas else "Welch ANOVA"
                p_val_total = stats.f_oneway(*datos_validos)[1] if homogeneas else stats.alexandergovern(*datos_validos).pvalue
            else:
                test_name = "Kruskal-Wallis"
                _, p_val_total = stats.kruskal(*datos_validos)
        metrica = "media ± DE" if es_normal else "mediana ± IQR"
    else:
        serie_clean = df[var].dropna().astype(str)
        contingencia = pd.crosstab(serie_clean, df.loc[serie_clean.index, grupo_col])
        test_name = "Chi-Square"
        _, p_val_total, _, _ = stats.chi2_contingency(contingencia)

    # Post-hoc pairwise
    pairs = list(combinations(grupos_ids, 2))
    p_pairs = []
    for g1_id, g2_id in pairs:
        d1, d2 = dict_datos[g1_id], dict_datos[g2_id]
        if len(d1) > 1 and len(d2) > 1:
            if es_numerica:
                _, p_p = stats.mannwhitneyu(d1, d2)
            else:
                sub_cont = pd.crosstab(df[df[grupo_col].isin([g1_id, g2_id])][var].astype(str), 
                                       df[df[grupo_col].isin([g1_id, g2_id])][grupo_col])
                _, p_p, _, _ = stats.chi2_contingency(sub_cont)
            p_adj = min(p_p * len(pairs), 1.0)
            p_pairs.append(f"G{g1_id}vG{g2_id}: {p_adj:.3f}")
        else:
            p_pairs.append(f"G{g1_id}vG{g2_id}: N/A")
    
    res_grupos = []
    for g in grupos_ids:
        g_data = dict_datos[g]
        if len(g_data) == 0: res_grupos.append("N/A")
        elif es_numerica:
            if metrica == "media ± DE":
                res_grupos.append(f"{g_data.mean():.2f} ± {g_data.std():.2f}")
            else:
                res_grupos.append(f"{g_data.median():.2f} ± {g_data.quantile(0.75)-g_data.quantile(0.25):.2f}")
        else:
            counts = g_data.astype(str).value_counts().sort_index()
            total_n = len(g_data)
            res_grupos.append(" | ".join([f"{c}: n={int(n)} ({n/total_n*100:.1f}%)" for c, n in counts.items()]))

    return [var, test_name, f"{p_val_total:.4f}", " | ".join(p_pairs)] + res_grupos

# Bucle principal de ejecución
vars_forzar_categorica = ['trastorno_hipertensivo', 'comp_placentaria', 'comp_maternaGrave', 
                          'comp_metabolica', 'ant_obstetrico', 'ant_medico']

resultados_filtrados = top3_results_mixto[top3_results_mixto['k'].isin([2, 3, 4, 5])]
pd.set_option('display.max_colwidth', None)

for idx, row in resultados_filtrados.iterrows():
    k_actual = int(row['k'])
    vars_clustering = row['variables']
    print(f"\n{'='*70}\nCOMBINACIÓN {idx+1} | K = {k_actual} | SILHOUETTE = {row['silhouette']:.4f}\n{'='*70}")

    # Ejecución K-Prototypes
    vars_num_cl = [v for v in vars_clustering if v in variables_numericas]
    vars_cat_cl = [v for v in vars_clustering if v in variables_categoricas]
    X_num_cl = StandardScaler().fit_transform(df_modelo[vars_num_cl]) if vars_num_cl else np.empty((len(df_modelo), 0))
    X_cat_cl = df_modelo[vars_cat_cl].values.astype(str) if vars_cat_cl else np.empty((len(df_modelo), 0))
    X_cl = np.concatenate([X_num_cl, X_cat_cl], axis=1)
    cat_indices = list(range(len(vars_num_cl), X_cl.shape[1]))

    kp = KPrototypes(n_clusters=k_actual, init='Cao', n_init=10, random_state=42)
    labels = kp.fit_predict(X_cl, categorical=cat_indices)

    # Preparar df_desc para esta iteración
    mapa = pd.DataFrame({'id': df_modelo['id'].values, 'cluster': labels})
    df_desc = df_maestro.drop(columns=['cluster'], errors='ignore').merge(mapa, on='id', how='inner')
    df_desc = df_desc.drop_duplicates(subset='id').loc[:, ~df_desc.columns.duplicated()]

    print(f"\nTAMAÑO DE GRUPOS:\n{df_desc['cluster'].value_counts().sort_index().to_frame().T}")

    # Bloques de descripción y estadística
    for nombre_bloque, vars_bloque in grupos_informe.items():
        v_num = [v for v in vars_bloque if v in df_desc.columns and v not in vars_forzar_categorica and pd.api.types.is_numeric_dtype(df_desc[v])]
        v_cat = [v for v in vars_bloque if v in df_desc.columns and (v in vars_forzar_categorica or not pd.api.types.is_numeric_dtype(df_desc[v]))]
        
        if v_num or v_cat:
            print(f"\n{nombre_bloque}")
            display(describir_clusters(df_desc, v_num, v_cat))
            
            data_stats = [realizar_analisis_avanzado(df_desc, v, 'cluster') for v in vars_bloque if v in df_desc.columns and v not in ['id', 'ID']]
            data_stats = [r for r in data_stats if r]
            if data_stats:
                headers = ["Variable", "Test", "p-valor (Total)", "p-valor (dos a dos)"] + [f"G{i}" for i in range(k_actual)]
                display(pd.DataFrame(data_stats, columns=headers))

======================================================================
COMBINACIÓN 1 | K = 2 | SILHOUETTE = 0.7222
======================================================================

TAMAÑO DE GRUPOS:
cluster   0    1
count    37  422

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1
peso_ini_gest         72.14 ± 17.02     66.39 ± 14.22
peso_fin_gest         84.36 ± 17.97     78.08 ± 14.83
aumento_peso_gest      12.31 ± 6.22      11.67 ± 5.43
talla                 162.04 ± 5.51     163.98 ± 6.22
imc_ini_gest           27.46 ± 6.59      24.67 ± 4.96
edad_materna_gest      36.93 ± 4.50      35.41 ± 4.67
tas_1tri             119.86 ± 13.40    113.87 ± 11.29
tad_1tri              76.63 ± 10.63      72.73 ± 8.02
eg_eco_1tri            12.79 ± 0.50      12.73 ± 0.61
eg_parto               35.84 ± 3.95      39.31 ± 1.71
peso_rn            2410.32 ± 958.13  3123.88 ± 554.14
apgar_1min              6.41 ± 2.23       8.95 ± 0.45
apgar_5min              7.97 ± 1.57       9.93 ± 0.26
apgar_10min             8.88 ± 0.49      10.00 ± 0.02
ratio_MoM             48.38 ± 91.04      3.75 ± 13.54
sflt1_MoM               4.20 ± 5.23       1.55 ± 1.17
plgf_MoM                1.02 ± 1.63       1.33 ± 1.04

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0369,G0vG1: 0.037,67.00 ± 19.00,63.70 ± 17.00
1,peso_fin_gest,U Mann-Whitney,0.0369,G0vG1: 0.037,83.00 ± 21.00,76.00 ± 17.00
2,aumento_peso_gest,U Mann-Whitney,0.7785,G0vG1: 0.778,12.00 ± 5.50,11.35 ± 5.30
3,talla,U Mann-Whitney,0.0679,G0vG1: 0.068,162.00 ± 9.50,164.00 ± 8.00
4,imc_ini_gest,U Mann-Whitney,0.0045,G0vG1: 0.005,24.97 ± 7.90,23.47 ± 6.37
5,edad_materna_gest,U Mann-Whitney,0.0678,G0vG1: 0.068,36.60 ± 5.89,35.48 ± 6.41
6,tas_1tri,U Mann-Whitney,0.0046,G0vG1: 0.005,118.00 ± 17.33,113.02 ± 14.00
7,tad_1tri,U Mann-Whitney,0.0029,G0vG1: 0.003,77.00 ± 7.35,72.41 ± 9.00
8,eg_eco_1tri,U Mann-Whitney,0.6157,G0vG1: 0.616,12.80 ± 0.44,12.79 ± 0.50
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,37.20 ± 5.30,39.60 ± 2.00
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,2560.00 ± 1520.00,3140.00 ± 670.00
11,apgar_1min,U Mann-Whitney,0.0000,G0vG1: 0.000,7.00 ± 3.00,9.00 ± 0.00
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,8.00 ± 1.00,10.00 ± 0.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,9.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,6.48 ± 50.01,1.69 ± 1.73
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,2.04 ± 3.92,1.26 ± 0.65
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,0.42 ± 0.94,1.18 ± 0.95

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1
diam_telediastolico           44.59 ± 4.90   44.99 ± 5.48
diam_telesistolico            28.80 ± 4.35   29.96 ± 4.53
dtsvi_indexado                15.65 ± 3.03   17.00 ± 2.72
septo_iv_diastole            11.47 ± 14.65    9.22 ± 8.98
pared_posterior_vi_diastole    9.52 ± 9.78    8.47 ± 8.38
diam_ai                       34.85 ± 4.78   33.28 ± 4.61
ai_volumen                   39.49 ± 12.69  36.88 ± 13.27
ad_volumen                   33.12 ± 12.83  32.73 ± 15.52
tapse                         26.49 ± 3.91  26.02 ± 17.50
e_mitral                     75.18 ± 16.17  79.47 ± 62.85
e_e                            3.89 ± 1.12    4.11 ± 3.41
gc_tsvi                       7.73 ± 10.13    6.35 ± 4.98
urato_acidourico               4.01 ± 0.78    4.19 ± 1.47

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.6718,G0vG1: 0.672,44.00 ± 6.00,45.00 ± 6.00
1,diam_telesistolico,U Mann-Whitney,0.2521,G0vG1: 0.252,29.00 ± 7.00,30.00 ± 5.00
2,dtsvi_indexado,U Mann-Whitney,0.0177,G0vG1: 0.018,15.73 ± 4.27,17.02 ± 3.49
3,septo_iv_diastole,U Mann-Whitney,0.0647,G0vG1: 0.065,9.00 ± 2.00,8.00 ± 2.00
4,pared_posterior_vi_diastole,U Mann-Whitney,0.3117,G0vG1: 0.312,7.90 ± 1.30,7.20 ± 2.00
5,diam_ai,U Mann-Whitney,0.0857,G0vG1: 0.086,35.00 ± 6.00,34.00 ± 7.00
6,ai_volumen,U Mann-Whitney,0.2027,G0vG1: 0.203,37.40 ± 20.60,35.00 ± 15.10
7,ad_volumen,U Mann-Whitney,0.7917,G0vG1: 0.792,31.20 ± 13.80,30.35 ± 15.60
8,tapse,U Mann-Whitney,0.0127,G0vG1: 0.013,27.00 ± 4.00,24.65 ± 5.25
9,e_mitral,U Mann-Whitney,0.8813,G0vG1: 0.881,74.00 ± 24.40,74.10 ± 18.10
10,e_e,U Mann-Whitney,0.6987,G0vG1: 0.699,3.84 ± 0.88,3.73 ± 1.17
11,gc_tsvi,U Mann-Whitney,0.8396,G0vG1: 0.840,5.55 ± 1.45,5.70 ± 1.50
12,urato_acidourico,U Mann-Whitney,0.7027,G0vG1: 0.703,3.94 ± 1.05,4.05 ± 1.14

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1
ta_sistolica                   125.17 ± 19.13  114.67 ± 14.49
ta_diastolica                   79.50 ± 13.56    75.07 ± 9.49
frec_cardiaca                   81.03 ± 11.11   78.82 ± 11.91
right_1peak_systolic_velocity    31.25 ± 8.40    31.41 ± 8.95
right_2peak_systolic_velocity    22.58 ± 7.56    21.80 ± 7.18
right_pulsatility_index           1.83 ± 0.45     1.77 ± 0.44
right_psv_ratio                   0.72 ± 0.14     0.70 ± 0.12
left_1peak_systolic_velocity     34.79 ± 9.92    33.35 ± 9.30
left_2peak_systolic_velocity     25.44 ± 8.49    23.40 ± 7.50
left_pulsatility_index            1.76 ± 0.44     1.77 ± 1.21
left_psv_ratio                    0.74 ± 0.14     0.71 ± 0.12
right_mean                        0.54 ± 0.09     0.53 ± 0.10
left_mean                         0.57 ± 0.09     0.55 ± 0.10

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0005,G0vG1: 0.000,126.50 ± 20.75,114.00 ± 17.00
1,ta_diastolica,U Mann-Whitney,0.0109,G0vG1: 0.011,81.00 ± 17.75,75.00 ± 13.00
2,frec_cardiaca,Prueba T,0.2831,G0vG1: 0.306,81.03 ± 11.11,78.82 ± 11.91
3,right_1peak_systolic_velocity,U Mann-Whitney,0.9481,G0vG1: 0.948,31.70 ± 11.67,31.20 ± 11.70
4,right_2peak_systolic_velocity,U Mann-Whitney,0.6196,G0vG1: 0.620,22.55 ± 12.08,21.20 ± 9.90
5,right_pulsatility_index,U Mann-Whitney,0.3322,G0vG1: 0.332,1.83 ± 0.50,1.74 ± 0.51
6,right_psv_ratio,Prueba T,0.1805,G0vG1: 0.311,0.72 ± 0.14,0.70 ± 0.12
7,left_1peak_systolic_velocity,U Mann-Whitney,0.4072,G0vG1: 0.407,35.70 ± 14.52,33.50 ± 11.60
8,left_2peak_systolic_velocity,U Mann-Whitney,0.2055,G0vG1: 0.205,24.95 ± 11.73,22.80 ± 9.05
9,left_pulsatility_index,U Mann-Whitney,0.7343,G0vG1: 0.734,1.73 ± 0.52,1.70 ± 0.54
10,left_psv_ratio,U Mann-Whitney,0.2510,G0vG1: 0.251,0.75 ± 0.18,0.70 ± 0.16
11,right_mean,U Mann-Whitney,0.2629,G0vG1: 0.263,0.53 ± 0.09,0.52 ± 0.11
12,left_mean,U Mann-Whitney,0.1464,G0vG1: 0.146,0.56 ± 0.17,0.53 ± 0.12

ANALÍTICA

                                  Grupo 0               Grupo 1
hemoglobina                122.15 ± 33.23        126.85 ± 23.14
hematocrito                   0.39 ± 0.03           0.39 ± 0.03
leucocitos              6318.21 ± 1822.90     6575.99 ± 1605.57
plaquetas            273250.00 ± 88312.84  271477.35 ± 61859.80
glucosa                     90.14 ± 11.60         87.42 ± 11.56
sodio                       138.96 ± 2.57         139.70 ± 1.72
potasio                       4.22 ± 0.28           4.22 ± 0.28
urato_acidourico              4.01 ± 0.78           4.19 ± 1.47
hemoglobina_glicada           5.50 ± 0.48           5.37 ± 0.37
ast                          21.36 ± 5.44         21.78 ± 10.47
alt                         19.96 ± 10.15         18.30 ± 13.29
bilirubina_total              0.61 ± 0.27           0.66 ± 0.31
ldh                        172.57 ± 27.65        165.15 ± 26.57
vldl                        17.48 ± 10.04          14.46 ± 8.80
ldl                        117.01 ± 29.02        111.62 ± 28.82
hdl                         54.73 ± 12.81         60.16 ± 14.13
colesterol_total           189.23 ± 33.57        186.13 ± 32.28
trigliceridos               86.97 ± 49.63         73.15 ± 43.13
prote_totales_orina          6.50 ± 19.81          2.36 ± 12.34

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.6659,G0vG1: 0.666,128.00 ± 18.75,131.00 ± 14.00
1,hematocrito,U Mann-Whitney,0.8973,G0vG1: 0.897,0.39 ± 0.05,0.39 ± 0.04
2,leucocitos,U Mann-Whitney,0.4429,G0vG1: 0.443,6150.00 ± 2250.00,6330.00 ± 2045.00
3,plaquetas,U Mann-Whitney,0.8997,G0vG1: 0.900,274000.00 ± 107250.00,265000.00 ± 79500.00
4,glucosa,U Mann-Whitney,0.1637,G0vG1: 0.164,87.00 ± 9.50,87.00 ± 9.00
5,sodio,U Mann-Whitney,0.2511,G0vG1: 0.251,139.00 ± 2.25,140.00 ± 3.00
6,potasio,U Mann-Whitney,0.8026,G0vG1: 0.803,4.23 ± 0.27,4.20 ± 0.33
7,urato_acidourico,U Mann-Whitney,0.7027,G0vG1: 0.703,3.94 ± 1.05,4.05 ± 1.14
8,hemoglobina_glicada,U Mann-Whitney,0.1535,G0vG1: 0.154,5.40 ± 0.40,5.30 ± 0.30
9,ast,U Mann-Whitney,0.7363,G0vG1: 0.736,20.00 ± 5.25,20.00 ± 6.00
10,alt,U Mann-Whitney,0.1684,G0vG1: 0.168,16.50 ± 9.75,15.00 ± 8.00
11,bilirubina_total,U Mann-Whitney,0.2991,G0vG1: 0.299,0.56 ± 0.22,0.57 ± 0.30
12,ldh,U Mann-Whitney,0.2526,G0vG1: 0.253,168.50 ± 37.50,162.00 ± 30.00
13,vldl,U Mann-Whitney,0.0362,G0vG1: 0.036,15.61 ± 7.71,11.59 ± 7.22
14,ldl,U Mann-Whitney,0.2592,G0vG1: 0.259,115.90 ± 35.21,106.47 ± 37.89
15,hdl,U Mann-Whitney,0.0480,G0vG1: 0.048,53.02 ± 16.74,59.21 ± 18.38
16,colesterol_total,U Mann-Whitney,0.3263,G0vG1: 0.326,189.82 ± 37.34,183.05 ± 40.44
17,trigliceridos,U Mann-Whitney,0.0470,G0vG1: 0.047,77.44 ± 38.28,57.52 ± 31.86
18,prote_totales_orina,U Mann-Whitney,0.4725,G0vG1: 0.472,0.08 ± 0.06,0.08 ± 0.05

SCORES CATEGÓRICOS

                                               Grupo 0      Grupo 1
Cat_Dieta: Adherencia moderada              25 (67.6%)  260 (61.6%)
Cat_Dieta: Alta adherencia                    0 (0.0%)    25 (5.9%)
Cat_Dieta: Baja adherencia                  12 (32.4%)  137 (32.5%)
Cat_Actividad: Actividad física alta        33 (94.3%)  380 (90.9%)
Cat_Actividad: Actividad física baja          0 (0.0%)    11 (2.6%)
Cat_Actividad: Actividad física moderada      2 (5.7%)    27 (6.5%)
Cat_Estres: Nivel de estrés alto            14 (38.9%)  148 (35.2%)
Cat_Estres: Nivel de estrés bajo              3 (8.3%)   49 (11.6%)
Cat_Estres: Nivel de estrés moderado        17 (47.2%)  211 (50.1%)
Cat_Estres: Nivel de estrés muy alto          2 (5.6%)    13 (3.1%)
Cat_Memoria: Deterioro leve                  6 (17.1%)   59 (14.1%)
Cat_Memoria: Disfunción moderada-grave        3 (8.6%)    41 (9.8%)
Cat_Memoria: Función normal (lapsus leves)  18 (51.4%)  242 (57.8%)
Cat_Memoria: Rendimiento de memoria óptimo   8 (22.9%)   77 (18.4%)
Cat_SCL90R: EN RIESGO                        8 (21.6%)   49 (11.8%)
Cat_SCL90R: Normal / Sin riesgo              4 (10.8%)   85 (20.5%)
Cat_SCL90R: Patología severa                25 (67.6%)  280 (67.6%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.3033,G0vG1: 0.303,Adherencia moderada: n=25 (67.6%) | Baja adherencia: n=12 (32.4%),Adherencia moderada: n=260 (61.6%) | Alta adherencia: n=25 (5.9%) | Baja adherencia: n=137 (32.5%)
1,Cat_Actividad,Chi-Square,0.6097,G0vG1: 0.103,Actividad física alta: n=33 (94.3%) | Actividad física moderada: n=2 (5.7%),Actividad física alta: n=380 (90.9%) | Actividad física baja: n=11 (2.6%) | Actividad física moderada: n=27 (6.5%)
2,Cat_Estres,Chi-Square,0.7722,G0vG1: 0.210,Nivel de estrés alto: n=14 (38.9%) | Nivel de estrés bajo: n=3 (8.3%) | Nivel de estrés moderado: n=17 (47.2%) | Nivel de estrés muy alto: n=2 (5.6%),Nivel de estrés alto: n=148 (35.2%) | Nivel de estrés bajo: n=49 (11.6%) | Nivel de estrés moderado: n=211 (50.1%) | Nivel de estrés muy alto: n=13 (3.1%)
3,Cat_Memoria,Chi-Square,0.8416,G0vG1: 0.101,Deterioro leve: n=6 (17.1%) | Disfunción moderada-grave: n=3 (8.6%) | Función normal (lapsus leves): n=18 (51.4%) | Rendimiento de memoria óptimo: n=8 (22.9%),Deterioro leve: n=59 (14.1%) | Disfunción moderada-grave: n=41 (9.8%) | Función normal (lapsus leves): n=242 (57.8%) | Rendimiento de memoria óptimo: n=77 (18.4%)
4,Cat_SCL90R,Chi-Square,0.1225,G0vG1: 0.173,EN RIESGO: n=8 (21.6%) | Normal / Sin riesgo: n=4 (10.8%) | Patología severa: n=25 (67.6%),EN RIESGO: n=49 (11.8%) | Normal / Sin riesgo: n=85 (20.5%) | Patología severa: n=280 (67.6%)

ANTECEDENTES

                                Grupo 0      Grupo 1
trastorno_hipertensivo: 0.0  15 (40.5%)  312 (73.9%)
trastorno_hipertensivo: 1.0  22 (59.5%)  110 (26.1%)
comp_placentaria: 0.0        24 (64.9%)  366 (86.7%)
comp_placentaria: 1.0        13 (35.1%)   56 (13.3%)
comp_maternaGrave: 0.0       22 (59.5%)  396 (93.8%)
comp_maternaGrave: 1.0       15 (40.5%)    26 (6.2%)
comp_metabolica: 0.0         33 (89.2%)  378 (89.6%)
comp_metabolica: 1.0          4 (10.8%)   44 (10.4%)
ant_obstetrico: -1           26 (70.3%)  310 (73.5%)
ant_obstetrico: 1             8 (21.6%)   91 (21.6%)
ant_obstetrico: 3              3 (8.1%)    15 (3.6%)
ant_obstetrico: 4              0 (0.0%)     6 (1.4%)
ant_medico: -1               23 (62.2%)  333 (78.9%)
ant_medico: 1                11 (29.7%)   75 (17.8%)
ant_medico: 3                  2 (5.4%)    14 (3.3%)
ant_medico: 5                  1 (2.7%)     0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=15 (40.5%) | 1.0: n=22 (59.5%),0.0: n=312 (73.9%) | 1.0: n=110 (26.1%)
1,comp_placentaria,Chi-Square,0.0009,G0vG1: 0.001,0.0: n=24 (64.9%) | 1.0: n=13 (35.1%),0.0: n=366 (86.7%) | 1.0: n=56 (13.3%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=22 (59.5%) | 1.0: n=15 (40.5%),0.0: n=396 (93.8%) | 1.0: n=26 (6.2%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=33 (89.2%) | 1.0: n=4 (10.8%),0.0: n=378 (89.6%) | 1.0: n=44 (10.4%)
4,ant_obstetrico,Chi-Square,0.4989,G0vG1: 0.499,-1: n=26 (70.3%) | 1: n=8 (21.6%) | 3: n=3 (8.1%),-1: n=310 (73.5%) | 1: n=91 (21.6%) | 3: n=15 (3.6%) | 4: n=6 (1.4%)
5,ant_medico,Chi-Square,0.0013,G0vG1: 0.001,-1: n=23 (62.2%) | 1: n=11 (29.7%) | 3: n=2 (5.4%) | 5: n=1 (2.7%),-1: n=333 (78.9%) | 1: n=75 (17.8%) | 3: n=14 (3.3%)

======================================================================
COMBINACIÓN 2 | K = 2 | SILHOUETTE = 0.7149
======================================================================

TAMAÑO DE GRUPOS:
cluster   0    1
count    35  424

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1
peso_ini_gest         71.58 ± 16.57     66.47 ± 14.30
peso_fin_gest         84.01 ± 17.60     78.14 ± 14.90
aumento_peso_gest      12.52 ± 6.32      11.66 ± 5.42
talla                 161.90 ± 5.53     163.98 ± 6.22
imc_ini_gest           27.32 ± 6.59      24.70 ± 4.98
edad_materna_gest      36.64 ± 4.45      35.44 ± 4.68
tas_1tri             120.73 ± 13.13    113.83 ± 11.29
tad_1tri              77.18 ± 10.39      72.70 ± 8.04
eg_eco_1tri            12.79 ± 0.44      12.73 ± 0.62
eg_parto               35.73 ± 4.04      39.30 ± 1.71
peso_rn            2389.77 ± 979.94  3122.21 ± 553.62
apgar_1min              6.52 ± 2.24       8.93 ± 0.54
apgar_5min              7.94 ± 1.60       9.93 ± 0.28
apgar_10min             8.82 ± 0.42      10.00 ± 0.02
ratio_MoM             50.36 ± 93.27      3.79 ± 13.53
sflt1_MoM               4.21 ± 5.38       1.56 ± 1.18
plgf_MoM                1.06 ± 1.67       1.33 ± 1.04

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0555,G0vG1: 0.056,67.00 ± 18.45,63.70 ± 17.12
1,peso_fin_gest,U Mann-Whitney,0.0445,G0vG1: 0.044,83.00 ± 19.92,76.00 ± 17.25
2,aumento_peso_gest,U Mann-Whitney,0.5585,G0vG1: 0.559,12.02 ± 5.25,11.30 ± 5.30
3,talla,U Mann-Whitney,0.0548,G0vG1: 0.055,162.00 ± 9.25,164.00 ± 8.00
4,imc_ini_gest,U Mann-Whitney,0.0088,G0vG1: 0.009,24.97 ± 7.88,23.50 ± 6.34
5,edad_materna_gest,U Mann-Whitney,0.1758,G0vG1: 0.176,35.99 ± 5.91,35.52 ± 6.46
6,tas_1tri,U Mann-Whitney,0.0013,G0vG1: 0.001,119.00 ± 16.50,113.00 ± 14.00
7,tad_1tri,U Mann-Whitney,0.0013,G0vG1: 0.001,77.00 ± 8.17,72.41 ± 9.00
8,eg_eco_1tri,U Mann-Whitney,0.6076,G0vG1: 0.608,12.80 ± 0.42,12.79 ± 0.50
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,36.00 ± 5.65,39.60 ± 2.00
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,2560.00 ± 1560.00,3140.00 ± 672.50
11,apgar_1min,U Mann-Whitney,0.0000,G0vG1: 0.000,7.00 ± 3.00,9.00 ± 0.00
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,8.00 ± 1.50,10.00 ± 0.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,9.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0001,G0vG1: 0.000,5.15 ± 55.68,1.69 ± 1.77
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.88 ± 4.38,1.26 ± 0.66
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,0.47 ± 1.00,1.17 ± 0.96

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1
diam_telediastolico           44.63 ± 5.09   44.98 ± 5.47
diam_telesistolico            28.93 ± 4.45   29.94 ± 4.52
dtsvi_indexado                16.01 ± 2.78   16.97 ± 2.76
septo_iv_diastole            11.67 ± 15.18    9.22 ± 8.96
pared_posterior_vi_diastole   9.72 ± 10.12    8.46 ± 8.36
diam_ai                       34.92 ± 4.86   33.28 ± 4.61
ai_volumen                   40.17 ± 12.74  36.85 ± 13.25
ad_volumen                   33.12 ± 13.21  32.73 ± 15.48
tapse                         26.46 ± 4.01  26.02 ± 17.45
e_mitral                     75.61 ± 16.33  79.43 ± 62.76
e_e                            3.93 ± 1.12    4.10 ± 3.40
gc_tsvi                       7.87 ± 10.31    6.35 ± 4.97
urato_acidourico               4.11 ± 0.69    4.18 ± 1.47

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.7275,G0vG1: 0.728,43.00 ± 6.00,45.00 ± 6.00
1,diam_telesistolico,U Mann-Whitney,0.3726,G0vG1: 0.373,29.00 ± 7.50,29.00 ± 5.00
2,dtsvi_indexado,U Mann-Whitney,0.0728,G0vG1: 0.073,16.23 ± 3.71,17.00 ± 3.49
3,septo_iv_diastole,U Mann-Whitney,0.0808,G0vG1: 0.081,9.00 ± 2.20,8.00 ± 2.10
4,pared_posterior_vi_diastole,U Mann-Whitney,0.1979,G0vG1: 0.198,8.00 ± 1.45,7.20 ± 1.90
5,diam_ai,U Mann-Whitney,0.0740,G0vG1: 0.074,35.00 ± 6.00,34.00 ± 7.00
6,ai_volumen,U Mann-Whitney,0.1273,G0vG1: 0.127,41.60 ± 20.40,35.00 ± 15.10
7,ad_volumen,U Mann-Whitney,0.8549,G0vG1: 0.855,31.20 ± 15.65,30.35 ± 15.50
8,tapse,U Mann-Whitney,0.0197,G0vG1: 0.020,27.00 ± 4.90,24.70 ± 5.75
9,e_mitral,U Mann-Whitney,0.9499,G0vG1: 0.950,74.00 ± 24.88,74.00 ± 18.00
10,e_e,U Mann-Whitney,0.5008,G0vG1: 0.501,3.86 ± 0.82,3.73 ± 1.18
11,gc_tsvi,U Mann-Whitney,0.9406,G0vG1: 0.941,5.60 ± 1.30,5.65 ± 1.50
12,urato_acidourico,U Mann-Whitney,0.8102,G0vG1: 0.810,3.98 ± 1.02,4.03 ± 1.15

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1
ta_sistolica                   126.53 ± 18.75  114.61 ± 14.49
ta_diastolica                   80.53 ± 13.22    75.01 ± 9.51
frec_cardiaca                   81.41 ± 10.66   78.80 ± 11.93
right_1peak_systolic_velocity    31.24 ± 8.61    31.41 ± 8.93
right_2peak_systolic_velocity    22.70 ± 7.76    21.79 ± 7.16
right_pulsatility_index           1.83 ± 0.46     1.77 ± 0.44
right_psv_ratio                   0.73 ± 0.14     0.70 ± 0.12
left_1peak_systolic_velocity    34.81 ± 10.21    33.35 ± 9.28
left_2peak_systolic_velocity     25.14 ± 8.58    23.44 ± 7.51
left_pulsatility_index            1.75 ± 0.45     1.77 ± 1.21
left_psv_ratio                    0.73 ± 0.14     0.71 ± 0.12
right_mean                        0.53 ± 0.07     0.53 ± 0.10
left_mean                         0.56 ± 0.09     0.55 ± 0.10

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0001,G0vG1: 0.000,127.50 ± 18.25,114.00 ± 17.00
1,ta_diastolica,U Mann-Whitney,0.0017,G0vG1: 0.002,81.50 ± 17.25,75.00 ± 13.00
2,frec_cardiaca,Prueba T,0.2160,G0vG1: 0.255,81.41 ± 10.66,78.80 ± 11.93
3,right_1peak_systolic_velocity,U Mann-Whitney,0.9446,G0vG1: 0.945,31.70 ± 12.83,31.20 ± 11.65
4,right_2peak_systolic_velocity,U Mann-Whitney,0.5832,G0vG1: 0.583,22.90 ± 13.03,21.20 ± 9.80
5,right_pulsatility_index,U Mann-Whitney,0.3755,G0vG1: 0.376,1.83 ± 0.48,1.74 ± 0.51
6,right_psv_ratio,Prueba T,0.1366,G0vG1: 0.242,0.73 ± 0.14,0.70 ± 0.12
7,left_1peak_systolic_velocity,U Mann-Whitney,0.4332,G0vG1: 0.433,36.00 ± 15.37,33.50 ± 11.50
8,left_2peak_systolic_velocity,U Mann-Whitney,0.3491,G0vG1: 0.349,24.25 ± 11.75,22.80 ± 9.10
9,left_pulsatility_index,U Mann-Whitney,0.9023,G0vG1: 0.902,1.73 ± 0.54,1.70 ± 0.54
10,left_psv_ratio,U Mann-Whitney,0.4674,G0vG1: 0.467,0.73 ± 0.17,0.70 ± 0.16
11,right_mean,U Mann-Whitney,0.5676,G0vG1: 0.568,0.53 ± 0.09,0.52 ± 0.11
12,left_mean,U Mann-Whitney,0.2441,G0vG1: 0.244,0.56 ± 0.16,0.53 ± 0.12

ANALÍTICA

                                  Grupo 0               Grupo 1
hemoglobina                121.93 ± 34.52        126.83 ± 23.06
hematocrito                   0.39 ± 0.03           0.39 ± 0.03
leucocitos              6435.00 ± 1731.91     6563.70 ± 1617.28
plaquetas            274307.69 ± 90698.96  271394.46 ± 61779.60
glucosa                     90.62 ± 11.75         87.40 ± 11.54
sodio                       139.27 ± 1.71         139.66 ± 1.83
potasio                       4.23 ± 0.29           4.22 ± 0.28
urato_acidourico              4.11 ± 0.69           4.18 ± 1.47
hemoglobina_glicada           5.53 ± 0.49           5.37 ± 0.37
ast                          21.08 ± 4.94         21.81 ± 10.46
alt                          19.27 ± 8.68         18.37 ± 13.37
bilirubina_total              0.61 ± 0.27           0.66 ± 0.31
ldh                        173.81 ± 27.90        165.09 ± 26.53
vldl                        17.75 ± 10.38          14.46 ± 8.77
ldl                        120.44 ± 26.32        111.34 ± 28.97
hdl                         55.12 ± 13.20         60.09 ± 14.11
colesterol_total           193.32 ± 30.29        185.78 ± 32.51
trigliceridos               88.35 ± 51.31         73.12 ± 42.98
prote_totales_orina          7.04 ± 20.56          2.34 ± 12.30

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.8501,G0vG1: 0.850,129.50 ± 20.25,131.00 ± 14.00
1,hematocrito,U Mann-Whitney,0.8166,G0vG1: 0.817,0.40 ± 0.05,0.39 ± 0.04
2,leucocitos,U Mann-Whitney,0.5810,G0vG1: 0.581,6150.00 ± 2252.50,6330.00 ± 2040.00
3,plaquetas,U Mann-Whitney,0.9328,G0vG1: 0.933,274000.00 ± 113750.00,265000.00 ± 80000.00
4,glucosa,U Mann-Whitney,0.1168,G0vG1: 0.117,87.00 ± 9.50,87.00 ± 9.00
5,sodio,U Mann-Whitney,0.3039,G0vG1: 0.304,139.00 ± 2.00,140.00 ± 3.00
6,potasio,U Mann-Whitney,0.6684,G0vG1: 0.668,4.24 ± 0.28,4.20 ± 0.33
7,urato_acidourico,U Mann-Whitney,0.8102,G0vG1: 0.810,3.98 ± 1.02,4.03 ± 1.15
8,hemoglobina_glicada,U Mann-Whitney,0.0791,G0vG1: 0.079,5.40 ± 0.38,5.30 ± 0.30
9,ast,U Mann-Whitney,0.7833,G0vG1: 0.783,20.00 ± 4.75,20.00 ± 6.00
10,alt,U Mann-Whitney,0.1710,G0vG1: 0.171,16.50 ± 8.50,15.00 ± 8.00
11,bilirubina_total,U Mann-Whitney,0.3603,G0vG1: 0.360,0.56 ± 0.20,0.57 ± 0.30
12,ldh,U Mann-Whitney,0.1839,G0vG1: 0.184,168.50 ± 41.75,162.00 ± 30.00
13,vldl,U Mann-Whitney,0.0466,G0vG1: 0.047,15.78 ± 8.87,11.59 ± 7.13
14,ldl,U Mann-Whitney,0.1005,G0vG1: 0.101,117.41 ± 21.23,106.29 ± 38.00
15,hdl,U Mann-Whitney,0.0903,G0vG1: 0.090,53.98 ± 18.48,59.21 ± 18.58
16,colesterol_total,U Mann-Whitney,0.1198,G0vG1: 0.120,192.34 ± 27.38,182.28 ± 40.64
17,trigliceridos,U Mann-Whitney,0.0600,G0vG1: 0.060,78.32 ± 44.03,57.53 ± 31.86
18,prote_totales_orina,U Mann-Whitney,0.3513,G0vG1: 0.351,0.08 ± 0.07,0.08 ± 0.05

SCORES CATEGÓRICOS

                                               Grupo 0      Grupo 1
Cat_Dieta: Adherencia moderada              23 (65.7%)  262 (61.8%)
Cat_Dieta: Alta adherencia                    0 (0.0%)    25 (5.9%)
Cat_Dieta: Baja adherencia                  12 (34.3%)  137 (32.3%)
Cat_Actividad: Actividad física alta        32 (97.0%)  381 (90.7%)
Cat_Actividad: Actividad física baja          0 (0.0%)    11 (2.6%)
Cat_Actividad: Actividad física moderada      1 (3.0%)    28 (6.7%)
Cat_Estres: Nivel de estrés alto            12 (35.3%)  150 (35.5%)
Cat_Estres: Nivel de estrés bajo              3 (8.8%)   49 (11.6%)
Cat_Estres: Nivel de estrés moderado        17 (50.0%)  211 (49.9%)
Cat_Estres: Nivel de estrés muy alto          2 (5.9%)    13 (3.1%)
Cat_Memoria: Deterioro leve                  5 (15.2%)   60 (14.3%)
Cat_Memoria: Disfunción moderada-grave        3 (9.1%)    41 (9.7%)
Cat_Memoria: Función normal (lapsus leves)  17 (51.5%)  243 (57.7%)
Cat_Memoria: Rendimiento de memoria óptimo   8 (24.2%)   77 (18.3%)
Cat_SCL90R: EN RIESGO                        8 (22.9%)   49 (11.8%)
Cat_SCL90R: Normal / Sin riesgo              4 (11.4%)   85 (20.4%)
Cat_SCL90R: Patología severa                23 (65.7%)  282 (67.8%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.3358,G0vG1: 0.336,Adherencia moderada: n=23 (65.7%) | Baja adherencia: n=12 (34.3%),Adherencia moderada: n=262 (61.8%) | Alta adherencia: n=25 (5.9%) | Baja adherencia: n=137 (32.3%)
1,Cat_Actividad,Chi-Square,0.4432,G0vG1: 0.064,Actividad física alta: n=32 (97.0%) | Actividad física moderada: n=1 (3.0%),Actividad física alta: n=381 (90.7%) | Actividad física baja: n=11 (2.6%) | Actividad física moderada: n=28 (6.7%)
2,Cat_Estres,Chi-Square,0.8091,G0vG1: 0.194,Nivel de estrés alto: n=12 (35.3%) | Nivel de estrés bajo: n=3 (8.8%) | Nivel de estrés moderado: n=17 (50.0%) | Nivel de estrés muy alto: n=2 (5.9%),Nivel de estrés alto: n=150 (35.5%) | Nivel de estrés bajo: n=49 (11.6%) | Nivel de estrés moderado: n=211 (49.9%) | Nivel de estrés muy alto: n=13 (3.1%)
3,Cat_Memoria,Chi-Square,0.8458,G0vG1: 0.081,Deterioro leve: n=5 (15.2%) | Disfunción moderada-grave: n=3 (9.1%) | Función normal (lapsus leves): n=17 (51.5%) | Rendimiento de memoria óptimo: n=8 (24.2%),Deterioro leve: n=60 (14.3%) | Disfunción moderada-grave: n=41 (9.7%) | Función normal (lapsus leves): n=243 (57.7%) | Rendimiento de memoria óptimo: n=77 (18.3%)
4,Cat_SCL90R,Chi-Square,0.1064,G0vG1: 0.156,EN RIESGO: n=8 (22.9%) | Normal / Sin riesgo: n=4 (11.4%) | Patología severa: n=23 (65.7%),EN RIESGO: n=49 (11.8%) | Normal / Sin riesgo: n=85 (20.4%) | Patología severa: n=282 (67.8%)

ANTECEDENTES

                                Grupo 0      Grupo 1
trastorno_hipertensivo: 0.0  13 (37.1%)  314 (74.1%)
trastorno_hipertensivo: 1.0  22 (62.9%)  110 (25.9%)
comp_placentaria: 0.0        22 (62.9%)  368 (86.8%)
comp_placentaria: 1.0        13 (37.1%)   56 (13.2%)
comp_maternaGrave: 0.0       20 (57.1%)  398 (93.9%)
comp_maternaGrave: 1.0       15 (42.9%)    26 (6.1%)
comp_metabolica: 0.0         31 (88.6%)  380 (89.6%)
comp_metabolica: 1.0          4 (11.4%)   44 (10.4%)
ant_obstetrico: -1           25 (71.4%)  311 (73.3%)
ant_obstetrico: 1             7 (20.0%)   92 (21.7%)
ant_obstetrico: 3              3 (8.6%)    15 (3.5%)
ant_obstetrico: 4              0 (0.0%)     6 (1.4%)
ant_medico: -1               22 (62.9%)  334 (78.8%)
ant_medico: 1                10 (28.6%)   76 (17.9%)
ant_medico: 3                  2 (5.7%)    14 (3.3%)
ant_medico: 5                  1 (2.9%)     0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=13 (37.1%) | 1.0: n=22 (62.9%),0.0: n=314 (74.1%) | 1.0: n=110 (25.9%)
1,comp_placentaria,Chi-Square,0.0004,G0vG1: 0.000,0.0: n=22 (62.9%) | 1.0: n=13 (37.1%),0.0: n=368 (86.8%) | 1.0: n=56 (13.2%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=20 (57.1%) | 1.0: n=15 (42.9%),0.0: n=398 (93.9%) | 1.0: n=26 (6.1%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=31 (88.6%) | 1.0: n=4 (11.4%),0.0: n=380 (89.6%) | 1.0: n=44 (10.4%)
4,ant_obstetrico,Chi-Square,0.4499,G0vG1: 0.450,-1: n=25 (71.4%) | 1: n=7 (20.0%) | 3: n=3 (8.6%),-1: n=311 (73.3%) | 1: n=92 (21.7%) | 3: n=15 (3.5%) | 4: n=6 (1.4%)
5,ant_medico,Chi-Square,0.0013,G0vG1: 0.001,-1: n=22 (62.9%) | 1: n=10 (28.6%) | 3: n=2 (5.7%) | 5: n=1 (2.9%),-1: n=334 (78.8%) | 1: n=76 (17.9%) | 3: n=14 (3.3%)

======================================================================
COMBINACIÓN 3 | K = 2 | SILHOUETTE = 0.7075
======================================================================

TAMAÑO DE GRUPOS:
cluster   0    1
count    31  428

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1
peso_ini_gest         72.61 ± 17.03     66.44 ± 14.26
peso_fin_gest         84.67 ± 18.02     78.15 ± 14.88
aumento_peso_gest      12.09 ± 6.50      11.70 ± 5.42
talla                 161.47 ± 5.23     164.00 ± 6.22
imc_ini_gest           27.87 ± 6.85      24.68 ± 4.95
edad_materna_gest      37.35 ± 4.49      35.40 ± 4.66
tas_1tri             121.55 ± 12.19    113.83 ± 11.36
tad_1tri               78.11 ± 9.75      72.68 ± 8.09
eg_eco_1tri            12.76 ± 0.54      12.73 ± 0.61
eg_parto               34.91 ± 3.62      39.33 ± 1.70
peso_rn            2202.16 ± 885.88  3128.96 ± 554.46
apgar_1min              5.91 ± 2.09       8.96 ± 0.44
apgar_5min              7.80 ± 1.66       9.92 ± 0.29
apgar_10min             8.84 ± 0.53       9.99 ± 0.11
ratio_MoM             57.58 ± 96.99      3.71 ± 13.44
sflt1_MoM               4.82 ± 5.52       1.54 ± 1.16
plgf_MoM                0.81 ± 1.57       1.34 ± 1.05

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0338,G0vG1: 0.034,67.00 ± 19.00,63.70 ± 17.15
1,peso_fin_gest,U Mann-Whitney,0.0440,G0vG1: 0.044,82.00 ± 21.11,76.00 ± 17.00
2,aumento_peso_gest,U Mann-Whitney,0.8109,G0vG1: 0.811,11.76 ± 5.05,11.52 ± 5.30
3,talla,U Mann-Whitney,0.0236,G0vG1: 0.024,160.00 ± 8.25,164.00 ± 8.00
4,imc_ini_gest,U Mann-Whitney,0.0035,G0vG1: 0.004,26.14 ± 7.64,23.47 ± 6.29
5,edad_materna_gest,U Mann-Whitney,0.0296,G0vG1: 0.030,36.60 ± 6.07,35.48 ± 6.44
6,tas_1tri,U Mann-Whitney,0.0007,G0vG1: 0.001,119.76 ± 16.50,113.02 ± 14.00
7,tad_1tri,U Mann-Whitney,0.0003,G0vG1: 0.000,77.00 ± 7.07,72.41 ± 9.00
8,eg_eco_1tri,U Mann-Whitney,0.9328,G0vG1: 0.933,12.80 ± 0.50,12.80 ± 0.50
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,35.20 ± 4.80,39.60 ± 2.00
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,2410.00 ± 1330.00,3140.00 ± 671.25
11,apgar_1min,U Mann-Whitney,0.0000,G0vG1: 0.000,6.00 ± 4.00,9.00 ± 0.00
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,8.00 ± 2.00,10.00 ± 0.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,9.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,7.72 ± 69.45,1.69 ± 1.66
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,2.95 ± 4.55,1.26 ± 0.65
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,0.32 ± 0.62,1.18 ± 0.96

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1
diam_telediastolico           44.08 ± 5.19   45.01 ± 5.45
diam_telesistolico            28.21 ± 4.34   29.98 ± 4.52
dtsvi_indexado                15.14 ± 2.92   17.02 ± 2.72
septo_iv_diastole              8.91 ± 2.01    9.42 ± 9.80
pared_posterior_vi_diastole    7.72 ± 0.95    8.60 ± 8.75
diam_ai                       34.62 ± 4.84   33.32 ± 4.62
ai_volumen                   38.87 ± 12.38  36.96 ± 13.29
ad_volumen                   32.94 ± 13.75  32.75 ± 15.43
tapse                         25.89 ± 3.94  26.06 ± 17.39
e_mitral                     73.90 ± 15.99  79.49 ± 62.43
e_e                            3.95 ± 1.24    4.10 ± 3.38
gc_tsvi                       8.00 ± 11.29    6.36 ± 4.94
urato_acidourico               3.93 ± 0.77    4.20 ± 1.46

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.2785,G0vG1: 0.278,43.00 ± 5.50,45.00 ± 6.00
1,diam_telesistolico,U Mann-Whitney,0.0820,G0vG1: 0.082,28.50 ± 7.25,30.00 ± 5.75
2,dtsvi_indexado,U Mann-Whitney,0.0025,G0vG1: 0.002,15.04 ± 3.75,17.04 ± 3.53
3,septo_iv_diastole,U Mann-Whitney,0.0783,G0vG1: 0.078,9.15 ± 1.88,8.00 ± 2.00
4,pared_posterior_vi_diastole,U Mann-Whitney,0.3627,G0vG1: 0.363,7.95 ± 1.07,7.20 ± 2.07
5,diam_ai,U Mann-Whitney,0.1622,G0vG1: 0.162,35.00 ± 6.00,34.00 ± 7.00
6,ai_volumen,U Mann-Whitney,0.3324,G0vG1: 0.332,37.20 ± 17.95,35.00 ± 15.68
7,ad_volumen,U Mann-Whitney,0.9689,G0vG1: 0.969,31.10 ± 15.45,30.40 ± 15.50
8,tapse,U Mann-Whitney,0.1334,G0vG1: 0.133,26.50 ± 4.90,24.80 ± 6.00
9,e_mitral,U Mann-Whitney,0.6432,G0vG1: 0.643,73.50 ± 21.45,74.20 ± 18.40
10,e_e,U Mann-Whitney,0.4862,G0vG1: 0.486,3.95 ± 1.14,3.72 ± 1.17
11,gc_tsvi,U Mann-Whitney,0.3543,G0vG1: 0.354,5.40 ± 1.00,5.70 ± 1.50
12,urato_acidourico,U Mann-Whitney,0.4042,G0vG1: 0.404,3.91 ± 0.93,4.05 ± 1.14

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1
ta_sistolica                   126.80 ± 19.09  114.70 ± 14.54
ta_diastolica                   80.37 ± 13.79    75.08 ± 9.52
frec_cardiaca                   82.63 ± 11.34   78.73 ± 11.86
right_1peak_systolic_velocity    30.50 ± 7.87    31.46 ± 8.97
right_2peak_systolic_velocity    22.43 ± 7.84    21.82 ± 7.16
right_pulsatility_index           1.82 ± 0.48     1.77 ± 0.44
right_psv_ratio                   0.73 ± 0.14     0.70 ± 0.12
left_1peak_systolic_velocity    35.40 ± 10.61    33.32 ± 9.25
left_2peak_systolic_velocity     26.38 ± 8.94    23.37 ± 7.46
left_pulsatility_index            1.72 ± 0.46     1.77 ± 1.20
left_psv_ratio                    0.75 ± 0.14     0.70 ± 0.12
right_mean                        0.55 ± 0.09     0.53 ± 0.10
left_mean                         0.58 ± 0.10     0.55 ± 0.10

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0002,G0vG1: 0.000,128.00 ± 18.25,114.00 ± 17.00
1,ta_diastolica,U Mann-Whitney,0.0050,G0vG1: 0.005,81.50 ± 17.25,75.00 ± 13.00
2,frec_cardiaca,Prueba T,0.0815,G0vG1: 0.074,82.63 ± 11.34,78.73 ± 11.86
3,right_1peak_systolic_velocity,U Mann-Whitney,0.7831,G0vG1: 0.783,31.70 ± 12.32,31.30 ± 11.65
4,right_2peak_systolic_velocity,U Mann-Whitney,0.8168,G0vG1: 0.817,22.55 ± 12.83,21.20 ± 10.15
5,right_pulsatility_index,U Mann-Whitney,0.6467,G0vG1: 0.647,1.77 ± 0.49,1.75 ± 0.50
6,right_psv_ratio,Prueba T,0.0958,G0vG1: 0.182,0.73 ± 0.14,0.70 ± 0.12
7,left_1peak_systolic_velocity,U Mann-Whitney,0.2561,G0vG1: 0.256,36.10 ± 15.68,33.50 ± 11.60
8,left_2peak_systolic_velocity,U Mann-Whitney,0.0625,G0vG1: 0.063,26.35 ± 12.70,22.70 ± 9.00
9,left_pulsatility_index,U Mann-Whitney,0.7832,G0vG1: 0.783,1.72 ± 0.53,1.70 ± 0.53
10,left_psv_ratio,U Mann-Whitney,0.0892,G0vG1: 0.089,0.75 ± 0.19,0.70 ± 0.16
11,right_mean,U Mann-Whitney,0.1423,G0vG1: 0.142,0.55 ± 0.11,0.52 ± 0.10
12,left_mean,U Mann-Whitney,0.0296,G0vG1: 0.030,0.58 ± 0.16,0.53 ± 0.12

ANALÍTICA

                                  Grupo 0               Grupo 1
hemoglobina                125.17 ± 27.06        126.53 ± 23.97
hematocrito                   0.39 ± 0.03           0.39 ± 0.03
leucocitos              6380.42 ± 1943.12     6567.32 ± 1598.56
plaquetas            278958.33 ± 93700.02  271030.93 ± 61637.11
glucosa                     88.62 ± 10.72         87.58 ± 11.65
sodio                       139.00 ± 2.78         139.68 ± 1.72
potasio                       4.21 ± 0.28           4.22 ± 0.28
urato_acidourico              3.93 ± 0.77           4.20 ± 1.46
hemoglobina_glicada           5.52 ± 0.47           5.37 ± 0.38
ast                          21.67 ± 5.84         21.75 ± 10.40
alt                         20.04 ± 10.87         18.31 ± 13.21
bilirubina_total              0.58 ± 0.19           0.67 ± 0.32
ldh                        175.29 ± 27.38        165.03 ± 26.55
vldl                        17.14 ± 10.37          14.53 ± 8.81
ldl                        117.09 ± 31.41        111.68 ± 28.63
hdl                         55.34 ± 13.18         60.04 ± 14.11
colesterol_total           189.58 ± 36.29        186.14 ± 32.07
trigliceridos               85.31 ± 51.24         73.47 ± 43.15
prote_totales_orina          7.67 ± 21.40          2.33 ± 12.25

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.7912,G0vG1: 0.791,128.00 ± 18.00,131.00 ± 14.00
1,hematocrito,U Mann-Whitney,0.9925,G0vG1: 0.993,0.39 ± 0.05,0.39 ± 0.04
2,leucocitos,U Mann-Whitney,0.6194,G0vG1: 0.619,6150.00 ± 2532.50,6310.00 ± 2035.00
3,plaquetas,U Mann-Whitney,0.7353,G0vG1: 0.735,280000.00 ± 120000.00,264000.00 ± 79500.00
4,glucosa,U Mann-Whitney,0.5014,G0vG1: 0.501,87.00 ± 9.00,87.00 ± 9.00
5,sodio,U Mann-Whitney,0.4934,G0vG1: 0.493,139.50 ± 3.00,140.00 ± 3.00
6,potasio,U Mann-Whitney,0.9972,G0vG1: 0.997,4.23 ± 0.26,4.20 ± 0.33
7,urato_acidourico,U Mann-Whitney,0.4042,G0vG1: 0.404,3.91 ± 0.93,4.05 ± 1.14
8,hemoglobina_glicada,U Mann-Whitney,0.0707,G0vG1: 0.071,5.40 ± 0.30,5.30 ± 0.30
9,ast,U Mann-Whitney,0.6276,G0vG1: 0.628,20.00 ± 6.75,20.00 ± 6.00
10,alt,U Mann-Whitney,0.3424,G0vG1: 0.342,16.00 ± 10.50,15.00 ± 8.00
11,bilirubina_total,U Mann-Whitney,0.2520,G0vG1: 0.252,0.56 ± 0.22,0.57 ± 0.30
12,ldh,U Mann-Whitney,0.1459,G0vG1: 0.146,168.50 ± 45.00,162.00 ± 30.00
13,vldl,U Mann-Whitney,0.1232,G0vG1: 0.123,14.98 ± 8.29,11.59 ± 7.13
14,ldl,U Mann-Whitney,0.3644,G0vG1: 0.364,116.66 ± 39.61,107.21 ± 37.56
15,hdl,U Mann-Whitney,0.1099,G0vG1: 0.110,53.02 ± 19.35,59.21 ± 18.19
16,colesterol_total,U Mann-Whitney,0.3594,G0vG1: 0.359,195.44 ± 41.03,183.05 ± 39.48
17,trigliceridos,U Mann-Whitney,0.1523,G0vG1: 0.152,74.34 ± 40.61,57.53 ± 32.75
18,prote_totales_orina,U Mann-Whitney,0.3737,G0vG1: 0.374,0.08 ± 0.10,0.08 ± 0.05

SCORES CATEGÓRICOS

                                               Grupo 0      Grupo 1
Cat_Dieta: Adherencia moderada              21 (67.7%)  264 (61.7%)
Cat_Dieta: Alta adherencia                    0 (0.0%)    25 (5.8%)
Cat_Dieta: Baja adherencia                  10 (32.3%)  139 (32.5%)
Cat_Actividad: Actividad física alta        28 (96.6%)  385 (90.8%)
Cat_Actividad: Actividad física baja          0 (0.0%)    11 (2.6%)
Cat_Actividad: Actividad física moderada      1 (3.4%)    28 (6.6%)
Cat_Estres: Nivel de estrés alto            11 (36.7%)  151 (35.4%)
Cat_Estres: Nivel de estrés bajo              2 (6.7%)   50 (11.7%)
Cat_Estres: Nivel de estrés moderado        15 (50.0%)  213 (49.9%)
Cat_Estres: Nivel de estrés muy alto          2 (6.7%)    13 (3.0%)
Cat_Memoria: Deterioro leve                  4 (13.8%)   61 (14.4%)
Cat_Memoria: Disfunción moderada-grave       3 (10.3%)    41 (9.6%)
Cat_Memoria: Función normal (lapsus leves)  14 (48.3%)  246 (57.9%)
Cat_Memoria: Rendimiento de memoria óptimo   8 (27.6%)   77 (18.1%)
Cat_SCL90R: EN RIESGO                        7 (22.6%)   50 (11.9%)
Cat_SCL90R: Normal / Sin riesgo              4 (12.9%)   85 (20.2%)
Cat_SCL90R: Patología severa                20 (64.5%)  285 (67.9%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.3712,G0vG1: 0.371,Adherencia moderada: n=21 (67.7%) | Baja adherencia: n=10 (32.3%),Adherencia moderada: n=264 (61.7%) | Alta adherencia: n=25 (5.8%) | Baja adherencia: n=139 (32.5%)
1,Cat_Actividad,Chi-Square,0.5291,G0vG1: 0.045,Actividad física alta: n=28 (96.6%) | Actividad física moderada: n=1 (3.4%),Actividad física alta: n=385 (90.8%) | Actividad física baja: n=11 (2.6%) | Actividad física moderada: n=28 (6.6%)
2,Cat_Estres,Chi-Square,0.6236,G0vG1: 0.104,Nivel de estrés alto: n=11 (36.7%) | Nivel de estrés bajo: n=2 (6.7%) | Nivel de estrés moderado: n=15 (50.0%) | Nivel de estrés muy alto: n=2 (6.7%),Nivel de estrés alto: n=151 (35.4%) | Nivel de estrés bajo: n=50 (11.7%) | Nivel de estrés moderado: n=213 (49.9%) | Nivel de estrés muy alto: n=13 (3.0%)
3,Cat_Memoria,Chi-Square,0.6243,G0vG1: 0.032,Deterioro leve: n=4 (13.8%) | Disfunción moderada-grave: n=3 (10.3%) | Función normal (lapsus leves): n=14 (48.3%) | Rendimiento de memoria óptimo: n=8 (27.6%),Deterioro leve: n=61 (14.4%) | Disfunción moderada-grave: n=41 (9.6%) | Función normal (lapsus leves): n=246 (57.9%) | Rendimiento de memoria óptimo: n=77 (18.1%)
4,Cat_SCL90R,Chi-Square,0.1792,G0vG1: 0.253,EN RIESGO: n=7 (22.6%) | Normal / Sin riesgo: n=4 (12.9%) | Patología severa: n=20 (64.5%),EN RIESGO: n=50 (11.9%) | Normal / Sin riesgo: n=85 (20.2%) | Patología severa: n=285 (67.9%)

ANTECEDENTES

                                Grupo 0      Grupo 1
trastorno_hipertensivo: 0.0  10 (32.3%)  317 (74.1%)
trastorno_hipertensivo: 1.0  21 (67.7%)  111 (25.9%)
comp_placentaria: 0.0        18 (58.1%)  372 (86.9%)
comp_placentaria: 1.0        13 (41.9%)   56 (13.1%)
comp_maternaGrave: 0.0       16 (51.6%)  402 (93.9%)
comp_maternaGrave: 1.0       15 (48.4%)    26 (6.1%)
comp_metabolica: 0.0         28 (90.3%)  383 (89.5%)
comp_metabolica: 1.0           3 (9.7%)   45 (10.5%)
ant_obstetrico: -1           20 (64.5%)  316 (73.8%)
ant_obstetrico: 1             8 (25.8%)   91 (21.3%)
ant_obstetrico: 3              3 (9.7%)    15 (3.5%)
ant_obstetrico: 4              0 (0.0%)     6 (1.4%)
ant_medico: -1               18 (58.1%)  338 (79.0%)
ant_medico: 1                10 (32.3%)   76 (17.8%)
ant_medico: 3                  2 (6.5%)    14 (3.3%)
ant_medico: 5                  1 (3.2%)     0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=10 (32.3%) | 1.0: n=21 (67.7%),0.0: n=317 (74.1%) | 1.0: n=111 (25.9%)
1,comp_placentaria,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=18 (58.1%) | 1.0: n=13 (41.9%),0.0: n=372 (86.9%) | 1.0: n=56 (13.1%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=16 (51.6%) | 1.0: n=15 (48.4%),0.0: n=402 (93.9%) | 1.0: n=26 (6.1%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=28 (90.3%) | 1.0: n=3 (9.7%),0.0: n=383 (89.5%) | 1.0: n=45 (10.5%)
4,ant_obstetrico,Chi-Square,0.2767,G0vG1: 0.277,-1: n=20 (64.5%) | 1: n=8 (25.8%) | 3: n=3 (9.7%),-1: n=316 (73.8%) | 1: n=91 (21.3%) | 3: n=15 (3.5%) | 4: n=6 (1.4%)
5,ant_medico,Chi-Square,0.0002,G0vG1: 0.000,-1: n=18 (58.1%) | 1: n=10 (32.3%) | 3: n=2 (6.5%) | 5: n=1 (3.2%),-1: n=338 (79.0%) | 1: n=76 (17.8%) | 3: n=14 (3.3%)

======================================================================
COMBINACIÓN 4 | K = 3 | SILHOUETTE = 0.4986
======================================================================

TAMAÑO DE GRUPOS:
cluster    0   1    2
count    100  33  326

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1           Grupo 2
peso_ini_gest         87.44 ± 12.27     70.10 ± 13.42      60.22 ± 7.62
peso_fin_gest         97.68 ± 13.70     82.20 ± 14.53      72.36 ± 9.71
aumento_peso_gest      10.29 ± 6.14      12.20 ± 6.32      12.12 ± 5.13
talla                 164.83 ± 6.22     162.05 ± 5.60     163.70 ± 6.20
imc_ini_gest           32.21 ± 4.36      26.65 ± 4.88      22.47 ± 2.58
edad_materna_gest      35.35 ± 5.30      36.58 ± 4.46      35.48 ± 4.48
tas_1tri             119.48 ± 10.87    120.78 ± 12.84    112.13 ± 10.92
tad_1tri               75.35 ± 8.02      77.55 ± 9.46      71.88 ± 8.00
eg_eco_1tri            12.86 ± 0.61      12.76 ± 0.43      12.69 ± 0.62
eg_parto               39.15 ± 1.58      35.58 ± 4.11      39.34 ± 1.74
peso_rn            3230.29 ± 529.91  2324.15 ± 955.31  3091.21 ± 559.04
apgar_1min              8.85 ± 0.90       6.58 ± 2.12       8.94 ± 0.53
apgar_5min              9.92 ± 0.31       7.93 ± 1.65       9.92 ± 0.31
apgar_10min             9.99 ± 0.10       8.79 ± 0.42      10.00 ± 0.04
ratio_MoM               3.35 ± 5.56     53.36 ± 95.29      3.91 ± 15.13
sflt1_MoM               1.54 ± 1.03       4.39 ± 5.49       1.57 ± 1.23
plgf_MoM                1.08 ± 0.79       1.05 ± 1.72       1.40 ± 1.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,85.60 ± 11.62,67.00 ± 18.90,60.00 ± 11.72
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,95.50 ± 13.25,82.00 ± 20.93,72.00 ± 14.45
2,aumento_peso_gest,Kruskal-Wallis,0.0072,G0vG1: 0.487 | G0vG2: 0.005 | G1vG2: 1.000,10.00 ± 7.78,12.00 ± 5.10,11.82 ± 5.15
3,talla,Kruskal-Wallis,0.1088,G0vG1: 0.118 | G0vG2: 0.627 | G1vG2: 0.411,165.00 ± 8.25,162.00 ± 9.50,163.00 ± 8.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,31.34 ± 5.95,24.97 ± 7.85,22.31 ± 4.13
5,edad_materna_gest,Kruskal-Wallis,0.4527,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.593,35.76 ± 7.30,35.99 ± 5.74,35.47 ± 6.03
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,118.37 ± 15.00,119.00 ± 15.00,112.00 ± 14.00
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.425 | G0vG2: 0.000 | G1vG2: 0.000,75.00 ± 9.25,77.00 ± 7.00,72.00 ± 9.75
8,eg_eco_1tri,Kruskal-Wallis,0.1540,G0vG1: 1.000 | G0vG2: 0.165 | G1vG2: 1.000,12.80 ± 0.70,12.80 ± 0.44,12.72 ± 0.50
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.495 | G1vG2: 0.000,39.30 ± 2.02,35.30 ± 5.60,39.60 ± 2.00
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.143 | G1vG2: 0.000,3180.00 ± 691.25,2450.00 ± 1540.00,3120.00 ± 697.50
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,9.00 ± 0.00,7.00 ± 3.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,10.00 ± 0.00,8.77 ± 2.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,10.00 ± 0.00,9.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0001,G0vG1: 0.001 | G0vG2: 0.955 | G1vG2: 0.000,1.70 ± 2.50,6.48 ± 61.25,1.68 ± 1.43
15,sflt1_MoM,Kruskal-Wallis,0.0001,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,1.27 ± 0.92,2.04 ± 4.80,1.26 ± 0.63
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.003 | G0vG2: 0.003 | G1vG2: 0.000,0.89 ± 0.89,0.42 ± 0.76,1.27 ± 0.92

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1        Grupo 2
diam_telediastolico           47.60 ± 4.84   44.72 ± 5.04   44.19 ± 5.41
diam_telesistolico            32.03 ± 5.30   29.27 ± 4.40   29.28 ± 4.08
dtsvi_indexado                16.30 ± 2.75   16.26 ± 2.64   17.14 ± 2.75
septo_iv_diastole              9.07 ± 1.85  11.81 ± 15.79   9.27 ± 10.14
pared_posterior_vi_diastole    8.00 ± 1.82   9.92 ± 10.50    8.58 ± 9.46
diam_ai                       36.85 ± 3.52   35.30 ± 4.87   32.16 ± 4.33
ai_volumen                   44.90 ± 15.96  40.12 ± 12.42  34.51 ± 11.37
ad_volumen                   38.92 ± 13.53  32.69 ± 13.52  31.05 ± 15.53
tapse                        27.59 ± 29.12   26.58 ± 3.99  25.55 ± 11.87
e_mitral                     70.91 ± 13.51  76.89 ± 16.31  81.92 ± 71.08
e_e                            3.72 ± 1.02    4.00 ± 1.13    4.21 ± 3.84
gc_tsvi                        7.13 ± 5.53   7.99 ± 10.76    6.12 ± 4.77
urato_acidourico               4.48 ± 1.00    4.13 ± 0.70    4.08 ± 1.57

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.035 | G0vG2: 0.000 | G1vG2: 1.000,47.00 ± 7.00,43.00 ± 6.00,44.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0001,G0vG1: 0.098 | G0vG2: 0.000 | G1vG2: 1.000,31.50 ± 8.00,29.00 ± 8.00,29.00 ± 5.00
2,dtsvi_indexado,Kruskal-Wallis,0.0108,G0vG1: 1.000 | G0vG2: 0.022 | G1vG2: 0.262,15.81 ± 3.85,16.46 ± 3.76,17.16 ± 3.28
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.149,9.00 ± 2.30,8.90 ± 2.30,8.00 ± 2.00
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0096,G0vG1: 1.000 | G0vG2: 0.023 | G1vG2: 0.206,8.00 ± 2.00,8.00 ± 1.60,7.00 ± 1.88
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.565 | G0vG2: 0.000 | G1vG2: 0.003,37.00 ± 4.00,36.00 ± 5.50,32.00 ± 5.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.069,42.25 ± 18.75,41.60 ± 19.50,33.00 ± 14.60
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.070 | G0vG2: 0.000 | G1vG2: 1.000,39.05 ± 18.20,31.00 ± 15.70,29.00 ± 14.93
8,tapse,Kruskal-Wallis,0.0508,G0vG1: 0.064 | G0vG2: 1.000 | G1vG2: 0.054,24.00 ± 5.00,27.00 ± 5.00,25.00 ± 6.00
9,e_mitral,Kruskal-Wallis,0.0094,G0vG1: 0.283 | G0vG2: 0.008 | G1vG2: 1.000,70.90 ± 16.15,75.55 ± 25.43,75.25 ± 18.10
10,e_e,Kruskal-Wallis,0.1519,G0vG1: 0.268 | G0vG2: 0.348 | G1vG2: 1.000,3.56 ± 1.16,3.90 ± 0.80,3.77 ± 1.17
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.113 | G0vG2: 0.000 | G1vG2: 1.000,6.60 ± 1.88,5.60 ± 1.40,5.50 ± 1.40
12,urato_acidourico,Kruskal-Wallis,0.0033,G0vG1: 0.693 | G0vG2: 0.002 | G1vG2: 1.000,4.38 ± 1.43,4.00 ± 1.05,3.98 ± 1.09

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1         Grupo 2
ta_sistolica                   124.61 ± 15.56  127.31 ± 19.00  111.55 ± 12.64
ta_diastolica                    80.89 ± 9.24   80.91 ± 13.52    73.21 ± 8.83
frec_cardiaca                   82.51 ± 12.11   81.84 ± 10.79   77.64 ± 11.63
right_1peak_systolic_velocity    32.21 ± 9.87    31.38 ± 8.64    31.15 ± 8.62
right_2peak_systolic_velocity    22.14 ± 7.51    23.00 ± 7.80    21.66 ± 7.05
right_pulsatility_index           1.77 ± 0.40     1.83 ± 0.47     1.77 ± 0.45
right_psv_ratio                   0.69 ± 0.12     0.74 ± 0.14     0.70 ± 0.12
left_1peak_systolic_velocity    35.79 ± 10.10   34.99 ± 10.43    32.60 ± 8.87
left_2peak_systolic_velocity     24.78 ± 8.23    25.47 ± 8.73    23.01 ± 7.22
left_pulsatility_index            1.97 ± 2.37     1.74 ± 0.46     1.71 ± 0.42
left_psv_ratio                    0.69 ± 0.12     0.73 ± 0.14     0.71 ± 0.12
right_mean                        0.59 ± 0.14     0.53 ± 0.07     0.52 ± 0.08
left_mean                         0.61 ± 0.12     0.56 ± 0.09     0.53 ± 0.08

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.992 | G0vG2: 0.000 | G1vG2: 0.000,123.00 ± 15.00,128.00 ± 18.75,110.00 ± 15.25
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,81.00 ± 11.50,82.00 ± 15.25,74.00 ± 11.00
2,frec_cardiaca,ANOVA,0.0006,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.169,82.51 ± 12.11,81.84 ± 10.79,77.64 ± 11.63
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5714,G0vG1: 1.000 | G0vG2: 0.891 | G1vG2: 1.000,31.40 ± 13.50,31.70 ± 11.97,31.20 ± 11.18
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.6478,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,21.60 ± 10.80,22.90 ± 12.85,21.05 ± 9.57
5,right_pulsatility_index,Kruskal-Wallis,0.6645,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.79 ± 0.50,1.83 ± 0.51,1.73 ± 0.50
6,right_psv_ratio,ANOVA,0.1925,G0vG1: 0.411 | G0vG2: 1.000 | G1vG2: 0.454,0.69 ± 0.12,0.74 ± 0.14,0.70 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0029,G0vG1: 1.000 | G0vG2: 0.002 | G1vG2: 0.612,36.20 ± 13.90,36.00 ± 15.95,32.45 ± 10.85
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.0350,G0vG1: 1.000 | G0vG2: 0.063 | G1vG2: 0.407,25.10 ± 10.30,24.95 ± 11.90,22.50 ± 8.32
9,left_pulsatility_index,Kruskal-Wallis,0.9482,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.68 ± 0.55,1.72 ± 0.51,1.72 ± 0.54
10,left_psv_ratio,Kruskal-Wallis,0.4748,G0vG1: 0.651 | G0vG2: 1.000 | G1vG2: 1.000,0.69 ± 0.13,0.75 ± 0.18,0.70 ± 0.16
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 0.134 | G0vG2: 0.000 | G1vG2: 0.785,0.56 ± 0.15,0.53 ± 0.09,0.51 ± 0.10
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.259 | G0vG2: 0.000 | G1vG2: 0.112,0.60 ± 0.12,0.56 ± 0.17,0.52 ± 0.10

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2
hemoglobina,127.82 ± 17.91,121.53 ± 35.16,126.55 ± 24.43
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,6945.51 ± 1679.17,6492.80 ± 1741.84,6437.38 ± 1581.79
plaquetas,280521.74 ± 61550.46,277040.00 ± 91470.61,268248.87 ± 61715.67
glucosa,91.09 ± 15.36,90.16 ± 11.76,86.31 ± 9.84
sodio,139.33 ± 2.12,139.28 ± 1.74,139.76 ± 1.72
potasio,4.22 ± 0.31,4.24 ± 0.29,4.21 ± 0.27
urato_acidourico,4.48 ± 1.00,4.13 ± 0.70,4.08 ± 1.57
hemoglobina_glicada,5.51 ± 0.47,5.54 ± 0.49,5.32 ± 0.32
ast,21.67 ± 12.58,21.16 ± 5.02,21.84 ± 9.72
alt,20.39 ± 20.54,19.24 ± 8.86,17.75 ± 10.10
bilirubina_total,0.59 ± 0.32,0.57 ± 0.18,0.69 ± 0.31
ldh,173.14 ± 28.95,174.76 ± 28.05,162.50 ± 25.21
vldl,19.17 ± 10.76,17.79 ± 10.59,13.00 ± 7.48
ldl,110.99 ± 29.35,120.73 ± 26.82,111.46 ± 28.85
hdl,53.47 ± 13.55,55.28 ± 13.44,62.12 ± 13.65
colesterol_total,183.60 ± 32.21,193.81 ± 30.81,186.44 ± 32.58
trigliceridos,95.64 ± 52.84,88.55 ± 52.35,66.13 ± 36.71
prote_totales_orina,2.25 ± 12.19,7.34 ± 20.96,2.36 ± 12.33

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.9451,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,131.00 ± 10.00,129.00 ± 21.00,131.00 ± 14.00
1,hematocrito,Kruskal-Wallis,0.9318,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.39 ± 0.03,0.40 ± 0.05,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0719,G0vG1: 0.546 | G0vG2: 0.071 | G1vG2: 1.000,6650.00 ± 1920.00,6150.00 ± 1990.00,6250.00 ± 1940.00
3,plaquetas,Kruskal-Wallis,0.4670,G0vG1: 1.000 | G0vG2: 0.654 | G1vG2: 1.000,276000.00 ± 75000.00,275000.00 ± 114000.00,263000.00 ± 83000.00
4,glucosa,Kruskal-Wallis,0.0137,G0vG1: 1.000 | G0vG2: 0.026 | G1vG2: 0.280,89.00 ± 11.00,87.00 ± 9.00,86.00 ± 10.00
5,sodio,Kruskal-Wallis,0.1952,G0vG1: 1.000 | G0vG2: 0.375 | G1vG2: 0.713,139.00 ± 3.00,139.00 ± 2.00,140.00 ± 2.00
6,potasio,Kruskal-Wallis,0.7827,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,4.18 ± 0.34,4.25 ± 0.28,4.21 ± 0.32
7,urato_acidourico,Kruskal-Wallis,0.0033,G0vG1: 0.693 | G0vG2: 0.002 | G1vG2: 1.000,4.38 ± 1.43,4.00 ± 1.05,3.98 ± 1.09
8,hemoglobina_glicada,Kruskal-Wallis,0.0002,G0vG1: 1.000 | G0vG2: 0.001 | G1vG2: 0.037,5.50 ± 0.40,5.40 ± 0.30,5.30 ± 0.27
9,ast,Kruskal-Wallis,0.2795,G0vG1: 0.902 | G0vG2: 0.362 | G1vG2: 1.000,19.00 ± 5.00,20.00 ± 5.00,20.00 ± 5.00
10,alt,Kruskal-Wallis,0.4615,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.630,15.00 ± 12.00,16.00 ± 9.00,15.00 ± 8.00
11,bilirubina_total,Kruskal-Wallis,0.0023,G0vG1: 1.000 | G0vG2: 0.004 | G1vG2: 0.190,0.54 ± 0.23,0.54 ± 0.19,0.62 ± 0.32
12,ldh,Kruskal-Wallis,0.0107,G0vG1: 1.000 | G0vG2: 0.028 | G1vG2: 0.175,168.00 ± 31.00,169.00 ± 44.00,159.50 ± 28.25
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.029,15.87 ± 13.73,15.69 ± 9.45,10.88 ± 5.71
14,ldl,Kruskal-Wallis,0.2615,G0vG1: 0.571 | G0vG2: 1.000 | G1vG2: 0.292,106.90 ± 37.66,118.17 ± 21.89,106.29 ± 37.42
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.067,52.63 ± 15.09,54.95 ± 19.35,61.15 ± 17.41
16,colesterol_total,Kruskal-Wallis,0.2423,G0vG1: 0.271 | G0vG2: 1.000 | G1vG2: 0.403,180.73 ± 35.22,194.66 ± 27.09,183.05 ± 40.64
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.041,78.77 ± 68.14,77.88 ± 46.91,53.98 ± 24.78
18,prote_totales_orina,Kruskal-Wallis,0.7565,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.08 ± 0.04,0.08 ± 0.08,0.08 ± 0.05

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2
Cat_Dieta: Adherencia moderada,44 (44.0%),22 (66.7%),219 (67.2%)
Cat_Dieta: Alta adherencia,4 (4.0%),0 (0.0%),21 (6.4%)
Cat_Dieta: Baja adherencia,52 (52.0%),11 (33.3%),86 (26.4%)
Cat_Actividad: Actividad física alta,85 (85.0%),30 (96.8%),298 (92.5%)
Cat_Actividad: Actividad física baja,2 (2.0%),0 (0.0%),9 (2.8%)
Cat_Actividad: Actividad física moderada,13 (13.0%),1 (3.2%),15 (4.7%)
Cat_Estres: Nivel de estrés alto,44 (44.4%),12 (37.5%),106 (32.5%)
Cat_Estres: Nivel de estrés bajo,12 (12.1%),1 (3.1%),39 (12.0%)
Cat_Estres: Nivel de estrés moderado,38 (38.4%),17 (53.1%),173 (53.1%)
Cat_Estres: Nivel de estrés muy alto,5 (5.1%),2 (6.2%),8 (2.5%)
Cat_Memoria: Deterioro leve,17 (17.2%),5 (16.1%),43 (13.3%)
Cat_Memoria: Disfunción moderada-grave,10 (10.1%),3 (9.7%),31 (9.6%)
Cat_Memoria: Función normal (lapsus leves),57 (57.6%),16 (51.6%),187 (57.7%)
Cat_Memoria: Rendimiento de memoria óptimo,15 (15.2%),7 (22.6%),63 (19.4%)
Cat_SCL90R: EN RIESGO,8 (8.2%),7 (21.2%),42 (13.1%)
Cat_SCL90R: Normal / Sin riesgo,15 (15.5%),3 (9.1%),71 (22.1%)
Cat_SCL90R: Patología severa,74 (76.3%),23 (69.7%),208 (64.8%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.0001,G0vG1: 0.172 | G0vG2: 0.000 | G1vG2: 0.792,Adherencia moderada: n=44 (44.0%) | Alta adherencia: n=4 (4.0%) | Baja adherencia: n=52 (52.0%),Adherencia moderada: n=22 (66.7%) | Baja adherencia: n=11 (33.3%),Adherencia moderada: n=219 (67.2%) | Alta adherencia: n=21 (6.4%) | Baja adherencia: n=86 (26.4%)
1,Cat_Actividad,Chi-Square,0.0340,G0vG1: 0.082 | G0vG2: 0.057 | G1vG2: 0.460,Actividad física alta: n=85 (85.0%) | Actividad física baja: n=2 (2.0%) | Actividad física moderada: n=13 (13.0%),Actividad física alta: n=30 (96.8%) | Actividad física moderada: n=1 (3.2%),Actividad física alta: n=298 (92.5%) | Actividad física baja: n=9 (2.8%) | Actividad física moderada: n=15 (4.7%)
2,Cat_Estres,Chi-Square,0.0887,G0vG1: 1.000 | G0vG2: 0.071 | G1vG2: 0.026,Nivel de estrés alto: n=44 (44.4%) | Nivel de estrés bajo: n=12 (12.1%) | Nivel de estrés moderado: n=38 (38.4%) | Nivel de estrés muy alto: n=5 (5.1%),Nivel de estrés alto: n=12 (37.5%) | Nivel de estrés bajo: n=1 (3.1%) | Nivel de estrés moderado: n=17 (53.1%) | Nivel de estrés muy alto: n=2 (6.2%),Nivel de estrés alto: n=106 (32.5%) | Nivel de estrés bajo: n=39 (12.0%) | Nivel de estrés moderado: n=173 (53.1%) | Nivel de estrés muy alto: n=8 (2.5%)
3,Cat_Memoria,Chi-Square,0.9102,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.221,Deterioro leve: n=17 (17.2%) | Disfunción moderada-grave: n=10 (10.1%) | Función normal (lapsus leves): n=57 (57.6%) | Rendimiento de memoria óptimo: n=15 (15.2%),Deterioro leve: n=5 (16.1%) | Disfunción moderada-grave: n=3 (9.7%) | Función normal (lapsus leves): n=16 (51.6%) | Rendimiento de memoria óptimo: n=7 (22.6%),Deterioro leve: n=43 (13.3%) | Disfunción moderada-grave: n=31 (9.6%) | Función normal (lapsus leves): n=187 (57.7%) | Rendimiento de memoria óptimo: n=63 (19.4%)
4,Cat_SCL90R,Chi-Square,0.0707,G0vG1: 0.410 | G0vG2: 0.439 | G1vG2: 0.629,EN RIESGO: n=8 (8.2%) | Normal / Sin riesgo: n=15 (15.5%) | Patología severa: n=74 (76.3%),EN RIESGO: n=7 (21.2%) | Normal / Sin riesgo: n=3 (9.1%) | Patología severa: n=23 (69.7%),EN RIESGO: n=42 (13.1%) | Normal / Sin riesgo: n=71 (22.1%) | Patología severa: n=208 (64.8%)

ANTECEDENTES

                                Grupo 0     Grupo 1      Grupo 2
trastorno_hipertensivo: 0.0  60 (60.0%)  12 (36.4%)  255 (78.2%)
trastorno_hipertensivo: 1.0  40 (40.0%)  21 (63.6%)   71 (21.8%)
comp_placentaria: 0.0        91 (91.0%)  20 (60.6%)  279 (85.6%)
comp_placentaria: 1.0          9 (9.0%)  13 (39.4%)   47 (14.4%)
comp_maternaGrave: 0.0       94 (94.0%)  18 (54.5%)  306 (93.9%)
comp_maternaGrave: 1.0         6 (6.0%)  15 (45.5%)    20 (6.1%)
comp_metabolica: 0.0         83 (83.0%)  29 (87.9%)  299 (91.7%)
comp_metabolica: 1.0         17 (17.0%)   4 (12.1%)    27 (8.3%)
ant_obstetrico: -1           72 (72.0%)  23 (69.7%)  241 (73.9%)
ant_obstetrico: 1            21 (21.0%)   7 (21.2%)   71 (21.8%)
ant_obstetrico: 3              4 (4.0%)    3 (9.1%)    11 (3.4%)
ant_obstetrico: 4              3 (3.0%)    0 (0.0%)     3 (0.9%)
ant_medico: -1               68 (68.0%)  21 (63.6%)  267 (81.9%)
ant_medico: 1                26 (26.0%)   9 (27.3%)   51 (15.6%)
ant_medico: 3                  6 (6.0%)    2 (6.1%)     8 (2.5%)
ant_medico: 5                  0 (0.0%)    1 (3.0%)     0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.092 | G0vG2: 0.001 | G1vG2: 0.000,0.0: n=60 (60.0%) | 1.0: n=40 (40.0%),0.0: n=12 (36.4%) | 1.0: n=21 (63.6%),0.0: n=255 (78.2%) | 1.0: n=71 (21.8%)
1,comp_placentaria,Chi-Square,0.0001,G0vG1: 0.000 | G0vG2: 0.652 | G1vG2: 0.002,0.0: n=91 (91.0%) | 1.0: n=9 (9.0%),0.0: n=20 (60.6%) | 1.0: n=13 (39.4%),0.0: n=279 (85.6%) | 1.0: n=47 (14.4%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,0.0: n=94 (94.0%) | 1.0: n=6 (6.0%),0.0: n=18 (54.5%) | 1.0: n=15 (45.5%),0.0: n=306 (93.9%) | 1.0: n=20 (6.1%)
3,comp_metabolica,Chi-Square,0.0425,G0vG1: 1.000 | G0vG2: 0.061 | G1vG2: 1.000,0.0: n=83 (83.0%) | 1.0: n=17 (17.0%),0.0: n=29 (87.9%) | 1.0: n=4 (12.1%),0.0: n=299 (91.7%) | 1.0: n=27 (8.3%)
4,ant_obstetrico,Chi-Square,0.4673,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,-1: n=72 (72.0%) | 1: n=21 (21.0%) | 3: n=4 (4.0%) | 4: n=3 (3.0%),-1: n=23 (69.7%) | 1: n=7 (21.2%) | 3: n=3 (9.1%),-1: n=241 (73.9%) | 1: n=71 (21.8%) | 3: n=11 (3.4%) | 4: n=3 (0.9%)
5,ant_medico,Chi-Square,0.0004,G0vG1: 1.000 | G0vG2: 0.028 | G1vG2: 0.006,-1: n=68 (68.0%) | 1: n=26 (26.0%) | 3: n=6 (6.0%),-1: n=21 (63.6%) | 1: n=9 (27.3%) | 3: n=2 (6.1%) | 5: n=1 (3.0%),-1: n=267 (81.9%) | 1: n=51 (15.6%) | 3: n=8 (2.5%)

======================================================================
COMBINACIÓN 5 | K = 3 | SILHOUETTE = 0.4885
======================================================================

TAMAÑO DE GRUPOS:
cluster    0   1    2
count    325  34  100

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1           Grupo 2
peso_ini_gest          60.21 ± 7.63     69.86 ± 13.28     87.44 ± 12.27
peso_fin_gest          72.33 ± 9.71     82.23 ± 14.31     97.68 ± 13.70
aumento_peso_gest      12.09 ± 5.11      12.46 ± 6.40      10.29 ± 6.14
talla                 163.70 ± 6.21     162.07 ± 5.51     164.83 ± 6.22
imc_ini_gest           22.47 ± 2.59      26.55 ± 4.84      32.21 ± 4.36
edad_materna_gest      35.49 ± 4.49      36.49 ± 4.42      35.35 ± 5.30
tas_1tri             112.16 ± 10.92    120.25 ± 13.01    119.48 ± 10.87
tad_1tri               71.94 ± 7.93     76.80 ± 10.30      75.35 ± 8.02
eg_eco_1tri            12.69 ± 0.62      12.77 ± 0.43      12.86 ± 0.61
eg_parto               39.34 ± 1.74      35.69 ± 4.09      39.15 ± 1.58
peso_rn            3087.91 ± 556.71  2378.29 ± 992.29  3230.29 ± 529.91
apgar_1min              8.94 ± 0.53       6.65 ± 2.13       8.85 ± 0.90
apgar_5min              9.92 ± 0.29       7.93 ± 1.63       9.92 ± 0.31
apgar_10min            10.00 ± 0.02       8.81 ± 0.43       9.99 ± 0.10
ratio_MoM              3.92 ± 15.15     51.80 ± 94.27       3.35 ± 5.56
sflt1_MoM               1.57 ± 1.23       4.28 ± 5.44       1.54 ± 1.03
plgf_MoM                1.40 ± 1.09       1.05 ± 1.69       1.08 ± 0.79

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,60.00 ± 11.80,66.75 ± 17.68,85.60 ± 11.62
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,72.00 ± 14.29,82.50 ± 19.42,95.50 ± 13.25
2,aumento_peso_gest,Kruskal-Wallis,0.0076,G0vG1: 1.000 | G0vG2: 0.005 | G1vG2: 0.330,11.82 ± 5.00,12.01 ± 5.15,10.00 ± 7.78
3,talla,Kruskal-Wallis,0.1087,G0vG1: 0.417 | G0vG2: 0.636 | G1vG2: 0.111,163.00 ± 8.00,162.50 ± 9.12,165.00 ± 8.25
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,22.31 ± 4.14,24.91 ± 7.59,31.34 ± 5.95
5,edad_materna_gest,Kruskal-Wallis,0.5254,G0vG1: 0.737 | G0vG2: 1.000 | G1vG2: 1.000,35.47 ± 6.06,35.94 ± 5.72,35.76 ± 7.30
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 0.000 | G1vG2: 1.000,112.00 ± 14.00,118.50 ± 14.75,118.37 ± 15.00
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 0.000 | G1vG2: 0.706,72.00 ± 10.00,76.50 ± 7.26,75.00 ± 9.25
8,eg_eco_1tri,Kruskal-Wallis,0.1434,G0vG1: 1.000 | G0vG2: 0.157 | G1vG2: 1.000,12.72 ± 0.50,12.80 ± 0.43,12.80 ± 0.70
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.489 | G1vG2: 0.000,39.60 ± 2.00,35.65 ± 5.82,39.30 ± 2.02
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.127 | G1vG2: 0.000,3120.00 ± 700.00,2505.00 ± 1590.00,3180.00 ± 691.25
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,9.00 ± 0.00,7.00 ± 3.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,10.00 ± 0.00,8.38 ± 1.75,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,10.00 ± 0.00,9.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0003,G0vG1: 0.000 | G0vG2: 0.996 | G1vG2: 0.002,1.68 ± 1.47,5.82 ± 58.46,1.70 ± 2.50
15,sflt1_MoM,Kruskal-Wallis,0.0002,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.001,1.26 ± 0.63,1.96 ± 4.61,1.27 ± 0.92
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.003 | G1vG2: 0.005,1.26 ± 0.92,0.45 ± 0.91,0.89 ± 0.89

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1        Grupo 2
diam_telediastolico           44.17 ± 5.41   44.88 ± 5.01   47.60 ± 4.84
diam_telesistolico            29.29 ± 4.08   29.18 ± 4.34   32.03 ± 5.30
dtsvi_indexado                17.15 ± 2.76   16.23 ± 2.59   16.30 ± 2.75
septo_iv_diastole             9.27 ± 10.15  11.70 ± 15.48    9.07 ± 1.85
pared_posterior_vi_diastole    8.59 ± 9.47   9.77 ± 10.32    8.00 ± 1.82
diam_ai                       32.16 ± 4.33   35.17 ± 4.81   36.85 ± 3.52
ai_volumen                   34.43 ± 11.31  40.77 ± 12.61  44.90 ± 15.96
ad_volumen                   31.00 ± 15.54  33.16 ± 13.47  38.92 ± 13.53
tapse                        25.53 ± 11.88   26.67 ± 3.93  27.59 ± 29.12
e_mitral                     81.98 ± 71.20  76.40 ± 16.16  70.91 ± 13.51
e_e                            4.21 ± 3.84    3.99 ± 1.11    3.72 ± 1.02
gc_tsvi                        6.12 ± 4.78   7.97 ± 10.52    7.13 ± 5.53
urato_acidourico               4.09 ± 1.58    4.11 ± 0.69    4.48 ± 1.00

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.051,44.00 ± 6.00,43.50 ± 6.00,47.00 ± 7.00
1,diam_telesistolico,Kruskal-Wallis,0.0001,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.065,29.00 ± 5.00,29.00 ± 7.25,31.50 ± 8.00
2,dtsvi_indexado,Kruskal-Wallis,0.0085,G0vG1: 0.189 | G0vG2: 0.021 | G1vG2: 1.000,17.17 ± 3.29,16.46 ± 3.41,15.81 ± 3.85
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 0.109 | G0vG2: 0.000 | G1vG2: 1.000,8.00 ± 2.00,8.95 ± 2.17,9.00 ± 2.30
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0149,G0vG1: 0.367 | G0vG2: 0.025 | G1vG2: 1.000,7.00 ± 1.85,7.95 ± 1.45,8.00 ± 2.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.004 | G0vG2: 0.000 | G1vG2: 0.379,32.00 ± 5.00,35.50 ± 6.00,37.00 ± 4.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.032 | G0vG2: 0.000 | G1vG2: 1.000,33.00 ± 14.62,41.80 ± 20.00,42.25 ± 18.75
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.105,29.00 ± 14.90,31.10 ± 16.82,39.05 ± 18.20
8,tapse,Kruskal-Wallis,0.0318,G0vG1: 0.032 | G0vG2: 1.000 | G1vG2: 0.043,25.00 ± 6.00,27.50 ± 4.75,24.00 ± 5.00
9,e_mitral,Kruskal-Wallis,0.0095,G0vG1: 1.000 | G0vG2: 0.007 | G1vG2: 0.386,75.30 ± 18.05,74.00 ± 25.30,70.90 ± 16.15
10,e_e,Kruskal-Wallis,0.1674,G0vG1: 1.000 | G0vG2: 0.343 | G1vG2: 0.299,3.77 ± 1.17,3.89 ± 0.80,3.56 ± 1.16
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.186,5.50 ± 1.35,5.65 ± 1.45,6.60 ± 1.88
12,urato_acidourico,Kruskal-Wallis,0.0036,G0vG1: 1.000 | G0vG2: 0.002 | G1vG2: 0.574,3.98 ± 1.10,3.98 ± 1.02,4.38 ± 1.43

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1         Grupo 2
ta_sistolica                   111.56 ± 12.66  126.73 ± 19.00  124.61 ± 15.56
ta_diastolica                    73.22 ± 8.85   80.61 ± 13.42    80.89 ± 9.24
frec_cardiaca                   77.66 ± 11.64   81.48 ± 10.82   82.51 ± 12.11
right_1peak_systolic_velocity    31.18 ± 8.61    31.08 ± 8.68    32.21 ± 9.87
right_2peak_systolic_velocity    21.69 ± 7.05    22.69 ± 7.88    22.14 ± 7.51
right_pulsatility_index           1.77 ± 0.45     1.83 ± 0.46     1.77 ± 0.40
right_psv_ratio                   0.70 ± 0.12     0.73 ± 0.14     0.69 ± 0.12
left_1peak_systolic_velocity     32.62 ± 8.88   34.74 ± 10.36   35.79 ± 10.10
left_2peak_systolic_velocity     23.02 ± 7.22    25.24 ± 8.69    24.78 ± 8.23
left_pulsatility_index            1.71 ± 0.42     1.74 ± 0.45     1.97 ± 2.37
left_psv_ratio                    0.71 ± 0.12     0.73 ± 0.14     0.69 ± 0.12
right_mean                        0.52 ± 0.08     0.53 ± 0.07     0.59 ± 0.14
left_mean                         0.53 ± 0.08     0.56 ± 0.09     0.61 ± 0.12

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 1.000,110.00 ± 15.50,128.00 ± 19.00,123.00 ± 15.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 1.000,74.00 ± 11.00,82.00 ± 19.00,81.00 ± 11.50
2,frec_cardiaca,ANOVA,0.0007,G0vG1: 0.250 | G0vG2: 0.000 | G1vG2: 1.000,77.66 ± 11.64,81.48 ± 10.82,82.51 ± 12.11
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5963,G0vG1: 1.000 | G0vG2: 0.935 | G1vG2: 1.000,31.20 ± 11.20,31.70 ± 13.40,31.40 ± 13.50
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.7815,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,21.10 ± 9.40,22.70 ± 13.50,21.60 ± 10.80
5,right_pulsatility_index,Kruskal-Wallis,0.6264,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.72 ± 0.50,1.84 ± 0.51,1.79 ± 0.50
6,right_psv_ratio,ANOVA,0.2562,G0vG1: 0.648 | G0vG2: 1.000 | G1vG2: 0.556,0.70 ± 0.12,0.73 ± 0.14,0.69 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0035,G0vG1: 0.820 | G0vG2: 0.003 | G1vG2: 1.000,32.50 ± 10.90,35.60 ± 15.80,36.20 ± 13.90
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.0457,G0vG1: 0.579 | G0vG2: 0.067 | G1vG2: 1.000,22.50 ± 8.30,24.80 ± 12.50,25.10 ± 10.30
9,left_pulsatility_index,Kruskal-Wallis,0.9479,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.72 ± 0.54,1.72 ± 0.48,1.68 ± 0.55
10,left_psv_ratio,Kruskal-Wallis,0.5106,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.717,0.70 ± 0.16,0.74 ± 0.17,0.69 ± 0.13
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 0.813 | G0vG2: 0.000 | G1vG2: 0.120,0.51 ± 0.10,0.53 ± 0.09,0.56 ± 0.15
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.141 | G0vG2: 0.000 | G1vG2: 0.191,0.52 ± 0.10,0.56 ± 0.17,0.60 ± 0.12

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2
hemoglobina,126.52 ± 24.48,121.93 ± 34.52,127.82 ± 17.91
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,6443.95 ± 1582.36,6435.00 ± 1731.91,6945.51 ± 1679.17
plaquetas,268531.82 ± 61712.57,274307.69 ± 90698.96,280521.74 ± 61550.46
glucosa,86.24 ± 9.81,90.62 ± 11.75,91.09 ± 15.36
sodio,139.77 ± 1.72,139.27 ± 1.71,139.33 ± 2.12
potasio,4.22 ± 0.27,4.23 ± 0.29,4.22 ± 0.31
urato_acidourico,4.09 ± 1.58,4.11 ± 0.69,4.48 ± 1.00
hemoglobina_glicada,5.32 ± 0.32,5.53 ± 0.49,5.51 ± 0.47
ast,21.85 ± 9.74,21.08 ± 4.94,21.67 ± 12.58
alt,17.74 ± 10.12,19.27 ± 8.68,20.39 ± 20.54
bilirubina_total,0.69 ± 0.31,0.61 ± 0.27,0.59 ± 0.32
ldh,162.55 ± 25.26,173.81 ± 27.90,173.14 ± 28.95
vldl,12.98 ± 7.49,17.75 ± 10.38,19.17 ± 10.76
ldl,111.46 ± 28.92,120.44 ± 26.32,110.99 ± 29.35
hdl,62.17 ± 13.66,55.12 ± 13.20,53.47 ± 13.55
colesterol_total,186.47 ± 32.65,193.32 ± 30.29,183.60 ± 32.21
trigliceridos,66.06 ± 36.78,88.35 ± 51.31,95.64 ± 52.84
prote_totales_orina,2.37 ± 12.36,7.04 ± 20.56,2.25 ± 12.19

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.9555,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,131.00 ± 14.00,129.50 ± 20.25,131.00 ± 10.00
1,hematocrito,Kruskal-Wallis,0.9581,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.39 ± 0.04,0.40 ± 0.05,0.39 ± 0.03
2,leucocitos,Kruskal-Wallis,0.0706,G0vG1: 1.000 | G0vG2: 0.078 | G1vG2: 0.377,6255.00 ± 1972.50,6150.00 ± 2252.50,6650.00 ± 1920.00
3,plaquetas,Kruskal-Wallis,0.4939,G0vG1: 1.000 | G0vG2: 0.705 | G1vG2: 1.000,263500.00 ± 82750.00,274000.00 ± 113750.00,276000.00 ± 75000.00
4,glucosa,Kruskal-Wallis,0.0078,G0vG1: 0.142 | G0vG2: 0.022 | G1vG2: 1.000,86.00 ± 10.00,87.00 ± 9.50,89.00 ± 11.00
5,sodio,Kruskal-Wallis,0.1757,G0vG1: 0.609 | G0vG2: 0.365 | G1vG2: 1.000,140.00 ± 2.00,139.00 ± 2.00,139.00 ± 3.00
6,potasio,Kruskal-Wallis,0.9057,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,4.21 ± 0.32,4.24 ± 0.28,4.18 ± 0.34
7,urato_acidourico,Kruskal-Wallis,0.0036,G0vG1: 1.000 | G0vG2: 0.002 | G1vG2: 0.574,3.98 ± 1.10,3.98 ± 1.02,4.38 ± 1.43
8,hemoglobina_glicada,Kruskal-Wallis,0.0003,G0vG1: 0.062 | G0vG2: 0.001 | G1vG2: 1.000,5.30 ± 0.30,5.40 ± 0.38,5.50 ± 0.40
9,ast,Kruskal-Wallis,0.2809,G0vG1: 1.000 | G0vG2: 0.357 | G1vG2: 0.950,20.00 ± 5.50,20.00 ± 4.75,19.00 ± 5.00
10,alt,Kruskal-Wallis,0.3793,G0vG1: 0.475 | G0vG2: 1.000 | G1vG2: 0.893,15.00 ± 7.25,16.50 ± 8.50,15.00 ± 12.00
11,bilirubina_total,Kruskal-Wallis,0.0040,G0vG1: 0.419 | G0vG2: 0.005 | G1vG2: 1.000,0.61 ± 0.33,0.56 ± 0.20,0.54 ± 0.23
12,ldh,Kruskal-Wallis,0.0152,G0vG1: 0.267 | G0vG2: 0.030 | G1vG2: 1.000,160.00 ± 28.50,168.50 ± 41.75,168.00 ± 31.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 0.017 | G0vG2: 0.000 | G1vG2: 1.000,10.88 ± 5.71,15.78 ± 8.87,15.87 ± 13.73
14,ldl,Kruskal-Wallis,0.2563,G0vG1: 0.287 | G0vG2: 1.000 | G1vG2: 0.557,106.29 ± 37.64,117.41 ± 21.23,106.90 ± 37.66
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.045 | G0vG2: 0.000 | G1vG2: 1.000,61.15 ± 17.51,53.98 ± 18.48,52.63 ± 15.09
16,colesterol_total,Kruskal-Wallis,0.2636,G0vG1: 0.452 | G0vG2: 1.000 | G1vG2: 0.293,183.25 ± 41.12,192.34 ± 27.38,180.73 ± 35.22
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 0.025 | G0vG2: 0.000 | G1vG2: 1.000,53.98 ± 24.11,78.32 ± 44.03,78.77 ± 68.14
18,prote_totales_orina,Kruskal-Wallis,0.6408,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.08 ± 0.05,0.08 ± 0.07,0.08 ± 0.04

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2
Cat_Dieta: Adherencia moderada,218 (67.1%),23 (67.6%),44 (44.0%)
Cat_Dieta: Alta adherencia,21 (6.5%),0 (0.0%),4 (4.0%)
Cat_Dieta: Baja adherencia,86 (26.5%),11 (32.4%),52 (52.0%)
Cat_Actividad: Actividad física alta,297 (92.5%),31 (96.9%),85 (85.0%)
Cat_Actividad: Actividad física baja,9 (2.8%),0 (0.0%),2 (2.0%)
Cat_Actividad: Actividad física moderada,15 (4.7%),1 (3.1%),13 (13.0%)
Cat_Estres: Nivel de estrés alto,106 (32.6%),12 (36.4%),44 (44.4%)
Cat_Estres: Nivel de estrés bajo,38 (11.7%),2 (6.1%),12 (12.1%)
Cat_Estres: Nivel de estrés moderado,173 (53.2%),17 (51.5%),38 (38.4%)
Cat_Estres: Nivel de estrés muy alto,8 (2.5%),2 (6.1%),5 (5.1%)
Cat_Memoria: Deterioro leve,43 (13.3%),5 (15.6%),17 (17.2%)
Cat_Memoria: Disfunción moderada-grave,31 (9.6%),3 (9.4%),10 (10.1%)
Cat_Memoria: Función normal (lapsus leves),186 (57.6%),17 (53.1%),57 (57.6%)
Cat_Memoria: Rendimiento de memoria óptimo,63 (19.5%),7 (21.9%),15 (15.2%)
Cat_SCL90R: EN RIESGO,41 (12.8%),8 (23.5%),8 (8.2%)
Cat_SCL90R: Normal / Sin riesgo,71 (22.2%),3 (8.8%),15 (15.5%)
Cat_SCL90R: Patología severa,208 (65.0%),23 (67.6%),74 (76.3%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.0001,G0vG1: 0.820 | G0vG2: 0.000 | G1vG2: 0.130,Adherencia moderada: n=218 (67.1%) | Alta adherencia: n=21 (6.5%) | Baja adherencia: n=86 (26.5%),Adherencia moderada: n=23 (67.6%) | Baja adherencia: n=11 (32.4%),Adherencia moderada: n=44 (44.0%) | Alta adherencia: n=4 (4.0%) | Baja adherencia: n=52 (52.0%)
1,Cat_Actividad,Chi-Square,0.0332,G0vG1: 0.490 | G0vG2: 0.058 | G1vG2: 0.083,Actividad física alta: n=297 (92.5%) | Actividad física baja: n=9 (2.8%) | Actividad física moderada: n=15 (4.7%),Actividad física alta: n=31 (96.9%) | Actividad física moderada: n=1 (3.1%),Actividad física alta: n=85 (85.0%) | Actividad física baja: n=2 (2.0%) | Actividad física moderada: n=13 (13.0%)
2,Cat_Estres,Chi-Square,0.1398,G0vG1: 0.054 | G0vG2: 0.072 | G1vG2: 1.000,Nivel de estrés alto: n=106 (32.6%) | Nivel de estrés bajo: n=38 (11.7%) | Nivel de estrés moderado: n=173 (53.2%) | Nivel de estrés muy alto: n=8 (2.5%),Nivel de estrés alto: n=12 (36.4%) | Nivel de estrés bajo: n=2 (6.1%) | Nivel de estrés moderado: n=17 (51.5%) | Nivel de estrés muy alto: n=2 (6.1%),Nivel de estrés alto: n=44 (44.4%) | Nivel de estrés bajo: n=12 (12.1%) | Nivel de estrés moderado: n=38 (38.4%) | Nivel de estrés muy alto: n=5 (5.1%)
3,Cat_Memoria,Chi-Square,0.9282,G0vG1: 0.271 | G0vG2: 1.000 | G1vG2: 1.000,Deterioro leve: n=43 (13.3%) | Disfunción moderada-grave: n=31 (9.6%) | Función normal (lapsus leves): n=186 (57.6%) | Rendimiento de memoria óptimo: n=63 (19.5%),Deterioro leve: n=5 (15.6%) | Disfunción moderada-grave: n=3 (9.4%) | Función normal (lapsus leves): n=17 (53.1%) | Rendimiento de memoria óptimo: n=7 (21.9%),Deterioro leve: n=17 (17.2%) | Disfunción moderada-grave: n=10 (10.1%) | Función normal (lapsus leves): n=57 (57.6%) | Rendimiento de memoria óptimo: n=15 (15.2%)
4,Cat_SCL90R,Chi-Square,0.0404,G0vG1: 0.364 | G0vG2: 0.472 | G1vG2: 0.215,EN RIESGO: n=41 (12.8%) | Normal / Sin riesgo: n=71 (22.2%) | Patología severa: n=208 (65.0%),EN RIESGO: n=8 (23.5%) | Normal / Sin riesgo: n=3 (8.8%) | Patología severa: n=23 (67.6%),EN RIESGO: n=8 (8.2%) | Normal / Sin riesgo: n=15 (15.5%) | Patología severa: n=74 (76.3%)

ANTECEDENTES

                                 Grupo 0     Grupo 1     Grupo 2
trastorno_hipertensivo: 0.0  254 (78.2%)  13 (38.2%)  60 (60.0%)
trastorno_hipertensivo: 1.0   71 (21.8%)  21 (61.8%)  40 (40.0%)
comp_placentaria: 0.0        278 (85.5%)  21 (61.8%)  91 (91.0%)
comp_placentaria: 1.0         47 (14.5%)  13 (38.2%)    9 (9.0%)
comp_maternaGrave: 0.0       305 (93.8%)  19 (55.9%)  94 (94.0%)
comp_maternaGrave: 1.0         20 (6.2%)  15 (44.1%)    6 (6.0%)
comp_metabolica: 0.0         298 (91.7%)  30 (88.2%)  83 (83.0%)
comp_metabolica: 1.0           27 (8.3%)   4 (11.8%)  17 (17.0%)
ant_obstetrico: -1           240 (73.8%)  24 (70.6%)  72 (72.0%)
ant_obstetrico: 1             71 (21.8%)   7 (20.6%)  21 (21.0%)
ant_obstetrico: 3              11 (3.4%)    3 (8.8%)    4 (4.0%)
ant_obstetrico: 4               3 (0.9%)    0 (0.0%)    3 (3.0%)
ant_medico: -1               266 (81.8%)  22 (64.7%)  68 (68.0%)
ant_medico: 1                 51 (15.7%)   9 (26.5%)  26 (26.0%)
ant_medico: 3                   8 (2.5%)    2 (5.9%)    6 (6.0%)
ant_medico: 5                   0 (0.0%)    1 (2.9%)    0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 0.001 | G1vG2: 0.136,0.0: n=254 (78.2%) | 1.0: n=71 (21.8%),0.0: n=13 (38.2%) | 1.0: n=21 (61.8%),0.0: n=60 (60.0%) | 1.0: n=40 (40.0%)
1,comp_placentaria,Chi-Square,0.0002,G0vG1: 0.003 | G0vG2: 0.642 | G1vG2: 0.001,0.0: n=278 (85.5%) | 1.0: n=47 (14.5%),0.0: n=21 (61.8%) | 1.0: n=13 (38.2%),0.0: n=91 (91.0%) | 1.0: n=9 (9.0%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,0.0: n=305 (93.8%) | 1.0: n=20 (6.2%),0.0: n=19 (55.9%) | 1.0: n=15 (44.1%),0.0: n=94 (94.0%) | 1.0: n=6 (6.0%)
3,comp_metabolica,Chi-Square,0.0442,G0vG1: 1.000 | G0vG2: 0.063 | G1vG2: 1.000,0.0: n=298 (91.7%) | 1.0: n=27 (8.3%),0.0: n=30 (88.2%) | 1.0: n=4 (11.8%),0.0: n=83 (83.0%) | 1.0: n=17 (17.0%)
4,ant_obstetrico,Chi-Square,0.4889,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,-1: n=240 (73.8%) | 1: n=71 (21.8%) | 3: n=11 (3.4%) | 4: n=3 (0.9%),-1: n=24 (70.6%) | 1: n=7 (20.6%) | 3: n=3 (8.8%),-1: n=72 (72.0%) | 1: n=21 (21.0%) | 3: n=4 (4.0%) | 4: n=3 (3.0%)
5,ant_medico,Chi-Square,0.0005,G0vG1: 0.008 | G0vG2: 0.029 | G1vG2: 1.000,-1: n=266 (81.8%) | 1: n=51 (15.7%) | 3: n=8 (2.5%),-1: n=22 (64.7%) | 1: n=9 (26.5%) | 3: n=2 (5.9%) | 5: n=1 (2.9%),-1: n=68 (68.0%) | 1: n=26 (26.0%) | 3: n=6 (6.0%)

======================================================================
COMBINACIÓN 6 | K = 3 | SILHOUETTE = 0.4866
======================================================================

TAMAÑO DE GRUPOS:
cluster    0    1   2
count    316  111  32

GESTACIÓN Y BIOMARCADORES

                            Grupo 0           Grupo 1           Grupo 2
peso_ini_gest          59.76 ± 7.28     86.41 ± 12.37     69.07 ± 12.24
peso_fin_gest          71.69 ± 9.07     97.49 ± 13.18     81.15 ± 13.41
aumento_peso_gest      11.89 ± 5.02      11.12 ± 6.42      12.18 ± 6.42
talla                 163.51 ± 6.06     165.32 ± 6.50     161.73 ± 5.39
imc_ini_gest           22.36 ± 2.53      31.67 ± 4.54      26.40 ± 4.73
edad_materna_gest      35.43 ± 4.48      35.54 ± 5.23      36.50 ± 4.51
tas_1tri             112.05 ± 10.88    118.90 ± 11.13    121.40 ± 12.54
tad_1tri               71.96 ± 7.99      74.80 ± 8.16      77.63 ± 9.60
eg_eco_1tri            12.70 ± 0.62      12.83 ± 0.61      12.77 ± 0.44
eg_parto               39.35 ± 1.73      39.16 ± 1.63      35.40 ± 4.04
peso_rn            3084.71 ± 561.90  3242.29 ± 521.86  2274.91 ± 927.07
apgar_1min              8.95 ± 0.50       8.84 ± 0.91       6.51 ± 2.11
apgar_5min              9.92 ± 0.31       9.91 ± 0.32       7.90 ± 1.67
apgar_10min            10.00 ± 0.04       9.98 ± 0.13       8.79 ± 0.42
ratio_MoM              3.95 ± 15.35       3.27 ± 5.41     55.01 ± 96.34
sflt1_MoM               1.58 ± 1.24       1.51 ± 1.01       4.51 ± 5.54
plgf_MoM                1.41 ± 1.10       1.07 ± 0.76       1.05 ± 1.75

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,60.00 ± 11.00,84.50 ± 12.50,66.75 ± 16.22
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,72.00 ± 13.60,95.00 ± 13.00,81.00 ± 18.48
2,aumento_peso_gest,Kruskal-Wallis,0.2739,G0vG1: 0.316 | G0vG2: 1.000 | G1vG2: 1.000,11.65 ± 5.00,10.00 ± 7.20,11.93 ± 5.20
3,talla,Kruskal-Wallis,0.0156,G0vG1: 0.107 | G0vG2: 0.304 | G1vG2: 0.025,163.00 ± 8.00,165.00 ± 9.00,161.50 ± 8.88
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,22.25 ± 4.02,30.82 ± 6.05,24.91 ± 7.48
5,edad_materna_gest,Kruskal-Wallis,0.4665,G0vG1: 1.000 | G0vG2: 0.692 | G1vG2: 1.000,35.47 ± 5.95,35.76 ± 7.23,35.94 ± 5.82
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.708,112.00 ± 14.25,118.00 ± 15.00,119.38 ± 15.39
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 0.001 | G1vG2: 0.198,72.00 ± 10.00,75.00 ± 9.00,77.00 ± 7.59
8,eg_eco_1tri,Kruskal-Wallis,0.3678,G0vG1: 0.489 | G0vG2: 1.000 | G1vG2: 1.000,12.73 ± 0.50,12.80 ± 0.70,12.80 ± 0.46
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.549 | G0vG2: 0.000 | G1vG2: 0.000,39.60 ± 2.00,39.30 ± 2.10,35.25 ± 5.62
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.060 | G0vG2: 0.000 | G1vG2: 0.000,3115.00 ± 707.33,3180.00 ± 680.00,2430.00 ± 1495.00
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,9.00 ± 0.00,9.00 ± 0.00,7.00 ± 3.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,10.00 ± 0.00,10.00 ± 0.00,8.38 ± 2.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,10.00 ± 0.00,10.00 ± 0.00,9.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,1.68 ± 1.51,1.70 ± 2.20,6.70 ± 65.99
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,1.26 ± 0.63,1.26 ± 0.82,2.37 ± 4.84
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 0.000 | G1vG2: 0.001,1.29 ± 0.90,0.93 ± 0.90,0.38 ± 0.71

ECOCARDIOGRAFÍA

                                   Grupo 0        Grupo 1        Grupo 2
diam_telediastolico           44.06 ± 5.41   47.62 ± 4.73   44.67 ± 5.14
diam_telesistolico            29.09 ± 3.93   32.34 ± 5.25   29.07 ± 4.38
dtsvi_indexado                17.08 ± 2.76   16.53 ± 2.78   16.33 ± 2.68
septo_iv_diastole             9.32 ± 10.30    9.75 ± 8.21    8.68 ± 2.01
pared_posterior_vi_diastole    8.62 ± 9.61    8.51 ± 5.62    7.84 ± 1.25
diam_ai                       32.13 ± 4.36   36.53 ± 3.71   35.00 ± 4.75
ai_volumen                   34.25 ± 11.15  44.68 ± 15.79  39.73 ± 12.53
ad_volumen                   30.98 ± 15.67  38.19 ± 13.32  32.76 ± 13.81
tapse                        25.54 ± 12.04  27.43 ± 27.56   26.43 ± 4.01
e_mitral                     82.26 ± 72.19  71.23 ± 14.30  76.35 ± 16.46
e_e                            4.23 ± 3.90    3.72 ± 1.00    4.02 ± 1.15
gc_tsvi                        5.98 ± 4.16    7.45 ± 6.69   7.98 ± 11.01
urato_acidourico               4.09 ± 1.59    4.44 ± 1.02    4.08 ± 0.67

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.027,44.00 ± 6.00,47.00 ± 7.00,43.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.029,29.00 ± 5.00,32.00 ± 7.00,29.00 ± 7.25
2,dtsvi_indexado,Kruskal-Wallis,0.0854,G0vG1: 0.176 | G0vG2: 0.473 | G1vG2: 1.000,17.11 ± 3.24,16.15 ± 3.97,16.47 ± 4.10
3,septo_iv_diastole,Kruskal-Wallis,0.0001,G0vG1: 0.000 | G0vG2: 0.317 | G1vG2: 1.000,8.00 ± 2.00,9.00 ± 2.35,8.60 ± 2.28
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0080,G0vG1: 0.012 | G0vG2: 0.347 | G1vG2: 1.000,7.00 ± 2.05,8.00 ± 2.00,7.95 ± 1.15
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.007 | G1vG2: 0.571,32.00 ± 5.00,37.00 ± 4.25,35.50 ± 5.75
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.096 | G1vG2: 0.804,33.00 ± 14.43,42.65 ± 18.25,39.30 ± 19.95
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.134,28.70 ± 15.30,38.40 ± 17.67,31.10 ± 16.88
8,tapse,Kruskal-Wallis,0.0903,G0vG1: 1.000 | G0vG2: 0.086 | G1vG2: 0.157,24.90 ± 6.00,24.40 ± 5.50,27.00 ± 4.45
9,e_mitral,Kruskal-Wallis,0.0091,G0vG1: 0.007 | G0vG2: 1.000 | G1vG2: 0.492,75.60 ± 17.65,71.00 ± 17.90,74.00 ± 24.55
10,e_e,Kruskal-Wallis,0.1215,G0vG1: 0.293 | G0vG2: 1.000 | G1vG2: 0.232,3.76 ± 1.17,3.57 ± 1.10,3.92 ± 0.79
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.062,5.50 ± 1.35,6.45 ± 1.85,5.55 ± 1.38
12,urato_acidourico,Kruskal-Wallis,0.0103,G0vG1: 0.008 | G0vG2: 1.000 | G1vG2: 0.646,3.98 ± 1.06,4.31 ± 1.49,3.98 ± 1.01

TA, CARÓTIDA Y OFTÁLMICA

                                      Grupo 0         Grupo 1         Grupo 2
ta_sistolica                   111.73 ± 12.76  122.88 ± 15.80  127.52 ± 19.28
ta_diastolica                    73.31 ± 8.88    79.93 ± 9.49   80.87 ± 13.74
frec_cardiaca                   77.85 ± 11.74   81.38 ± 12.00   82.06 ± 10.90
right_1peak_systolic_velocity    31.21 ± 8.68    32.11 ± 9.76    30.72 ± 7.92
right_2peak_systolic_velocity    21.73 ± 7.07    21.96 ± 7.41    22.84 ± 7.88
right_pulsatility_index           1.77 ± 0.46     1.78 ± 0.40     1.83 ± 0.48
right_psv_ratio                   0.70 ± 0.12     0.69 ± 0.12     0.74 ± 0.14
left_1peak_systolic_velocity     32.75 ± 8.92    35.08 ± 9.98   34.94 ± 10.60
left_2peak_systolic_velocity     23.12 ± 7.24    24.24 ± 8.14    25.73 ± 8.75
left_pulsatility_index            1.71 ± 0.41     1.96 ± 2.26     1.72 ± 0.45
left_psv_ratio                    0.71 ± 0.12     0.69 ± 0.13     0.74 ± 0.14
right_mean                        0.52 ± 0.08     0.58 ± 0.14     0.53 ± 0.07
left_mean                         0.53 ± 0.08     0.60 ± 0.11     0.56 ± 0.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.398,110.00 ± 15.75,121.00 ± 17.00,128.00 ± 19.50
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 1.000,74.00 ± 11.00,80.50 ± 11.75,82.00 ± 16.50
2,frec_cardiaca,ANOVA,0.0085,G0vG1: 0.006 | G0vG2: 0.171 | G1vG2: 1.000,77.85 ± 11.74,81.38 ± 12.00,82.06 ± 10.90
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.6769,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,31.20 ± 11.20,31.35 ± 12.75,31.70 ± 11.55
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.8096,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,21.05 ± 9.32,21.60 ± 10.75,22.70 ± 13.30
5,right_pulsatility_index,Kruskal-Wallis,0.5949,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.72 ± 0.50,1.80 ± 0.50,1.81 ± 0.52
6,right_psv_ratio,ANOVA,0.0944,G0vG1: 1.000 | G0vG2: 0.284 | G1vG2: 0.173,0.70 ± 0.12,0.69 ± 0.12,0.74 ± 0.14
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0343,G0vG1: 0.037 | G0vG2: 0.828 | G1vG2: 1.000,32.60 ± 11.02,35.70 ± 13.75,35.60 ± 16.10
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.1238,G0vG1: 0.408 | G0vG2: 0.323 | G1vG2: 1.000,22.50 ± 8.25,24.25 ± 10.75,25.10 ± 11.15
9,left_pulsatility_index,Kruskal-Wallis,0.7494,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.71 ± 0.53,1.69 ± 0.60,1.72 ± 0.47
10,left_psv_ratio,Kruskal-Wallis,0.2983,G0vG1: 1.000 | G0vG2: 0.688 | G1vG2: 0.335,0.70 ± 0.16,0.70 ± 0.13,0.75 ± 0.18
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.775 | G1vG2: 0.202,0.51 ± 0.10,0.55 ± 0.15,0.53 ± 0.09
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.118 | G1vG2: 0.340,0.52 ± 0.10,0.58 ± 0.13,0.56 ± 0.17

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2
hemoglobina,126.73 ± 23.37,127.11 ± 22.03,121.55 ± 35.92
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,6402.62 ± 1539.90,6986.36 ± 1745.30,6504.58 ± 1778.28
plaquetas,269023.36 ± 61360.74,277155.84 ± 62593.10,277208.33 ± 93433.99
glucosa,86.36 ± 9.94,90.87 ± 15.08,89.00 ± 10.45
sodio,139.75 ± 1.72,139.42 ± 2.09,139.29 ± 1.78
potasio,4.21 ± 0.27,4.24 ± 0.31,4.22 ± 0.28
urato_acidourico,4.09 ± 1.59,4.44 ± 1.02,4.08 ± 0.67
hemoglobina_glicada,5.32 ± 0.33,5.51 ± 0.46,5.51 ± 0.48
ast,21.78 ± 9.79,21.82 ± 12.08,21.21 ± 5.12
alt,17.74 ± 10.12,20.14 ± 19.64,19.25 ± 9.05
bilirubina_total,0.68 ± 0.31,0.61 ± 0.33,0.58 ± 0.18
ldh,162.24 ± 25.23,173.04 ± 28.33,174.75 ± 28.65
vldl,12.86 ± 7.15,19.17 ± 11.09,17.18 ± 10.36
ldl,110.81 ± 27.87,112.90 ± 31.63,120.98 ± 27.37
hdl,62.16 ± 13.42,53.92 ± 14.41,56.08 ± 13.10
colesterol_total,185.68 ± 31.27,185.98 ± 35.59,194.26 ± 31.39
trigliceridos,65.48 ± 35.09,95.61 ± 54.57,85.53 ± 51.20
prote_totales_orina,2.44 ± 12.53,2.02 ± 11.52,7.67 ± 21.40

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.9961,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,131.00 ± 14.00,131.00 ± 12.00,129.50 ± 21.50
1,hematocrito,Kruskal-Wallis,0.8168,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.39 ± 0.04,0.39 ± 0.04,0.40 ± 0.05
2,leucocitos,Kruskal-Wallis,0.0457,G0vG1: 0.041 | G0vG2: 1.000 | G1vG2: 0.580,6225.00 ± 1900.00,6650.00 ± 2080.00,6150.00 ± 2137.50
3,plaquetas,Kruskal-Wallis,0.6413,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,263000.00 ± 83250.00,273000.00 ± 74000.00,276500.00 ± 120000.00
4,glucosa,Kruskal-Wallis,0.0303,G0vG1: 0.041 | G0vG2: 0.538 | G1vG2: 1.000,86.00 ± 10.00,89.00 ± 9.00,87.00 ± 7.75
5,sodio,Kruskal-Wallis,0.3318,G0vG1: 0.685 | G0vG2: 0.878 | G1vG2: 1.000,140.00 ± 2.00,139.00 ± 3.00,139.00 ± 2.25
6,potasio,Kruskal-Wallis,0.7655,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,4.21 ± 0.31,4.20 ± 0.43,4.24 ± 0.25
7,urato_acidourico,Kruskal-Wallis,0.0103,G0vG1: 0.008 | G0vG2: 1.000 | G1vG2: 0.646,3.98 ± 1.06,4.31 ± 1.49,3.98 ± 1.01
8,hemoglobina_glicada,Kruskal-Wallis,0.0004,G0vG1: 0.001 | G0vG2: 0.080 | G1vG2: 1.000,5.30 ± 0.40,5.40 ± 0.42,5.40 ± 0.32
9,ast,Kruskal-Wallis,0.4663,G0vG1: 0.707 | G0vG2: 1.000 | G1vG2: 1.000,20.00 ± 5.00,19.00 ± 6.00,20.00 ± 5.25
10,alt,Kruskal-Wallis,0.5013,G0vG1: 1.000 | G0vG2: 0.753 | G1vG2: 1.000,15.00 ± 7.00,15.00 ± 10.00,16.00 ± 9.75
11,bilirubina_total,Kruskal-Wallis,0.0126,G0vG1: 0.019 | G0vG2: 0.372 | G1vG2: 1.000,0.61 ± 0.32,0.54 ± 0.24,0.56 ± 0.19
12,ldh,Kruskal-Wallis,0.0043,G0vG1: 0.008 | G0vG2: 0.193 | G1vG2: 1.000,159.00 ± 28.75,168.50 ± 30.50,168.50 ± 45.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.051 | G1vG2: 1.000,10.88 ± 5.71,15.69 ± 13.73,15.61 ± 8.29
14,ldl,Kruskal-Wallis,0.2390,G0vG1: 1.000 | G0vG2: 0.282 | G1vG2: 0.689,106.29 ± 37.16,107.42 ± 37.87,119.50 ± 26.53
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.123 | G1vG2: 1.000,61.15 ± 17.32,53.02 ± 15.48,55.53 ± 19.35
16,colesterol_total,Kruskal-Wallis,0.2544,G0vG1: 1.000 | G0vG2: 0.341 | G1vG2: 0.329,182.08 ± 40.92,183.05 ± 32.89,197.75 ± 30.09
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.072 | G1vG2: 1.000,53.98 ± 24.56,77.88 ± 68.14,77.44 ± 40.61
18,prote_totales_orina,Kruskal-Wallis,0.6087,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.08 ± 0.05,0.08 ± 0.04,0.08 ± 0.10

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2
Cat_Dieta: Adherencia moderada,213 (67.4%),51 (45.9%),21 (65.6%)
Cat_Dieta: Alta adherencia,21 (6.6%),4 (3.6%),0 (0.0%)
Cat_Dieta: Baja adherencia,82 (25.9%),56 (50.5%),11 (34.4%)
Cat_Actividad: Actividad física alta,290 (92.9%),94 (84.7%),29 (96.7%)
Cat_Actividad: Actividad física baja,9 (2.9%),2 (1.8%),0 (0.0%)
Cat_Actividad: Actividad física moderada,13 (4.2%),15 (13.5%),1 (3.3%)
Cat_Estres: Nivel de estrés alto,102 (32.3%),49 (44.5%),11 (35.5%)
Cat_Estres: Nivel de estrés bajo,37 (11.7%),14 (12.7%),1 (3.2%)
Cat_Estres: Nivel de estrés moderado,170 (53.8%),41 (37.3%),17 (54.8%)
Cat_Estres: Nivel de estrés muy alto,7 (2.2%),6 (5.5%),2 (6.5%)
Cat_Memoria: Deterioro leve,43 (13.7%),18 (16.4%),4 (13.3%)
Cat_Memoria: Disfunción moderada-grave,27 (8.6%),14 (12.7%),3 (10.0%)
Cat_Memoria: Función normal (lapsus leves),184 (58.6%),60 (54.5%),16 (53.3%)
Cat_Memoria: Rendimiento de memoria óptimo,60 (19.1%),18 (16.4%),7 (23.3%)
Cat_SCL90R: EN RIESGO,41 (13.2%),9 (8.3%),7 (21.9%)
Cat_SCL90R: Normal / Sin riesgo,68 (21.9%),18 (16.7%),3 (9.4%)
Cat_SCL90R: Patología severa,202 (65.0%),81 (75.0%),22 (68.8%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.0001,G0vG1: 0.000 | G0vG2: 0.699 | G1vG2: 0.327,Adherencia moderada: n=213 (67.4%) | Alta adherencia: n=21 (6.6%) | Baja adherencia: n=82 (25.9%),Adherencia moderada: n=51 (45.9%) | Alta adherencia: n=4 (3.6%) | Baja adherencia: n=56 (50.5%),Adherencia moderada: n=21 (65.6%) | Baja adherencia: n=11 (34.4%)
1,Cat_Actividad,Chi-Square,0.0089,G0vG1: 0.012 | G0vG2: 0.479 | G1vG2: 0.055,Actividad física alta: n=290 (92.9%) | Actividad física baja: n=9 (2.9%) | Actividad física moderada: n=13 (4.2%),Actividad física alta: n=94 (84.7%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=15 (13.5%),Actividad física alta: n=29 (96.7%) | Actividad física moderada: n=1 (3.3%)
2,Cat_Estres,Chi-Square,0.0327,G0vG1: 0.026 | G0vG2: 0.025 | G1vG2: 0.799,Nivel de estrés alto: n=102 (32.3%) | Nivel de estrés bajo: n=37 (11.7%) | Nivel de estrés moderado: n=170 (53.8%) | Nivel de estrés muy alto: n=7 (2.2%),Nivel de estrés alto: n=49 (44.5%) | Nivel de estrés bajo: n=14 (12.7%) | Nivel de estrés moderado: n=41 (37.3%) | Nivel de estrés muy alto: n=6 (5.5%),Nivel de estrés alto: n=11 (35.5%) | Nivel de estrés bajo: n=1 (3.2%) | Nivel de estrés moderado: n=17 (54.8%) | Nivel de estrés muy alto: n=2 (6.5%)
3,Cat_Memoria,Chi-Square,0.8242,G0vG1: 1.000 | G0vG2: 0.225 | G1vG2: 1.000,Deterioro leve: n=43 (13.7%) | Disfunción moderada-grave: n=27 (8.6%) | Función normal (lapsus leves): n=184 (58.6%) | Rendimiento de memoria óptimo: n=60 (19.1%),Deterioro leve: n=18 (16.4%) | Disfunción moderada-grave: n=14 (12.7%) | Función normal (lapsus leves): n=60 (54.5%) | Rendimiento de memoria óptimo: n=18 (16.4%),Deterioro leve: n=4 (13.3%) | Disfunción moderada-grave: n=3 (10.0%) | Función normal (lapsus leves): n=16 (53.3%) | Rendimiento de memoria óptimo: n=7 (23.3%)
4,Cat_SCL90R,Chi-Square,0.0919,G0vG1: 0.672 | G0vG2: 0.670 | G1vG2: 0.346,EN RIESGO: n=41 (13.2%) | Normal / Sin riesgo: n=68 (21.9%) | Patología severa: n=202 (65.0%),EN RIESGO: n=9 (8.3%) | Normal / Sin riesgo: n=18 (16.7%) | Patología severa: n=81 (75.0%),EN RIESGO: n=7 (21.9%) | Normal / Sin riesgo: n=3 (9.4%) | Patología severa: n=22 (68.8%)

ANTECEDENTES

                                 Grupo 0      Grupo 1     Grupo 2
trastorno_hipertensivo: 0.0  247 (78.2%)   69 (62.2%)  11 (34.4%)
trastorno_hipertensivo: 1.0   69 (21.8%)   42 (37.8%)  21 (65.6%)
comp_placentaria: 0.0        269 (85.1%)  102 (91.9%)  19 (59.4%)
comp_placentaria: 1.0         47 (14.9%)     9 (8.1%)  13 (40.6%)
comp_maternaGrave: 0.0       296 (93.7%)  105 (94.6%)  17 (53.1%)
comp_maternaGrave: 1.0         20 (6.3%)     6 (5.4%)  15 (46.9%)
comp_metabolica: 0.0         290 (91.8%)   92 (82.9%)  29 (90.6%)
comp_metabolica: 1.0           26 (8.2%)   19 (17.1%)    3 (9.4%)
ant_obstetrico: -1           235 (74.4%)   79 (71.2%)  22 (68.8%)
ant_obstetrico: 1             67 (21.2%)   25 (22.5%)   7 (21.9%)
ant_obstetrico: 3              11 (3.5%)     4 (3.6%)    3 (9.4%)
ant_obstetrico: 4               3 (0.9%)     3 (2.7%)    0 (0.0%)
ant_medico: -1               260 (82.3%)   75 (67.6%)  21 (65.6%)
ant_medico: 1                 48 (15.2%)   30 (27.0%)   8 (25.0%)
ant_medico: 3                   8 (2.5%)     6 (5.4%)    2 (6.2%)
ant_medico: 5                   0 (0.0%)     0 (0.0%)    1 (3.1%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.004 | G0vG2: 0.000 | G1vG2: 0.029,0.0: n=247 (78.2%) | 1.0: n=69 (21.8%),0.0: n=69 (62.2%) | 1.0: n=42 (37.8%),0.0: n=11 (34.4%) | 1.0: n=21 (65.6%)
1,comp_placentaria,Chi-Square,0.0000,G0vG1: 0.295 | G0vG2: 0.002 | G1vG2: 0.000,0.0: n=269 (85.1%) | 1.0: n=47 (14.9%),0.0: n=102 (91.9%) | 1.0: n=9 (8.1%),0.0: n=19 (59.4%) | 1.0: n=13 (40.6%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G1vG2: 0.000,0.0: n=296 (93.7%) | 1.0: n=20 (6.3%),0.0: n=105 (94.6%) | 1.0: n=6 (5.4%),0.0: n=17 (53.1%) | 1.0: n=15 (46.9%)
3,comp_metabolica,Chi-Square,0.0306,G0vG1: 0.044 | G0vG2: 1.000 | G1vG2: 1.000,0.0: n=290 (91.8%) | 1.0: n=26 (8.2%),0.0: n=92 (82.9%) | 1.0: n=19 (17.1%),0.0: n=29 (90.6%) | 1.0: n=3 (9.4%)
4,ant_obstetrico,Chi-Square,0.5098,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,-1: n=235 (74.4%) | 1: n=67 (21.2%) | 3: n=11 (3.5%) | 4: n=3 (0.9%),-1: n=79 (71.2%) | 1: n=25 (22.5%) | 3: n=4 (3.6%) | 4: n=3 (2.7%),-1: n=22 (68.8%) | 1: n=7 (21.9%) | 3: n=3 (9.4%)
5,ant_medico,Chi-Square,0.0002,G0vG1: 0.015 | G0vG2: 0.009 | G1vG2: 0.942,-1: n=260 (82.3%) | 1: n=48 (15.2%) | 3: n=8 (2.5%),-1: n=75 (67.6%) | 1: n=30 (27.0%) | 3: n=6 (5.4%),-1: n=21 (65.6%) | 1: n=8 (25.0%) | 3: n=2 (6.2%) | 5: n=1 (3.1%)

======================================================================
COMBINACIÓN 7 | K = 4 | SILHOUETTE = 0.4660
======================================================================

TAMAÑO DE GRUPOS:
cluster    0  1    2   3
count    109  8  313  29

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
peso_ini_gest,86.16 ± 11.65,84.50 ± 22.52,59.73 ± 7.30,66.32 ± 10.01
peso_fin_gest,96.99 ± 12.47,99.27 ± 21.62,71.62 ± 9.06,78.91 ± 12.42
aumento_peso_gest,10.87 ± 6.04,14.84 ± 9.93,11.86 ± 4.99,12.69 ± 6.57
talla,165.40 ± 6.50,161.50 ± 5.18,163.51 ± 6.07,161.98 ± 5.43
imc_ini_gest,31.53 ± 4.03,32.60 ± 9.64,22.35 ± 2.54,25.28 ± 4.05
edad_materna_gest,35.42 ± 5.20,37.06 ± 3.51,35.43 ± 4.47,36.61 ± 4.95
tas_1tri,118.81 ± 11.06,121.72 ± 13.63,112.06 ± 10.83,120.34 ± 13.31
tad_1tri,74.89 ± 7.74,82.30 ± 5.45,72.05 ± 7.89,74.30 ± 12.19
eg_eco_1tri,12.82 ± 0.61,12.78 ± 0.48,12.70 ± 0.62,12.78 ± 0.49
eg_parto,39.17 ± 1.64,35.26 ± 3.92,39.35 ± 1.73,36.06 ± 4.06
peso_rn,3239.67 ± 519.83,2365.00 ± 803.74,3079.82 ± 557.39,2463.17 ± 1055.40
apgar_1min,8.93 ± 0.57,3.50 ± 1.41,8.97 ± 0.41,7.18 ± 1.60
apgar_5min,9.94 ± 0.25,5.88 ± 2.17,9.94 ± 0.24,8.51 ± 0.63
apgar_10min,9.99 ± 0.10,8.25 ± 0.46,10.00 ± 0.02,9.09 ± 0.38
ratio_MoM,3.29 ± 5.45,52.81 ± 125.96,3.96 ± 15.42,46.58 ± 82.01
sflt1_MoM,1.51 ± 1.02,5.77 ± 9.69,1.58 ± 1.24,3.64 ± 3.31
plgf_MoM,1.08 ± 0.77,1.38 ± 2.64,1.40 ± 1.03,1.19 ± 1.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.094 | G2vG3: 0.005,84.50 ± 12.00,80.25 ± 18.12,60.00 ± 11.00,66.00 ± 14.50
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.059 | G2vG3: 0.017,95.00 ± 13.00,96.65 ± 17.40,72.00 ± 13.70,77.80 ± 16.40
2,aumento_peso_gest,Kruskal-Wallis,0.2522,G0vG1: 1.000 | G0vG2: 0.418 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,10.00 ± 7.10,12.55 ± 2.92,11.63 ± 5.00,12.00 ± 7.00
3,talla,Kruskal-Wallis,0.0292,G0vG1: 0.592 | G0vG2: 0.158 | G0vG3: 0.108 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,165.00 ± 9.00,160.00 ± 6.00,163.00 ± 8.00,163.00 ± 8.50
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.081 | G2vG3: 0.001,30.82 ± 5.88,30.96 ± 7.44,22.23 ± 4.03,24.31 ± 5.20
5,edad_materna_gest,Kruskal-Wallis,0.5077,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.68 ± 7.19,36.19 ± 3.92,35.47 ± 5.92,35.99 ± 6.21
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.289 | G1vG3: 1.000 | G2vG3: 0.002,118.00 ± 15.00,117.38 ± 18.00,112.00 ± 14.00,119.00 ± 16.52
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.022 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 0.120 | G2vG3: 0.582,75.00 ± 9.00,83.00 ± 8.18,72.00 ± 10.00,76.00 ± 9.42
8,eg_eco_1tri,Kruskal-Wallis,0.6433,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.80 ± 0.70,12.80 ± 0.53,12.72 ± 0.50,12.80 ± 0.44
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 0.002 | G1vG2: 0.001 | G1vG3: 1.000 | G2vG3: 0.000,39.30 ± 2.10,36.25 ± 2.65,39.60 ± 2.00,37.30 ± 6.10
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.007 | G0vG2: 0.110 | G0vG3: 0.002 | G1vG2: 0.033 | G1vG3: 1.000 | G2vG3: 0.011,3180.00 ± 645.00,2485.00 ± 662.50,3110.00 ± 696.44,2640.00 ± 1820.00
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,9.00 ± 0.00,4.00 ± 1.50,9.00 ± 0.00,7.21 ± 2.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.000,10.00 ± 0.00,6.50 ± 1.25,10.00 ± 0.00,9.00 ± 1.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,10.00 ± 0.00,8.00 ± 0.25,10.00 ± 0.00,9.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0006,G0vG1: 0.232 | G0vG2: 1.000 | G0vG3: 0.017 | G1vG2: 0.097 | G1vG3: 1.000 | G2vG3: 0.004,1.70 ± 2.10,7.03 ± 12.05,1.68 ± 1.47,4.75 ± 61.28
15,sflt1_MoM,Kruskal-Wallis,0.0003,G0vG1: 0.091 | G0vG2: 1.000 | G0vG3: 0.003 | G1vG2: 0.147 | G1vG3: 1.000 | G2vG3: 0.002,1.26 ± 0.82,2.79 ± 1.70,1.26 ± 0.62,1.83 ± 4.85
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.304 | G0vG2: 0.003 | G0vG3: 0.041 | G1vG2: 0.107 | G1vG3: 1.000 | G2vG3: 0.001,0.93 ± 0.93,0.37 ± 0.53,1.29 ± 0.90,0.47 ± 1.03

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
diam_telediastolico,47.69 ± 4.66,45.00 ± 5.73,44.01 ± 5.41,45.04 ± 5.21
diam_telesistolico,32.34 ± 5.10,29.72 ± 4.96,29.10 ± 3.94,28.99 ± 5.02
dtsvi_indexado,16.53 ± 2.65,15.59 ± 3.59,17.12 ± 2.73,16.20 ± 3.22
septo_iv_diastole,9.76 ± 8.30,9.10 ± 1.41,9.33 ± 10.35,8.67 ± 2.02
pared_posterior_vi_diastole,8.51 ± 5.68,8.30 ± 0.93,8.63 ± 9.66,7.68 ± 1.27
diam_ai,36.69 ± 3.59,33.33 ± 4.13,32.14 ± 4.37,34.60 ± 4.89
ai_volumen,44.91 ± 15.82,41.25 ± 13.03,34.19 ± 11.09,38.92 ± 12.70
ad_volumen,38.26 ± 13.46,36.65 ± 21.11,30.95 ± 15.74,32.10 ± 10.21
tapse,27.55 ± 27.84,25.98 ± 3.26,25.51 ± 12.10,26.37 ± 4.23
e_mitral,71.59 ± 14.25,74.43 ± 17.47,82.35 ± 72.46,74.29 ± 16.40
e_e,3.73 ± 1.00,4.06 ± 1.20,4.23 ± 3.91,3.94 ± 1.10
gc_tsvi,7.51 ± 6.76,6.10 ± 0.96,5.98 ± 4.19,8.00 ± 11.30
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.179 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,47.00 ± 7.00,43.00 ± 7.50,44.00 ± 6.00,44.00 ± 6.50
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.040 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,32.00 ± 7.00,29.00 ± 3.75,29.00 ± 5.00,29.00 ± 7.00
2,dtsvi_indexado,Kruskal-Wallis,0.0890,G0vG1: 1.000 | G0vG2: 0.279 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.902,16.15 ± 3.81,16.23 ± 2.59,17.13 ± 3.28,16.57 ± 4.45
3,septo_iv_diastole,Kruskal-Wallis,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.469 | G1vG3: 1.000 | G2vG3: 0.767,9.00 ± 2.20,9.35 ± 1.62,8.00 ± 2.00,8.30 ± 2.10
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0186,G0vG1: 1.000 | G0vG2: 0.044 | G0vG3: 1.000 | G1vG2: 0.510 | G1vG3: 0.857 | G2vG3: 1.000,8.00 ± 2.00,8.15 ± 0.82,7.00 ± 2.12,7.80 ± 1.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.479 | G0vG2: 0.000 | G0vG3: 0.367 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.097,37.00 ± 4.00,33.50 ± 7.25,32.00 ± 5.00,34.50 ± 6.25
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.423,42.65 ± 18.75,39.50 ± 16.40,33.00 ± 14.20,40.90 ± 20.45
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.343 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,38.40 ± 18.03,31.10 ± 3.12,28.65 ± 15.30,32.00 ± 15.80
8,tapse,Kruskal-Wallis,0.1922,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.559 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.263,24.60 ± 6.00,27.50 ± 4.00,24.70 ± 5.50,26.00 ± 5.40
9,e_mitral,Kruskal-Wallis,0.0422,G0vG1: 1.000 | G0vG2: 0.027 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,71.70 ± 16.80,73.00 ± 25.78,75.60 ± 17.60,74.00 ± 18.10
10,e_e,Kruskal-Wallis,0.3415,G0vG1: 1.000 | G0vG2: 0.746 | G0vG3: 0.770 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.57 ± 1.16,4.07 ± 1.12,3.76 ± 1.17,3.89 ± 0.78
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.070 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6.55 ± 1.73,5.70 ± 1.15,5.50 ± 1.30,5.40 ± 1.80
12,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
ta_sistolica,123.11 ± 15.81,133.75 ± 16.68,111.79 ± 12.79,122.11 ± 19.70
ta_diastolica,80.06 ± 9.49,84.25 ± 5.42,73.39 ± 8.87,77.57 ± 15.06
frec_cardiaca,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
right_1peak_systolic_velocity,32.03 ± 9.84,27.24 ± 7.78,31.27 ± 8.70,31.49 ± 7.49
right_2peak_systolic_velocity,21.86 ± 7.42,18.70 ± 5.63,21.79 ± 7.07,23.51 ± 8.13
right_pulsatility_index,1.79 ± 0.40,1.74 ± 0.40,1.77 ± 0.46,1.84 ± 0.48
right_psv_ratio,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
left_1peak_systolic_velocity,35.06 ± 10.07,33.88 ± 12.35,32.76 ± 8.96,34.96 ± 9.37
left_2peak_systolic_velocity,24.19 ± 8.18,23.41 ± 9.84,23.13 ± 7.26,26.00 ± 7.97
left_pulsatility_index,1.96 ± 2.28,1.86 ± 0.38,1.71 ± 0.41,1.68 ± 0.44
left_psv_ratio,0.69 ± 0.13,0.69 ± 0.12,0.71 ± 0.12,0.75 ± 0.14
right_mean,0.58 ± 0.14,0.58 ± 0.05,0.51 ± 0.08,0.52 ± 0.08
left_mean,0.60 ± 0.12,0.57 ± 0.08,0.53 ± 0.08,0.56 ± 0.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.318 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.712 | G2vG3: 0.035,121.00 ± 17.00,131.50 ± 9.50,110.00 ± 16.00,120.50 ± 24.75
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.803 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.003 | G1vG3: 1.000 | G2vG3: 0.669,81.00 ± 11.25,85.50 ± 9.00,74.00 ± 11.00,78.50 ± 20.75
2,frec_cardiaca,ANOVA,0.0177,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.304 | G1vG3: 0.950 | G2vG3: 1.000,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5711,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,31.30 ± 12.85,29.65 ± 10.30,31.20 ± 11.20,32.35 ± 11.07
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.4466,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.826 | G2vG3: 1.000,21.45 ± 10.48,16.85 ± 8.48,21.20 ± 9.30,23.10 ± 14.95
5,right_pulsatility_index,Kruskal-Wallis,0.7471,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.80 ± 0.50,1.69 ± 0.22,1.72 ± 0.50,1.85 ± 0.54
6,right_psv_ratio,ANOVA,0.2587,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.392 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.778,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0992,G0vG1: 1.000 | G0vG2: 0.100 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.35 ± 14.10,36.65 ± 11.70,32.60 ± 11.05,33.60 ± 14.52
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.2196,G0vG1: 1.000 | G0vG2: 0.999 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.444,24.25 ± 10.53,21.50 ± 11.40,22.50 ± 8.30,25.55 ± 10.65
9,left_pulsatility_index,Kruskal-Wallis,0.6289,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.69 ± 0.60,1.79 ± 0.23,1.71 ± 0.53,1.70 ± 0.51
10,left_psv_ratio,Kruskal-Wallis,0.3288,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.387 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.907,0.70 ± 0.13,0.66 ± 0.17,0.70 ± 0.16,0.75 ± 0.18
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.213 | G1vG2: 0.041 | G1vG3: 0.218 | G2vG3: 1.000,0.55 ± 0.15,0.56 ± 0.04,0.51 ± 0.10,0.51 ± 0.11
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.394 | G1vG2: 0.512 | G1vG3: 1.000 | G2vG3: 0.591,0.58 ± 0.13,0.58 ± 0.08,0.52 ± 0.10,0.55 ± 0.17

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
hemoglobina,126.98 ± 22.15,135.75 ± 12.61,126.75 ± 23.53,120.35 ± 35.33
hematocrito,0.39 ± 0.03,0.40 ± 0.04,0.39 ± 0.03,0.39 ± 0.03
leucocitos,7005.13 ± 1749.06,6007.50 ± 2574.74,6436.07 ± 1519.65,6241.25 ± 1774.76
plaquetas,277078.95 ± 63005.35,250000.00 ± 91524.13,269687.20 ± 61499.41,275125.00 ± 89137.08
glucosa,90.95 ± 15.16,90.00 ± 6.93,86.32 ± 9.93,88.71 ± 10.81
sodio,139.43 ± 2.09,139.25 ± 1.89,139.74 ± 1.73,139.33 ± 1.71
potasio,4.24 ± 0.31,4.05 ± 0.37,4.21 ± 0.27,4.22 ± 0.26
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93
hemoglobina_glicada,5.51 ± 0.46,5.57 ± 0.25,5.32 ± 0.33,5.46 ± 0.48
ast,21.92 ± 12.13,20.75 ± 3.95,21.74 ± 9.82,21.38 ± 5.81
alt,20.33 ± 19.71,18.75 ± 6.85,17.56 ± 9.96,20.21 ± 10.92
bilirubina_total,0.60 ± 0.32,0.51 ± 0.08,0.68 ± 0.30,0.65 ± 0.33
ldh,173.11 ± 28.51,189.00 ± 32.56,162.81 ± 24.67,165.56 ± 32.35
vldl,19.07 ± 11.13,23.01 ± 13.96,12.85 ± 7.19,16.15 ± 9.05
ldl,112.78 ± 31.82,134.62 ± 41.14,111.04 ± 27.73,115.42 ± 26.34
hdl,54.05 ± 14.47,45.18 ± 6.65,62.36 ± 13.40,56.41 ± 12.66
colesterol_total,185.88 ± 35.81,202.88 ± 45.28,186.11 ± 31.04,187.97 ± 31.57
trigliceridos,95.12 ± 54.76,114.17 ± 69.26,65.46 ± 35.29,80.41 ± 44.72
prote_totales_orina,2.04 ± 11.60,17.95 ± 35.63,2.47 ± 12.62,4.42 ± 16.01

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.7793,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,131.00 ± 11.75,135.50 ± 16.75,131.00 ± 14.00,128.50 ± 17.00
1,hematocrito,Kruskal-Wallis,0.9534,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.04,0.40 ± 0.05,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0521,G0vG1: 1.000 | G0vG2: 0.093 | G0vG3: 0.328 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6670.00 ± 2060.00,5200.00 ± 2802.50,6260.00 ± 1910.00,6000.00 ± 2250.00
3,plaquetas,Kruskal-Wallis,0.8439,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,272500.00 ± 74500.00,257500.00 ± 123000.00,264000.00 ± 82500.00,267500.00 ± 105000.00
4,glucosa,Kruskal-Wallis,0.0476,G0vG1: 1.000 | G0vG2: 0.068 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,89.00 ± 9.75,92.00 ± 4.00,86.00 ± 10.00,87.00 ± 7.00
5,sodio,Kruskal-Wallis,0.5574,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,139.00 ± 3.00,138.50 ± 1.75,140.00 ± 2.00,139.50 ± 2.25
6,potasio,Kruskal-Wallis,0.7840,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.21 ± 0.41,4.13 ± 0.45,4.21 ± 0.31,4.23 ± 0.26
7,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12
8,hemoglobina_glicada,Kruskal-Wallis,0.0008,G0vG1: 1.000 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.265 | G1vG3: 1.000 | G2vG3: 1.000,5.40 ± 0.45,5.55 ± 0.22,5.30 ± 0.40,5.35 ± 0.40
9,ast,Kruskal-Wallis,0.7869,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,19.00 ± 6.00,21.50 ± 5.75,20.00 ± 5.50,20.00 ± 4.75
10,alt,Kruskal-Wallis,0.4748,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,15.50 ± 10.25,18.50 ± 7.75,15.00 ± 7.00,16.50 ± 11.25
11,bilirubina_total,Kruskal-Wallis,0.0132,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.840 | G1vG3: 1.000 | G2vG3: 1.000,0.54 ± 0.24,0.51 ± 0.07,0.61 ± 0.32,0.59 ± 0.24
12,ldh,Kruskal-Wallis,0.0146,G0vG1: 1.000 | G0vG2: 0.025 | G0vG3: 1.000 | G1vG2: 0.457 | G1vG3: 1.000 | G2vG3: 1.000,169.00 ± 31.00,182.00 ± 39.00,159.00 ± 28.00,159.50 ± 33.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.180 | G1vG3: 1.000 | G2vG3: 0.201,15.34 ± 13.23,18.81 ± 10.25,10.88 ± 5.71,14.98 ± 7.62
14,ldl,Kruskal-Wallis,0.3958,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,107.16 ± 38.03,139.31 ± 32.11,106.29 ± 37.31,117.41 ± 20.34
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.047 | G1vG3: 0.645 | G2vG3: 0.224,53.41 ± 15.77,45.09 ± 7.64,61.15 ± 17.02,55.53 ± 19.16
16,colesterol_total,Kruskal-Wallis,0.5769,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,182.67 ± 33.86,213.62 ± 43.44,183.05 ± 41.60,189.82 ± 31.83
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.183 | G1vG3: 1.000 | G2vG3: 0.329,76.11 ± 65.71,93.37 ± 50.88,53.98 ± 23.89,74.34 ± 35.74
18,prote_totales_orina,Kruskal-Wallis,0.5068,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.988 | G1vG3: 1.000 | G2vG3: 1.000,0.08 ± 0.04,0.16 ± 17.95,0.08 ± 0.05,0.08 ± 0.06

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
Cat_Dieta: Adherencia moderada,51 (46.8%),3 (37.5%),210 (67.1%),21 (72.4%)
Cat_Dieta: Alta adherencia,4 (3.7%),0 (0.0%),21 (6.7%),0 (0.0%)
Cat_Dieta: Baja adherencia,54 (49.5%),5 (62.5%),82 (26.2%),8 (27.6%)
Cat_Actividad: Actividad física alta,93 (85.3%),8 (100.0%),288 (93.2%),24 (88.9%)
Cat_Actividad: Actividad física baja,2 (1.8%),0 (0.0%),9 (2.9%),0 (0.0%)
Cat_Actividad: Actividad física moderada,14 (12.8%),0 (0.0%),12 (3.9%),3 (11.1%)
Cat_Estres: Nivel de estrés alto,48 (44.4%),0 (0.0%),100 (31.9%),14 (50.0%)
Cat_Estres: Nivel de estrés bajo,13 (12.0%),1 (12.5%),36 (11.5%),2 (7.1%)
Cat_Estres: Nivel de estrés moderado,41 (38.0%),7 (87.5%),170 (54.3%),10 (35.7%)
Cat_Estres: Nivel de estrés muy alto,6 (5.6%),0 (0.0%),7 (2.2%),2 (7.1%)
Cat_Memoria: Deterioro leve,18 (16.7%),0 (0.0%),43 (13.8%),4 (14.8%)
Cat_Memoria: Disfunción moderada-grave,13 (12.0%),0 (0.0%),26 (8.4%),5 (18.5%)
Cat_Memoria: Función normal (lapsus leves),60 (55.6%),4 (50.0%),182 (58.5%),14 (51.9%)
Cat_Memoria: Rendimiento de memoria óptimo,17 (15.7%),4 (50.0%),60 (19.3%),4 (14.8%)
Cat_SCL90R: EN RIESGO,9 (8.5%),5 (62.5%),40 (13.0%),3 (10.3%)
Cat_SCL90R: Normal / Sin riesgo,17 (16.0%),1 (12.5%),68 (22.1%),3 (10.3%)
Cat_SCL90R: Patología severa,80 (75.5%),2 (25.0%),200 (64.9%),23 (79.3%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.244 | G1vG2: 0.412 | G1vG3: 0.946 | G2vG3: 1.000,Adherencia moderada: n=51 (46.8%) | Alta adherencia: n=4 (3.7%) | Baja adherencia: n=54 (49.5%),Adherencia moderada: n=3 (37.5%) | Baja adherencia: n=5 (62.5%),Adherencia moderada: n=210 (67.1%) | Alta adherencia: n=21 (6.7%) | Baja adherencia: n=82 (26.2%),Adherencia moderada: n=21 (72.4%) | Baja adherencia: n=8 (27.6%)
1,Cat_Actividad,Chi-Square,0.0356,G0vG1: 1.000 | G0vG2: 0.031 | G0vG3: 0.254 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.228,Actividad física alta: n=93 (85.3%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=14 (12.8%),Actividad física alta: n=8 (100.0%),Actividad física alta: n=288 (93.2%) | Actividad física baja: n=9 (2.9%) | Actividad física moderada: n=12 (3.9%),Actividad física alta: n=24 (88.9%) | Actividad física moderada: n=3 (11.1%)
2,Cat_Estres,Chi-Square,0.0149,G0vG1: 0.439 | G0vG2: 0.053 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.403 | G2vG3: 0.009,Nivel de estrés alto: n=48 (44.4%) | Nivel de estrés bajo: n=13 (12.0%) | Nivel de estrés moderado: n=41 (38.0%) | Nivel de estrés muy alto: n=6 (5.6%),Nivel de estrés bajo: n=1 (12.5%) | Nivel de estrés moderado: n=7 (87.5%),Nivel de estrés alto: n=100 (31.9%) | Nivel de estrés bajo: n=36 (11.5%) | Nivel de estrés moderado: n=170 (54.3%) | Nivel de estrés muy alto: n=7 (2.2%),Nivel de estrés alto: n=14 (50.0%) | Nivel de estrés bajo: n=2 (7.1%) | Nivel de estrés moderado: n=10 (35.7%) | Nivel de estrés muy alto: n=2 (7.1%)
3,Cat_Memoria,Chi-Square,0.2712,G0vG1: 0.726 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.868 | G2vG3: 0.100,Deterioro leve: n=18 (16.7%) | Disfunción moderada-grave: n=13 (12.0%) | Función normal (lapsus leves): n=60 (55.6%) | Rendimiento de memoria óptimo: n=17 (15.7%),Función normal (lapsus leves): n=4 (50.0%) | Rendimiento de memoria óptimo: n=4 (50.0%),Deterioro leve: n=43 (13.8%) | Disfunción moderada-grave: n=26 (8.4%) | Función normal (lapsus leves): n=182 (58.5%) | Rendimiento de memoria óptimo: n=60 (19.3%),Deterioro leve: n=4 (14.8%) | Disfunción moderada-grave: n=5 (18.5%) | Función normal (lapsus leves): n=14 (51.9%) | Rendimiento de memoria óptimo: n=4 (14.8%)
4,Cat_SCL90R,Chi-Square,0.0004,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.007 | G1vG3: 0.029 | G2vG3: 1.000,EN RIESGO: n=9 (8.5%) | Normal / Sin riesgo: n=17 (16.0%) | Patología severa: n=80 (75.5%),EN RIESGO: n=5 (62.5%) | Normal / Sin riesgo: n=1 (12.5%) | Patología severa: n=2 (25.0%),EN RIESGO: n=40 (13.0%) | Normal / Sin riesgo: n=68 (22.1%) | Patología severa: n=200 (64.9%),EN RIESGO: n=3 (10.3%) | Normal / Sin riesgo: n=3 (10.3%) | Patología severa: n=23 (79.3%)

ANTECEDENTES

                                 Grupo 0     Grupo 1      Grupo 2     Grupo 3
trastorno_hipertensivo: 0.0   68 (62.4%)   2 (25.0%)  244 (78.0%)  13 (44.8%)
trastorno_hipertensivo: 1.0   41 (37.6%)   6 (75.0%)   69 (22.0%)  16 (55.2%)
comp_placentaria: 0.0        100 (91.7%)   7 (87.5%)  266 (85.0%)  17 (58.6%)
comp_placentaria: 1.0           9 (8.3%)   1 (12.5%)   47 (15.0%)  12 (41.4%)
comp_maternaGrave: 0.0       103 (94.5%)   4 (50.0%)  293 (93.6%)  18 (62.1%)
comp_maternaGrave: 1.0          6 (5.5%)   4 (50.0%)    20 (6.4%)  11 (37.9%)
comp_metabolica: 0.0          90 (82.6%)  8 (100.0%)  287 (91.7%)  26 (89.7%)
comp_metabolica: 1.0          19 (17.4%)    0 (0.0%)    26 (8.3%)   3 (10.3%)
ant_obstetrico: -1            78 (71.6%)   7 (87.5%)  233 (74.4%)  18 (62.1%)
ant_obstetrico: 1             24 (22.0%)    0 (0.0%)   66 (21.1%)   9 (31.0%)
ant_obstetrico: 3               4 (3.7%)   1 (12.5%)    11 (3.5%)    2 (6.9%)
ant_obstetrico: 4               3 (2.8%)    0 (0.0%)     3 (1.0%)    0 (0.0%)
ant_medico: -1                74 (67.9%)   3 (37.5%)  257 (82.1%)  22 (75.9%)
ant_medico: 1                 29 (26.6%)   5 (62.5%)   48 (15.3%)   4 (13.8%)
ant_medico: 3                   6 (5.5%)    0 (0.0%)     8 (2.6%)    2 (6.9%)
ant_medico: 5                   0 (0.0%)    0 (0.0%)     0 (0.0%)    1 (3.4%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.525 | G0vG2: 0.013 | G0vG3: 0.810 | G1vG2: 0.013 | G1vG3: 1.000 | G2vG3: 0.001,0.0: n=68 (62.4%) | 1.0: n=41 (37.6%),0.0: n=2 (25.0%) | 1.0: n=6 (75.0%),0.0: n=244 (78.0%) | 1.0: n=69 (22.0%),0.0: n=13 (44.8%) | 1.0: n=16 (55.2%)
1,comp_placentaria,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.622 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.005,0.0: n=100 (91.7%) | 1.0: n=9 (8.3%),0.0: n=7 (87.5%) | 1.0: n=1 (12.5%),0.0: n=266 (85.0%) | 1.0: n=47 (15.0%),0.0: n=17 (58.6%) | 1.0: n=12 (41.4%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 1.000 | G2vG3: 0.000,0.0: n=103 (94.5%) | 1.0: n=6 (5.5%),0.0: n=4 (50.0%) | 1.0: n=4 (50.0%),0.0: n=293 (93.6%) | 1.0: n=20 (6.4%),0.0: n=18 (62.1%) | 1.0: n=11 (37.9%)
3,comp_metabolica,Chi-Square,0.0432,G0vG1: 1.000 | G0vG2: 0.079 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=90 (82.6%) | 1.0: n=19 (17.4%),0.0: n=8 (100.0%),0.0: n=287 (91.7%) | 1.0: n=26 (8.3%),0.0: n=26 (89.7%) | 1.0: n=3 (10.3%)
4,ant_obstetrico,Chi-Square,0.4734,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=78 (71.6%) | 1: n=24 (22.0%) | 3: n=4 (3.7%) | 4: n=3 (2.8%),-1: n=7 (87.5%) | 3: n=1 (12.5%),-1: n=233 (74.4%) | 1: n=66 (21.1%) | 3: n=11 (3.5%) | 4: n=3 (1.0%),-1: n=18 (62.1%) | 1: n=9 (31.0%) | 3: n=2 (6.9%)
5,ant_medico,Chi-Square,0.0000,G0vG1: 0.547 | G0vG2: 0.044 | G0vG3: 0.791 | G1vG2: 0.011 | G1vG3: 0.240 | G2vG3: 0.032,-1: n=74 (67.9%) | 1: n=29 (26.6%) | 3: n=6 (5.5%),-1: n=3 (37.5%) | 1: n=5 (62.5%),-1: n=257 (82.1%) | 1: n=48 (15.3%) | 3: n=8 (2.6%),-1: n=22 (75.9%) | 1: n=4 (13.8%) | 3: n=2 (6.9%) | 5: n=1 (3.4%)

======================================================================
COMBINACIÓN 8 | K = 4 | SILHOUETTE = 0.4173
======================================================================

TAMAÑO DE GRUPOS:
cluster    0  1    2   3
count    109  8  313  29

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
peso_ini_gest,86.16 ± 11.65,84.50 ± 22.52,59.73 ± 7.30,66.32 ± 10.01
peso_fin_gest,96.99 ± 12.47,99.27 ± 21.62,71.62 ± 9.06,78.91 ± 12.42
aumento_peso_gest,10.87 ± 6.04,14.84 ± 9.93,11.86 ± 4.99,12.69 ± 6.57
talla,165.40 ± 6.50,161.50 ± 5.18,163.51 ± 6.07,161.98 ± 5.43
imc_ini_gest,31.53 ± 4.03,32.60 ± 9.64,22.35 ± 2.54,25.28 ± 4.05
edad_materna_gest,35.42 ± 5.20,37.06 ± 3.51,35.43 ± 4.47,36.61 ± 4.95
tas_1tri,118.81 ± 11.06,121.72 ± 13.63,112.06 ± 10.83,120.34 ± 13.31
tad_1tri,74.89 ± 7.74,82.30 ± 5.45,72.05 ± 7.89,74.30 ± 12.19
eg_eco_1tri,12.82 ± 0.61,12.78 ± 0.48,12.70 ± 0.62,12.78 ± 0.49
eg_parto,39.17 ± 1.64,35.26 ± 3.92,39.35 ± 1.73,36.06 ± 4.06
peso_rn,3239.67 ± 519.83,2365.00 ± 803.74,3079.82 ± 557.39,2463.17 ± 1055.40
apgar_1min,8.93 ± 0.57,3.50 ± 1.41,8.97 ± 0.41,7.18 ± 1.60
apgar_5min,9.94 ± 0.25,5.88 ± 2.17,9.94 ± 0.24,8.51 ± 0.63
apgar_10min,9.99 ± 0.10,8.25 ± 0.46,10.00 ± 0.02,9.09 ± 0.38
ratio_MoM,3.29 ± 5.45,52.81 ± 125.96,3.96 ± 15.42,46.58 ± 82.01
sflt1_MoM,1.51 ± 1.02,5.77 ± 9.69,1.58 ± 1.24,3.64 ± 3.31
plgf_MoM,1.08 ± 0.77,1.38 ± 2.64,1.40 ± 1.03,1.19 ± 1.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.094 | G2vG3: 0.005,84.50 ± 12.00,80.25 ± 18.12,60.00 ± 11.00,66.00 ± 14.50
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.059 | G2vG3: 0.017,95.00 ± 13.00,96.65 ± 17.40,72.00 ± 13.70,77.80 ± 16.40
2,aumento_peso_gest,Kruskal-Wallis,0.2522,G0vG1: 1.000 | G0vG2: 0.418 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,10.00 ± 7.10,12.55 ± 2.92,11.63 ± 5.00,12.00 ± 7.00
3,talla,Kruskal-Wallis,0.0292,G0vG1: 0.592 | G0vG2: 0.158 | G0vG3: 0.108 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,165.00 ± 9.00,160.00 ± 6.00,163.00 ± 8.00,163.00 ± 8.50
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.081 | G2vG3: 0.001,30.82 ± 5.88,30.96 ± 7.44,22.23 ± 4.03,24.31 ± 5.20
5,edad_materna_gest,Kruskal-Wallis,0.5077,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.68 ± 7.19,36.19 ± 3.92,35.47 ± 5.92,35.99 ± 6.21
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.289 | G1vG3: 1.000 | G2vG3: 0.002,118.00 ± 15.00,117.38 ± 18.00,112.00 ± 14.00,119.00 ± 16.52
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.022 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 0.120 | G2vG3: 0.582,75.00 ± 9.00,83.00 ± 8.18,72.00 ± 10.00,76.00 ± 9.42
8,eg_eco_1tri,Kruskal-Wallis,0.6433,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.80 ± 0.70,12.80 ± 0.53,12.72 ± 0.50,12.80 ± 0.44
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 0.002 | G1vG2: 0.001 | G1vG3: 1.000 | G2vG3: 0.000,39.30 ± 2.10,36.25 ± 2.65,39.60 ± 2.00,37.30 ± 6.10
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.007 | G0vG2: 0.110 | G0vG3: 0.002 | G1vG2: 0.033 | G1vG3: 1.000 | G2vG3: 0.011,3180.00 ± 645.00,2485.00 ± 662.50,3110.00 ± 696.44,2640.00 ± 1820.00
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,9.00 ± 0.00,4.00 ± 1.50,9.00 ± 0.00,7.21 ± 2.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.000,10.00 ± 0.00,6.50 ± 1.25,10.00 ± 0.00,9.00 ± 1.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,10.00 ± 0.00,8.00 ± 0.25,10.00 ± 0.00,9.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0006,G0vG1: 0.232 | G0vG2: 1.000 | G0vG3: 0.017 | G1vG2: 0.097 | G1vG3: 1.000 | G2vG3: 0.004,1.70 ± 2.10,7.03 ± 12.05,1.68 ± 1.47,4.75 ± 61.28
15,sflt1_MoM,Kruskal-Wallis,0.0003,G0vG1: 0.091 | G0vG2: 1.000 | G0vG3: 0.003 | G1vG2: 0.147 | G1vG3: 1.000 | G2vG3: 0.002,1.26 ± 0.82,2.79 ± 1.70,1.26 ± 0.62,1.83 ± 4.85
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.304 | G0vG2: 0.003 | G0vG3: 0.041 | G1vG2: 0.107 | G1vG3: 1.000 | G2vG3: 0.001,0.93 ± 0.93,0.37 ± 0.53,1.29 ± 0.90,0.47 ± 1.03

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
diam_telediastolico,47.69 ± 4.66,45.00 ± 5.73,44.01 ± 5.41,45.04 ± 5.21
diam_telesistolico,32.34 ± 5.10,29.72 ± 4.96,29.10 ± 3.94,28.99 ± 5.02
dtsvi_indexado,16.53 ± 2.65,15.59 ± 3.59,17.12 ± 2.73,16.20 ± 3.22
septo_iv_diastole,9.76 ± 8.30,9.10 ± 1.41,9.33 ± 10.35,8.67 ± 2.02
pared_posterior_vi_diastole,8.51 ± 5.68,8.30 ± 0.93,8.63 ± 9.66,7.68 ± 1.27
diam_ai,36.69 ± 3.59,33.33 ± 4.13,32.14 ± 4.37,34.60 ± 4.89
ai_volumen,44.91 ± 15.82,41.25 ± 13.03,34.19 ± 11.09,38.92 ± 12.70
ad_volumen,38.26 ± 13.46,36.65 ± 21.11,30.95 ± 15.74,32.10 ± 10.21
tapse,27.55 ± 27.84,25.98 ± 3.26,25.51 ± 12.10,26.37 ± 4.23
e_mitral,71.59 ± 14.25,74.43 ± 17.47,82.35 ± 72.46,74.29 ± 16.40
e_e,3.73 ± 1.00,4.06 ± 1.20,4.23 ± 3.91,3.94 ± 1.10
gc_tsvi,7.51 ± 6.76,6.10 ± 0.96,5.98 ± 4.19,8.00 ± 11.30
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.179 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,47.00 ± 7.00,43.00 ± 7.50,44.00 ± 6.00,44.00 ± 6.50
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.040 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,32.00 ± 7.00,29.00 ± 3.75,29.00 ± 5.00,29.00 ± 7.00
2,dtsvi_indexado,Kruskal-Wallis,0.0890,G0vG1: 1.000 | G0vG2: 0.279 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.902,16.15 ± 3.81,16.23 ± 2.59,17.13 ± 3.28,16.57 ± 4.45
3,septo_iv_diastole,Kruskal-Wallis,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.469 | G1vG3: 1.000 | G2vG3: 0.767,9.00 ± 2.20,9.35 ± 1.62,8.00 ± 2.00,8.30 ± 2.10
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0186,G0vG1: 1.000 | G0vG2: 0.044 | G0vG3: 1.000 | G1vG2: 0.510 | G1vG3: 0.857 | G2vG3: 1.000,8.00 ± 2.00,8.15 ± 0.82,7.00 ± 2.12,7.80 ± 1.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.479 | G0vG2: 0.000 | G0vG3: 0.367 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.097,37.00 ± 4.00,33.50 ± 7.25,32.00 ± 5.00,34.50 ± 6.25
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.423,42.65 ± 18.75,39.50 ± 16.40,33.00 ± 14.20,40.90 ± 20.45
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.343 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,38.40 ± 18.03,31.10 ± 3.12,28.65 ± 15.30,32.00 ± 15.80
8,tapse,Kruskal-Wallis,0.1922,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.559 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.263,24.60 ± 6.00,27.50 ± 4.00,24.70 ± 5.50,26.00 ± 5.40
9,e_mitral,Kruskal-Wallis,0.0422,G0vG1: 1.000 | G0vG2: 0.027 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,71.70 ± 16.80,73.00 ± 25.78,75.60 ± 17.60,74.00 ± 18.10
10,e_e,Kruskal-Wallis,0.3415,G0vG1: 1.000 | G0vG2: 0.746 | G0vG3: 0.770 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.57 ± 1.16,4.07 ± 1.12,3.76 ± 1.17,3.89 ± 0.78
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.070 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6.55 ± 1.73,5.70 ± 1.15,5.50 ± 1.30,5.40 ± 1.80
12,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
ta_sistolica,123.11 ± 15.81,133.75 ± 16.68,111.79 ± 12.79,122.11 ± 19.70
ta_diastolica,80.06 ± 9.49,84.25 ± 5.42,73.39 ± 8.87,77.57 ± 15.06
frec_cardiaca,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
right_1peak_systolic_velocity,32.03 ± 9.84,27.24 ± 7.78,31.27 ± 8.70,31.49 ± 7.49
right_2peak_systolic_velocity,21.86 ± 7.42,18.70 ± 5.63,21.79 ± 7.07,23.51 ± 8.13
right_pulsatility_index,1.79 ± 0.40,1.74 ± 0.40,1.77 ± 0.46,1.84 ± 0.48
right_psv_ratio,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
left_1peak_systolic_velocity,35.06 ± 10.07,33.88 ± 12.35,32.76 ± 8.96,34.96 ± 9.37
left_2peak_systolic_velocity,24.19 ± 8.18,23.41 ± 9.84,23.13 ± 7.26,26.00 ± 7.97
left_pulsatility_index,1.96 ± 2.28,1.86 ± 0.38,1.71 ± 0.41,1.68 ± 0.44
left_psv_ratio,0.69 ± 0.13,0.69 ± 0.12,0.71 ± 0.12,0.75 ± 0.14
right_mean,0.58 ± 0.14,0.58 ± 0.05,0.51 ± 0.08,0.52 ± 0.08
left_mean,0.60 ± 0.12,0.57 ± 0.08,0.53 ± 0.08,0.56 ± 0.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.318 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.712 | G2vG3: 0.035,121.00 ± 17.00,131.50 ± 9.50,110.00 ± 16.00,120.50 ± 24.75
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.803 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.003 | G1vG3: 1.000 | G2vG3: 0.669,81.00 ± 11.25,85.50 ± 9.00,74.00 ± 11.00,78.50 ± 20.75
2,frec_cardiaca,ANOVA,0.0177,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.304 | G1vG3: 0.950 | G2vG3: 1.000,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5711,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,31.30 ± 12.85,29.65 ± 10.30,31.20 ± 11.20,32.35 ± 11.07
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.4466,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.826 | G2vG3: 1.000,21.45 ± 10.48,16.85 ± 8.48,21.20 ± 9.30,23.10 ± 14.95
5,right_pulsatility_index,Kruskal-Wallis,0.7471,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.80 ± 0.50,1.69 ± 0.22,1.72 ± 0.50,1.85 ± 0.54
6,right_psv_ratio,ANOVA,0.2587,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.392 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.778,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0992,G0vG1: 1.000 | G0vG2: 0.100 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.35 ± 14.10,36.65 ± 11.70,32.60 ± 11.05,33.60 ± 14.52
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.2196,G0vG1: 1.000 | G0vG2: 0.999 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.444,24.25 ± 10.53,21.50 ± 11.40,22.50 ± 8.30,25.55 ± 10.65
9,left_pulsatility_index,Kruskal-Wallis,0.6289,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.69 ± 0.60,1.79 ± 0.23,1.71 ± 0.53,1.70 ± 0.51
10,left_psv_ratio,Kruskal-Wallis,0.3288,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.387 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.907,0.70 ± 0.13,0.66 ± 0.17,0.70 ± 0.16,0.75 ± 0.18
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.213 | G1vG2: 0.041 | G1vG3: 0.218 | G2vG3: 1.000,0.55 ± 0.15,0.56 ± 0.04,0.51 ± 0.10,0.51 ± 0.11
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.394 | G1vG2: 0.512 | G1vG3: 1.000 | G2vG3: 0.591,0.58 ± 0.13,0.58 ± 0.08,0.52 ± 0.10,0.55 ± 0.17

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
hemoglobina,126.98 ± 22.15,135.75 ± 12.61,126.75 ± 23.53,120.35 ± 35.33
hematocrito,0.39 ± 0.03,0.40 ± 0.04,0.39 ± 0.03,0.39 ± 0.03
leucocitos,7005.13 ± 1749.06,6007.50 ± 2574.74,6436.07 ± 1519.65,6241.25 ± 1774.76
plaquetas,277078.95 ± 63005.35,250000.00 ± 91524.13,269687.20 ± 61499.41,275125.00 ± 89137.08
glucosa,90.95 ± 15.16,90.00 ± 6.93,86.32 ± 9.93,88.71 ± 10.81
sodio,139.43 ± 2.09,139.25 ± 1.89,139.74 ± 1.73,139.33 ± 1.71
potasio,4.24 ± 0.31,4.05 ± 0.37,4.21 ± 0.27,4.22 ± 0.26
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93
hemoglobina_glicada,5.51 ± 0.46,5.57 ± 0.25,5.32 ± 0.33,5.46 ± 0.48
ast,21.92 ± 12.13,20.75 ± 3.95,21.74 ± 9.82,21.38 ± 5.81
alt,20.33 ± 19.71,18.75 ± 6.85,17.56 ± 9.96,20.21 ± 10.92
bilirubina_total,0.60 ± 0.32,0.51 ± 0.08,0.68 ± 0.30,0.65 ± 0.33
ldh,173.11 ± 28.51,189.00 ± 32.56,162.81 ± 24.67,165.56 ± 32.35
vldl,19.07 ± 11.13,23.01 ± 13.96,12.85 ± 7.19,16.15 ± 9.05
ldl,112.78 ± 31.82,134.62 ± 41.14,111.04 ± 27.73,115.42 ± 26.34
hdl,54.05 ± 14.47,45.18 ± 6.65,62.36 ± 13.40,56.41 ± 12.66
colesterol_total,185.88 ± 35.81,202.88 ± 45.28,186.11 ± 31.04,187.97 ± 31.57
trigliceridos,95.12 ± 54.76,114.17 ± 69.26,65.46 ± 35.29,80.41 ± 44.72
prote_totales_orina,2.04 ± 11.60,17.95 ± 35.63,2.47 ± 12.62,4.42 ± 16.01

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.7793,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,131.00 ± 11.75,135.50 ± 16.75,131.00 ± 14.00,128.50 ± 17.00
1,hematocrito,Kruskal-Wallis,0.9534,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.04,0.40 ± 0.05,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0521,G0vG1: 1.000 | G0vG2: 0.093 | G0vG3: 0.328 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6670.00 ± 2060.00,5200.00 ± 2802.50,6260.00 ± 1910.00,6000.00 ± 2250.00
3,plaquetas,Kruskal-Wallis,0.8439,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,272500.00 ± 74500.00,257500.00 ± 123000.00,264000.00 ± 82500.00,267500.00 ± 105000.00
4,glucosa,Kruskal-Wallis,0.0476,G0vG1: 1.000 | G0vG2: 0.068 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,89.00 ± 9.75,92.00 ± 4.00,86.00 ± 10.00,87.00 ± 7.00
5,sodio,Kruskal-Wallis,0.5574,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,139.00 ± 3.00,138.50 ± 1.75,140.00 ± 2.00,139.50 ± 2.25
6,potasio,Kruskal-Wallis,0.7840,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.21 ± 0.41,4.13 ± 0.45,4.21 ± 0.31,4.23 ± 0.26
7,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12
8,hemoglobina_glicada,Kruskal-Wallis,0.0008,G0vG1: 1.000 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.265 | G1vG3: 1.000 | G2vG3: 1.000,5.40 ± 0.45,5.55 ± 0.22,5.30 ± 0.40,5.35 ± 0.40
9,ast,Kruskal-Wallis,0.7869,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,19.00 ± 6.00,21.50 ± 5.75,20.00 ± 5.50,20.00 ± 4.75
10,alt,Kruskal-Wallis,0.4748,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,15.50 ± 10.25,18.50 ± 7.75,15.00 ± 7.00,16.50 ± 11.25
11,bilirubina_total,Kruskal-Wallis,0.0132,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.840 | G1vG3: 1.000 | G2vG3: 1.000,0.54 ± 0.24,0.51 ± 0.07,0.61 ± 0.32,0.59 ± 0.24
12,ldh,Kruskal-Wallis,0.0146,G0vG1: 1.000 | G0vG2: 0.025 | G0vG3: 1.000 | G1vG2: 0.457 | G1vG3: 1.000 | G2vG3: 1.000,169.00 ± 31.00,182.00 ± 39.00,159.00 ± 28.00,159.50 ± 33.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.180 | G1vG3: 1.000 | G2vG3: 0.201,15.34 ± 13.23,18.81 ± 10.25,10.88 ± 5.71,14.98 ± 7.62
14,ldl,Kruskal-Wallis,0.3958,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,107.16 ± 38.03,139.31 ± 32.11,106.29 ± 37.31,117.41 ± 20.34
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.047 | G1vG3: 0.645 | G2vG3: 0.224,53.41 ± 15.77,45.09 ± 7.64,61.15 ± 17.02,55.53 ± 19.16
16,colesterol_total,Kruskal-Wallis,0.5769,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,182.67 ± 33.86,213.62 ± 43.44,183.05 ± 41.60,189.82 ± 31.83
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.183 | G1vG3: 1.000 | G2vG3: 0.329,76.11 ± 65.71,93.37 ± 50.88,53.98 ± 23.89,74.34 ± 35.74
18,prote_totales_orina,Kruskal-Wallis,0.5068,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.988 | G1vG3: 1.000 | G2vG3: 1.000,0.08 ± 0.04,0.16 ± 17.95,0.08 ± 0.05,0.08 ± 0.06

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
Cat_Dieta: Adherencia moderada,51 (46.8%),3 (37.5%),210 (67.1%),21 (72.4%)
Cat_Dieta: Alta adherencia,4 (3.7%),0 (0.0%),21 (6.7%),0 (0.0%)
Cat_Dieta: Baja adherencia,54 (49.5%),5 (62.5%),82 (26.2%),8 (27.6%)
Cat_Actividad: Actividad física alta,93 (85.3%),8 (100.0%),288 (93.2%),24 (88.9%)
Cat_Actividad: Actividad física baja,2 (1.8%),0 (0.0%),9 (2.9%),0 (0.0%)
Cat_Actividad: Actividad física moderada,14 (12.8%),0 (0.0%),12 (3.9%),3 (11.1%)
Cat_Estres: Nivel de estrés alto,48 (44.4%),0 (0.0%),100 (31.9%),14 (50.0%)
Cat_Estres: Nivel de estrés bajo,13 (12.0%),1 (12.5%),36 (11.5%),2 (7.1%)
Cat_Estres: Nivel de estrés moderado,41 (38.0%),7 (87.5%),170 (54.3%),10 (35.7%)
Cat_Estres: Nivel de estrés muy alto,6 (5.6%),0 (0.0%),7 (2.2%),2 (7.1%)
Cat_Memoria: Deterioro leve,18 (16.7%),0 (0.0%),43 (13.8%),4 (14.8%)
Cat_Memoria: Disfunción moderada-grave,13 (12.0%),0 (0.0%),26 (8.4%),5 (18.5%)
Cat_Memoria: Función normal (lapsus leves),60 (55.6%),4 (50.0%),182 (58.5%),14 (51.9%)
Cat_Memoria: Rendimiento de memoria óptimo,17 (15.7%),4 (50.0%),60 (19.3%),4 (14.8%)
Cat_SCL90R: EN RIESGO,9 (8.5%),5 (62.5%),40 (13.0%),3 (10.3%)
Cat_SCL90R: Normal / Sin riesgo,17 (16.0%),1 (12.5%),68 (22.1%),3 (10.3%)
Cat_SCL90R: Patología severa,80 (75.5%),2 (25.0%),200 (64.9%),23 (79.3%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.244 | G1vG2: 0.412 | G1vG3: 0.946 | G2vG3: 1.000,Adherencia moderada: n=51 (46.8%) | Alta adherencia: n=4 (3.7%) | Baja adherencia: n=54 (49.5%),Adherencia moderada: n=3 (37.5%) | Baja adherencia: n=5 (62.5%),Adherencia moderada: n=210 (67.1%) | Alta adherencia: n=21 (6.7%) | Baja adherencia: n=82 (26.2%),Adherencia moderada: n=21 (72.4%) | Baja adherencia: n=8 (27.6%)
1,Cat_Actividad,Chi-Square,0.0356,G0vG1: 1.000 | G0vG2: 0.031 | G0vG3: 0.254 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.228,Actividad física alta: n=93 (85.3%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=14 (12.8%),Actividad física alta: n=8 (100.0%),Actividad física alta: n=288 (93.2%) | Actividad física baja: n=9 (2.9%) | Actividad física moderada: n=12 (3.9%),Actividad física alta: n=24 (88.9%) | Actividad física moderada: n=3 (11.1%)
2,Cat_Estres,Chi-Square,0.0149,G0vG1: 0.439 | G0vG2: 0.053 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.403 | G2vG3: 0.009,Nivel de estrés alto: n=48 (44.4%) | Nivel de estrés bajo: n=13 (12.0%) | Nivel de estrés moderado: n=41 (38.0%) | Nivel de estrés muy alto: n=6 (5.6%),Nivel de estrés bajo: n=1 (12.5%) | Nivel de estrés moderado: n=7 (87.5%),Nivel de estrés alto: n=100 (31.9%) | Nivel de estrés bajo: n=36 (11.5%) | Nivel de estrés moderado: n=170 (54.3%) | Nivel de estrés muy alto: n=7 (2.2%),Nivel de estrés alto: n=14 (50.0%) | Nivel de estrés bajo: n=2 (7.1%) | Nivel de estrés moderado: n=10 (35.7%) | Nivel de estrés muy alto: n=2 (7.1%)
3,Cat_Memoria,Chi-Square,0.2712,G0vG1: 0.726 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.868 | G2vG3: 0.100,Deterioro leve: n=18 (16.7%) | Disfunción moderada-grave: n=13 (12.0%) | Función normal (lapsus leves): n=60 (55.6%) | Rendimiento de memoria óptimo: n=17 (15.7%),Función normal (lapsus leves): n=4 (50.0%) | Rendimiento de memoria óptimo: n=4 (50.0%),Deterioro leve: n=43 (13.8%) | Disfunción moderada-grave: n=26 (8.4%) | Función normal (lapsus leves): n=182 (58.5%) | Rendimiento de memoria óptimo: n=60 (19.3%),Deterioro leve: n=4 (14.8%) | Disfunción moderada-grave: n=5 (18.5%) | Función normal (lapsus leves): n=14 (51.9%) | Rendimiento de memoria óptimo: n=4 (14.8%)
4,Cat_SCL90R,Chi-Square,0.0004,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.007 | G1vG3: 0.029 | G2vG3: 1.000,EN RIESGO: n=9 (8.5%) | Normal / Sin riesgo: n=17 (16.0%) | Patología severa: n=80 (75.5%),EN RIESGO: n=5 (62.5%) | Normal / Sin riesgo: n=1 (12.5%) | Patología severa: n=2 (25.0%),EN RIESGO: n=40 (13.0%) | Normal / Sin riesgo: n=68 (22.1%) | Patología severa: n=200 (64.9%),EN RIESGO: n=3 (10.3%) | Normal / Sin riesgo: n=3 (10.3%) | Patología severa: n=23 (79.3%)

ANTECEDENTES

                                 Grupo 0     Grupo 1      Grupo 2     Grupo 3
trastorno_hipertensivo: 0.0   68 (62.4%)   2 (25.0%)  244 (78.0%)  13 (44.8%)
trastorno_hipertensivo: 1.0   41 (37.6%)   6 (75.0%)   69 (22.0%)  16 (55.2%)
comp_placentaria: 0.0        100 (91.7%)   7 (87.5%)  266 (85.0%)  17 (58.6%)
comp_placentaria: 1.0           9 (8.3%)   1 (12.5%)   47 (15.0%)  12 (41.4%)
comp_maternaGrave: 0.0       103 (94.5%)   4 (50.0%)  293 (93.6%)  18 (62.1%)
comp_maternaGrave: 1.0          6 (5.5%)   4 (50.0%)    20 (6.4%)  11 (37.9%)
comp_metabolica: 0.0          90 (82.6%)  8 (100.0%)  287 (91.7%)  26 (89.7%)
comp_metabolica: 1.0          19 (17.4%)    0 (0.0%)    26 (8.3%)   3 (10.3%)
ant_obstetrico: -1            78 (71.6%)   7 (87.5%)  233 (74.4%)  18 (62.1%)
ant_obstetrico: 1             24 (22.0%)    0 (0.0%)   66 (21.1%)   9 (31.0%)
ant_obstetrico: 3               4 (3.7%)   1 (12.5%)    11 (3.5%)    2 (6.9%)
ant_obstetrico: 4               3 (2.8%)    0 (0.0%)     3 (1.0%)    0 (0.0%)
ant_medico: -1                74 (67.9%)   3 (37.5%)  257 (82.1%)  22 (75.9%)
ant_medico: 1                 29 (26.6%)   5 (62.5%)   48 (15.3%)   4 (13.8%)
ant_medico: 3                   6 (5.5%)    0 (0.0%)     8 (2.6%)    2 (6.9%)
ant_medico: 5                   0 (0.0%)    0 (0.0%)     0 (0.0%)    1 (3.4%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.525 | G0vG2: 0.013 | G0vG3: 0.810 | G1vG2: 0.013 | G1vG3: 1.000 | G2vG3: 0.001,0.0: n=68 (62.4%) | 1.0: n=41 (37.6%),0.0: n=2 (25.0%) | 1.0: n=6 (75.0%),0.0: n=244 (78.0%) | 1.0: n=69 (22.0%),0.0: n=13 (44.8%) | 1.0: n=16 (55.2%)
1,comp_placentaria,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.622 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.005,0.0: n=100 (91.7%) | 1.0: n=9 (8.3%),0.0: n=7 (87.5%) | 1.0: n=1 (12.5%),0.0: n=266 (85.0%) | 1.0: n=47 (15.0%),0.0: n=17 (58.6%) | 1.0: n=12 (41.4%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 1.000 | G2vG3: 0.000,0.0: n=103 (94.5%) | 1.0: n=6 (5.5%),0.0: n=4 (50.0%) | 1.0: n=4 (50.0%),0.0: n=293 (93.6%) | 1.0: n=20 (6.4%),0.0: n=18 (62.1%) | 1.0: n=11 (37.9%)
3,comp_metabolica,Chi-Square,0.0432,G0vG1: 1.000 | G0vG2: 0.079 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=90 (82.6%) | 1.0: n=19 (17.4%),0.0: n=8 (100.0%),0.0: n=287 (91.7%) | 1.0: n=26 (8.3%),0.0: n=26 (89.7%) | 1.0: n=3 (10.3%)
4,ant_obstetrico,Chi-Square,0.4734,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=78 (71.6%) | 1: n=24 (22.0%) | 3: n=4 (3.7%) | 4: n=3 (2.8%),-1: n=7 (87.5%) | 3: n=1 (12.5%),-1: n=233 (74.4%) | 1: n=66 (21.1%) | 3: n=11 (3.5%) | 4: n=3 (1.0%),-1: n=18 (62.1%) | 1: n=9 (31.0%) | 3: n=2 (6.9%)
5,ant_medico,Chi-Square,0.0000,G0vG1: 0.547 | G0vG2: 0.044 | G0vG3: 0.791 | G1vG2: 0.011 | G1vG3: 0.240 | G2vG3: 0.032,-1: n=74 (67.9%) | 1: n=29 (26.6%) | 3: n=6 (5.5%),-1: n=3 (37.5%) | 1: n=5 (62.5%),-1: n=257 (82.1%) | 1: n=48 (15.3%) | 3: n=8 (2.6%),-1: n=22 (75.9%) | 1: n=4 (13.8%) | 3: n=2 (6.9%) | 5: n=1 (3.4%)

======================================================================
COMBINACIÓN 9 | K = 4 | SILHOUETTE = 0.4151
======================================================================

TAMAÑO DE GRUPOS:
cluster    0  1    2   3
count    109  8  313  29

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
peso_ini_gest,86.16 ± 11.65,84.50 ± 22.52,59.73 ± 7.30,66.32 ± 10.01
peso_fin_gest,96.99 ± 12.47,99.27 ± 21.62,71.62 ± 9.06,78.91 ± 12.42
aumento_peso_gest,10.87 ± 6.04,14.84 ± 9.93,11.86 ± 4.99,12.69 ± 6.57
talla,165.40 ± 6.50,161.50 ± 5.18,163.51 ± 6.07,161.98 ± 5.43
imc_ini_gest,31.53 ± 4.03,32.60 ± 9.64,22.35 ± 2.54,25.28 ± 4.05
edad_materna_gest,35.42 ± 5.20,37.06 ± 3.51,35.43 ± 4.47,36.61 ± 4.95
tas_1tri,118.81 ± 11.06,121.72 ± 13.63,112.06 ± 10.83,120.34 ± 13.31
tad_1tri,74.89 ± 7.74,82.30 ± 5.45,72.05 ± 7.89,74.30 ± 12.19
eg_eco_1tri,12.82 ± 0.61,12.78 ± 0.48,12.70 ± 0.62,12.78 ± 0.49
eg_parto,39.17 ± 1.64,35.26 ± 3.92,39.35 ± 1.73,36.06 ± 4.06
peso_rn,3239.67 ± 519.83,2365.00 ± 803.74,3079.82 ± 557.39,2463.17 ± 1055.40
apgar_1min,8.93 ± 0.57,3.50 ± 1.41,8.97 ± 0.41,7.18 ± 1.60
apgar_5min,9.94 ± 0.25,5.88 ± 2.17,9.94 ± 0.24,8.51 ± 0.63
apgar_10min,9.99 ± 0.10,8.25 ± 0.46,10.00 ± 0.02,9.09 ± 0.38
ratio_MoM,3.29 ± 5.45,52.81 ± 125.96,3.96 ± 15.42,46.58 ± 82.01
sflt1_MoM,1.51 ± 1.02,5.77 ± 9.69,1.58 ± 1.24,3.64 ± 3.31
plgf_MoM,1.08 ± 0.77,1.38 ± 2.64,1.40 ± 1.03,1.19 ± 1.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.094 | G2vG3: 0.005,84.50 ± 12.00,80.25 ± 18.12,60.00 ± 11.00,66.00 ± 14.50
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.059 | G2vG3: 0.017,95.00 ± 13.00,96.65 ± 17.40,72.00 ± 13.70,77.80 ± 16.40
2,aumento_peso_gest,Kruskal-Wallis,0.2522,G0vG1: 1.000 | G0vG2: 0.418 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,10.00 ± 7.10,12.55 ± 2.92,11.63 ± 5.00,12.00 ± 7.00
3,talla,Kruskal-Wallis,0.0292,G0vG1: 0.592 | G0vG2: 0.158 | G0vG3: 0.108 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,165.00 ± 9.00,160.00 ± 6.00,163.00 ± 8.00,163.00 ± 8.50
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.001 | G1vG3: 0.081 | G2vG3: 0.001,30.82 ± 5.88,30.96 ± 7.44,22.23 ± 4.03,24.31 ± 5.20
5,edad_materna_gest,Kruskal-Wallis,0.5077,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.68 ± 7.19,36.19 ± 3.92,35.47 ± 5.92,35.99 ± 6.21
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.289 | G1vG3: 1.000 | G2vG3: 0.002,118.00 ± 15.00,117.38 ± 18.00,112.00 ± 14.00,119.00 ± 16.52
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.022 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 0.120 | G2vG3: 0.582,75.00 ± 9.00,83.00 ± 8.18,72.00 ± 10.00,76.00 ± 9.42
8,eg_eco_1tri,Kruskal-Wallis,0.6433,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.80 ± 0.70,12.80 ± 0.53,12.72 ± 0.50,12.80 ± 0.44
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 0.002 | G1vG2: 0.001 | G1vG3: 1.000 | G2vG3: 0.000,39.30 ± 2.10,36.25 ± 2.65,39.60 ± 2.00,37.30 ± 6.10
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.007 | G0vG2: 0.110 | G0vG3: 0.002 | G1vG2: 0.033 | G1vG3: 1.000 | G2vG3: 0.011,3180.00 ± 645.00,2485.00 ± 662.50,3110.00 ± 696.44,2640.00 ± 1820.00
11,apgar_1min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,9.00 ± 0.00,4.00 ± 1.50,9.00 ± 0.00,7.21 ± 2.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.000,10.00 ± 0.00,6.50 ± 1.25,10.00 ± 0.00,9.00 ± 1.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.000,10.00 ± 0.00,8.00 ± 0.25,10.00 ± 0.00,9.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0006,G0vG1: 0.232 | G0vG2: 1.000 | G0vG3: 0.017 | G1vG2: 0.097 | G1vG3: 1.000 | G2vG3: 0.004,1.70 ± 2.10,7.03 ± 12.05,1.68 ± 1.47,4.75 ± 61.28
15,sflt1_MoM,Kruskal-Wallis,0.0003,G0vG1: 0.091 | G0vG2: 1.000 | G0vG3: 0.003 | G1vG2: 0.147 | G1vG3: 1.000 | G2vG3: 0.002,1.26 ± 0.82,2.79 ± 1.70,1.26 ± 0.62,1.83 ± 4.85
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.304 | G0vG2: 0.003 | G0vG3: 0.041 | G1vG2: 0.107 | G1vG3: 1.000 | G2vG3: 0.001,0.93 ± 0.93,0.37 ± 0.53,1.29 ± 0.90,0.47 ± 1.03

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
diam_telediastolico,47.69 ± 4.66,45.00 ± 5.73,44.01 ± 5.41,45.04 ± 5.21
diam_telesistolico,32.34 ± 5.10,29.72 ± 4.96,29.10 ± 3.94,28.99 ± 5.02
dtsvi_indexado,16.53 ± 2.65,15.59 ± 3.59,17.12 ± 2.73,16.20 ± 3.22
septo_iv_diastole,9.76 ± 8.30,9.10 ± 1.41,9.33 ± 10.35,8.67 ± 2.02
pared_posterior_vi_diastole,8.51 ± 5.68,8.30 ± 0.93,8.63 ± 9.66,7.68 ± 1.27
diam_ai,36.69 ± 3.59,33.33 ± 4.13,32.14 ± 4.37,34.60 ± 4.89
ai_volumen,44.91 ± 15.82,41.25 ± 13.03,34.19 ± 11.09,38.92 ± 12.70
ad_volumen,38.26 ± 13.46,36.65 ± 21.11,30.95 ± 15.74,32.10 ± 10.21
tapse,27.55 ± 27.84,25.98 ± 3.26,25.51 ± 12.10,26.37 ± 4.23
e_mitral,71.59 ± 14.25,74.43 ± 17.47,82.35 ± 72.46,74.29 ± 16.40
e_e,3.73 ± 1.00,4.06 ± 1.20,4.23 ± 3.91,3.94 ± 1.10
gc_tsvi,7.51 ± 6.76,6.10 ± 0.96,5.98 ± 4.19,8.00 ± 11.30
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.179 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,47.00 ± 7.00,43.00 ± 7.50,44.00 ± 6.00,44.00 ± 6.50
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.040 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,32.00 ± 7.00,29.00 ± 3.75,29.00 ± 5.00,29.00 ± 7.00
2,dtsvi_indexado,Kruskal-Wallis,0.0890,G0vG1: 1.000 | G0vG2: 0.279 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.902,16.15 ± 3.81,16.23 ± 2.59,17.13 ± 3.28,16.57 ± 4.45
3,septo_iv_diastole,Kruskal-Wallis,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.469 | G1vG3: 1.000 | G2vG3: 0.767,9.00 ± 2.20,9.35 ± 1.62,8.00 ± 2.00,8.30 ± 2.10
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0186,G0vG1: 1.000 | G0vG2: 0.044 | G0vG3: 1.000 | G1vG2: 0.510 | G1vG3: 0.857 | G2vG3: 1.000,8.00 ± 2.00,8.15 ± 0.82,7.00 ± 2.12,7.80 ± 1.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.479 | G0vG2: 0.000 | G0vG3: 0.367 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.097,37.00 ± 4.00,33.50 ± 7.25,32.00 ± 5.00,34.50 ± 6.25
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.423,42.65 ± 18.75,39.50 ± 16.40,33.00 ± 14.20,40.90 ± 20.45
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.343 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,38.40 ± 18.03,31.10 ± 3.12,28.65 ± 15.30,32.00 ± 15.80
8,tapse,Kruskal-Wallis,0.1922,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.559 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.263,24.60 ± 6.00,27.50 ± 4.00,24.70 ± 5.50,26.00 ± 5.40
9,e_mitral,Kruskal-Wallis,0.0422,G0vG1: 1.000 | G0vG2: 0.027 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,71.70 ± 16.80,73.00 ± 25.78,75.60 ± 17.60,74.00 ± 18.10
10,e_e,Kruskal-Wallis,0.3415,G0vG1: 1.000 | G0vG2: 0.746 | G0vG3: 0.770 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.57 ± 1.16,4.07 ± 1.12,3.76 ± 1.17,3.89 ± 0.78
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.070 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6.55 ± 1.73,5.70 ± 1.15,5.50 ± 1.30,5.40 ± 1.80
12,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
ta_sistolica,123.11 ± 15.81,133.75 ± 16.68,111.79 ± 12.79,122.11 ± 19.70
ta_diastolica,80.06 ± 9.49,84.25 ± 5.42,73.39 ± 8.87,77.57 ± 15.06
frec_cardiaca,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
right_1peak_systolic_velocity,32.03 ± 9.84,27.24 ± 7.78,31.27 ± 8.70,31.49 ± 7.49
right_2peak_systolic_velocity,21.86 ± 7.42,18.70 ± 5.63,21.79 ± 7.07,23.51 ± 8.13
right_pulsatility_index,1.79 ± 0.40,1.74 ± 0.40,1.77 ± 0.46,1.84 ± 0.48
right_psv_ratio,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
left_1peak_systolic_velocity,35.06 ± 10.07,33.88 ± 12.35,32.76 ± 8.96,34.96 ± 9.37
left_2peak_systolic_velocity,24.19 ± 8.18,23.41 ± 9.84,23.13 ± 7.26,26.00 ± 7.97
left_pulsatility_index,1.96 ± 2.28,1.86 ± 0.38,1.71 ± 0.41,1.68 ± 0.44
left_psv_ratio,0.69 ± 0.13,0.69 ± 0.12,0.71 ± 0.12,0.75 ± 0.14
right_mean,0.58 ± 0.14,0.58 ± 0.05,0.51 ± 0.08,0.52 ± 0.08
left_mean,0.60 ± 0.12,0.57 ± 0.08,0.53 ± 0.08,0.56 ± 0.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.318 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.712 | G2vG3: 0.035,121.00 ± 17.00,131.50 ± 9.50,110.00 ± 16.00,120.50 ± 24.75
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.803 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.003 | G1vG3: 1.000 | G2vG3: 0.669,81.00 ± 11.25,85.50 ± 9.00,74.00 ± 11.00,78.50 ± 20.75
2,frec_cardiaca,ANOVA,0.0177,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.304 | G1vG3: 0.950 | G2vG3: 1.000,81.31 ± 12.07,85.88 ± 11.01,77.87 ± 11.69,80.46 ± 11.41
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5711,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,31.30 ± 12.85,29.65 ± 10.30,31.20 ± 11.20,32.35 ± 11.07
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.4466,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.826 | G2vG3: 1.000,21.45 ± 10.48,16.85 ± 8.48,21.20 ± 9.30,23.10 ± 14.95
5,right_pulsatility_index,Kruskal-Wallis,0.7471,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.80 ± 0.50,1.69 ± 0.22,1.72 ± 0.50,1.85 ± 0.54
6,right_psv_ratio,ANOVA,0.2587,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.392 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.778,0.69 ± 0.12,0.70 ± 0.15,0.70 ± 0.12,0.74 ± 0.14
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0992,G0vG1: 1.000 | G0vG2: 0.100 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,35.35 ± 14.10,36.65 ± 11.70,32.60 ± 11.05,33.60 ± 14.52
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.2196,G0vG1: 1.000 | G0vG2: 0.999 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.444,24.25 ± 10.53,21.50 ± 11.40,22.50 ± 8.30,25.55 ± 10.65
9,left_pulsatility_index,Kruskal-Wallis,0.6289,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.69 ± 0.60,1.79 ± 0.23,1.71 ± 0.53,1.70 ± 0.51
10,left_psv_ratio,Kruskal-Wallis,0.3288,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.387 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.907,0.70 ± 0.13,0.66 ± 0.17,0.70 ± 0.16,0.75 ± 0.18
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.213 | G1vG2: 0.041 | G1vG3: 0.218 | G2vG3: 1.000,0.55 ± 0.15,0.56 ± 0.04,0.51 ± 0.10,0.51 ± 0.11
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.394 | G1vG2: 0.512 | G1vG3: 1.000 | G2vG3: 0.591,0.58 ± 0.13,0.58 ± 0.08,0.52 ± 0.10,0.55 ± 0.17

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
hemoglobina,126.98 ± 22.15,135.75 ± 12.61,126.75 ± 23.53,120.35 ± 35.33
hematocrito,0.39 ± 0.03,0.40 ± 0.04,0.39 ± 0.03,0.39 ± 0.03
leucocitos,7005.13 ± 1749.06,6007.50 ± 2574.74,6436.07 ± 1519.65,6241.25 ± 1774.76
plaquetas,277078.95 ± 63005.35,250000.00 ± 91524.13,269687.20 ± 61499.41,275125.00 ± 89137.08
glucosa,90.95 ± 15.16,90.00 ± 6.93,86.32 ± 9.93,88.71 ± 10.81
sodio,139.43 ± 2.09,139.25 ± 1.89,139.74 ± 1.73,139.33 ± 1.71
potasio,4.24 ± 0.31,4.05 ± 0.37,4.21 ± 0.27,4.22 ± 0.26
urato_acidourico,4.46 ± 1.01,4.08 ± 0.58,4.09 ± 1.58,4.04 ± 0.93
hemoglobina_glicada,5.51 ± 0.46,5.57 ± 0.25,5.32 ± 0.33,5.46 ± 0.48
ast,21.92 ± 12.13,20.75 ± 3.95,21.74 ± 9.82,21.38 ± 5.81
alt,20.33 ± 19.71,18.75 ± 6.85,17.56 ± 9.96,20.21 ± 10.92
bilirubina_total,0.60 ± 0.32,0.51 ± 0.08,0.68 ± 0.30,0.65 ± 0.33
ldh,173.11 ± 28.51,189.00 ± 32.56,162.81 ± 24.67,165.56 ± 32.35
vldl,19.07 ± 11.13,23.01 ± 13.96,12.85 ± 7.19,16.15 ± 9.05
ldl,112.78 ± 31.82,134.62 ± 41.14,111.04 ± 27.73,115.42 ± 26.34
hdl,54.05 ± 14.47,45.18 ± 6.65,62.36 ± 13.40,56.41 ± 12.66
colesterol_total,185.88 ± 35.81,202.88 ± 45.28,186.11 ± 31.04,187.97 ± 31.57
trigliceridos,95.12 ± 54.76,114.17 ± 69.26,65.46 ± 35.29,80.41 ± 44.72
prote_totales_orina,2.04 ± 11.60,17.95 ± 35.63,2.47 ± 12.62,4.42 ± 16.01

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.7793,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,131.00 ± 11.75,135.50 ± 16.75,131.00 ± 14.00,128.50 ± 17.00
1,hematocrito,Kruskal-Wallis,0.9534,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.04,0.40 ± 0.05,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0521,G0vG1: 1.000 | G0vG2: 0.093 | G0vG3: 0.328 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6670.00 ± 2060.00,5200.00 ± 2802.50,6260.00 ± 1910.00,6000.00 ± 2250.00
3,plaquetas,Kruskal-Wallis,0.8439,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,272500.00 ± 74500.00,257500.00 ± 123000.00,264000.00 ± 82500.00,267500.00 ± 105000.00
4,glucosa,Kruskal-Wallis,0.0476,G0vG1: 1.000 | G0vG2: 0.068 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,89.00 ± 9.75,92.00 ± 4.00,86.00 ± 10.00,87.00 ± 7.00
5,sodio,Kruskal-Wallis,0.5574,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,139.00 ± 3.00,138.50 ± 1.75,140.00 ± 2.00,139.50 ± 2.25
6,potasio,Kruskal-Wallis,0.7840,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.21 ± 0.41,4.13 ± 0.45,4.21 ± 0.31,4.23 ± 0.26
7,urato_acidourico,Kruskal-Wallis,0.0173,G0vG1: 1.000 | G0vG2: 0.009 | G0vG3: 0.630 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.36 ± 1.46,3.96 ± 0.77,3.98 ± 1.05,3.94 ± 1.12
8,hemoglobina_glicada,Kruskal-Wallis,0.0008,G0vG1: 1.000 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.265 | G1vG3: 1.000 | G2vG3: 1.000,5.40 ± 0.45,5.55 ± 0.22,5.30 ± 0.40,5.35 ± 0.40
9,ast,Kruskal-Wallis,0.7869,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,19.00 ± 6.00,21.50 ± 5.75,20.00 ± 5.50,20.00 ± 4.75
10,alt,Kruskal-Wallis,0.4748,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,15.50 ± 10.25,18.50 ± 7.75,15.00 ± 7.00,16.50 ± 11.25
11,bilirubina_total,Kruskal-Wallis,0.0132,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 1.000 | G1vG2: 0.840 | G1vG3: 1.000 | G2vG3: 1.000,0.54 ± 0.24,0.51 ± 0.07,0.61 ± 0.32,0.59 ± 0.24
12,ldh,Kruskal-Wallis,0.0146,G0vG1: 1.000 | G0vG2: 0.025 | G0vG3: 1.000 | G1vG2: 0.457 | G1vG3: 1.000 | G2vG3: 1.000,169.00 ± 31.00,182.00 ± 39.00,159.00 ± 28.00,159.50 ± 33.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.180 | G1vG3: 1.000 | G2vG3: 0.201,15.34 ± 13.23,18.81 ± 10.25,10.88 ± 5.71,14.98 ± 7.62
14,ldl,Kruskal-Wallis,0.3958,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,107.16 ± 38.03,139.31 ± 32.11,106.29 ± 37.31,117.41 ± 20.34
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.047 | G1vG3: 0.645 | G2vG3: 0.224,53.41 ± 15.77,45.09 ± 7.64,61.15 ± 17.02,55.53 ± 19.16
16,colesterol_total,Kruskal-Wallis,0.5769,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,182.67 ± 33.86,213.62 ± 43.44,183.05 ± 41.60,189.82 ± 31.83
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.183 | G1vG3: 1.000 | G2vG3: 0.329,76.11 ± 65.71,93.37 ± 50.88,53.98 ± 23.89,74.34 ± 35.74
18,prote_totales_orina,Kruskal-Wallis,0.5068,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.988 | G1vG3: 1.000 | G2vG3: 1.000,0.08 ± 0.04,0.16 ± 17.95,0.08 ± 0.05,0.08 ± 0.06

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3
Cat_Dieta: Adherencia moderada,51 (46.8%),3 (37.5%),210 (67.1%),21 (72.4%)
Cat_Dieta: Alta adherencia,4 (3.7%),0 (0.0%),21 (6.7%),0 (0.0%)
Cat_Dieta: Baja adherencia,54 (49.5%),5 (62.5%),82 (26.2%),8 (27.6%)
Cat_Actividad: Actividad física alta,93 (85.3%),8 (100.0%),288 (93.2%),24 (88.9%)
Cat_Actividad: Actividad física baja,2 (1.8%),0 (0.0%),9 (2.9%),0 (0.0%)
Cat_Actividad: Actividad física moderada,14 (12.8%),0 (0.0%),12 (3.9%),3 (11.1%)
Cat_Estres: Nivel de estrés alto,48 (44.4%),0 (0.0%),100 (31.9%),14 (50.0%)
Cat_Estres: Nivel de estrés bajo,13 (12.0%),1 (12.5%),36 (11.5%),2 (7.1%)
Cat_Estres: Nivel de estrés moderado,41 (38.0%),7 (87.5%),170 (54.3%),10 (35.7%)
Cat_Estres: Nivel de estrés muy alto,6 (5.6%),0 (0.0%),7 (2.2%),2 (7.1%)
Cat_Memoria: Deterioro leve,18 (16.7%),0 (0.0%),43 (13.8%),4 (14.8%)
Cat_Memoria: Disfunción moderada-grave,13 (12.0%),0 (0.0%),26 (8.4%),5 (18.5%)
Cat_Memoria: Función normal (lapsus leves),60 (55.6%),4 (50.0%),182 (58.5%),14 (51.9%)
Cat_Memoria: Rendimiento de memoria óptimo,17 (15.7%),4 (50.0%),60 (19.3%),4 (14.8%)
Cat_SCL90R: EN RIESGO,9 (8.5%),5 (62.5%),40 (13.0%),3 (10.3%)
Cat_SCL90R: Normal / Sin riesgo,17 (16.0%),1 (12.5%),68 (22.1%),3 (10.3%)
Cat_SCL90R: Patología severa,80 (75.5%),2 (25.0%),200 (64.9%),23 (79.3%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.244 | G1vG2: 0.412 | G1vG3: 0.946 | G2vG3: 1.000,Adherencia moderada: n=51 (46.8%) | Alta adherencia: n=4 (3.7%) | Baja adherencia: n=54 (49.5%),Adherencia moderada: n=3 (37.5%) | Baja adherencia: n=5 (62.5%),Adherencia moderada: n=210 (67.1%) | Alta adherencia: n=21 (6.7%) | Baja adherencia: n=82 (26.2%),Adherencia moderada: n=21 (72.4%) | Baja adherencia: n=8 (27.6%)
1,Cat_Actividad,Chi-Square,0.0356,G0vG1: 1.000 | G0vG2: 0.031 | G0vG3: 0.254 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.228,Actividad física alta: n=93 (85.3%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=14 (12.8%),Actividad física alta: n=8 (100.0%),Actividad física alta: n=288 (93.2%) | Actividad física baja: n=9 (2.9%) | Actividad física moderada: n=12 (3.9%),Actividad física alta: n=24 (88.9%) | Actividad física moderada: n=3 (11.1%)
2,Cat_Estres,Chi-Square,0.0149,G0vG1: 0.439 | G0vG2: 0.053 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.403 | G2vG3: 0.009,Nivel de estrés alto: n=48 (44.4%) | Nivel de estrés bajo: n=13 (12.0%) | Nivel de estrés moderado: n=41 (38.0%) | Nivel de estrés muy alto: n=6 (5.6%),Nivel de estrés bajo: n=1 (12.5%) | Nivel de estrés moderado: n=7 (87.5%),Nivel de estrés alto: n=100 (31.9%) | Nivel de estrés bajo: n=36 (11.5%) | Nivel de estrés moderado: n=170 (54.3%) | Nivel de estrés muy alto: n=7 (2.2%),Nivel de estrés alto: n=14 (50.0%) | Nivel de estrés bajo: n=2 (7.1%) | Nivel de estrés moderado: n=10 (35.7%) | Nivel de estrés muy alto: n=2 (7.1%)
3,Cat_Memoria,Chi-Square,0.2712,G0vG1: 0.726 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.868 | G2vG3: 0.100,Deterioro leve: n=18 (16.7%) | Disfunción moderada-grave: n=13 (12.0%) | Función normal (lapsus leves): n=60 (55.6%) | Rendimiento de memoria óptimo: n=17 (15.7%),Función normal (lapsus leves): n=4 (50.0%) | Rendimiento de memoria óptimo: n=4 (50.0%),Deterioro leve: n=43 (13.8%) | Disfunción moderada-grave: n=26 (8.4%) | Función normal (lapsus leves): n=182 (58.5%) | Rendimiento de memoria óptimo: n=60 (19.3%),Deterioro leve: n=4 (14.8%) | Disfunción moderada-grave: n=5 (18.5%) | Función normal (lapsus leves): n=14 (51.9%) | Rendimiento de memoria óptimo: n=4 (14.8%)
4,Cat_SCL90R,Chi-Square,0.0004,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.007 | G1vG3: 0.029 | G2vG3: 1.000,EN RIESGO: n=9 (8.5%) | Normal / Sin riesgo: n=17 (16.0%) | Patología severa: n=80 (75.5%),EN RIESGO: n=5 (62.5%) | Normal / Sin riesgo: n=1 (12.5%) | Patología severa: n=2 (25.0%),EN RIESGO: n=40 (13.0%) | Normal / Sin riesgo: n=68 (22.1%) | Patología severa: n=200 (64.9%),EN RIESGO: n=3 (10.3%) | Normal / Sin riesgo: n=3 (10.3%) | Patología severa: n=23 (79.3%)

ANTECEDENTES

                                 Grupo 0     Grupo 1      Grupo 2     Grupo 3
trastorno_hipertensivo: 0.0   68 (62.4%)   2 (25.0%)  244 (78.0%)  13 (44.8%)
trastorno_hipertensivo: 1.0   41 (37.6%)   6 (75.0%)   69 (22.0%)  16 (55.2%)
comp_placentaria: 0.0        100 (91.7%)   7 (87.5%)  266 (85.0%)  17 (58.6%)
comp_placentaria: 1.0           9 (8.3%)   1 (12.5%)   47 (15.0%)  12 (41.4%)
comp_maternaGrave: 0.0       103 (94.5%)   4 (50.0%)  293 (93.6%)  18 (62.1%)
comp_maternaGrave: 1.0          6 (5.5%)   4 (50.0%)    20 (6.4%)  11 (37.9%)
comp_metabolica: 0.0          90 (82.6%)  8 (100.0%)  287 (91.7%)  26 (89.7%)
comp_metabolica: 1.0          19 (17.4%)    0 (0.0%)    26 (8.3%)   3 (10.3%)
ant_obstetrico: -1            78 (71.6%)   7 (87.5%)  233 (74.4%)  18 (62.1%)
ant_obstetrico: 1             24 (22.0%)    0 (0.0%)   66 (21.1%)   9 (31.0%)
ant_obstetrico: 3               4 (3.7%)   1 (12.5%)    11 (3.5%)    2 (6.9%)
ant_obstetrico: 4               3 (2.8%)    0 (0.0%)     3 (1.0%)    0 (0.0%)
ant_medico: -1                74 (67.9%)   3 (37.5%)  257 (82.1%)  22 (75.9%)
ant_medico: 1                 29 (26.6%)   5 (62.5%)   48 (15.3%)   4 (13.8%)
ant_medico: 3                   6 (5.5%)    0 (0.0%)     8 (2.6%)    2 (6.9%)
ant_medico: 5                   0 (0.0%)    0 (0.0%)     0 (0.0%)    1 (3.4%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.525 | G0vG2: 0.013 | G0vG3: 0.810 | G1vG2: 0.013 | G1vG3: 1.000 | G2vG3: 0.001,0.0: n=68 (62.4%) | 1.0: n=41 (37.6%),0.0: n=2 (25.0%) | 1.0: n=6 (75.0%),0.0: n=244 (78.0%) | 1.0: n=69 (22.0%),0.0: n=13 (44.8%) | 1.0: n=16 (55.2%)
1,comp_placentaria,Chi-Square,0.0002,G0vG1: 1.000 | G0vG2: 0.622 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.005,0.0: n=100 (91.7%) | 1.0: n=9 (8.3%),0.0: n=7 (87.5%) | 1.0: n=1 (12.5%),0.0: n=266 (85.0%) | 1.0: n=47 (15.0%),0.0: n=17 (58.6%) | 1.0: n=12 (41.4%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 1.000 | G2vG3: 0.000,0.0: n=103 (94.5%) | 1.0: n=6 (5.5%),0.0: n=4 (50.0%) | 1.0: n=4 (50.0%),0.0: n=293 (93.6%) | 1.0: n=20 (6.4%),0.0: n=18 (62.1%) | 1.0: n=11 (37.9%)
3,comp_metabolica,Chi-Square,0.0432,G0vG1: 1.000 | G0vG2: 0.079 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=90 (82.6%) | 1.0: n=19 (17.4%),0.0: n=8 (100.0%),0.0: n=287 (91.7%) | 1.0: n=26 (8.3%),0.0: n=26 (89.7%) | 1.0: n=3 (10.3%)
4,ant_obstetrico,Chi-Square,0.4734,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=78 (71.6%) | 1: n=24 (22.0%) | 3: n=4 (3.7%) | 4: n=3 (2.8%),-1: n=7 (87.5%) | 3: n=1 (12.5%),-1: n=233 (74.4%) | 1: n=66 (21.1%) | 3: n=11 (3.5%) | 4: n=3 (1.0%),-1: n=18 (62.1%) | 1: n=9 (31.0%) | 3: n=2 (6.9%)
5,ant_medico,Chi-Square,0.0000,G0vG1: 0.547 | G0vG2: 0.044 | G0vG3: 0.791 | G1vG2: 0.011 | G1vG3: 0.240 | G2vG3: 0.032,-1: n=74 (67.9%) | 1: n=29 (26.6%) | 3: n=6 (5.5%),-1: n=3 (37.5%) | 1: n=5 (62.5%),-1: n=257 (82.1%) | 1: n=48 (15.3%) | 3: n=8 (2.6%),-1: n=22 (75.9%) | 1: n=4 (13.8%) | 3: n=2 (6.9%) | 5: n=1 (3.4%)

======================================================================
COMBINACIÓN 10 | K = 5 | SILHOUETTE = 0.3991
======================================================================

TAMAÑO DE GRUPOS:
cluster   0   1    2    3   4
count    92  59  152  135  21

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
peso_ini_gest,82.61 ± 5.38,64.66 ± 6.35,65.22 ± 3.85,52.65 ± 3.68,107.18 ± 11.60
peso_fin_gest,93.08 ± 7.22,76.65 ± 8.28,77.94 ± 6.86,64.20 ± 6.55,117.72 ± 14.48
aumento_peso_gest,10.53 ± 5.52,12.04 ± 5.22,12.72 ± 5.62,11.47 ± 4.91,10.55 ± 7.54
talla,165.05 ± 6.77,163.84 ± 6.09,165.08 ± 5.53,160.92 ± 5.43,168.00 ± 6.07
imc_ini_gest,30.46 ± 3.02,24.19 ± 2.79,23.99 ± 2.08,20.38 ± 1.66,38.08 ± 4.82
edad_materna_gest,34.73 ± 5.11,36.67 ± 4.46,35.89 ± 4.20,34.84 ± 4.92,37.74 ± 3.34
tas_1tri,119.46 ± 12.18,113.71 ± 12.96,113.58 ± 10.00,111.02 ± 10.90,120.83 ± 10.40
tad_1tri,75.16 ± 8.53,74.42 ± 7.94,72.47 ± 8.41,70.97 ± 7.78,77.39 ± 7.14
eg_eco_1tri,12.80 ± 0.56,12.71 ± 0.60,12.66 ± 0.63,12.73 ± 0.61,13.06 ± 0.60
eg_parto,38.95 ± 2.15,38.24 ± 2.77,39.21 ± 2.09,39.25 ± 2.05,38.86 ± 1.71
peso_rn,3179.30 ± 617.01,2913.90 ± 672.78,3110.56 ± 648.47,3002.92 ± 569.95,3087.86 ± 645.16
apgar_1min,8.73 ± 1.14,8.58 ± 1.19,8.79 ± 0.97,8.88 ± 0.67,8.24 ± 1.89
apgar_5min,9.71 ± 1.05,9.68 ± 0.86,9.78 ± 0.63,9.88 ± 0.40,9.57 ± 0.98
apgar_10min,9.88 ± 0.36,9.85 ± 0.48,9.92 ± 0.31,9.95 ± 0.21,9.81 ± 0.51
ratio_MoM,6.68 ± 21.07,15.19 ± 65.46,6.82 ± 24.31,5.37 ± 21.15,4.80 ± 7.61
sflt1_MoM,1.67 ± 1.32,2.19 ± 3.99,1.67 ± 1.63,1.78 ± 1.45,1.61 ± 1.05
plgf_MoM,1.13 ± 1.01,1.15 ± 0.94,1.37 ± 1.25,1.47 ± 1.04,0.94 ± 0.99

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,82.00 ± 9.00,64.00 ± 10.50,65.00 ± 6.12,53.00 ± 5.55,103.00 ± 12.00
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,93.05 ± 9.17,76.77 ± 12.00,77.15 ± 9.00,64.00 ± 8.80,113.00 ± 16.10
2,aumento_peso_gest,Kruskal-Wallis,0.0288,G0vG1: 1.000 | G0vG2: 0.053 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.461 | G2vG4: 0.665 | G3vG4: 1.000,10.40 ± 7.03,11.40 ± 4.95,12.00 ± 5.47,11.00 ± 5.10,10.00 ± 8.00
3,talla,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.207 | G1vG2: 1.000 | G1vG3: 0.014 | G1vG4: 0.126 | G2vG3: 0.000 | G2vG4: 0.291 | G3vG4: 0.000,165.00 ± 9.00,164.00 ± 9.00,165.00 ± 8.50,161.00 ± 6.00,168.00 ± 3.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,30.35 ± 4.01,24.01 ± 4.18,23.95 ± 3.04,20.31 ± 2.19,36.41 ± 3.77
5,edad_materna_gest,Kruskal-Wallis,0.0081,G0vG1: 0.346 | G0vG2: 0.975 | G0vG3: 1.000 | G0vG4: 0.058 | G1vG2: 1.000 | G1vG3: 0.242 | G1vG4: 1.000 | G2vG3: 0.741 | G2vG4: 0.399 | G3vG4: 0.064,34.79 ± 6.92,36.12 ± 6.44,35.81 ± 5.82,34.83 ± 7.01,38.88 ± 5.25
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.011 | G0vG2: 0.001 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.072 | G2vG3: 0.818 | G2vG4: 0.046 | G3vG4: 0.005,118.50 ± 15.00,113.00 ± 10.00,113.00 ± 14.00,111.52 ± 14.00,119.00 ± 15.00
7,tad_1tri,Kruskal-Wallis,0.0001,G0vG1: 1.000 | G0vG2: 0.298 | G0vG3: 0.003 | G0vG4: 0.637 | G1vG2: 1.000 | G1vG3: 0.112 | G1vG4: 0.702 | G2vG3: 1.000 | G2vG4: 0.037 | G3vG4: 0.002,74.22 ± 8.25,73.79 ± 10.71,72.59 ± 9.25,71.52 ± 9.00,78.00 ± 7.00
8,eg_eco_1tri,Kruskal-Wallis,0.1219,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.787 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.246 | G2vG3: 1.000 | G2vG4: 0.166 | G3vG4: 0.624,12.80 ± 0.50,12.68 ± 0.60,12.71 ± 0.70,12.80 ± 0.60,12.96 ± 0.90
9,eg_parto,Kruskal-Wallis,0.0189,G0vG1: 0.782 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.022 | G1vG3: 0.041 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,39.45 ± 2.30,38.90 ± 1.80,39.50 ± 1.80,39.60 ± 2.50,39.30 ± 1.90
10,peso_rn,Kruskal-Wallis,0.0223,G0vG1: 0.045 | G0vG2: 1.000 | G0vG3: 0.127 | G0vG4: 1.000 | G1vG2: 0.217 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.672 | G2vG4: 1.000 | G3vG4: 1.000,3195.00 ± 570.00,2975.00 ± 682.50,3170.00 ± 608.75,3040.00 ± 800.00,3020.00 ± 895.00
11,apgar_1min,Kruskal-Wallis,0.3122,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.927 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.2902,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.911 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.639,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.4574,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.5236,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.71 ± 2.56,1.72 ± 2.71,1.69 ± 1.54,1.65 ± 2.21,1.79 ± 2.78
15,sflt1_MoM,Kruskal-Wallis,0.6649,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.28 ± 1.01,1.29 ± 0.55,1.26 ± 0.59,1.28 ± 0.78,1.27 ± 0.84
16,plgf_MoM,Kruskal-Wallis,0.0021,G0vG1: 1.000 | G0vG2: 0.436 | G0vG3: 0.024 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.330 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.114 | G3vG4: 0.026,0.94 ± 0.98,0.98 ± 1.10,1.26 ± 0.91,1.29 ± 1.01,0.65 ± 0.63

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
diam_telediastolico,47.41 ± 4.73,45.14 ± 4.08,45.02 ± 6.30,42.61 ± 4.24,48.29 ± 5.17
diam_telesistolico,31.69 ± 4.81,30.44 ± 3.99,29.28 ± 4.29,28.64 ± 3.70,32.76 ± 7.09
dtsvi_indexado,16.38 ± 2.38,17.31 ± 2.88,16.56 ± 2.74,17.77 ± 2.63,15.02 ± 3.38
septo_iv_diastole,8.93 ± 1.82,8.03 ± 1.93,9.40 ± 9.63,9.55 ± 12.06,14.23 ± 18.84
pared_posterior_vi_diastole,7.97 ± 1.66,7.66 ± 1.58,8.49 ± 9.30,8.98 ± 10.96,11.24 ± 12.70
diam_ai,36.77 ± 3.46,33.45 ± 3.78,33.15 ± 4.32,30.53 ± 4.17,37.65 ± 3.74
ai_volumen,43.18 ± 15.44,36.21 ± 10.86,37.35 ± 11.57,30.59 ± 9.38,53.23 ± 16.76
ad_volumen,36.43 ± 12.84,36.85 ± 28.42,33.39 ± 10.86,26.42 ± 10.28,43.65 ± 18.87
tapse,24.28 ± 4.33,25.70 ± 3.67,25.21 ± 4.11,26.12 ± 18.10,41.45 ± 64.16
e_mitral,72.74 ± 15.38,84.76 ± 77.35,73.97 ± 12.85,89.34 ± 99.80,69.05 ± 13.39
e_e,3.83 ± 1.14,4.60 ± 4.86,3.86 ± 0.96,4.40 ± 5.10,3.69 ± 0.83
gc_tsvi,7.59 ± 7.62,5.71 ± 1.03,6.05 ± 4.05,5.93 ± 4.71,10.47 ± 12.58
urato_acidourico,4.42 ± 0.92,3.95 ± 0.85,4.06 ± 0.91,4.15 ± 2.18,4.66 ± 1.20

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.036 | G0vG2: 0.001 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.012 | G1vG4: 0.151 | G2vG3: 0.000 | G2vG4: 0.110 | G3vG4: 0.001,48.00 ± 7.00,44.00 ± 5.00,45.00 ± 5.50,42.00 ± 6.00,48.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.005 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 0.673 | G1vG3: 0.047 | G1vG4: 1.000 | G2vG3: 0.995 | G2vG4: 0.329 | G3vG4: 0.098,31.50 ± 8.00,31.00 ± 5.00,29.00 ± 4.00,28.00 ± 5.00,33.00 ± 7.00
2,dtsvi_indexado,Kruskal-Wallis,0.0000,G0vG1: 0.271 | G0vG2: 1.000 | G0vG3: 0.002 | G0vG4: 0.738 | G1vG2: 0.746 | G1vG3: 1.000 | G1vG4: 0.081 | G2vG3: 0.005 | G2vG4: 0.212 | G3vG4: 0.009,16.15 ± 3.65,17.80 ± 3.06,16.63 ± 2.88,17.90 ± 3.30,14.88 ± 2.93
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 0.180 | G0vG2: 0.199 | G0vG3: 0.000 | G0vG4: 0.913 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.024 | G2vG3: 0.057 | G2vG4: 0.037 | G3vG4: 0.001,9.00 ± 2.40,8.00 ± 2.00,8.00 ± 2.30,7.70 ± 2.12,9.40 ± 2.30
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0128,G0vG1: 1.000 | G0vG2: 0.253 | G0vG3: 0.014 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.739 | G3vG4: 0.328,8.00 ± 1.70,7.60 ± 2.00,7.10 ± 2.25,7.00 ± 1.95,8.50 ± 2.10
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.001 | G1vG4: 0.004 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,37.00 ± 3.00,34.00 ± 6.75,33.00 ± 5.00,30.00 ± 5.25,39.00 ± 5.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.094 | G0vG2: 0.064 | G0vG3: 0.000 | G0vG4: 0.119 | G1vG2: 1.000 | G1vG3: 0.029 | G1vG4: 0.002 | G2vG3: 0.000 | G2vG4: 0.001 | G3vG4: 0.000,41.35 ± 17.70,34.80 ± 15.73,36.20 ± 13.88,29.70 ± 12.80,52.00 ± 21.00
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.002 | G1vG4: 0.702 | G2vG3: 0.000 | G2vG4: 0.384 | G3vG4: 0.001,36.00 ± 19.55,33.00 ± 14.12,32.00 ± 14.00,25.00 ± 12.20,39.20 ± 17.65
8,tapse,Kruskal-Wallis,0.2400,G0vG1: 0.823 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.952 | G1vG2: 1.000 | G1vG3: 0.921 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,24.00 ± 5.30,26.00 ± 5.00,25.00 ± 6.00,24.15 ± 5.00,27.00 ± 6.00
9,e_mitral,Kruskal-Wallis,0.0042,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.032 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.167 | G1vG4: 1.000 | G2vG3: 0.073 | G2vG4: 1.000 | G3vG4: 0.083,72.40 ± 18.80,71.00 ± 19.88,74.00 ± 15.40,78.10 ± 20.85,68.00 ± 13.50
10,e_e,Kruskal-Wallis,0.7695,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,3.75 ± 1.19,3.73 ± 1.34,3.72 ± 1.12,3.87 ± 1.07,3.48 ± 0.74
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.032 | G0vG2: 0.003 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.035 | G2vG3: 0.972 | G2vG4: 0.017 | G3vG4: 0.005,6.40 ± 1.55,5.50 ± 1.00,5.60 ± 1.30,5.30 ± 1.40,7.00 ± 2.20
12,urato_acidourico,Kruskal-Wallis,0.0066,G0vG1: 0.149 | G0vG2: 0.180 | G0vG3: 0.020 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.512 | G2vG3: 1.000 | G2vG4: 0.529 | G3vG4: 0.155,4.25 ± 1.25,3.91 ± 0.95,3.90 ± 1.10,4.01 ± 1.03,4.64 ± 1.25

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
ta_sistolica,123.84 ± 16.64,118.60 ± 17.41,112.84 ± 11.99,109.45 ± 11.83,128.67 ± 16.39
ta_diastolica,80.00 ± 10.36,78.03 ± 10.31,73.87 ± 9.43,71.65 ± 7.65,83.76 ± 9.65
frec_cardiaca,81.58 ± 12.09,80.62 ± 11.31,77.91 ± 11.94,77.48 ± 11.50,80.71 ± 12.33
right_1peak_systolic_velocity,32.25 ± 9.27,28.72 ± 7.78,31.44 ± 8.62,32.09 ± 8.91,30.28 ± 11.09
right_2peak_systolic_velocity,22.68 ± 7.36,19.97 ± 5.82,21.85 ± 7.53,22.53 ± 7.07,19.22 ± 7.45
right_pulsatility_index,1.73 ± 0.40,1.77 ± 0.43,1.80 ± 0.50,1.76 ± 0.41,1.96 ± 0.40
right_psv_ratio,0.71 ± 0.13,0.71 ± 0.14,0.69 ± 0.12,0.71 ± 0.12,0.65 ± 0.11
left_1peak_systolic_velocity,35.11 ± 10.35,32.19 ± 8.91,32.85 ± 8.93,32.89 ± 9.11,37.73 ± 9.05
left_2peak_systolic_velocity,24.62 ± 8.61,22.84 ± 7.07,23.15 ± 7.67,23.39 ± 7.06,25.07 ± 6.98
left_pulsatility_index,1.95 ± 2.46,1.67 ± 0.44,1.72 ± 0.40,1.73 ± 0.43,1.90 ± 0.47
left_psv_ratio,0.70 ± 0.13,0.72 ± 0.13,0.70 ± 0.11,0.72 ± 0.13,0.67 ± 0.13
right_mean,0.57 ± 0.15,0.54 ± 0.09,0.53 ± 0.09,0.50 ± 0.06,0.59 ± 0.09
left_mean,0.59 ± 0.12,0.56 ± 0.09,0.53 ± 0.08,0.51 ± 0.07,0.63 ± 0.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.963 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 0.184 | G1vG3: 0.002 | G1vG4: 0.283 | G2vG3: 0.224 | G2vG4: 0.000 | G3vG4: 0.000,122.00 ± 17.00,119.50 ± 22.75,110.50 ± 15.00,108.00 ± 16.00,127.00 ± 13.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 0.120 | G1vG3: 0.000 | G1vG4: 0.320 | G2vG3: 0.159 | G2vG4: 0.000 | G3vG4: 0.000,80.00 ± 13.00,80.00 ± 12.00,74.50 ± 11.75,72.00 ± 10.50,83.00 ± 6.00
2,frec_cardiaca,ANOVA,0.0524,G0vG1: 1.000 | G0vG2: 0.098 | G0vG3: 0.034 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.633 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,81.58 ± 12.09,80.62 ± 11.31,77.91 ± 11.94,77.48 ± 11.50,80.71 ± 12.33
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.1992,G0vG1: 0.401 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.711 | G1vG3: 0.268 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,31.30 ± 13.88,30.10 ± 12.85,31.60 ± 10.50,31.30 ± 11.95,29.30 ± 12.00
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.0698,G0vG1: 0.325 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.578 | G1vG2: 1.000 | G1vG3: 0.305 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.577,21.80 ± 12.07,20.20 ± 9.33,21.00 ± 9.60,21.90 ± 10.40,16.70 ± 7.40
5,right_pulsatility_index,Kruskal-Wallis,0.3110,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.265 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.971 | G2vG3: 1.000 | G2vG4: 0.537 | G3vG4: 0.500,1.75 ± 0.48,1.78 ± 0.41,1.73 ± 0.53,1.71 ± 0.50,1.97 ± 0.54
6,right_psv_ratio,ANOVA,0.2188,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.583 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.885 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.304,0.71 ± 0.13,0.71 ± 0.14,0.69 ± 0.12,0.71 ± 0.12,0.65 ± 0.11
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0293,G0vG1: 0.676 | G0vG2: 0.403 | G0vG3: 0.758 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.152 | G2vG3: 1.000 | G2vG4: 0.098 | G3vG4: 0.239,35.00 ± 14.97,30.70 ± 13.00,33.00 ± 10.15,32.45 ± 12.70,36.50 ± 7.60
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.3937,G0vG1: 1.000 | G0vG2: 0.836 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,24.30 ± 10.15,22.30 ± 9.40,22.50 ± 7.35,22.75 ± 9.50,25.10 ± 12.30
9,left_pulsatility_index,Kruskal-Wallis,0.3308,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.443 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.67 ± 0.52,1.59 ± 0.49,1.74 ± 0.54,1.71 ± 0.50,1.95 ± 0.51
10,left_psv_ratio,Kruskal-Wallis,0.4239,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.955 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.794,0.71 ± 0.14,0.73 ± 0.14,0.69 ± 0.17,0.71 ± 0.16,0.65 ± 0.12
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.284 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.006 | G1vG4: 0.322 | G2vG3: 0.045 | G2vG4: 0.019 | G3vG4: 0.000,0.55 ± 0.16,0.53 ± 0.09,0.52 ± 0.10,0.49 ± 0.10,0.57 ± 0.13
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.729 | G1vG2: 0.159 | G1vG3: 0.001 | G1vG4: 0.039 | G2vG3: 0.473 | G2vG4: 0.000 | G3vG4: 0.000,0.58 ± 0.14,0.56 ± 0.10,0.53 ± 0.11,0.51 ± 0.09,0.63 ± 0.09

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
hemoglobina,126.40 ± 23.11,127.06 ± 21.57,127.14 ± 25.41,124.88 ± 26.04,129.86 ± 13.56
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,7068.79 ± 1763.14,6848.72 ± 2025.88,6373.88 ± 1452.39,6244.30 ± 1483.06,6667.86 ± 1234.87
plaquetas,282954.55 ± 66598.09,270923.08 ± 67984.28,264757.28 ± 65431.37,271537.63 ± 61599.79,271500.00 ± 56848.99
glucosa,88.50 ± 8.90,91.92 ± 20.03,86.33 ± 9.35,85.42 ± 7.66,96.57 ± 19.21
sodio,139.55 ± 1.78,140.10 ± 1.43,139.63 ± 1.75,139.73 ± 1.81,138.07 ± 2.81
potasio,4.25 ± 0.29,4.25 ± 0.31,4.21 ± 0.26,4.20 ± 0.28,4.16 ± 0.34
urato_acidourico,4.42 ± 0.92,3.95 ± 0.85,4.06 ± 0.91,4.15 ± 2.18,4.66 ± 1.20
hemoglobina_glicada,5.47 ± 0.37,5.44 ± 0.54,5.29 ± 0.33,5.34 ± 0.33,5.64 ± 0.48
ast,22.18 ± 12.81,21.79 ± 6.15,22.20 ± 12.39,21.33 ± 6.37,18.93 ± 6.04
alt,21.65 ± 21.04,18.90 ± 10.50,18.32 ± 11.31,16.55 ± 7.64,15.57 ± 8.08
bilirubina_total,0.58 ± 0.30,0.60 ± 0.22,0.67 ± 0.34,0.74 ± 0.29,0.61 ± 0.35
ldh,176.41 ± 29.72,170.87 ± 15.20,161.33 ± 27.25,162.10 ± 26.00,159.79 ± 23.37
vldl,19.22 ± 11.25,15.80 ± 11.03,13.90 ± 7.92,11.26 ± 4.75,19.81 ± 8.11
ldl,110.28 ± 28.71,118.67 ± 29.91,111.18 ± 28.25,111.18 ± 29.73,115.17 ± 25.52
hdl,55.23 ± 14.68,60.99 ± 14.23,58.63 ± 12.49,65.58 ± 13.30,45.61 ± 8.14
colesterol_total,184.71 ± 32.56,195.45 ± 30.39,183.78 ± 32.76,187.60 ± 33.02,180.59 ± 28.04
trigliceridos,96.11 ± 55.10,79.57 ± 53.83,70.61 ± 39.26,57.35 ± 23.09,98.30 ± 40.22
prote_totales_orina,2.39 ± 12.57,0.11 ± 0.06,2.26 ± 12.26,4.96 ± 17.43,0.09 ± 0.05

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,hemoglobina,Kruskal-Wallis,0.7878,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,131.00 ± 14.75,131.00 ± 14.50,132.00 ± 13.00,131.00 ± 14.00,127.50 ± 9.75
1,hematocrito,Kruskal-Wallis,0.8239,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.39 ± 0.04,0.39 ± 0.04,0.39 ± 0.03,0.39 ± 0.04,0.38 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0424,G0vG1: 1.000 | G0vG2: 0.159 | G0vG3: 0.031 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,6775.00 ± 1960.00,6260.00 ± 3110.00,6270.00 ± 1750.00,6120.00 ± 2100.00,6260.00 ± 827.50
3,plaquetas,Kruskal-Wallis,0.4823,G0vG1: 1.000 | G0vG2: 0.627 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,272000.00 ± 81500.00,274000.00 ± 81000.00,252000.00 ± 86500.00,268000.00 ± 82000.00,274500.00 ± 57000.00
4,glucosa,Kruskal-Wallis,0.1055,G0vG1: 1.000 | G0vG2: 0.535 | G0vG3: 0.307 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.862 | G3vG4: 0.829,89.00 ± 11.50,86.00 ± 10.50,86.00 ± 10.00,87.00 ± 8.00,89.50 ± 26.50
5,sodio,Kruskal-Wallis,0.0296,G0vG1: 0.540 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.532 | G1vG2: 0.904 | G1vG3: 1.000 | G1vG4: 0.008 | G2vG3: 1.000 | G2vG4: 0.234 | G3vG4: 0.126,139.00 ± 3.00,140.00 ± 2.00,140.00 ± 3.00,140.00 ± 2.00,138.50 ± 1.00
6,potasio,Kruskal-Wallis,0.7499,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,4.21 ± 0.33,4.25 ± 0.38,4.22 ± 0.29,4.20 ± 0.32,4.14 ± 0.37
7,urato_acidourico,Kruskal-Wallis,0.0066,G0vG1: 0.149 | G0vG2: 0.180 | G0vG3: 0.020 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.512 | G2vG3: 1.000 | G2vG4: 0.529 | G3vG4: 0.155,4.25 ± 1.25,3.91 ± 0.95,3.90 ± 1.10,4.01 ± 1.03,4.64 ± 1.25
8,hemoglobina_glicada,Kruskal-Wallis,0.0010,G0vG1: 1.000 | G0vG2: 0.006 | G0vG3: 0.057 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.627 | G2vG3: 1.000 | G2vG4: 0.043 | G3vG4: 0.175,5.40 ± 0.48,5.30 ± 0.30,5.30 ± 0.30,5.30 ± 0.30,5.50 ± 0.53
9,ast,Kruskal-Wallis,0.1930,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.138 | G2vG3: 1.000 | G2vG4: 0.331 | G3vG4: 0.354,19.00 ± 6.75,20.00 ± 5.00,20.00 ± 6.00,20.00 ± 6.00,17.50 ± 3.75
10,alt,Kruskal-Wallis,0.4650,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,15.50 ± 12.00,16.00 ± 7.50,15.00 ± 8.50,14.00 ± 7.00,12.00 ± 10.50
11,bilirubina_total,Kruskal-Wallis,0.0001,G0vG1: 1.000 | G0vG2: 0.173 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.065 | G1vG4: 1.000 | G2vG3: 0.115 | G2vG4: 1.000 | G3vG4: 0.310,0.51 ± 0.23,0.55 ± 0.27,0.59 ± 0.28,0.70 ± 0.31,0.57 ± 0.20
12,ldh,Kruskal-Wallis,0.0008,G0vG1: 1.000 | G0vG2: 0.010 | G0vG3: 0.012 | G0vG4: 0.618 | G1vG2: 0.069 | G1vG3: 0.063 | G1vG4: 0.867 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,170.50 ± 33.25,169.00 ± 23.75,156.00 ± 31.00,159.00 ± 27.00,160.00 ± 31.25
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.025 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.024 | G1vG4: 0.198 | G2vG3: 0.149 | G2vG4: 0.031 | G3vG4: 0.000,15.61 ± 14.93,12.66 ± 5.08,11.59 ± 7.49,9.81 ± 4.62,17.84 ± 9.54
14,ldl,Kruskal-Wallis,0.5848,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,106.56 ± 37.62,112.47 ± 44.43,108.64 ± 37.85,105.51 ± 35.48,117.17 ± 22.98
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.171 | G0vG2: 0.291 | G0vG3: 0.000 | G0vG4: 0.113 | G1vG2: 1.000 | G1vG3: 0.885 | G1vG4: 0.002 | G2vG3: 0.001 | G2vG4: 0.001 | G3vG4: 0.000,53.98 ± 15.77,59.60 ± 17.41,58.44 ± 16.06,66.18 ± 14.32,44.70 ± 12.87
16,colesterol_total,Kruskal-Wallis,0.4167,G0vG1: 0.858 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.703 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,179.76 ± 36.09,191.18 ± 32.71,181.50 ± 47.80,184.21 ± 38.31,188.08 ± 29.22
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.031 | G0vG3: 0.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.012 | G1vG4: 0.209 | G2vG3: 0.072 | G2vG4: 0.041 | G3vG4: 0.000,77.44 ± 73.79,62.83 ± 25.23,57.52 ± 34.51,50.00 ± 18.86,88.50 ± 47.35
18,prote_totales_orina,Kruskal-Wallis,0.5459,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.923 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.718 | G3vG4: 1.000,0.08 ± 0.05,0.08 ± 0.05,0.08 ± 0.05,0.07 ± 0.06,0.07 ± 0.01

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
Cat_Dieta: Adherencia moderada,47 (51.1%),40 (67.8%),99 (65.1%),88 (65.2%),11 (52.4%)
Cat_Dieta: Alta adherencia,2 (2.2%),2 (3.4%),14 (9.2%),7 (5.2%),0 (0.0%)
Cat_Dieta: Baja adherencia,43 (46.7%),17 (28.8%),39 (25.7%),40 (29.6%),10 (47.6%)
Cat_Actividad: Actividad física alta,79 (85.9%),55 (96.5%),139 (92.1%),121 (91.7%),19 (90.5%)
Cat_Actividad: Actividad física baja,1 (1.1%),0 (0.0%),3 (2.0%),6 (4.5%),1 (4.8%)
Cat_Actividad: Actividad física moderada,12 (13.0%),2 (3.5%),9 (6.0%),5 (3.8%),1 (4.8%)
Cat_Estres: Nivel de estrés alto,37 (40.7%),26 (44.1%),47 (30.9%),42 (31.3%),10 (47.6%)
Cat_Estres: Nivel de estrés bajo,10 (11.0%),7 (11.9%),20 (13.2%),12 (9.0%),3 (14.3%)
Cat_Estres: Nivel de estrés moderado,38 (41.8%),24 (40.7%),82 (53.9%),77 (57.5%),7 (33.3%)
Cat_Estres: Nivel de estrés muy alto,6 (6.6%),2 (3.4%),3 (2.0%),3 (2.2%),1 (4.8%)
Cat_Memoria: Deterioro leve,15 (16.7%),9 (15.3%),16 (10.6%),20 (15.0%),5 (23.8%)
Cat_Memoria: Disfunción moderada-grave,7 (7.8%),6 (10.2%),15 (9.9%),12 (9.0%),4 (19.0%)
Cat_Memoria: Función normal (lapsus leves),53 (58.9%),32 (54.2%),91 (60.3%),76 (57.1%),8 (38.1%)
Cat_Memoria: Rendimiento de memoria óptimo,15 (16.7%),12 (20.3%),29 (19.2%),25 (18.8%),4 (19.0%)
Cat_SCL90R: EN RIESGO,10 (11.2%),9 (15.3%),21 (13.9%),15 (11.5%),2 (9.5%)
Cat_SCL90R: Normal / Sin riesgo,13 (14.6%),8 (13.6%),40 (26.5%),25 (19.1%),3 (14.3%)
Cat_SCL90R: Patología severa,66 (74.2%),42 (71.2%),90 (59.6%),91 (69.5%),16 (76.2%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,Cat_Dieta,Chi-Square,0.0094,G0vG1: 0.885 | G0vG2: 0.010 | G0vG3: 0.240 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.624 | G3vG4: 1.000,Adherencia moderada: n=47 (51.1%) | Alta adherencia: n=2 (2.2%) | Baja adherencia: n=43 (46.7%),Adherencia moderada: n=40 (67.8%) | Alta adherencia: n=2 (3.4%) | Baja adherencia: n=17 (28.8%),Adherencia moderada: n=99 (65.1%) | Alta adherencia: n=14 (9.2%) | Baja adherencia: n=39 (25.7%),Adherencia moderada: n=88 (65.2%) | Alta adherencia: n=7 (5.2%) | Baja adherencia: n=40 (29.6%),Adherencia moderada: n=11 (52.4%) | Baja adherencia: n=10 (47.6%)
1,Cat_Actividad,Chi-Square,0.0767,G0vG1: 0.552 | G0vG2: 1.000 | G0vG3: 0.147 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Actividad física alta: n=79 (85.9%) | Actividad física baja: n=1 (1.1%) | Actividad física moderada: n=12 (13.0%),Actividad física alta: n=55 (96.5%) | Actividad física moderada: n=2 (3.5%),Actividad física alta: n=139 (92.1%) | Actividad física baja: n=3 (2.0%) | Actividad física moderada: n=9 (6.0%),Actividad física alta: n=121 (91.7%) | Actividad física baja: n=6 (4.5%) | Actividad física moderada: n=5 (3.8%),Actividad física alta: n=19 (90.5%) | Actividad física baja: n=1 (4.8%) | Actividad física moderada: n=1 (4.8%)
2,Cat_Estres,Chi-Square,0.2179,G0vG1: 1.000 | G0vG2: 0.776 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Nivel de estrés alto: n=37 (40.7%) | Nivel de estrés bajo: n=10 (11.0%) | Nivel de estrés moderado: n=38 (41.8%) | Nivel de estrés muy alto: n=6 (6.6%),Nivel de estrés alto: n=26 (44.1%) | Nivel de estrés bajo: n=7 (11.9%) | Nivel de estrés moderado: n=24 (40.7%) | Nivel de estrés muy alto: n=2 (3.4%),Nivel de estrés alto: n=47 (30.9%) | Nivel de estrés bajo: n=20 (13.2%) | Nivel de estrés moderado: n=82 (53.9%) | Nivel de estrés muy alto: n=3 (2.0%),Nivel de estrés alto: n=42 (31.3%) | Nivel de estrés bajo: n=12 (9.0%) | Nivel de estrés moderado: n=77 (57.5%) | Nivel de estrés muy alto: n=3 (2.2%),Nivel de estrés alto: n=10 (47.6%) | Nivel de estrés bajo: n=3 (14.3%) | Nivel de estrés moderado: n=7 (33.3%) | Nivel de estrés muy alto: n=1 (4.8%)
3,Cat_Memoria,Chi-Square,0.8184,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Deterioro leve: n=15 (16.7%) | Disfunción moderada-grave: n=7 (7.8%) | Función normal (lapsus leves): n=53 (58.9%) | Rendimiento de memoria óptimo: n=15 (16.7%),Deterioro leve: n=9 (15.3%) | Disfunción moderada-grave: n=6 (10.2%) | Función normal (lapsus leves): n=32 (54.2%) | Rendimiento de memoria óptimo: n=12 (20.3%),Deterioro leve: n=16 (10.6%) | Disfunción moderada-grave: n=15 (9.9%) | Función normal (lapsus leves): n=91 (60.3%) | Rendimiento de memoria óptimo: n=29 (19.2%),Deterioro leve: n=20 (15.0%) | Disfunción moderada-grave: n=12 (9.0%) | Función normal (lapsus leves): n=76 (57.1%) | Rendimiento de memoria óptimo: n=25 (18.8%),Deterioro leve: n=5 (23.8%) | Disfunción moderada-grave: n=4 (19.0%) | Función normal (lapsus leves): n=8 (38.1%) | Rendimiento de memoria óptimo: n=4 (19.0%)
4,Cat_SCL90R,Chi-Square,0.3001,G0vG1: 1.000 | G0vG2: 0.443 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,EN RIESGO: n=10 (11.2%) | Normal / Sin riesgo: n=13 (14.6%) | Patología severa: n=66 (74.2%),EN RIESGO: n=9 (15.3%) | Normal / Sin riesgo: n=8 (13.6%) | Patología severa: n=42 (71.2%),EN RIESGO: n=21 (13.9%) | Normal / Sin riesgo: n=40 (26.5%) | Patología severa: n=90 (59.6%),EN RIESGO: n=15 (11.5%) | Normal / Sin riesgo: n=25 (19.1%) | Patología severa: n=91 (69.5%),EN RIESGO: n=2 (9.5%) | Normal / Sin riesgo: n=3 (14.3%) | Patología severa: n=16 (76.2%)

ANTECEDENTES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
trastorno_hipertensivo: 0.0,55 (59.8%),39 (66.1%),117 (77.0%),104 (77.0%),12 (57.1%)
trastorno_hipertensivo: 1.0,37 (40.2%),20 (33.9%),35 (23.0%),31 (23.0%),9 (42.9%)
comp_placentaria: 0.0,81 (88.0%),51 (86.4%),132 (86.8%),108 (80.0%),18 (85.7%)
comp_placentaria: 1.0,11 (12.0%),8 (13.6%),20 (13.2%),27 (20.0%),3 (14.3%)
comp_maternaGrave: 0.0,83 (90.2%),51 (86.4%),137 (90.1%),127 (94.1%),20 (95.2%)
comp_maternaGrave: 1.0,9 (9.8%),8 (13.6%),15 (9.9%),8 (5.9%),1 (4.8%)
comp_metabolica: 0.0,76 (82.6%),53 (89.8%),143 (94.1%),121 (89.6%),18 (85.7%)
comp_metabolica: 1.0,16 (17.4%),6 (10.2%),9 (5.9%),14 (10.4%),3 (14.3%)
ant_obstetrico: -1,64 (69.6%),36 (61.0%),118 (77.6%),101 (74.8%),17 (81.0%)
ant_obstetrico: 1,22 (23.9%),14 (23.7%),32 (21.1%),29 (21.5%),2 (9.5%)
ant_obstetrico: 3,4 (4.3%),9 (15.3%),2 (1.3%),2 (1.5%),1 (4.8%)
ant_obstetrico: 4,2 (2.2%),0 (0.0%),0 (0.0%),3 (2.2%),1 (4.8%)
ant_medico: -1,69 (75.0%),0 (0.0%),149 (98.0%),127 (94.1%),11 (52.4%)
ant_medico: 1,18 (19.6%),56 (94.9%),0 (0.0%),4 (3.0%),8 (38.1%)
ant_medico: 3,5 (5.4%),2 (3.4%),3 (2.0%),4 (3.0%),2 (9.5%)
ant_medico: 5,0 (0.0%),1 (1.7%),0 (0.0%),0 (0.0%),0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,trastorno_hipertensivo,Chi-Square,0.0097,G0vG1: 1.000 | G0vG2: 0.068 | G0vG3: 0.083 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.913 | G3vG4: 0.942,0.0: n=55 (59.8%) | 1.0: n=37 (40.2%),0.0: n=39 (66.1%) | 1.0: n=20 (33.9%),0.0: n=117 (77.0%) | 1.0: n=35 (23.0%),0.0: n=104 (77.0%) | 1.0: n=31 (23.0%),0.0: n=12 (57.1%) | 1.0: n=9 (42.9%)
1,comp_placentaria,Chi-Square,0.4313,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=81 (88.0%) | 1.0: n=11 (12.0%),0.0: n=51 (86.4%) | 1.0: n=8 (13.6%),0.0: n=132 (86.8%) | 1.0: n=20 (13.2%),0.0: n=108 (80.0%) | 1.0: n=27 (20.0%),0.0: n=18 (85.7%) | 1.0: n=3 (14.3%)
2,comp_maternaGrave,Chi-Square,0.4413,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=83 (90.2%) | 1.0: n=9 (9.8%),0.0: n=51 (86.4%) | 1.0: n=8 (13.6%),0.0: n=137 (90.1%) | 1.0: n=15 (9.9%),0.0: n=127 (94.1%) | 1.0: n=8 (5.9%),0.0: n=20 (95.2%) | 1.0: n=1 (4.8%)
3,comp_metabolica,Chi-Square,0.0780,G0vG1: 1.000 | G0vG2: 0.082 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=76 (82.6%) | 1.0: n=16 (17.4%),0.0: n=53 (89.8%) | 1.0: n=6 (10.2%),0.0: n=143 (94.1%) | 1.0: n=9 (5.9%),0.0: n=121 (89.6%) | 1.0: n=14 (10.4%),0.0: n=18 (85.7%) | 1.0: n=3 (14.3%)
4,ant_obstetrico,Chi-Square,0.0007,G0vG1: 0.841 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.002 | G1vG3: 0.010 | G1vG4: 0.834 | G2vG3: 1.000 | G2vG4: 0.206 | G3vG4: 1.000,-1: n=64 (69.6%) | 1: n=22 (23.9%) | 3: n=4 (4.3%) | 4: n=2 (2.2%),-1: n=36 (61.0%) | 1: n=14 (23.7%) | 3: n=9 (15.3%),-1: n=118 (77.6%) | 1: n=32 (21.1%) | 3: n=2 (1.3%),-1: n=101 (74.8%) | 1: n=29 (21.5%) | 3: n=2 (1.5%) | 4: n=3 (2.2%),-1: n=17 (81.0%) | 1: n=2 (9.5%) | 3: n=1 (4.8%) | 4: n=1 (4.8%)
5,ant_medico,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.001 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.860 | G2vG4: 0.000 | G3vG4: 0.000,-1: n=69 (75.0%) | 1: n=18 (19.6%) | 3: n=5 (5.4%),1: n=56 (94.9%) | 3: n=2 (3.4%) | 5: n=1 (1.7%),-1: n=149 (98.0%) | 3: n=3 (2.0%),-1: n=127 (94.1%) | 1: n=4 (3.0%) | 3: n=4 (3.0%),-1: n=11 (52.4%) | 1: n=8 (38.1%) | 3: n=2 (9.5%)

======================================================================
COMBINACIÓN 11 | K = 5 | SILHOUETTE = 0.3940
======================================================================

TAMAÑO DE GRUPOS:
cluster   0   1    2   3    4
count    22  26  170  93  148

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
peso_ini_gest,106.60 ± 11.64,66.44 ± 5.58,65.37 ± 3.97,82.30 ± 5.34,53.02 ± 3.75
peso_fin_gest,117.05 ± 14.47,78.97 ± 8.07,77.85 ± 6.74,92.93 ± 7.20,64.63 ± 6.59
aumento_peso_gest,10.45 ± 7.37,12.60 ± 5.95,12.49 ± 5.47,10.68 ± 5.66,11.54 ± 4.89
talla,168.14 ± 5.96,162.33 ± 5.74,165.11 ± 5.61,164.96 ± 6.77,161.27 ± 5.58
imc_ini_gest,37.82 ± 4.86,25.20 ± 2.29,24.06 ± 2.10,30.38 ± 3.04,20.44 ± 1.67
edad_materna_gest,37.42 ± 3.58,38.42 ± 4.24,35.82 ± 4.14,34.56 ± 5.16,35.03 ± 4.87
tas_1tri,120.02 ± 10.83,116.49 ± 10.16,113.45 ± 10.99,119.29 ± 12.29,111.08 ± 10.80
tad_1tri,77.65 ± 7.07,76.06 ± 6.87,72.58 ± 8.42,74.80 ± 8.61,71.26 ± 7.88
eg_eco_1tri,13.03 ± 0.60,12.76 ± 0.64,12.66 ± 0.62,12.79 ± 0.58,12.74 ± 0.59
eg_parto,38.82 ± 1.69,35.53 ± 3.58,39.42 ± 1.62,38.99 ± 2.13,39.24 ± 2.02
peso_rn,3052.05 ± 651.63,2189.42 ± 722.85,3181.09 ± 547.84,3205.12 ± 620.62,3003.58 ± 564.82
apgar_1min,8.27 ± 1.86,7.83 ± 1.81,8.82 ± 0.85,8.74 ± 1.12,8.90 ± 0.64
apgar_5min,9.59 ± 0.96,8.97 ± 1.25,9.84 ± 0.54,9.73 ± 1.03,9.90 ± 0.38
apgar_10min,9.82 ± 0.50,9.46 ± 0.75,9.95 ± 0.24,9.89 ± 0.34,9.96 ± 0.18
ratio_MoM,4.59 ± 7.48,56.70 ± 103.58,2.50 ± 5.22,6.52 ± 20.96,5.15 ± 20.28
sflt1_MoM,1.57 ± 1.05,5.12 ± 5.97,1.39 ± 0.91,1.63 ± 1.23,1.72 ± 1.40
plgf_MoM,0.97 ± 0.98,0.53 ± 0.53,1.44 ± 1.23,1.13 ± 1.00,1.45 ± 1.02

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,103.00 ± 12.50,65.75 ± 7.20,65.00 ± 6.88,82.00 ± 8.60,53.50 ± 5.62
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,113.00 ± 16.45,78.65 ± 10.73,77.15 ± 9.00,93.00 ± 9.70,64.00 ± 8.59
2,aumento_peso_gest,Kruskal-Wallis,0.0708,G0vG1: 1.000 | G0vG2: 0.628 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.177 | G2vG4: 1.000 | G3vG4: 1.000,9.75 ± 7.67,12.01 ± 5.57,11.97 ± 5.38,10.80 ± 7.00,11.00 ± 5.22
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.009 | G0vG2: 0.196 | G0vG3: 0.110 | G0vG4: 0.000 | G1vG2: 0.431 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.000 | G3vG4: 0.001,168.50 ± 3.75,164.00 ± 9.00,165.00 ± 8.75,165.00 ± 9.00,161.00 ± 7.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.245 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,36.27 ± 3.75,25.00 ± 2.52,23.92 ± 2.93,30.12 ± 3.97,20.31 ± 2.16
5,edad_materna_gest,Kruskal-Wallis,0.0010,G0vG1: 1.000 | G0vG2: 0.653 | G0vG3: 0.089 | G0vG4: 0.187 | G1vG2: 0.078 | G1vG3: 0.012 | G1vG4: 0.015 | G2vG3: 0.669 | G2vG4: 1.000 | G3vG4: 1.000,38.21 ± 5.48,38.02 ± 7.45,35.79 ± 6.00,34.72 ± 7.01,35.30 ± 6.73
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.075 | G0vG3: 1.000 | G0vG4: 0.012 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.467 | G2vG3: 0.000 | G2vG4: 1.000 | G3vG4: 0.000,118.87 ± 16.50,114.28 ± 11.50,113.00 ± 13.75,119.00 ± 15.00,111.86 ± 14.00
7,tad_1tri,Kruskal-Wallis,0.0001,G0vG1: 1.000 | G0vG2: 0.017 | G0vG3: 0.250 | G0vG4: 0.002 | G1vG2: 0.322 | G1vG3: 1.000 | G1vG4: 0.044 | G2vG3: 0.677 | G2vG4: 1.000 | G3vG4: 0.021,78.50 ± 7.75,75.98 ± 10.28,72.59 ± 9.75,74.00 ± 8.00,71.64 ± 9.00
8,eg_eco_1tri,Kruskal-Wallis,0.1832,G0vG1: 1.000 | G0vG2: 0.221 | G0vG3: 0.988 | G0vG4: 0.948 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,12.88 ± 0.83,12.67 ± 0.43,12.72 ± 0.70,12.80 ± 0.50,12.80 ± 0.55
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.005 | G0vG2: 0.873 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,39.10 ± 1.98,35.40 ± 4.38,39.50 ± 1.80,39.60 ± 2.10,39.60 ± 2.60
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.003 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 0.083 | G3vG4: 0.042,2905.00 ± 888.75,2460.00 ± 1166.25,3170.00 ± 563.75,3220.00 ± 600.00,3045.00 ± 792.50
11,apgar_1min,Kruskal-Wallis,0.0003,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.017 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,9.00 ± 0.00,9.00 ± 1.95,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.190 | G0vG2: 0.946 | G0vG3: 1.000 | G0vG4: 0.528 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,10.00 ± 0.00,9.00 ± 1.81,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.386 | G0vG2: 0.852 | G0vG3: 1.000 | G0vG4: 0.876 | G1vG2: 0.000 | G1vG3: 0.001 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,10.00 ± 0.00,10.00 ± 1.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.72 ± 2.78,7.47 ± 36.46,1.68 ± 1.22,1.70 ± 2.10,1.64 ± 1.95
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 0.541 | G3vG4: 1.000,1.27 ± 0.93,2.89 ± 4.27,1.26 ± 0.46,1.27 ± 0.97,1.26 ± 0.75
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.142 | G0vG2: 0.067 | G0vG3: 1.000 | G0vG4: 0.057 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.047 | G2vG4: 1.000 | G3vG4: 0.022,0.66 ± 0.87,0.40 ± 0.38,1.29 ± 0.83,0.95 ± 0.93,1.32 ± 1.00

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
diam_telediastolico,48.61 ± 5.19,44.71 ± 3.94,45.09 ± 6.07,47.34 ± 4.84,42.76 ± 4.19
diam_telesistolico,32.78 ± 6.88,30.10 ± 4.24,29.54 ± 3.68,31.72 ± 4.81,28.62 ± 4.38
dtsvi_indexado,15.07 ± 3.28,17.33 ± 2.45,16.65 ± 2.54,16.42 ± 2.42,17.73 ± 2.98
septo_iv_diastole,13.88 ± 18.34,8.43 ± 1.86,9.23 ± 9.12,8.81 ± 1.84,9.45 ± 11.63
pared_posterior_vi_diastole,11.01 ± 12.36,7.50 ± 1.48,8.48 ± 8.78,7.96 ± 1.65,8.81 ± 10.57
diam_ai,37.89 ± 3.77,35.00 ± 3.44,33.07 ± 4.28,36.51 ± 3.62,30.68 ± 4.11
ai_volumen,53.22 ± 16.26,39.76 ± 11.44,37.05 ± 11.59,42.64 ± 15.43,30.76 ± 9.23
ad_volumen,42.86 ± 18.50,35.45 ± 8.96,34.06 ± 18.54,36.46 ± 12.78,27.09 ± 10.42
tapse,40.31 ± 62.43,24.73 ± 3.34,25.40 ± 4.09,24.37 ± 4.32,26.09 ± 17.45
e_mitral,69.38 ± 13.07,98.07 ± 115.62,73.90 ± 13.33,72.33 ± 15.41,88.63 ± 95.99
e_e,3.68 ± 0.81,5.45 ± 7.33,3.89 ± 0.95,3.81 ± 1.13,4.36 ± 4.90
gc_tsvi,10.15 ± 12.15,5.42 ± 0.81,6.02 ± 3.87,7.58 ± 7.57,5.94 ± 4.53
urato_acidourico,4.66 ± 1.20,3.59 ± 0.85,4.10 ± 0.89,4.43 ± 0.92,4.15 ± 2.09

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.121 | G0vG2: 0.046 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.159 | G1vG4: 0.817 | G2vG3: 0.002 | G2vG4: 0.000 | G3vG4: 0.000,48.00 ± 6.75,43.00 ± 4.00,45.00 ± 6.00,47.50 ± 7.00,42.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0001,G0vG1: 1.000 | G0vG2: 0.254 | G0vG3: 1.000 | G0vG4: 0.068 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.008 | G2vG4: 0.729 | G3vG4: 0.000,33.00 ± 7.00,30.00 ± 6.00,29.00 ± 5.00,32.00 ± 8.00,29.00 ± 5.00
2,dtsvi_indexado,Kruskal-Wallis,0.0000,G0vG1: 0.171 | G0vG2: 0.168 | G0vG3: 0.800 | G0vG4: 0.005 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.003 | G3vG4: 0.003,15.08 ± 2.70,17.22 ± 2.28,16.66 ± 2.83,16.17 ± 3.76,18.04 ± 3.22
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 0.663 | G0vG2: 0.043 | G0vG3: 0.744 | G0vG4: 0.001 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.584 | G2vG4: 0.064 | G3vG4: 0.001,9.25 ± 2.85,8.00 ± 3.00,8.00 ± 2.00,8.40 ± 2.53,7.80 ± 2.15
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0088,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.306 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.774 | G2vG4: 0.870 | G3vG4: 0.006,8.40 ± 2.07,7.00 ± 2.00,7.50 ± 2.45,8.00 ± 1.70,7.00 ± 2.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.108 | G0vG2: 0.000 | G0vG3: 0.744 | G0vG4: 0.000 | G1vG2: 0.598 | G1vG3: 0.889 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,39.00 ± 5.00,34.00 ± 5.00,33.00 ± 5.50,37.00 ± 3.25,30.00 ± 6.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.058 | G0vG2: 0.000 | G0vG3: 0.055 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.014 | G2vG3: 0.099 | G2vG4: 0.000 | G3vG4: 0.000,52.50 ± 19.67,40.00 ± 20.40,36.00 ± 14.52,40.00 ± 16.40,30.20 ± 12.08
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.357 | G0vG3: 1.000 | G0vG4: 0.002 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.004 | G2vG3: 0.640 | G2vG4: 0.000 | G3vG4: 0.000,39.10 ± 17.75,37.00 ± 8.00,31.50 ± 15.33,36.00 ± 19.55,25.40 ± 13.70
8,tapse,Kruskal-Wallis,0.5674,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,25.80 ± 6.60,25.00 ± 4.00,25.00 ± 6.00,24.20 ± 5.07,24.30 ± 5.50
9,e_mitral,Kruskal-Wallis,0.0034,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.113 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.049 | G3vG4: 0.016,69.15 ± 13.05,71.50 ± 17.92,74.00 ± 15.30,72.20 ± 18.50,78.10 ± 21.40
10,e_e,Kruskal-Wallis,0.6636,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,3.46 ± 0.66,3.86 ± 1.29,3.72 ± 1.11,3.72 ± 1.20,3.89 ± 1.11
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.023 | G0vG2: 0.015 | G0vG3: 1.000 | G0vG4: 0.006 | G1vG2: 1.000 | G1vG3: 0.043 | G1vG4: 1.000 | G2vG3: 0.001 | G2vG4: 1.000 | G3vG4: 0.000,6.90 ± 2.10,5.55 ± 0.75,5.50 ± 1.25,6.40 ± 1.67,5.30 ± 1.40
12,urato_acidourico,Kruskal-Wallis,0.0011,G0vG1: 0.100 | G0vG2: 0.687 | G0vG3: 1.000 | G0vG4: 0.170 | G1vG2: 0.393 | G1vG3: 0.013 | G1vG4: 0.717 | G2vG3: 0.289 | G2vG4: 1.000 | G3vG4: 0.021,4.64 ± 1.25,3.64 ± 1.25,3.93 ± 1.05,4.31 ± 1.25,4.01 ± 0.99

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
ta_sistolica,127.77 ± 16.54,122.84 ± 15.00,112.80 ± 13.11,123.88 ± 16.58,110.28 ± 12.52
ta_diastolica,83.45 ± 9.53,78.68 ± 8.08,73.86 ± 9.85,80.30 ± 10.24,72.43 ± 8.20
frec_cardiaca,78.91 ± 14.71,81.36 ± 12.11,78.35 ± 11.91,82.22 ± 11.37,77.33 ± 11.27
right_1peak_systolic_velocity,30.62 ± 10.94,30.85 ± 10.78,30.70 ± 8.29,32.30 ± 9.22,31.82 ± 8.73
right_2peak_systolic_velocity,19.39 ± 7.32,23.74 ± 8.77,21.08 ± 7.08,22.59 ± 7.31,22.34 ± 6.87
right_pulsatility_index,1.95 ± 0.40,1.69 ± 0.47,1.80 ± 0.49,1.74 ± 0.40,1.76 ± 0.41
right_psv_ratio,0.64 ± 0.10,0.78 ± 0.12,0.68 ± 0.12,0.70 ± 0.13,0.71 ± 0.12
left_1peak_systolic_velocity,37.98 ± 8.91,33.74 ± 10.44,32.93 ± 8.96,34.55 ± 10.26,32.65 ± 8.91
left_2peak_systolic_velocity,25.11 ± 6.81,25.72 ± 8.50,22.88 ± 7.60,24.30 ± 8.51,23.29 ± 6.85
left_pulsatility_index,1.89 ± 0.46,1.67 ± 0.41,1.72 ± 0.41,1.93 ± 2.45,1.72 ± 0.42
left_psv_ratio,0.67 ± 0.13,0.77 ± 0.11,0.70 ± 0.12,0.71 ± 0.13,0.72 ± 0.12
right_mean,0.59 ± 0.09,0.56 ± 0.11,0.53 ± 0.08,0.57 ± 0.14,0.50 ± 0.07
left_mean,0.64 ± 0.09,0.59 ± 0.10,0.53 ± 0.08,0.59 ± 0.12,0.52 ± 0.08

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 0.021 | G1vG3: 1.000 | G1vG4: 0.002 | G2vG3: 0.000 | G2vG4: 0.807 | G3vG4: 0.000,127.00 ± 13.25,122.00 ± 25.00,111.00 ± 16.00,122.00 ± 16.25,108.50 ± 15.25
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 0.127 | G1vG3: 1.000 | G1vG4: 0.005 | G2vG3: 0.000 | G2vG4: 0.947 | G3vG4: 0.000,82.50 ± 6.50,80.00 ± 12.00,74.00 ± 13.00,81.00 ± 12.25,72.50 ± 10.00
2,frec_cardiaca,ANOVA,0.0235,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.840 | G2vG3: 0.073 | G2vG4: 1.000 | G3vG4: 0.008,78.91 ± 14.71,81.36 ± 12.11,78.35 ± 11.91,82.22 ± 11.37,77.33 ± 11.27
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.6812,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,29.65 ± 11.70,29.70 ± 13.40,31.30 ± 10.90,31.40 ± 13.80,31.25 ± 11.85
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.1528,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.760 | G0vG4: 0.837 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,17.10 ± 7.30,23.50 ± 15.40,20.70 ± 9.40,21.70 ± 12.00,21.65 ± 10.23
5,right_pulsatility_index,Kruskal-Wallis,0.2731,G0vG1: 0.417 | G0vG2: 0.881 | G0vG3: 0.449 | G0vG4: 0.640 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.94 ± 0.54,1.68 ± 0.48,1.75 ± 0.50,1.76 ± 0.46,1.71 ± 0.50
6,right_psv_ratio,ANOVA,0.0017,G0vG1: 0.006 | G0vG2: 1.000 | G0vG3: 0.518 | G0vG4: 0.194 | G1vG2: 0.011 | G1vG3: 0.177 | G1vG4: 0.163 | G2vG3: 1.000 | G2vG4: 0.780 | G3vG4: 1.000,0.64 ± 0.10,0.78 ± 0.12,0.68 ± 0.12,0.70 ± 0.13,0.71 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0561,G0vG1: 1.000 | G0vG2: 0.062 | G0vG3: 1.000 | G0vG4: 0.086 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,36.90 ± 7.52,32.70 ± 16.10,33.00 ± 10.70,34.20 ± 13.10,32.45 ± 11.62
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.1963,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.636 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.989 | G2vG4: 1.000 | G3vG4: 1.000,25.60 ± 11.88,24.50 ± 11.30,22.30 ± 7.90,23.40 ± 9.80,22.95 ± 9.35
9,left_pulsatility_index,Kruskal-Wallis,0.3943,G0vG1: 0.984 | G0vG2: 1.000 | G0vG3: 0.748 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.85 ± 0.50,1.65 ± 0.48,1.74 ± 0.53,1.67 ± 0.54,1.69 ± 0.50
10,left_psv_ratio,Kruskal-Wallis,0.0072,G0vG1: 0.070 | G0vG2: 1.000 | G0vG3: 0.737 | G0vG4: 0.444 | G1vG2: 0.026 | G1vG3: 0.177 | G1vG4: 0.372 | G2vG3: 1.000 | G2vG4: 0.620 | G3vG4: 1.000,0.65 ± 0.12,0.79 ± 0.16,0.68 ± 0.15,0.72 ± 0.15,0.71 ± 0.16
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.013 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.127 | G2vG3: 0.421 | G2vG4: 0.121 | G3vG4: 0.002,0.58 ± 0.12,0.54 ± 0.11,0.52 ± 0.10,0.53 ± 0.16,0.50 ± 0.10
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.233 | G0vG4: 0.000 | G1vG2: 0.094 | G1vG3: 1.000 | G1vG4: 0.012 | G2vG3: 0.001 | G2vG4: 1.000 | G3vG4: 0.000,0.64 ± 0.11,0.59 ± 0.12,0.53 ± 0.11,0.57 ± 0.14,0.51 ± 0.10

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
hemoglobina,129.86 ± 13.56,129.29 ± 11.97,126.19 ± 26.76,127.11 ± 23.29,125.17 ± 24.98
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,6667.86 ± 1234.87,6202.86 ± 1381.39,6531.25 ± 1644.70,7172.09 ± 1824.10,6223.56 ± 1453.87
plaquetas,271500.00 ± 56848.99,252761.90 ± 73698.65,269732.14 ± 64042.21,281432.84 ± 68098.69,271188.12 ± 61544.08
glucosa,96.57 ± 19.21,90.62 ± 16.03,87.51 ± 10.99,87.70 ± 8.61,85.96 ± 11.05
sodio,138.07 ± 2.81,139.67 ± 1.71,139.79 ± 1.68,139.54 ± 1.82,139.73 ± 1.76
potasio,4.16 ± 0.34,4.14 ± 0.34,4.23 ± 0.25,4.25 ± 0.29,4.20 ± 0.29
urato_acidourico,4.66 ± 1.20,3.59 ± 0.85,4.10 ± 0.89,4.43 ± 0.92,4.15 ± 2.09
hemoglobina_glicada,5.64 ± 0.48,5.43 ± 0.46,5.33 ± 0.39,5.46 ± 0.37,5.34 ± 0.33
ast,18.93 ± 6.04,21.95 ± 7.45,21.87 ± 11.71,22.42 ± 12.75,21.51 ± 6.69
alt,15.57 ± 8.08,21.71 ± 11.52,17.91 ± 10.81,21.52 ± 20.87,16.71 ± 8.26
bilirubina_total,0.61 ± 0.35,0.62 ± 0.28,0.64 ± 0.32,0.59 ± 0.31,0.74 ± 0.29
ldh,159.79 ± 23.37,167.05 ± 20.22,162.61 ± 25.89,177.24 ± 29.51,162.48 ± 25.60
vldl,19.81 ± 8.11,14.82 ± 9.91,14.69 ± 8.98,18.91 ± 11.12,11.28 ± 4.95
ldl,115.17 ± 25.52,114.41 ± 33.64,111.91 ± 25.56,111.93 ± 32.12,111.50 ± 29.83
hdl,45.61 ± 8.14,60.10 ± 13.61,58.45 ± 12.74,55.23 ± 14.93,65.87 ± 12.98
colesterol_total,180.59 ± 28.04,189.34 ± 36.47,185.11 ± 29.64,186.05 ± 35.82,188.27 ± 32.94
trigliceridos,98.30 ± 40.22,74.85 ± 48.27,74.24 ± 44.51,94.57 ± 54.48,57.72 ± 23.79
prote_totales_orina,0.09 ± 0.05,4.16 ± 17.13,1.40 ± 9.49,2.35 ± 12.47,4.51 ± 16.67

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,hemoglobina,Kruskal-Wallis,0.8936,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,127.50 ± 9.75,129.00 ± 14.00,131.00 ± 14.25,132.00 ± 15.50,131.00 ± 13.00
1,hematocrito,Kruskal-Wallis,0.6443,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.38 ± 0.04,0.38 ± 0.04,0.39 ± 0.03,0.39 ± 0.04,0.39 ± 0.03
2,leucocitos,Kruskal-Wallis,0.0097,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.276 | G1vG4: 1.000 | G2vG3: 0.243 | G2vG4: 1.000 | G3vG4: 0.006,6260.00 ± 827.50,5860.00 ± 1830.00,6300.00 ± 1852.50,6880.00 ± 2025.00,6090.00 ± 2070.00
3,plaquetas,Kruskal-Wallis,0.4768,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.876 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,274500.00 ± 57000.00,261000.00 ± 74000.00,259500.00 ± 87250.00,274000.00 ± 81000.00,265000.00 ± 82000.00
4,glucosa,Kruskal-Wallis,0.2457,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.763 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.998,89.50 ± 26.50,87.00 ± 8.00,86.00 ± 9.25,88.00 ± 11.00,86.00 ± 9.00
5,sodio,Kruskal-Wallis,0.1050,G0vG1: 0.446 | G0vG2: 0.075 | G0vG3: 0.520 | G0vG4: 0.105 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,138.50 ± 1.00,140.00 ± 3.00,140.00 ± 2.00,139.00 ± 3.00,140.00 ± 2.00
6,potasio,Kruskal-Wallis,0.6902,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,4.14 ± 0.37,4.21 ± 0.52,4.22 ± 0.29,4.20 ± 0.33,4.20 ± 0.33
7,urato_acidourico,Kruskal-Wallis,0.0011,G0vG1: 0.100 | G0vG2: 0.687 | G0vG3: 1.000 | G0vG4: 0.170 | G1vG2: 0.393 | G1vG3: 0.013 | G1vG4: 0.717 | G2vG3: 0.289 | G2vG4: 1.000 | G3vG4: 0.021,4.64 ± 1.25,3.64 ± 1.25,3.93 ± 1.05,4.31 ± 1.25,4.01 ± 0.99
8,hemoglobina_glicada,Kruskal-Wallis,0.0051,G0vG1: 0.770 | G0vG2: 0.077 | G0vG3: 1.000 | G0vG4: 0.159 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.039 | G2vG4: 1.000 | G3vG4: 0.100,5.50 ± 0.53,5.30 ± 0.10,5.30 ± 0.30,5.40 ± 0.50,5.30 ± 0.30
9,ast,Kruskal-Wallis,0.2724,G0vG1: 0.849 | G0vG2: 0.289 | G0vG3: 0.981 | G0vG4: 0.271 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,17.50 ± 3.75,21.00 ± 7.00,20.00 ± 6.00,19.00 ± 7.00,20.00 ± 5.00
10,alt,Kruskal-Wallis,0.1399,G0vG1: 0.686 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.687 | G1vG3: 1.000 | G1vG4: 0.363 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,12.00 ± 10.50,18.00 ± 13.00,15.00 ± 8.00,16.00 ± 11.50,14.00 ± 7.00
11,bilirubina_total,Kruskal-Wallis,0.0002,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.318 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.239 | G2vG3: 1.000 | G2vG4: 0.018 | G3vG4: 0.000,0.57 ± 0.20,0.54 ± 0.19,0.56 ± 0.28,0.53 ± 0.24,0.70 ± 0.30
12,ldh,Kruskal-Wallis,0.0052,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.427 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.012 | G2vG4: 1.000 | G3vG4: 0.006,160.00 ± 31.25,160.00 ± 33.00,159.00 ± 29.25,173.00 ± 31.75,160.00 ± 27.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 0.451 | G0vG2: 0.051 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.109 | G2vG4: 0.012 | G3vG4: 0.000,17.84 ± 9.54,13.55 ± 9.27,11.68 ± 6.37,14.98 ± 13.99,9.81 ± 5.00
14,ldl,Kruskal-Wallis,0.8564,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,117.17 ± 22.98,111.11 ± 39.08,111.52 ± 38.43,106.23 ± 39.25,105.51 ± 36.30
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.008 | G0vG2: 0.002 | G0vG3: 0.139 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.395 | G2vG3: 0.396 | G2vG4: 0.000 | G3vG4: 0.000,44.70 ± 12.87,60.37 ± 15.48,57.85 ± 16.54,54.18 ± 16.06,66.95 ± 13.55
16,colesterol_total,Kruskal-Wallis,0.8648,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,188.08 ± 29.22,185.76 ± 39.09,181.89 ± 44.21,178.79 ± 36.77,184.21 ± 37.54
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 0.488 | G0vG2: 0.064 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.833 | G2vG3: 0.104 | G2vG4: 0.010 | G3vG4: 0.000,88.50 ± 47.35,67.26 ± 40.71,57.97 ± 31.20,74.34 ± 69.47,50.00 ± 21.24
18,prote_totales_orina,Kruskal-Wallis,0.2222,G0vG1: 0.345 | G0vG2: 0.849 | G0vG3: 0.883 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.07 ± 0.01,0.12 ± 0.08,0.08 ± 0.05,0.08 ± 0.04,0.07 ± 0.06

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
Cat_Dieta: Adherencia moderada,11 (50.0%),18 (69.2%),114 (67.1%),46 (49.5%),96 (64.9%)
Cat_Dieta: Alta adherencia,0 (0.0%),1 (3.8%),12 (7.1%),3 (3.2%),9 (6.1%)
Cat_Dieta: Baja adherencia,11 (50.0%),7 (26.9%),44 (25.9%),44 (47.3%),43 (29.1%)
Cat_Actividad: Actividad física alta,20 (90.9%),23 (95.8%),156 (92.3%),80 (86.0%),134 (92.4%)
Cat_Actividad: Actividad física baja,1 (4.5%),0 (0.0%),3 (1.8%),1 (1.1%),6 (4.1%)
Cat_Actividad: Actividad física moderada,1 (4.5%),1 (4.2%),10 (5.9%),12 (12.9%),5 (3.4%)
Cat_Estres: Nivel de estrés alto,10 (45.5%),8 (30.8%),59 (34.7%),39 (42.4%),46 (31.3%)
Cat_Estres: Nivel de estrés bajo,3 (13.6%),4 (15.4%),18 (10.6%),10 (10.9%),17 (11.6%)
Cat_Estres: Nivel de estrés moderado,7 (31.8%),13 (50.0%),89 (52.4%),38 (41.3%),81 (55.1%)
Cat_Estres: Nivel de estrés muy alto,2 (9.1%),1 (3.8%),4 (2.4%),5 (5.4%),3 (2.0%)
Cat_Memoria: Deterioro leve,6 (27.3%),6 (25.0%),18 (10.6%),15 (16.3%),20 (13.7%)
Cat_Memoria: Disfunción moderada-grave,4 (18.2%),1 (4.2%),19 (11.2%),7 (7.6%),13 (8.9%)
Cat_Memoria: Función normal (lapsus leves),8 (36.4%),10 (41.7%),104 (61.2%),56 (60.9%),82 (56.2%)
Cat_Memoria: Rendimiento de memoria óptimo,4 (18.2%),7 (29.2%),29 (17.1%),14 (15.2%),31 (21.2%)
Cat_SCL90R: EN RIESGO,2 (9.1%),5 (19.2%),22 (13.0%),12 (13.3%),16 (11.1%)
Cat_SCL90R: Normal / Sin riesgo,3 (13.6%),3 (11.5%),41 (24.3%),12 (13.3%),30 (20.8%)
Cat_SCL90R: Patología severa,17 (77.3%),18 (69.2%),106 (62.7%),66 (73.3%),98 (68.1%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,Cat_Dieta,Chi-Square,0.0177,G0vG1: 1.000 | G0vG2: 0.412 | G0vG3: 1.000 | G0vG4: 0.975 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.016 | G2vG4: 1.000 | G3vG4: 0.142,Adherencia moderada: n=11 (50.0%) | Baja adherencia: n=11 (50.0%),Adherencia moderada: n=18 (69.2%) | Alta adherencia: n=1 (3.8%) | Baja adherencia: n=7 (26.9%),Adherencia moderada: n=114 (67.1%) | Alta adherencia: n=12 (7.1%) | Baja adherencia: n=44 (25.9%),Adherencia moderada: n=46 (49.5%) | Alta adherencia: n=3 (3.2%) | Baja adherencia: n=44 (47.3%),Adherencia moderada: n=96 (64.9%) | Alta adherencia: n=9 (6.1%) | Baja adherencia: n=43 (29.1%)
1,Cat_Actividad,Chi-Square,0.1267,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.442 | G1vG3: 0.296 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.112,Actividad física alta: n=20 (90.9%) | Actividad física baja: n=1 (4.5%) | Actividad física moderada: n=1 (4.5%),Actividad física alta: n=23 (95.8%) | Actividad física moderada: n=1 (4.2%),Actividad física alta: n=156 (92.3%) | Actividad física baja: n=3 (1.8%) | Actividad física moderada: n=10 (5.9%),Actividad física alta: n=80 (86.0%) | Actividad física baja: n=1 (1.1%) | Actividad física moderada: n=12 (12.9%),Actividad física alta: n=134 (92.4%) | Actividad física baja: n=6 (4.1%) | Actividad física moderada: n=5 (3.4%)
2,Cat_Estres,Chi-Square,0.4546,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Nivel de estrés alto: n=10 (45.5%) | Nivel de estrés bajo: n=3 (13.6%) | Nivel de estrés moderado: n=7 (31.8%) | Nivel de estrés muy alto: n=2 (9.1%),Nivel de estrés alto: n=8 (30.8%) | Nivel de estrés bajo: n=4 (15.4%) | Nivel de estrés moderado: n=13 (50.0%) | Nivel de estrés muy alto: n=1 (3.8%),Nivel de estrés alto: n=59 (34.7%) | Nivel de estrés bajo: n=18 (10.6%) | Nivel de estrés moderado: n=89 (52.4%) | Nivel de estrés muy alto: n=4 (2.4%),Nivel de estrés alto: n=39 (42.4%) | Nivel de estrés bajo: n=10 (10.9%) | Nivel de estrés moderado: n=38 (41.3%) | Nivel de estrés muy alto: n=5 (5.4%),Nivel de estrés alto: n=46 (31.3%) | Nivel de estrés bajo: n=17 (11.6%) | Nivel de estrés moderado: n=81 (55.1%) | Nivel de estrés muy alto: n=3 (2.0%)
3,Cat_Memoria,Chi-Square,0.1977,G0vG1: 1.000 | G0vG2: 0.656 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.004 | G1vG3: 0.972 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Deterioro leve: n=6 (27.3%) | Disfunción moderada-grave: n=4 (18.2%) | Función normal (lapsus leves): n=8 (36.4%) | Rendimiento de memoria óptimo: n=4 (18.2%),Deterioro leve: n=6 (25.0%) | Disfunción moderada-grave: n=1 (4.2%) | Función normal (lapsus leves): n=10 (41.7%) | Rendimiento de memoria óptimo: n=7 (29.2%),Deterioro leve: n=18 (10.6%) | Disfunción moderada-grave: n=19 (11.2%) | Función normal (lapsus leves): n=104 (61.2%) | Rendimiento de memoria óptimo: n=29 (17.1%),Deterioro leve: n=15 (16.3%) | Disfunción moderada-grave: n=7 (7.6%) | Función normal (lapsus leves): n=56 (60.9%) | Rendimiento de memoria óptimo: n=14 (15.2%),Deterioro leve: n=20 (13.7%) | Disfunción moderada-grave: n=13 (8.9%) | Función normal (lapsus leves): n=82 (56.2%) | Rendimiento de memoria óptimo: n=31 (21.2%)
4,Cat_SCL90R,Chi-Square,0.4538,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.663 | G2vG4: 1.000 | G3vG4: 1.000,EN RIESGO: n=2 (9.1%) | Normal / Sin riesgo: n=3 (13.6%) | Patología severa: n=17 (77.3%),EN RIESGO: n=5 (19.2%) | Normal / Sin riesgo: n=3 (11.5%) | Patología severa: n=18 (69.2%),EN RIESGO: n=22 (13.0%) | Normal / Sin riesgo: n=41 (24.3%) | Patología severa: n=106 (62.7%),EN RIESGO: n=12 (13.3%) | Normal / Sin riesgo: n=12 (13.3%) | Patología severa: n=66 (73.3%),EN RIESGO: n=16 (11.1%) | Normal / Sin riesgo: n=30 (20.8%) | Patología severa: n=98 (68.1%)

ANTECEDENTES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
trastorno_hipertensivo: 0.0,13 (59.1%),2 (7.7%),139 (81.8%),58 (62.4%),115 (77.7%)
trastorno_hipertensivo: 1.0,9 (40.9%),24 (92.3%),31 (18.2%),35 (37.6%),33 (22.3%)
comp_placentaria: 0.0,18 (81.8%),18 (69.2%),152 (89.4%),83 (89.2%),119 (80.4%)
comp_placentaria: 1.0,4 (18.2%),8 (30.8%),18 (10.6%),10 (10.8%),29 (19.6%)
comp_maternaGrave: 0.0,21 (95.5%),0 (0.0%),170 (100.0%),86 (92.5%),141 (95.3%)
comp_maternaGrave: 1.0,1 (4.5%),26 (100.0%),0 (0.0%),7 (7.5%),7 (4.7%)
comp_metabolica: 0.0,19 (86.4%),22 (84.6%),159 (93.5%),77 (82.8%),134 (90.5%)
comp_metabolica: 1.0,3 (13.6%),4 (15.4%),11 (6.5%),16 (17.2%),14 (9.5%)
ant_obstetrico: -1,18 (81.8%),20 (76.9%),127 (74.7%),65 (69.9%),106 (71.6%)
ant_obstetrico: 1,2 (9.1%),5 (19.2%),36 (21.2%),22 (23.7%),34 (23.0%)
ant_obstetrico: 3,1 (4.5%),1 (3.8%),7 (4.1%),4 (4.3%),5 (3.4%)
ant_obstetrico: 4,1 (4.5%),0 (0.0%),0 (0.0%),2 (2.2%),3 (2.0%)
ant_medico: -1,12 (54.5%),17 (65.4%),133 (78.2%),66 (71.0%),128 (86.5%)
ant_medico: 1,8 (36.4%),8 (30.8%),32 (18.8%),22 (23.7%),16 (10.8%)
ant_medico: 3,2 (9.1%),1 (3.8%),4 (2.4%),5 (5.4%),4 (2.7%)
ant_medico: 5,0 (0.0%),0 (0.0%),1 (0.6%),0 (0.0%),0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.004 | G0vG2: 0.289 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.009 | G2vG4: 1.000 | G3vG4: 0.152,0.0: n=13 (59.1%) | 1.0: n=9 (40.9%),0.0: n=2 (7.7%) | 1.0: n=24 (92.3%),0.0: n=139 (81.8%) | 1.0: n=31 (18.2%),0.0: n=58 (62.4%) | 1.0: n=35 (37.6%),0.0: n=115 (77.7%) | 1.0: n=33 (22.3%)
1,comp_placentaria,Chi-Square,0.0207,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.119 | G1vG3: 0.272 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.358 | G3vG4: 1.000,0.0: n=18 (81.8%) | 1.0: n=4 (18.2%),0.0: n=18 (69.2%) | 1.0: n=8 (30.8%),0.0: n=152 (89.4%) | 1.0: n=18 (10.6%),0.0: n=83 (89.2%) | 1.0: n=10 (10.8%),0.0: n=119 (80.4%) | 1.0: n=29 (19.6%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.013 | G2vG4: 0.130 | G3vG4: 1.000,0.0: n=21 (95.5%) | 1.0: n=1 (4.5%),1.0: n=26 (100.0%),0.0: n=170 (100.0%),0.0: n=86 (92.5%) | 1.0: n=7 (7.5%),0.0: n=141 (95.3%) | 1.0: n=7 (4.7%)
3,comp_metabolica,Chi-Square,0.0756,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.114 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=19 (86.4%) | 1.0: n=3 (13.6%),0.0: n=22 (84.6%) | 1.0: n=4 (15.4%),0.0: n=159 (93.5%) | 1.0: n=11 (6.5%),0.0: n=77 (82.8%) | 1.0: n=16 (17.2%),0.0: n=134 (90.5%) | 1.0: n=14 (9.5%)
4,ant_obstetrico,Chi-Square,0.7767,G0vG1: 1.000 | G0vG2: 0.255 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,-1: n=18 (81.8%) | 1: n=2 (9.1%) | 3: n=1 (4.5%) | 4: n=1 (4.5%),-1: n=20 (76.9%) | 1: n=5 (19.2%) | 3: n=1 (3.8%),-1: n=127 (74.7%) | 1: n=36 (21.2%) | 3: n=7 (4.1%),-1: n=65 (69.9%) | 1: n=22 (23.7%) | 3: n=4 (4.3%) | 4: n=2 (2.2%),-1: n=106 (71.6%) | 1: n=34 (23.0%) | 3: n=5 (3.4%) | 4: n=3 (2.0%)
5,ant_medico,Chi-Square,0.0448,G0vG1: 1.000 | G0vG2: 0.634 | G0vG3: 1.000 | G0vG4: 0.012 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.216 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.124,-1: n=12 (54.5%) | 1: n=8 (36.4%) | 3: n=2 (9.1%),-1: n=17 (65.4%) | 1: n=8 (30.8%) | 3: n=1 (3.8%),-1: n=133 (78.2%) | 1: n=32 (18.8%) | 3: n=4 (2.4%) | 5: n=1 (0.6%),-1: n=66 (71.0%) | 1: n=22 (23.7%) | 3: n=5 (5.4%),-1: n=128 (86.5%) | 1: n=16 (10.8%) | 3: n=4 (2.7%)

======================================================================
COMBINACIÓN 12 | K = 5 | SILHOUETTE = 0.3757
======================================================================

TAMAÑO DE GRUPOS:
cluster   0   1   2    3    4
count    84  69  21  148  137

GESTACIÓN Y BIOMARCADORES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
peso_ini_gest,83.26 ± 5.17,66.20 ± 6.18,107.18 ± 11.60,65.32 ± 4.09,52.61 ± 3.59
peso_fin_gest,93.62 ± 7.08,79.52 ± 8.88,117.72 ± 14.48,77.41 ± 6.40,64.17 ± 6.59
aumento_peso_gest,10.41 ± 5.52,13.33 ± 6.49,10.55 ± 7.54,12.11 ± 4.87,11.48 ± 5.01
talla,165.21 ± 6.99,162.67 ± 5.11,168.00 ± 6.07,165.58 ± 5.62,161.02 ± 5.53
imc_ini_gest,30.65 ± 3.07,25.05 ± 2.68,38.08 ± 4.82,23.90 ± 2.10,20.34 ± 1.65
edad_materna_gest,34.43 ± 5.21,36.70 ± 4.88,37.74 ± 3.34,35.76 ± 3.93,35.04 ± 4.91
tas_1tri,119.56 ± 12.54,116.72 ± 9.23,120.83 ± 10.40,112.51 ± 11.08,110.97 ± 11.07
tad_1tri,74.90 ± 8.84,76.05 ± 7.02,77.39 ± 7.14,71.77 ± 8.42,71.10 ± 7.83
eg_eco_1tri,12.80 ± 0.59,12.66 ± 0.55,13.06 ± 0.60,12.68 ± 0.64,12.75 ± 0.60
eg_parto,39.04 ± 2.05,37.36 ± 3.01,38.86 ± 1.71,39.59 ± 1.57,39.28 ± 2.04
peso_rn,3227.89 ± 582.48,2654.10 ± 739.78,3087.86 ± 645.16,3221.25 ± 541.45,3004.34 ± 574.22
apgar_1min,8.73 ± 1.15,8.46 ± 1.32,8.24 ± 1.89,8.81 ± 0.86,8.92 ± 0.65
apgar_5min,9.71 ± 1.08,9.50 ± 0.98,9.57 ± 0.98,9.84 ± 0.50,9.91 ± 0.37
apgar_10min,9.89 ± 0.35,9.77 ± 0.54,9.81 ± 0.51,9.95 ± 0.25,9.96 ± 0.19
ratio_MoM,5.20 ± 18.49,26.66 ± 68.67,4.80 ± 7.61,1.93 ± 3.56,5.16 ± 20.97
sflt1_MoM,1.53 ± 1.16,3.28 ± 4.08,1.61 ± 1.05,1.27 ± 0.70,1.70 ± 1.40
plgf_MoM,1.19 ± 1.03,0.80 ± 0.62,0.94 ± 0.99,1.50 ± 1.29,1.48 ± 1.04

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.000 | G1vG3: 1.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,82.75 ± 8.00,65.00 ± 10.00,103.00 ± 12.00,65.00 ± 6.62,53.00 ± 5.40
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.000 | G1vG3: 1.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,94.00 ± 8.78,79.50 ± 11.50,113.00 ± 16.10,77.00 ± 8.52,63.80 ± 8.60
2,aumento_peso_gest,Kruskal-Wallis,0.0229,G0vG1: 0.076 | G0vG2: 1.000 | G0vG3: 0.187 | G0vG4: 1.000 | G1vG2: 0.711 | G1vG3: 1.000 | G1vG4: 0.620 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,10.00 ± 7.03,12.00 ± 5.20,10.00 ± 8.00,11.92 ± 5.12,11.00 ± 5.30
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.592 | G0vG2: 0.354 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 0.002 | G1vG3: 0.008 | G1vG4: 0.380 | G2vG3: 0.783 | G2vG4: 0.000 | G3vG4: 0.000,165.00 ± 9.00,163.00 ± 8.00,168.00 ± 3.00,165.00 ± 8.00,161.00 ± 6.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.000 | G1vG3: 0.027 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,30.75 ± 3.86,24.97 ± 3.78,36.41 ± 3.77,23.80 ± 2.96,20.28 ± 2.19
5,edad_materna_gest,Kruskal-Wallis,0.0046,G0vG1: 0.086 | G0vG2: 0.033 | G0vG3: 0.585 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.269 | G2vG3: 0.186 | G2vG4: 0.088 | G3vG4: 1.000,34.54 ± 6.88,37.01 ± 7.85,38.88 ± 5.25,35.77 ± 5.42,35.33 ± 6.83
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.793 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.930 | G1vG3: 0.030 | G1vG4: 0.007 | G2vG3: 0.012 | G2vG4: 0.004 | G3vG4: 1.000,118.50 ± 15.00,115.00 ± 11.00,119.00 ± 15.00,112.00 ± 15.00,111.52 ± 13.00
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.519 | G0vG3: 0.121 | G0vG4: 0.019 | G1vG2: 1.000 | G1vG3: 0.002 | G1vG4: 0.000 | G2vG3: 0.010 | G2vG4: 0.003 | G3vG4: 1.000,74.00 ± 8.25,75.95 ± 8.00,78.00 ± 7.00,72.00 ± 9.00,71.36 ± 9.00
8,eg_eco_1tri,Kruskal-Wallis,0.0901,G0vG1: 1.000 | G0vG2: 0.842 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.122 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.211 | G2vG4: 0.684 | G3vG4: 1.000,12.80 ± 0.70,12.69 ± 0.50,12.96 ± 0.90,12.74 ± 0.70,12.80 ± 0.70
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.489 | G0vG4: 1.000 | G1vG2: 0.321 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.475 | G2vG4: 1.000 | G3vG4: 1.000,39.60 ± 2.15,38.30 ± 3.80,39.30 ± 1.90,39.60 ± 1.70,39.80 ± 2.40
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.046 | G1vG2: 0.426 | G1vG3: 0.000 | G1vG4: 0.013 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.021,3235.00 ± 592.50,2840.00 ± 740.00,3020.00 ± 895.00,3200.00 ± 628.75,3050.00 ± 810.00
11,apgar_1min,Kruskal-Wallis,0.0187,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.165 | G1vG4: 0.022 | G2vG3: 1.000 | G2vG4: 0.570 | G3vG4: 1.000,9.00 ± 0.00,9.00 ± 1.00,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0001,G0vG1: 0.232 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.756 | G1vG2: 1.000 | G1vG3: 0.003 | G1vG4: 0.000 | G2vG3: 0.856 | G2vG4: 0.209 | G3vG4: 1.000,10.00 ± 0.00,10.00 ± 1.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0029,G0vG1: 0.951 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.008 | G1vG4: 0.013 | G2vG3: 0.784 | G2vG4: 0.963 | G3vG4: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.067 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.277 | G2vG4: 1.000 | G3vG4: 1.000,1.66 ± 1.83,4.23 ± 7.83,1.79 ± 2.78,1.39 ± 1.07,1.58 ± 1.52
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.025 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.036,1.26 ± 0.82,1.75 ± 1.87,1.27 ± 0.84,1.23 ± 0.43,1.26 ± 0.75
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.031 | G0vG2: 0.678 | G0vG3: 0.088 | G0vG4: 0.070 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.011 | G2vG4: 0.022 | G3vG4: 1.000,0.98 ± 0.94,0.58 ± 1.02,0.65 ± 0.63,1.29 ± 0.82,1.37 ± 0.98

ECOCARDIOGRAFÍA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
diam_telediastolico,47.54 ± 4.83,44.41 ± 3.65,48.29 ± 5.17,45.51 ± 6.41,42.50 ± 4.15
diam_telesistolico,31.68 ± 4.94,29.43 ± 4.08,32.76 ± 7.09,29.73 ± 4.37,28.72 ± 3.64
dtsvi_indexado,16.28 ± 2.43,16.62 ± 2.58,15.02 ± 3.38,16.79 ± 2.80,17.84 ± 2.64
septo_iv_diastole,8.74 ± 1.82,8.66 ± 2.12,14.23 ± 18.84,9.30 ± 9.70,9.53 ± 12.02
pared_posterior_vi_diastole,7.89 ± 1.71,7.64 ± 1.32,11.24 ± 12.70,8.63 ± 9.37,8.90 ± 10.92
diam_ai,36.85 ± 3.58,34.70 ± 3.77,37.65 ± 3.74,32.82 ± 4.27,30.45 ± 4.00
ai_volumen,44.04 ± 15.78,36.66 ± 11.30,53.23 ± 16.76,37.34 ± 11.24,30.42 ± 9.37
ad_volumen,36.14 ± 13.12,33.46 ± 10.90,43.65 ± 18.87,34.72 ± 19.08,26.71 ± 10.43
tapse,24.41 ± 4.42,24.46 ± 3.67,41.45 ± 64.16,25.49 ± 4.06,26.24 ± 18.02
e_mitral,72.88 ± 15.54,83.44 ± 71.81,69.05 ± 13.39,73.67 ± 13.28,89.33 ± 99.40
e_e,3.89 ± 1.15,4.51 ± 4.54,3.69 ± 0.83,3.83 ± 0.96,4.38 ± 5.08
gc_tsvi,7.10 ± 6.41,5.70 ± 1.08,10.47 ± 12.58,6.42 ± 5.39,5.92 ± 4.67
urato_acidourico,4.48 ± 0.94,3.91 ± 0.86,4.66 ± 1.20,4.09 ± 0.88,4.15 ± 2.18

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.018 | G0vG4: 0.000 | G1vG2: 0.038 | G1vG3: 0.815 | G1vG4: 0.054 | G2vG3: 0.304 | G2vG4: 0.000 | G3vG4: 0.000,48.00 ± 7.50,44.00 ± 4.75,48.00 ± 6.00,45.00 ± 5.00,42.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0002,G0vG1: 0.148 | G0vG2: 1.000 | G0vG3: 0.103 | G0vG4: 0.000 | G1vG2: 0.756 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.638 | G2vG4: 0.110 | G3vG4: 0.128,31.50 ± 8.00,30.00 ± 6.00,33.00 ± 7.00,29.50 ± 5.00,29.00 ± 5.00
2,dtsvi_indexado,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.721 | G0vG4: 0.001 | G1vG2: 0.423 | G1vG3: 1.000 | G1vG4: 0.077 | G2vG3: 0.105 | G2vG4: 0.007 | G3vG4: 0.031,15.99 ± 3.48,16.93 ± 3.54,14.88 ± 2.93,16.71 ± 3.20,18.04 ± 3.22
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.424 | G0vG3: 0.631 | G0vG4: 0.002 | G1vG2: 0.551 | G1vG3: 1.000 | G1vG4: 0.010 | G2vG3: 0.017 | G2vG4: 0.001 | G3vG4: 0.122,8.30 ± 2.65,8.55 ± 3.00,9.40 ± 2.30,8.00 ± 2.00,7.50 ± 2.30
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0150,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.030 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.324 | G2vG3: 1.000 | G2vG4: 0.225 | G3vG4: 0.845,8.00 ± 1.60,7.60 ± 1.67,8.50 ± 2.10,7.50 ± 2.60,7.00 ± 2.00
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.039 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.049 | G1vG3: 0.042 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 0.000,37.00 ± 3.25,35.00 ± 5.25,39.00 ± 5.00,33.00 ± 5.00,30.00 ± 5.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.102 | G0vG2: 0.220 | G0vG3: 0.022 | G0vG4: 0.000 | G1vG2: 0.003 | G1vG3: 1.000 | G1vG4: 0.004 | G2vG3: 0.001 | G2vG4: 0.000 | G3vG4: 0.000,42.25 ± 19.20,37.00 ± 16.00,52.00 ± 21.00,35.50 ± 13.58,29.00 ± 12.75
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.000 | G1vG2: 0.724 | G1vG3: 1.000 | G1vG4: 0.001 | G2vG3: 0.366 | G2vG4: 0.001 | G3vG4: 0.000,34.00 ± 20.05,36.75 ± 16.45,39.20 ± 17.65,30.50 ± 14.00,25.00 ± 12.70
8,tapse,Kruskal-Wallis,0.3452,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.994 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,24.20 ± 5.00,24.00 ± 5.65,27.00 ± 6.00,25.00 ± 6.00,24.70 ± 6.00
9,e_mitral,Kruskal-Wallis,0.0052,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.047 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.423 | G2vG3: 1.000 | G2vG4: 0.092 | G3vG4: 0.035,72.85 ± 18.30,73.20 ± 20.20,68.00 ± 13.50,73.85 ± 16.00,78.10 ± 20.70
10,e_e,Kruskal-Wallis,0.6586,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,3.80 ± 1.14,3.89 ± 1.09,3.48 ± 0.74,3.69 ± 1.11,3.84 ± 1.08
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.079 | G0vG2: 1.000 | G0vG3: 0.018 | G0vG4: 0.000 | G1vG2: 0.034 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.028 | G2vG4: 0.005 | G3vG4: 0.338,6.40 ± 1.50,5.50 ± 1.25,7.00 ± 2.20,5.60 ± 1.30,5.30 ± 1.30
12,urato_acidourico,Kruskal-Wallis,0.0027,G0vG1: 0.042 | G0vG2: 1.000 | G0vG3: 0.133 | G0vG4: 0.010 | G1vG2: 0.299 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.622 | G2vG4: 0.155 | G3vG4: 1.000,4.37 ± 1.26,3.73 ± 1.06,4.64 ± 1.25,3.95 ± 0.99,3.99 ± 0.99

TA, CARÓTIDA Y OFTÁLMICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
ta_sistolica,124.06 ± 16.88,122.19 ± 12.73,128.67 ± 16.39,110.99 ± 12.52,109.77 ± 12.64
ta_diastolica,80.29 ± 10.41,79.09 ± 7.82,83.76 ± 9.65,72.86 ± 9.72,72.12 ± 8.31
frec_cardiaca,81.45 ± 11.73,80.85 ± 13.28,80.71 ± 12.33,77.79 ± 11.65,77.59 ± 11.07
right_1peak_systolic_velocity,32.70 ± 9.15,31.12 ± 10.52,30.28 ± 11.09,30.47 ± 7.76,31.90 ± 8.62
right_2peak_systolic_velocity,22.68 ± 7.28,22.91 ± 8.24,19.22 ± 7.45,20.81 ± 6.74,22.36 ± 6.90
right_pulsatility_index,1.74 ± 0.41,1.69 ± 0.44,1.96 ± 0.40,1.81 ± 0.49,1.77 ± 0.42
right_psv_ratio,0.70 ± 0.12,0.74 ± 0.12,0.65 ± 0.11,0.68 ± 0.12,0.71 ± 0.12
left_1peak_systolic_velocity,35.13 ± 9.89,32.77 ± 10.88,37.73 ± 9.05,32.61 ± 8.65,33.03 ± 8.77
left_2peak_systolic_velocity,24.55 ± 8.49,24.04 ± 8.74,25.07 ± 6.98,22.65 ± 7.32,23.48 ± 6.72
left_pulsatility_index,1.98 ± 2.57,1.65 ± 0.44,1.90 ± 0.47,1.72 ± 0.40,1.73 ± 0.43
left_psv_ratio,0.70 ± 0.13,0.74 ± 0.12,0.67 ± 0.13,0.70 ± 0.12,0.72 ± 0.12
right_mean,0.58 ± 0.15,0.55 ± 0.09,0.59 ± 0.09,0.52 ± 0.08,0.50 ± 0.07
left_mean,0.59 ± 0.12,0.57 ± 0.09,0.63 ± 0.09,0.53 ± 0.08,0.52 ± 0.08

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 1.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 1.000,122.00 ± 17.00,121.00 ± 18.25,127.00 ± 13.00,109.00 ± 15.00,108.00 ± 16.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.349 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 1.000,81.00 ± 13.00,80.00 ± 9.25,83.00 ± 6.00,73.00 ± 11.00,72.00 ± 10.00
2,frec_cardiaca,ANOVA,0.0583,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.070 | G0vG4: 0.042 | G1vG2: 1.000 | G1vG3: 0.472 | G1vG4: 0.342 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,81.45 ± 11.73,80.85 ± 13.28,80.71 ± 12.33,77.79 ± 11.65,77.59 ± 11.07
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.3890,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.620 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,31.85 ± 12.07,32.80 ± 15.05,29.30 ± 12.00,30.60 ± 10.05,31.20 ± 11.90
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.0670,G0vG1: 1.000 | G0vG2: 0.571 | G0vG3: 0.574 | G0vG4: 1.000 | G1vG2: 0.582 | G1vG3: 0.565 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.702 | G3vG4: 0.819,21.80 ± 11.65,23.30 ± 11.70,16.70 ± 7.40,20.50 ± 9.10,21.60 ± 10.30
5,right_pulsatility_index,Kruskal-Wallis,0.0874,G0vG1: 1.000 | G0vG2: 0.383 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.135 | G1vG3: 0.647 | G1vG4: 1.000 | G2vG3: 0.796 | G2vG4: 0.648 | G3vG4: 1.000,1.78 ± 0.43,1.69 ± 0.46,1.97 ± 0.54,1.76 ± 0.49,1.72 ± 0.51
6,right_psv_ratio,ANOVA,0.0018,G0vG1: 0.219 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.025 | G1vG3: 0.005 | G1vG4: 0.422 | G2vG3: 1.000 | G2vG4: 0.335 | G3vG4: 0.713,0.70 ± 0.12,0.74 ± 0.12,0.65 ± 0.11,0.68 ± 0.12,0.71 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0339,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.214 | G0vG4: 0.872 | G1vG2: 0.789 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.050 | G2vG4: 0.241 | G3vG4: 1.000,34.75 ± 13.18,31.90 ± 16.60,36.50 ± 7.60,32.30 ± 9.20,32.60 ± 12.50
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.2178,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.287 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,24.25 ± 10.00,23.80 ± 11.40,25.10 ± 12.30,22.30 ± 7.50,22.95 ± 9.23
9,left_pulsatility_index,Kruskal-Wallis,0.2210,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.366 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,1.67 ± 0.62,1.63 ± 0.49,1.95 ± 0.51,1.74 ± 0.51,1.71 ± 0.49
10,left_psv_ratio,Kruskal-Wallis,0.0281,G0vG1: 0.635 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.244 | G1vG3: 0.076 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 0.652 | G3vG4: 0.726,0.70 ± 0.14,0.74 ± 0.16,0.65 ± 0.12,0.68 ± 0.15,0.71 ± 0.15
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.060 | G0vG4: 0.000 | G1vG2: 0.663 | G1vG3: 0.229 | G1vG4: 0.001 | G2vG3: 0.008 | G2vG4: 0.000 | G3vG4: 0.202,0.55 ± 0.16,0.55 ± 0.11,0.57 ± 0.13,0.51 ± 0.10,0.49 ± 0.10
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.715 | G0vG3: 0.000 | G0vG4: 0.000 | G1vG2: 0.128 | G1vG3: 0.013 | G1vG4: 0.001 | G2vG3: 0.000 | G2vG4: 0.000 | G3vG4: 1.000,0.57 ± 0.14,0.55 ± 0.12,0.63 ± 0.09,0.53 ± 0.10,0.51 ± 0.10

ANALÍTICA

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
hemoglobina,127.94 ± 19.08,126.11 ± 26.33,129.86 ± 13.56,126.81 ± 25.62,124.70 ± 25.79
hematocrito,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03,0.39 ± 0.03
leucocitos,7231.36 ± 1840.78,6194.79 ± 1412.33,6667.86 ± 1234.87,6610.40 ± 1675.48,6228.17 ± 1452.92
plaquetas,282305.08 ± 69701.89,273833.33 ± 73290.54,271500.00 ± 56848.99,264574.26 ± 60601.87,271419.35 ± 61641.38
glucosa,87.80 ± 8.92,90.46 ± 14.82,96.57 ± 19.21,87.37 ± 12.00,85.12 ± 7.94
sodio,139.68 ± 1.76,139.75 ± 1.64,138.07 ± 2.81,139.65 ± 1.73,139.75 ± 1.80
potasio,4.24 ± 0.30,4.28 ± 0.32,4.16 ± 0.34,4.21 ± 0.26,4.19 ± 0.27
urato_acidourico,4.48 ± 0.94,3.91 ± 0.86,4.66 ± 1.20,4.09 ± 0.88,4.15 ± 2.18
hemoglobina_glicada,5.47 ± 0.39,5.44 ± 0.48,5.64 ± 0.48,5.29 ± 0.33,5.34 ± 0.34
ast,22.73 ± 13.51,21.10 ± 5.77,18.93 ± 6.04,22.23 ± 12.53,21.35 ± 6.24
alt,21.93 ± 22.10,19.19 ± 9.15,15.57 ± 8.08,18.45 ± 11.77,16.28 ± 7.45
bilirubina_total,0.59 ± 0.31,0.61 ± 0.31,0.61 ± 0.35,0.66 ± 0.30,0.73 ± 0.30
ldh,178.00 ± 26.92,167.23 ± 29.36,159.79 ± 23.37,161.29 ± 24.29,163.30 ± 26.26
vldl,19.26 ± 11.48,15.46 ± 8.33,19.81 ± 8.11,14.22 ± 9.20,11.28 ± 4.83
ldl,112.39 ± 33.14,110.57 ± 26.64,115.17 ± 25.52,111.86 ± 26.83,112.49 ± 30.07
hdl,55.51 ± 15.41,58.82 ± 13.98,45.61 ± 8.14,58.96 ± 12.26,65.67 ± 13.27
colesterol_total,187.13 ± 36.95,184.84 ± 33.09,180.59 ± 28.04,185.12 ± 28.86,189.02 ± 33.48
trigliceridos,96.36 ± 56.19,77.41 ± 40.74,98.30 ± 40.22,72.25 ± 45.55,57.57 ± 23.34
prote_totales_orina,2.68 ± 13.33,3.38 ± 15.17,0.09 ± 0.05,0.80 ± 6.97,4.90 ± 17.34

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,hemoglobina,Kruskal-Wallis,0.9017,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,132.00 ± 15.50,129.00 ± 13.25,127.50 ± 9.75,132.00 ± 15.00,131.00 ± 13.00
1,hematocrito,Kruskal-Wallis,0.8044,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.40 ± 0.04,0.39 ± 0.04,0.38 ± 0.04,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0053,G0vG1: 0.033 | G0vG2: 1.000 | G0vG3: 0.300 | G0vG4: 0.005 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,7020.00 ± 2000.00,5980.00 ± 2325.00,6260.00 ± 827.50,6370.00 ± 1900.00,6100.00 ± 2010.00
3,plaquetas,Kruskal-Wallis,0.7645,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,266000.00 ± 86000.00,272000.00 ± 92500.00,274500.00 ± 57000.00,257000.00 ± 80000.00,268000.00 ± 82000.00
4,glucosa,Kruskal-Wallis,0.0704,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.547 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.273 | G2vG3: 1.000 | G2vG4: 0.573 | G3vG4: 1.000,89.00 ± 11.00,88.00 ± 8.25,89.50 ± 26.50,86.00 ± 10.00,85.00 ± 9.00
5,sodio,Kruskal-Wallis,0.1347,G0vG1: 1.000 | G0vG2: 0.361 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.089 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.172 | G2vG4: 0.110 | G3vG4: 1.000,139.00 ± 3.00,140.00 ± 2.00,138.50 ± 1.00,140.00 ± 3.00,140.00 ± 2.00
6,potasio,Kruskal-Wallis,0.4072,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.913 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,4.20 ± 0.33,4.25 ± 0.32,4.14 ± 0.37,4.19 ± 0.30,4.17 ± 0.34
7,urato_acidourico,Kruskal-Wallis,0.0027,G0vG1: 0.042 | G0vG2: 1.000 | G0vG3: 0.133 | G0vG4: 0.010 | G1vG2: 0.299 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.622 | G2vG4: 0.155 | G3vG4: 1.000,4.37 ± 1.26,3.73 ± 1.06,4.64 ± 1.25,3.95 ± 0.99,3.99 ± 0.99
8,hemoglobina_glicada,Kruskal-Wallis,0.0010,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.007 | G0vG4: 0.065 | G1vG2: 0.668 | G1vG3: 0.541 | G1vG4: 1.000 | G2vG3: 0.046 | G2vG4: 0.164 | G3vG4: 1.000,5.45 ± 0.50,5.40 ± 0.10,5.50 ± 0.53,5.30 ± 0.30,5.30 ± 0.30
9,ast,Kruskal-Wallis,0.2782,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.552 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.302 | G2vG4: 0.249 | G3vG4: 1.000,19.00 ± 7.50,20.50 ± 7.00,17.50 ± 3.75,20.00 ± 6.00,21.00 ± 5.00
10,alt,Kruskal-Wallis,0.2062,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 0.984 | G1vG3: 1.000 | G1vG4: 0.465 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,16.00 ± 11.50,17.50 ± 9.75,12.00 ± 10.50,15.00 ± 8.00,14.00 ± 6.00
11,bilirubina_total,Kruskal-Wallis,0.0006,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.296 | G0vG4: 0.001 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.026 | G2vG3: 1.000 | G2vG4: 0.430 | G3vG4: 0.373,0.52 ± 0.24,0.55 ± 0.20,0.57 ± 0.20,0.59 ± 0.29,0.68 ± 0.33
12,ldh,Kruskal-Wallis,0.0021,G0vG1: 0.329 | G0vG2: 0.300 | G0vG3: 0.002 | G0vG4: 0.007 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,173.00 ± 31.25,158.50 ± 34.50,160.00 ± 31.25,159.00 ± 27.00,160.00 ± 29.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.058 | G0vG4: 0.000 | G1vG2: 0.640 | G1vG3: 1.000 | G1vG4: 0.012 | G2vG3: 0.017 | G2vG4: 0.000 | G3vG4: 0.143,15.52 ± 14.89,14.09 ± 10.16,17.84 ± 9.54,11.59 ± 5.17,9.81 ± 5.17
14,ldl,Kruskal-Wallis,0.9060,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,107.42 ± 38.28,109.00 ± 38.31,117.17 ± 22.98,110.29 ± 40.67,106.47 ± 35.94
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.994 | G0vG2: 0.162 | G0vG3: 0.369 | G0vG4: 0.000 | G1vG2: 0.006 | G1vG3: 1.000 | G1vG4: 0.033 | G2vG3: 0.001 | G2vG4: 0.000 | G3vG4: 0.002,54.18 ± 17.23,58.05 ± 17.80,44.70 ± 12.87,58.44 ± 16.25,66.18 ± 14.32
16,colesterol_total,Kruskal-Wallis,0.9814,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,182.28 ± 40.25,184.02 ± 44.70,188.08 ± 29.22,181.50 ± 42.96,184.21 ± 38.70
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.058 | G0vG4: 0.000 | G1vG2: 0.664 | G1vG3: 1.000 | G1vG4: 0.015 | G2vG3: 0.024 | G2vG4: 0.000 | G3vG4: 0.082,77.00 ± 73.68,69.91 ± 47.68,88.50 ± 47.35,57.52 ± 27.00,50.00 ± 22.12
18,prote_totales_orina,Kruskal-Wallis,0.5363,G0vG1: 1.000 | G0vG2: 0.664 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.891 | G2vG4: 1.000 | G3vG4: 1.000,0.08 ± 0.04,0.08 ± 0.05,0.07 ± 0.01,0.08 ± 0.05,0.07 ± 0.06

SCORES CATEGÓRICOS

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
Cat_Dieta: Adherencia moderada,40 (47.6%),43 (62.3%),11 (52.4%),98 (66.2%),93 (67.9%)
Cat_Dieta: Alta adherencia,2 (2.4%),5 (7.2%),0 (0.0%),12 (8.1%),6 (4.4%)
Cat_Dieta: Baja adherencia,42 (50.0%),21 (30.4%),10 (47.6%),38 (25.7%),38 (27.7%)
Cat_Actividad: Actividad física alta,71 (84.5%),63 (95.5%),19 (90.5%),137 (92.6%),123 (91.8%)
Cat_Actividad: Actividad física baja,1 (1.2%),0 (0.0%),1 (4.8%),3 (2.0%),6 (4.5%)
Cat_Actividad: Actividad física moderada,12 (14.3%),3 (4.5%),1 (4.8%),8 (5.4%),5 (3.7%)
Cat_Estres: Nivel de estrés alto,34 (41.0%),26 (37.7%),10 (47.6%),50 (33.8%),42 (30.9%)
Cat_Estres: Nivel de estrés bajo,10 (12.0%),8 (11.6%),3 (14.3%),16 (10.8%),15 (11.0%)
Cat_Estres: Nivel de estrés moderado,33 (39.8%),33 (47.8%),7 (33.3%),79 (53.4%),76 (55.9%)
Cat_Estres: Nivel de estrés muy alto,6 (7.2%),2 (2.9%),1 (4.8%),3 (2.0%),3 (2.2%)
Cat_Memoria: Deterioro leve,13 (15.7%),12 (17.9%),5 (23.8%),16 (10.8%),19 (14.1%)
Cat_Memoria: Disfunción moderada-grave,7 (8.4%),4 (6.0%),4 (19.0%),18 (12.2%),11 (8.1%)
Cat_Memoria: Función normal (lapsus leves),52 (62.7%),38 (56.7%),8 (38.1%),86 (58.1%),76 (56.3%)
Cat_Memoria: Rendimiento de memoria óptimo,11 (13.3%),13 (19.4%),4 (19.0%),28 (18.9%),29 (21.5%)
Cat_SCL90R: EN RIESGO,10 (12.3%),12 (17.4%),2 (9.5%),17 (11.6%),16 (12.0%)
Cat_SCL90R: Normal / Sin riesgo,11 (13.6%),7 (10.1%),3 (14.3%),41 (27.9%),27 (20.3%)
Cat_SCL90R: Patología severa,60 (74.1%),50 (72.5%),16 (76.2%),89 (60.5%),90 (67.7%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,Cat_Dieta,Chi-Square,0.0048,G0vG1: 0.303 | G0vG2: 1.000 | G0vG3: 0.005 | G0vG4: 0.036 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.683 | G2vG4: 1.000 | G3vG4: 1.000,Adherencia moderada: n=40 (47.6%) | Alta adherencia: n=2 (2.4%) | Baja adherencia: n=42 (50.0%),Adherencia moderada: n=43 (62.3%) | Alta adherencia: n=5 (7.2%) | Baja adherencia: n=21 (30.4%),Adherencia moderada: n=11 (52.4%) | Baja adherencia: n=10 (47.6%),Adherencia moderada: n=98 (66.2%) | Alta adherencia: n=12 (8.1%) | Baja adherencia: n=38 (25.7%),Adherencia moderada: n=93 (67.9%) | Alta adherencia: n=6 (4.4%) | Baja adherencia: n=38 (27.7%)
1,Cat_Actividad,Chi-Square,0.0436,G0vG1: 0.369 | G0vG2: 1.000 | G0vG3: 0.637 | G0vG4: 0.101 | G1vG2: 1.000 | G1vG3: 0.472 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Actividad física alta: n=71 (84.5%) | Actividad física baja: n=1 (1.2%) | Actividad física moderada: n=12 (14.3%),Actividad física alta: n=63 (95.5%) | Actividad física moderada: n=3 (4.5%),Actividad física alta: n=19 (90.5%) | Actividad física baja: n=1 (4.8%) | Actividad física moderada: n=1 (4.8%),Actividad física alta: n=137 (92.6%) | Actividad física baja: n=3 (2.0%) | Actividad física moderada: n=8 (5.4%),Actividad física alta: n=123 (91.8%) | Actividad física baja: n=6 (4.5%) | Actividad física moderada: n=5 (3.7%)
2,Cat_Estres,Chi-Square,0.4133,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.811 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Nivel de estrés alto: n=34 (41.0%) | Nivel de estrés bajo: n=10 (12.0%) | Nivel de estrés moderado: n=33 (39.8%) | Nivel de estrés muy alto: n=6 (7.2%),Nivel de estrés alto: n=26 (37.7%) | Nivel de estrés bajo: n=8 (11.6%) | Nivel de estrés moderado: n=33 (47.8%) | Nivel de estrés muy alto: n=2 (2.9%),Nivel de estrés alto: n=10 (47.6%) | Nivel de estrés bajo: n=3 (14.3%) | Nivel de estrés moderado: n=7 (33.3%) | Nivel de estrés muy alto: n=1 (4.8%),Nivel de estrés alto: n=50 (33.8%) | Nivel de estrés bajo: n=16 (10.8%) | Nivel de estrés moderado: n=79 (53.4%) | Nivel de estrés muy alto: n=3 (2.0%),Nivel de estrés alto: n=42 (30.9%) | Nivel de estrés bajo: n=15 (11.0%) | Nivel de estrés moderado: n=76 (55.9%) | Nivel de estrés muy alto: n=3 (2.2%)
3,Cat_Memoria,Chi-Square,0.5060,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.982 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,Deterioro leve: n=13 (15.7%) | Disfunción moderada-grave: n=7 (8.4%) | Función normal (lapsus leves): n=52 (62.7%) | Rendimiento de memoria óptimo: n=11 (13.3%),Deterioro leve: n=12 (17.9%) | Disfunción moderada-grave: n=4 (6.0%) | Función normal (lapsus leves): n=38 (56.7%) | Rendimiento de memoria óptimo: n=13 (19.4%),Deterioro leve: n=5 (23.8%) | Disfunción moderada-grave: n=4 (19.0%) | Función normal (lapsus leves): n=8 (38.1%) | Rendimiento de memoria óptimo: n=4 (19.0%),Deterioro leve: n=16 (10.8%) | Disfunción moderada-grave: n=18 (12.2%) | Función normal (lapsus leves): n=86 (58.1%) | Rendimiento de memoria óptimo: n=28 (18.9%),Deterioro leve: n=19 (14.1%) | Disfunción moderada-grave: n=11 (8.1%) | Función normal (lapsus leves): n=76 (56.3%) | Rendimiento de memoria óptimo: n=29 (21.5%)
4,Cat_SCL90R,Chi-Square,0.0902,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.324 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 0.248 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,EN RIESGO: n=10 (12.3%) | Normal / Sin riesgo: n=11 (13.6%) | Patología severa: n=60 (74.1%),EN RIESGO: n=12 (17.4%) | Normal / Sin riesgo: n=7 (10.1%) | Patología severa: n=50 (72.5%),EN RIESGO: n=2 (9.5%) | Normal / Sin riesgo: n=3 (14.3%) | Patología severa: n=16 (76.2%),EN RIESGO: n=17 (11.6%) | Normal / Sin riesgo: n=41 (27.9%) | Patología severa: n=89 (60.5%),EN RIESGO: n=16 (12.0%) | Normal / Sin riesgo: n=27 (20.3%) | Patología severa: n=90 (67.7%)

ANTECEDENTES

,Grupo 0,Grupo 1,Grupo 2,Grupo 3,Grupo 4
trastorno_hipertensivo: 0.0,56 (66.7%),0 (0.0%),12 (57.1%),148 (100.0%),111 (81.0%)
trastorno_hipertensivo: 1.0,28 (33.3%),69 (100.0%),9 (42.9%),0 (0.0%),26 (19.0%)
comp_placentaria: 0.0,76 (90.5%),55 (79.7%),18 (85.7%),132 (89.2%),109 (79.6%)
comp_placentaria: 1.0,8 (9.5%),14 (20.3%),3 (14.3%),16 (10.8%),28 (20.4%)
comp_maternaGrave: 0.0,77 (91.7%),45 (65.2%),20 (95.2%),146 (98.6%),130 (94.9%)
comp_maternaGrave: 1.0,7 (8.3%),24 (34.8%),1 (4.8%),2 (1.4%),7 (5.1%)
comp_metabolica: 0.0,69 (82.1%),63 (91.3%),18 (85.7%),138 (93.2%),123 (89.8%)
comp_metabolica: 1.0,15 (17.9%),6 (8.7%),3 (14.3%),10 (6.8%),14 (10.2%)
ant_obstetrico: -1,61 (72.6%),52 (75.4%),17 (81.0%),106 (71.6%),100 (73.0%)
ant_obstetrico: 1,18 (21.4%),15 (21.7%),2 (9.5%),34 (23.0%),30 (21.9%)
ant_obstetrico: 3,3 (3.6%),2 (2.9%),1 (4.8%),8 (5.4%),4 (2.9%)
ant_obstetrico: 4,2 (2.4%),0 (0.0%),1 (4.8%),0 (0.0%),3 (2.2%)
ant_medico: -1,60 (71.4%),48 (69.6%),11 (52.4%),117 (79.1%),120 (87.6%)
ant_medico: 1,19 (22.6%),19 (27.5%),8 (38.1%),27 (18.2%),13 (9.5%)
ant_medico: 3,5 (6.0%),2 (2.9%),2 (9.5%),3 (2.0%),4 (2.9%)
ant_medico: 5,0 (0.0%),0 (0.0%),0 (0.0%),1 (0.7%),0 (0.0%)

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3,G4
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 0.000 | G0vG4: 0.245 | G1vG2: 0.000 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 0.000 | G2vG4: 0.299 | G3vG4: 0.000,0.0: n=56 (66.7%) | 1.0: n=28 (33.3%),1.0: n=69 (100.0%),0.0: n=12 (57.1%) | 1.0: n=9 (42.9%),0.0: n=148 (100.0%),0.0: n=111 (81.0%) | 1.0: n=26 (19.0%)
1,comp_placentaria,Chi-Square,0.0691,G0vG1: 0.975 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.518 | G1vG2: 1.000 | G1vG3: 0.944 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 0.372,0.0: n=76 (90.5%) | 1.0: n=8 (9.5%),0.0: n=55 (79.7%) | 1.0: n=14 (20.3%),0.0: n=18 (85.7%) | 1.0: n=3 (14.3%),0.0: n=132 (89.2%) | 1.0: n=16 (10.8%),0.0: n=109 (79.6%) | 1.0: n=28 (20.4%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.218 | G0vG4: 1.000 | G1vG2: 0.159 | G1vG3: 0.000 | G1vG4: 0.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=77 (91.7%) | 1.0: n=7 (8.3%),0.0: n=45 (65.2%) | 1.0: n=24 (34.8%),0.0: n=20 (95.2%) | 1.0: n=1 (4.8%),0.0: n=146 (98.6%) | 1.0: n=2 (1.4%),0.0: n=130 (94.9%) | 1.0: n=7 (5.1%)
3,comp_metabolica,Chi-Square,0.1056,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.164 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 1.000 | G2vG4: 1.000 | G3vG4: 1.000,0.0: n=69 (82.1%) | 1.0: n=15 (17.9%),0.0: n=63 (91.3%) | 1.0: n=6 (8.7%),0.0: n=18 (85.7%) | 1.0: n=3 (14.3%),0.0: n=138 (93.2%) | 1.0: n=10 (6.8%),0.0: n=123 (89.8%) | 1.0: n=14 (10.2%)
4,ant_obstetrico,Chi-Square,0.6537,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 1.000 | G2vG3: 0.314 | G2vG4: 1.000 | G3vG4: 1.000,-1: n=61 (72.6%) | 1: n=18 (21.4%) | 3: n=3 (3.6%) | 4: n=2 (2.4%),-1: n=52 (75.4%) | 1: n=15 (21.7%) | 3: n=2 (2.9%),-1: n=17 (81.0%) | 1: n=2 (9.5%) | 3: n=1 (4.8%) | 4: n=1 (4.8%),-1: n=106 (71.6%) | 1: n=34 (23.0%) | 3: n=8 (5.4%),-1: n=100 (73.0%) | 1: n=30 (21.9%) | 3: n=4 (2.9%) | 4: n=3 (2.2%)
5,ant_medico,Chi-Square,0.0131,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G0vG4: 0.109 | G1vG2: 1.000 | G1vG3: 1.000 | G1vG4: 0.033 | G2vG3: 0.312 | G2vG4: 0.003 | G3vG4: 1.000,-1: n=60 (71.4%) | 1: n=19 (22.6%) | 3: n=5 (6.0%),-1: n=48 (69.6%) | 1: n=19 (27.5%) | 3: n=2 (2.9%),-1: n=11 (52.4%) | 1: n=8 (38.1%) | 3: n=2 (9.5%),-1: n=117 (79.1%) | 1: n=27 (18.2%) | 3: n=3 (2.0%) | 5: n=1 (0.7%),-1: n=120 (87.6%) | 1: n=13 (9.5%) | 3: n=4 (2.9%)

# Clustering con K-Medoids

In [38]:
%pip install scikit-learn-extra gower

Requirement already satisfied: scikit-learn-extra in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.3.0)
Requirement already satisfied: gower in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.1.2)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn-extra) (1.26.4)
Requirement already satisfied: scipy>=0.19.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn-extra) (1.16.3)
Requirement already satisfied: scikit-learn>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn-extra) (1.7.2)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn>=0.23.0->scikit-learn-extra) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [39]:
from sklearn_extra.cluster import KMedoids
import gower
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

In [40]:
vars_clustering_kmedoids = [
    'peso_ini_gest', 'peso_fin_gest', 'aumento_peso_gest', 'talla', 'imc_ini_gest', 
    'peso_rn', 'apgar_1min', 'apgar_5min', 'apgar_10min', 'eg_parto', 
    'sflt1_MoM', 'tas_1tri', 'tad_1tri', 'edad_materna_gest', 'plgf_MoM', 'ratio_MoM', 
    'ant_obstetrico', 'ant_medico', 'trastorno_hipertensivo', 
    'comp_placentaria', 'comp_maternaGrave', 'comp_metabolica'
]

# Filtrar variables existentes y limpiar NaNs
vars_disponibles = [v for v in vars_clustering_kmedoids if v in df_maestro.columns]
df_clean = df_maestro.dropna(subset=vars_disponibles).copy()
vars_finales = [v for v in vars_disponibles if df_clean[v].nunique() > 1]

# Forzar tipos numéricos para evitar conflictos en la matriz de Gower
for v in vars_finales:
    df_clean[v] = pd.to_numeric(df_clean[v], errors='coerce').fillna(0)

# FUNCIÓN DE EVALUACIÓN 
def evaluar_kmedoids(df_input, vars_list, k):
    # Forzamos float64 para evitar el error UFuncTypeError: Cannot cast ufunc 'divide'
    X = df_input[vars_list].copy().astype(np.float64)
    cat_features = [v in variables_categoricas for v in vars_list]
    
    # Cálculo de matriz de Gower
    dist_matrix = gower.gower_matrix(X, cat_features=cat_features)
    dist_matrix = (dist_matrix + dist_matrix.T) / 2
    np.fill_diagonal(dist_matrix, 0)
    
    # Modelo K-Medoids
    km = KMedoids(n_clusters=k, metric='precomputed', method='pam', random_state=42)
    labels = km.fit_predict(dist_matrix)
    
    if len(np.unique(labels)) < 2:
        return 0.0, labels
        
    sil = silhouette_score(dist_matrix, labels, metric='precomputed')
    return sil, labels

# BÚSQUEDA DE COMBINACIONES (FORWARD SELECTION + FILTRO n>=100)
def buscar_top3_kmedoids(df_input, k_range, candidate_vars):
    all_k_results = []
    for k in k_range:
        print(f"\n>>> BUSCANDO PARA K={k} (Requisito: cada grupo n >= 100) <<<")
        tested_combinations = []
        current_vars = []
        remaining = list(candidate_vars)
        
        while remaining:
            step_scores = []
            for var in remaining:
                temp_vars = current_vars + [var]
                try:
                    sil, labels = evaluar_kmedoids(df_input, temp_vars, k)
                    counts = pd.Series(labels).value_counts().sort_index()
                    counts_list = counts.tolist()
                    
                    # Lógica de filtrado:
                    # Si ya formó K grupos, verificamos que todos tengan >= 100
                    formo_k = (len(counts_list) == k)
                    cumple_n = all(n >= 100 for n in counts_list)

                    if formo_k and cumple_n:
                        tested_combinations.append({
                            'k': k, 'silhouette': sil, 
                            'num_variables': len(temp_vars),
                            'variables': list(temp_vars),
                            'n_grupos': counts_list
                        })
                        step_scores.append((sil, var))
                    elif not formo_k:
                        # Si aún no separa en K grupos, permitimos que siga para añadir más variables
                        step_scores.append((0.0001, var))
                except: continue
            
            if not step_scores: break
            
            step_scores.sort(key=lambda x: x[0], reverse=True)
            best_sil, best_var = step_scores[0]
            if best_sil <= 0: break
                
            current_vars.append(best_var)
            remaining.remove(best_var)
            print(f" Paso {len(current_vars)}: +{best_var:<25} | Sil: {best_sil:.4f}")

        df_k = pd.DataFrame(tested_combinations)
        if not df_k.empty:
            top3 = df_k.sort_values('silhouette', ascending=False).head(3)
            all_k_results.append(top3)
        else:
            print(f"  AVISO: No se encontraron combinaciones válidas para K={k}")
    
    return pd.concat(all_k_results, ignore_index=True) if all_k_results else pd.DataFrame()

# EJECUCIÓN DE LA BÚSQUEDA
top3_kmedoids = buscar_top3_kmedoids(df_clean, [2, 3, 4], vars_finales)

# ANÁLISIS ESTADÍSTICO DE LOS RESULTADOS
if not top3_kmedoids.empty:
    print("\n" + "="*80)
    print("RESUMEN DE LAS MEJORES COMBINACIONES ENCONTRADAS")
    print("="*80)
    pd.set_option('display.max_colwidth', None)
    display(top3_kmedoids)

    for idx, row in top3_kmedoids.iterrows():
        k_val = int(row['k'])
        vars_sel = row['variables']
        
        print(f"\n\n{'#'*100}")
        print(f"ANÁLISIS DETALLADO: K={k_val} | Sil: {row['silhouette']:.4f} | Tamaños: {row['n_grupos']}")
        print(f"Variables: {vars_sel}")
        print(f"{'#'*100}")
        
        # Generar mapa de clusters para esta combinación
        _, labels = evaluar_kmedoids(df_clean, vars_sel, k_val)
        mapa = pd.DataFrame({'id': df_clean['id'], 'cluster': labels})
        
        # Unir con maestro (limpiando duplicados)
        df_base = df_maestro.loc[:, ~df_maestro.columns.duplicated()].copy()
        if 'cluster' in df_base.columns: df_base = df_base.drop(columns=['cluster'])
        df_final = pd.merge(df_base, mapa, on='id', how='inner')
        
        for nombre_bloque, vars_bloque in grupos_informe.items():
            v_existentes = [v for v in vars_bloque if v in df_final.columns]
            data_stats = []
            for v in v_existentes:
                if v not in ['id', 'ID']:
                    try:
                        res = realizar_analisis_avanzado(df_final, v, 'cluster')
                        if res: data_stats.append(res)
                    except: continue
            
            if data_stats:
                print(f"\n{nombre_bloque}")
                # Headers dinámicos para evitar errores de dimensión
                num_tot = len(data_stats[0])
                headers_fijos = ["Variable", "Test", "p-valor (Total)", "p-valor (dos a dos)"]
                headers_dinamicos = headers_fijos + [f"G{i}" for i in range(num_tot - len(headers_fijos))]
                
                df_res = pd.DataFrame(data_stats, columns=headers_dinamicos)
                display(df_res)
else:
    print("\nERROR: No se encontró ninguna combinación que cumpla con el mínimo de 100 pacientes por grupo.")

>>> BUSCANDO PARA K=2 (Requisito: cada grupo n >= 100) <<<
 Paso 1: +trastorno_hipertensivo    | Sil: 1.0000
 Paso 2: +ratio_MoM                 | Sil: 0.9740
 Paso 3: +sflt1_MoM                 | Sil: 0.9421
 Paso 4: +apgar_5min                | Sil: 0.9105
 Paso 5: +apgar_1min                | Sil: 0.8662
 Paso 6: +apgar_10min               | Sil: 0.8260
 Paso 7: +comp_maternaGrave         | Sil: 0.7704
 Paso 8: +plgf_MoM                  | Sil: 0.7248
 Paso 9: +eg_parto                  | Sil: 0.6814
 Paso 10: +tad_1tri                  | Sil: 0.6410
 Paso 11: +aumento_peso_gest         | Sil: 0.6037
 Paso 12: +imc_ini_gest              | Sil: 0.5676
 Paso 13: +tas_1tri                  | Sil: 0.5347
 Paso 14: +peso_ini_gest             | Sil: 0.5054
 Paso 15: +peso_fin_gest             | Sil: 0.4796
 Paso 16: +peso_rn                   | Sil: 0.4563
 Paso 17: +talla                     | Sil: 0.4334
 Paso 18: +edad_materna_gest         | Sil: 0.4126
 Paso 19: +comp_metabolica           | Sil: 0.3927
 Paso 20: +comp_placentaria          | Sil: 0.3714
 Paso 21: +ant_medico                | Sil: 0.3447
 Paso 22: +ant_obstetrico            | Sil: 0.3142

>>> BUSCANDO PARA K=3 (Requisito: cada grupo n >= 100) <<<
 Paso 1: +peso_ini_gest             | Sil: 0.5471
 Paso 2: +ratio_MoM                 | Sil: 0.4616
 Paso 3: +apgar_5min                | Sil: 0.3742
 Paso 4: +peso_fin_gest             | Sil: 0.4045
 Paso 5: +trastorno_hipertensivo    | Sil: 0.5205
 Paso 6: +sflt1_MoM                 | Sil: 0.4926
 Paso 7: +apgar_1min                | Sil: 0.4520
 Paso 8: +apgar_10min               | Sil: 0.4151
 Paso 9: +tas_1tri                  | Sil: 0.3522
 Paso 10: +talla                     | Sil: 0.3248
 Paso 11: +eg_parto                  | Sil: 0.2883
 Paso 12: +plgf_MoM                  | Sil: 0.2290
 Paso 13: +tad_1tri                  | Sil: 0.2156
 Paso 14: +imc_ini_gest              | Sil: 0.2240
 Paso 15: +edad_materna_gest         | Sil: 0.2153
 Paso 16: +aumento_peso_gest         | Sil: 0.2068
 Paso 17: +peso_rn                   | Sil: 0.1915

>>> BUSCANDO PARA K=4 (Requisito: cada grupo n >= 100) <<<
 Paso 1: +trastorno_hipertensivo    | Sil: 0.0001
 Paso 2: +talla                     | Sil: 0.6136
 Paso 3: +ratio_MoM                 | Sil: 0.5819
 Paso 4: +sflt1_MoM                 | Sil: 0.5219
 Paso 5: +apgar_5min                | Sil: 0.4692
 Paso 6: +imc_ini_gest              | Sil: 0.3817
 Paso 7: +plgf_MoM                  | Sil: 0.3277
 Paso 8: +apgar_1min                | Sil: 0.2971
 Paso 9: +aumento_peso_gest         | Sil: 0.2511

================================================================================
RESUMEN DE LAS MEJORES COMBINACIONES ENCONTRADAS
================================================================================

,k,silhouette,num_variables,variables,n_grupos
0,2,1.000000,1,[trastorno_hipertensivo],"[132, 326]"
1,2,0.974011,2,"[trastorno_hipertensivo, ratio_MoM]","[132, 326]"
2,2,0.963747,2,"[trastorno_hipertensivo, sflt1_MoM]","[326, 132]"
3,3,0.547074,1,[peso_ini_gest],"[104, 150, 204]"
4,3,0.545810,1,[tas_1tri],"[197, 123, 138]"
5,3,0.536295,1,[peso_fin_gest],"[125, 112, 221]"
6,4,0.613570,2,"[trastorno_hipertensivo, talla]","[132, 119, 106, 101]"
7,4,0.581894,3,"[trastorno_hipertensivo, talla, ratio_MoM]","[110, 132, 106, 110]"
8,4,0.548163,3,"[trastorno_hipertensivo, talla, sflt1_MoM]","[109, 132, 111, 106]"

####################################################################################################
ANÁLISIS DETALLADO: K=2 | Sil: 1.0000 | Tamaños: [132, 326]
Variables: ['trastorno_hipertensivo']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0040,G0vG1: 0.004,67.35 ± 21.25,63.00 ± 15.20
1,peso_fin_gest,U Mann-Whitney,0.0004,G0vG1: 0.000,82.00 ± 22.25,74.54 ± 16.00
2,aumento_peso_gest,U Mann-Whitney,0.1289,G0vG1: 0.129,12.00 ± 5.50,11.00 ± 5.50
3,talla,U Mann-Whitney,0.0067,G0vG1: 0.007,163.00 ± 8.25,164.00 ± 9.00
4,imc_ini_gest,U Mann-Whitney,0.0000,G0vG1: 0.000,25.70 ± 6.65,22.98 ± 5.52
5,edad_materna_gest,U Mann-Whitney,0.0133,G0vG1: 0.013,36.88 ± 6.86,35.31 ± 5.98
6,tas_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,116.04 ± 13.00,112.16 ± 16.00
7,tad_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,75.63 ± 9.03,72.00 ± 9.00
8,eg_eco_1tri,U Mann-Whitney,0.5746,G0vG1: 0.575,12.73 ± 0.70,12.80 ± 0.50
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,38.30 ± 2.80,39.80 ± 1.70
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,2920.00 ± 748.75,3200.00 ± 640.00
11,apgar_1min,U Mann-Whitney,0.0022,G0vG1: 0.002,9.00 ± 0.17,9.00 ± 0.00
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 1.00,10.00 ± 0.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,3.72 ± 6.81,1.38 ± 1.18
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.79 ± 1.79,1.24 ± 0.53
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,0.64 ± 1.02,1.29 ± 0.85

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.4315,G0vG1: 0.431,44.00 ± 5.00,45.00 ± 6.00
1,diam_telesistolico,U Mann-Whitney,0.8002,G0vG1: 0.800,30.00 ± 6.00,29.00 ± 6.00
2,dtsvi_indexado,U Mann-Whitney,0.1795,G0vG1: 0.179,16.82 ± 3.41,16.96 ± 3.57
3,septo_iv_diastole,U Mann-Whitney,0.0057,G0vG1: 0.006,8.40 ± 2.60,8.00 ± 2.00
4,pared_posterior_vi_diastole,U Mann-Whitney,0.1421,G0vG1: 0.142,7.80 ± 1.70,7.10 ± 2.05
5,diam_ai,U Mann-Whitney,0.0002,G0vG1: 0.000,36.00 ± 6.00,33.00 ± 6.00
6,ai_volumen,U Mann-Whitney,0.4734,G0vG1: 0.473,36.00 ± 17.50,35.00 ± 15.00
7,ad_volumen,U Mann-Whitney,0.1200,G0vG1: 0.120,35.00 ± 16.10,30.00 ± 15.45
8,tapse,U Mann-Whitney,0.2672,G0vG1: 0.267,24.00 ± 5.00,25.00 ± 6.00
9,e_mitral,U Mann-Whitney,0.3705,G0vG1: 0.371,73.55 ± 21.20,74.40 ± 18.10
10,e_e,U Mann-Whitney,0.4077,G0vG1: 0.408,3.82 ± 1.15,3.70 ± 1.12
11,gc_tsvi,U Mann-Whitney,0.3357,G0vG1: 0.336,5.70 ± 1.65,5.60 ± 1.50
12,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.09 ± 1.20,4.03 ± 1.11

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0000,G0vG1: 0.000,121.00 ± 18.50,110.00 ± 17.00
1,ta_diastolica,U Mann-Whitney,0.0000,G0vG1: 0.000,79.00 ± 11.00,74.00 ± 13.00
2,frec_cardiaca,Prueba T,0.5504,G0vG1: 0.529,79.54 ± 12.01,78.81 ± 11.79
3,right_1peak_systolic_velocity,U Mann-Whitney,0.9177,G0vG1: 0.918,32.60 ± 13.35,31.20 ± 11.10
4,right_2peak_systolic_velocity,U Mann-Whitney,0.1525,G0vG1: 0.152,22.00 ± 11.55,21.00 ± 9.70
5,right_pulsatility_index,U Mann-Whitney,0.0935,G0vG1: 0.094,1.69 ± 0.53,1.77 ± 0.48
6,right_psv_ratio,Prueba T,0.0002,G0vG1: 0.000,0.73 ± 0.13,0.69 ± 0.12
7,left_1peak_systolic_velocity,U Mann-Whitney,0.6982,G0vG1: 0.698,32.75 ± 14.90,33.60 ± 10.23
8,left_2peak_systolic_velocity,U Mann-Whitney,0.4818,G0vG1: 0.482,23.55 ± 10.43,22.70 ± 8.88
9,left_pulsatility_index,U Mann-Whitney,0.2588,G0vG1: 0.259,1.68 ± 0.56,1.71 ± 0.52
10,left_psv_ratio,U Mann-Whitney,0.0045,G0vG1: 0.004,0.74 ± 0.17,0.69 ± 0.15
11,right_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.55 ± 0.11,0.51 ± 0.10
12,left_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.57 ± 0.13,0.53 ± 0.11

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.3803,G0vG1: 0.380,132.00 ± 12.50,130.00 ± 14.00
1,hematocrito,U Mann-Whitney,0.5287,G0vG1: 0.529,0.39 ± 0.03,0.39 ± 0.04
2,leucocitos,U Mann-Whitney,0.8963,G0vG1: 0.896,6310.00 ± 2150.00,6300.00 ± 1920.00
3,plaquetas,U Mann-Whitney,0.2276,G0vG1: 0.228,279000.00 ± 74000.00,261000.00 ± 81750.00
4,glucosa,U Mann-Whitney,0.0988,G0vG1: 0.099,88.00 ± 10.00,86.00 ± 9.00
5,sodio,U Mann-Whitney,0.9685,G0vG1: 0.968,140.00 ± 2.50,140.00 ± 3.00
6,potasio,U Mann-Whitney,0.2004,G0vG1: 0.200,4.26 ± 0.35,4.18 ± 0.31
7,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.09 ± 1.20,4.03 ± 1.11
8,hemoglobina_glicada,U Mann-Whitney,0.0113,G0vG1: 0.011,5.40 ± 0.30,5.30 ± 0.30
9,ast,U Mann-Whitney,0.4128,G0vG1: 0.413,20.00 ± 6.00,20.00 ± 6.00
10,alt,U Mann-Whitney,0.1924,G0vG1: 0.192,16.00 ± 10.00,15.00 ± 8.00
11,bilirubina_total,U Mann-Whitney,0.1166,G0vG1: 0.117,0.56 ± 0.24,0.60 ± 0.31
12,ldh,U Mann-Whitney,0.1165,G0vG1: 0.116,167.00 ± 32.00,161.00 ± 29.50
13,vldl,U Mann-Whitney,0.0008,G0vG1: 0.001,14.27 ± 11.41,11.06 ± 6.60
14,ldl,U Mann-Whitney,0.3619,G0vG1: 0.362,104.20 ± 34.42,110.29 ± 38.60
15,hdl,U Mann-Whitney,0.0301,G0vG1: 0.030,56.50 ± 17.42,59.80 ± 18.38
16,colesterol_total,U Mann-Whitney,0.3301,G0vG1: 0.330,180.73 ± 40.05,185.18 ± 42.75
17,trigliceridos,U Mann-Whitney,0.0009,G0vG1: 0.001,70.80 ± 55.31,54.87 ± 28.32
18,prote_totales_orina,U Mann-Whitney,0.6018,G0vG1: 0.602,0.08 ± 0.05,0.08 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.5030,G0vG1: 0.503,Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%),Adherencia moderada: n=206 (63.2%) | Alta adherencia: n=19 (5.8%) | Baja adherencia: n=101 (31.0%)
1,Cat_Actividad,Chi-Square,0.3409,G0vG1: 0.325,Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%),Actividad física alta: n=293 (90.7%) | Actividad física baja: n=10 (3.1%) | Actividad física moderada: n=20 (6.2%)
2,Cat_Estres,Chi-Square,0.6488,G0vG1: 0.721,Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%),Nivel de estrés alto: n=112 (34.5%) | Nivel de estrés bajo: n=39 (12.0%) | Nivel de estrés moderado: n=165 (50.8%) | Nivel de estrés muy alto: n=9 (2.8%)
3,Cat_Memoria,Chi-Square,0.1246,G0vG1: 0.088,Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%),Deterioro leve: n=39 (12.0%) | Disfunción moderada-grave: n=29 (9.0%) | Función normal (lapsus leves): n=195 (60.2%) | Rendimiento de memoria óptimo: n=61 (18.8%)
4,Cat_SCL90R,Chi-Square,0.0284,G0vG1: 0.009,EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%),EN RIESGO: n=40 (12.4%) | Normal / Sin riesgo: n=74 (22.9%) | Patología severa: n=209 (64.7%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,1.0: n=132 (100.0%),0.0: n=326 (100.0%)
1,comp_placentaria,Chi-Square,0.0565,G0vG1: 0.056,0.0: n=105 (79.5%) | 1.0: n=27 (20.5%),0.0: n=284 (87.1%) | 1.0: n=42 (12.9%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=94 (71.2%) | 1.0: n=38 (28.8%),0.0: n=323 (99.1%) | 1.0: n=3 (0.9%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=118 (89.4%) | 1.0: n=14 (10.6%),0.0: n=292 (89.6%) | 1.0: n=34 (10.4%)
4,ant_obstetrico,Chi-Square,0.6062,G0vG1: 0.606,-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%),-1: n=237 (72.7%) | 1: n=72 (22.1%) | 3: n=14 (4.3%) | 4: n=3 (0.9%)
5,ant_medico,Chi-Square,0.1523,G0vG1: 0.152,-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%),-1: n=261 (80.1%) | 1: n=55 (16.9%) | 3: n=9 (2.8%) | 5: n=1 (0.3%)

####################################################################################################
ANÁLISIS DETALLADO: K=2 | Sil: 0.9740 | Tamaños: [132, 326]
Variables: ['trastorno_hipertensivo', 'ratio_MoM']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0040,G0vG1: 0.004,67.35 ± 21.25,63.00 ± 15.20
1,peso_fin_gest,U Mann-Whitney,0.0004,G0vG1: 0.000,82.00 ± 22.25,74.54 ± 16.00
2,aumento_peso_gest,U Mann-Whitney,0.1289,G0vG1: 0.129,12.00 ± 5.50,11.00 ± 5.50
3,talla,U Mann-Whitney,0.0067,G0vG1: 0.007,163.00 ± 8.25,164.00 ± 9.00
4,imc_ini_gest,U Mann-Whitney,0.0000,G0vG1: 0.000,25.70 ± 6.65,22.98 ± 5.52
5,edad_materna_gest,U Mann-Whitney,0.0133,G0vG1: 0.013,36.88 ± 6.86,35.31 ± 5.98
6,tas_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,116.04 ± 13.00,112.16 ± 16.00
7,tad_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,75.63 ± 9.03,72.00 ± 9.00
8,eg_eco_1tri,U Mann-Whitney,0.5746,G0vG1: 0.575,12.73 ± 0.70,12.80 ± 0.50
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,38.30 ± 2.80,39.80 ± 1.70
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,2920.00 ± 748.75,3200.00 ± 640.00
11,apgar_1min,U Mann-Whitney,0.0022,G0vG1: 0.002,9.00 ± 0.17,9.00 ± 0.00
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 1.00,10.00 ± 0.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,3.72 ± 6.81,1.38 ± 1.18
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.79 ± 1.79,1.24 ± 0.53
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,0.64 ± 1.02,1.29 ± 0.85

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.4315,G0vG1: 0.431,44.00 ± 5.00,45.00 ± 6.00
1,diam_telesistolico,U Mann-Whitney,0.8002,G0vG1: 0.800,30.00 ± 6.00,29.00 ± 6.00
2,dtsvi_indexado,U Mann-Whitney,0.1795,G0vG1: 0.179,16.82 ± 3.41,16.96 ± 3.57
3,septo_iv_diastole,U Mann-Whitney,0.0057,G0vG1: 0.006,8.40 ± 2.60,8.00 ± 2.00
4,pared_posterior_vi_diastole,U Mann-Whitney,0.1421,G0vG1: 0.142,7.80 ± 1.70,7.10 ± 2.05
5,diam_ai,U Mann-Whitney,0.0002,G0vG1: 0.000,36.00 ± 6.00,33.00 ± 6.00
6,ai_volumen,U Mann-Whitney,0.4734,G0vG1: 0.473,36.00 ± 17.50,35.00 ± 15.00
7,ad_volumen,U Mann-Whitney,0.1200,G0vG1: 0.120,35.00 ± 16.10,30.00 ± 15.45
8,tapse,U Mann-Whitney,0.2672,G0vG1: 0.267,24.00 ± 5.00,25.00 ± 6.00
9,e_mitral,U Mann-Whitney,0.3705,G0vG1: 0.371,73.55 ± 21.20,74.40 ± 18.10
10,e_e,U Mann-Whitney,0.4077,G0vG1: 0.408,3.82 ± 1.15,3.70 ± 1.12
11,gc_tsvi,U Mann-Whitney,0.3357,G0vG1: 0.336,5.70 ± 1.65,5.60 ± 1.50
12,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.09 ± 1.20,4.03 ± 1.11

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0000,G0vG1: 0.000,121.00 ± 18.50,110.00 ± 17.00
1,ta_diastolica,U Mann-Whitney,0.0000,G0vG1: 0.000,79.00 ± 11.00,74.00 ± 13.00
2,frec_cardiaca,Prueba T,0.5504,G0vG1: 0.529,79.54 ± 12.01,78.81 ± 11.79
3,right_1peak_systolic_velocity,U Mann-Whitney,0.9177,G0vG1: 0.918,32.60 ± 13.35,31.20 ± 11.10
4,right_2peak_systolic_velocity,U Mann-Whitney,0.1525,G0vG1: 0.152,22.00 ± 11.55,21.00 ± 9.70
5,right_pulsatility_index,U Mann-Whitney,0.0935,G0vG1: 0.094,1.69 ± 0.53,1.77 ± 0.48
6,right_psv_ratio,Prueba T,0.0002,G0vG1: 0.000,0.73 ± 0.13,0.69 ± 0.12
7,left_1peak_systolic_velocity,U Mann-Whitney,0.6982,G0vG1: 0.698,32.75 ± 14.90,33.60 ± 10.23
8,left_2peak_systolic_velocity,U Mann-Whitney,0.4818,G0vG1: 0.482,23.55 ± 10.43,22.70 ± 8.88
9,left_pulsatility_index,U Mann-Whitney,0.2588,G0vG1: 0.259,1.68 ± 0.56,1.71 ± 0.52
10,left_psv_ratio,U Mann-Whitney,0.0045,G0vG1: 0.004,0.74 ± 0.17,0.69 ± 0.15
11,right_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.55 ± 0.11,0.51 ± 0.10
12,left_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.57 ± 0.13,0.53 ± 0.11

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.3803,G0vG1: 0.380,132.00 ± 12.50,130.00 ± 14.00
1,hematocrito,U Mann-Whitney,0.5287,G0vG1: 0.529,0.39 ± 0.03,0.39 ± 0.04
2,leucocitos,U Mann-Whitney,0.8963,G0vG1: 0.896,6310.00 ± 2150.00,6300.00 ± 1920.00
3,plaquetas,U Mann-Whitney,0.2276,G0vG1: 0.228,279000.00 ± 74000.00,261000.00 ± 81750.00
4,glucosa,U Mann-Whitney,0.0988,G0vG1: 0.099,88.00 ± 10.00,86.00 ± 9.00
5,sodio,U Mann-Whitney,0.9685,G0vG1: 0.968,140.00 ± 2.50,140.00 ± 3.00
6,potasio,U Mann-Whitney,0.2004,G0vG1: 0.200,4.26 ± 0.35,4.18 ± 0.31
7,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.09 ± 1.20,4.03 ± 1.11
8,hemoglobina_glicada,U Mann-Whitney,0.0113,G0vG1: 0.011,5.40 ± 0.30,5.30 ± 0.30
9,ast,U Mann-Whitney,0.4128,G0vG1: 0.413,20.00 ± 6.00,20.00 ± 6.00
10,alt,U Mann-Whitney,0.1924,G0vG1: 0.192,16.00 ± 10.00,15.00 ± 8.00
11,bilirubina_total,U Mann-Whitney,0.1166,G0vG1: 0.117,0.56 ± 0.24,0.60 ± 0.31
12,ldh,U Mann-Whitney,0.1165,G0vG1: 0.116,167.00 ± 32.00,161.00 ± 29.50
13,vldl,U Mann-Whitney,0.0008,G0vG1: 0.001,14.27 ± 11.41,11.06 ± 6.60
14,ldl,U Mann-Whitney,0.3619,G0vG1: 0.362,104.20 ± 34.42,110.29 ± 38.60
15,hdl,U Mann-Whitney,0.0301,G0vG1: 0.030,56.50 ± 17.42,59.80 ± 18.38
16,colesterol_total,U Mann-Whitney,0.3301,G0vG1: 0.330,180.73 ± 40.05,185.18 ± 42.75
17,trigliceridos,U Mann-Whitney,0.0009,G0vG1: 0.001,70.80 ± 55.31,54.87 ± 28.32
18,prote_totales_orina,U Mann-Whitney,0.6018,G0vG1: 0.602,0.08 ± 0.05,0.08 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.5030,G0vG1: 0.503,Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%),Adherencia moderada: n=206 (63.2%) | Alta adherencia: n=19 (5.8%) | Baja adherencia: n=101 (31.0%)
1,Cat_Actividad,Chi-Square,0.3409,G0vG1: 0.325,Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%),Actividad física alta: n=293 (90.7%) | Actividad física baja: n=10 (3.1%) | Actividad física moderada: n=20 (6.2%)
2,Cat_Estres,Chi-Square,0.6488,G0vG1: 0.721,Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%),Nivel de estrés alto: n=112 (34.5%) | Nivel de estrés bajo: n=39 (12.0%) | Nivel de estrés moderado: n=165 (50.8%) | Nivel de estrés muy alto: n=9 (2.8%)
3,Cat_Memoria,Chi-Square,0.1246,G0vG1: 0.088,Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%),Deterioro leve: n=39 (12.0%) | Disfunción moderada-grave: n=29 (9.0%) | Función normal (lapsus leves): n=195 (60.2%) | Rendimiento de memoria óptimo: n=61 (18.8%)
4,Cat_SCL90R,Chi-Square,0.0284,G0vG1: 0.009,EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%),EN RIESGO: n=40 (12.4%) | Normal / Sin riesgo: n=74 (22.9%) | Patología severa: n=209 (64.7%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,1.0: n=132 (100.0%),0.0: n=326 (100.0%)
1,comp_placentaria,Chi-Square,0.0565,G0vG1: 0.056,0.0: n=105 (79.5%) | 1.0: n=27 (20.5%),0.0: n=284 (87.1%) | 1.0: n=42 (12.9%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=94 (71.2%) | 1.0: n=38 (28.8%),0.0: n=323 (99.1%) | 1.0: n=3 (0.9%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=118 (89.4%) | 1.0: n=14 (10.6%),0.0: n=292 (89.6%) | 1.0: n=34 (10.4%)
4,ant_obstetrico,Chi-Square,0.6062,G0vG1: 0.606,-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%),-1: n=237 (72.7%) | 1: n=72 (22.1%) | 3: n=14 (4.3%) | 4: n=3 (0.9%)
5,ant_medico,Chi-Square,0.1523,G0vG1: 0.152,-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%),-1: n=261 (80.1%) | 1: n=55 (16.9%) | 3: n=9 (2.8%) | 5: n=1 (0.3%)

####################################################################################################
ANÁLISIS DETALLADO: K=2 | Sil: 0.9637 | Tamaños: [326, 132]
Variables: ['trastorno_hipertensivo', 'sflt1_MoM']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,peso_ini_gest,U Mann-Whitney,0.0040,G0vG1: 0.004,63.00 ± 15.20,67.35 ± 21.25
1,peso_fin_gest,U Mann-Whitney,0.0004,G0vG1: 0.000,74.54 ± 16.00,82.00 ± 22.25
2,aumento_peso_gest,U Mann-Whitney,0.1289,G0vG1: 0.129,11.00 ± 5.50,12.00 ± 5.50
3,talla,U Mann-Whitney,0.0067,G0vG1: 0.007,164.00 ± 9.00,163.00 ± 8.25
4,imc_ini_gest,U Mann-Whitney,0.0000,G0vG1: 0.000,22.98 ± 5.52,25.70 ± 6.65
5,edad_materna_gest,U Mann-Whitney,0.0133,G0vG1: 0.013,35.31 ± 5.98,36.88 ± 6.86
6,tas_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,112.16 ± 16.00,116.04 ± 13.00
7,tad_1tri,U Mann-Whitney,0.0000,G0vG1: 0.000,72.00 ± 9.00,75.63 ± 9.03
8,eg_eco_1tri,U Mann-Whitney,0.5746,G0vG1: 0.575,12.80 ± 0.50,12.73 ± 0.70
9,eg_parto,U Mann-Whitney,0.0000,G0vG1: 0.000,39.80 ± 1.70,38.30 ± 2.80
10,peso_rn,U Mann-Whitney,0.0000,G0vG1: 0.000,3200.00 ± 640.00,2920.00 ± 748.75
11,apgar_1min,U Mann-Whitney,0.0022,G0vG1: 0.002,9.00 ± 0.00,9.00 ± 0.17
12,apgar_5min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 0.00,10.00 ± 1.00
13,apgar_10min,U Mann-Whitney,0.0000,G0vG1: 0.000,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.38 ± 1.18,3.72 ± 6.81
15,sflt1_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.24 ± 0.53,1.79 ± 1.79
16,plgf_MoM,U Mann-Whitney,0.0000,G0vG1: 0.000,1.29 ± 0.85,0.64 ± 1.02

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,diam_telediastolico,U Mann-Whitney,0.4315,G0vG1: 0.431,45.00 ± 6.00,44.00 ± 5.00
1,diam_telesistolico,U Mann-Whitney,0.8002,G0vG1: 0.800,29.00 ± 6.00,30.00 ± 6.00
2,dtsvi_indexado,U Mann-Whitney,0.1795,G0vG1: 0.179,16.96 ± 3.57,16.82 ± 3.41
3,septo_iv_diastole,U Mann-Whitney,0.0057,G0vG1: 0.006,8.00 ± 2.00,8.40 ± 2.60
4,pared_posterior_vi_diastole,U Mann-Whitney,0.1421,G0vG1: 0.142,7.10 ± 2.05,7.80 ± 1.70
5,diam_ai,U Mann-Whitney,0.0002,G0vG1: 0.000,33.00 ± 6.00,36.00 ± 6.00
6,ai_volumen,U Mann-Whitney,0.4734,G0vG1: 0.473,35.00 ± 15.00,36.00 ± 17.50
7,ad_volumen,U Mann-Whitney,0.1200,G0vG1: 0.120,30.00 ± 15.45,35.00 ± 16.10
8,tapse,U Mann-Whitney,0.2672,G0vG1: 0.267,25.00 ± 6.00,24.00 ± 5.00
9,e_mitral,U Mann-Whitney,0.3705,G0vG1: 0.371,74.40 ± 18.10,73.55 ± 21.20
10,e_e,U Mann-Whitney,0.4077,G0vG1: 0.408,3.70 ± 1.12,3.82 ± 1.15
11,gc_tsvi,U Mann-Whitney,0.3357,G0vG1: 0.336,5.60 ± 1.50,5.70 ± 1.65
12,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.03 ± 1.11,4.09 ± 1.20

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,ta_sistolica,U Mann-Whitney,0.0000,G0vG1: 0.000,110.00 ± 17.00,121.00 ± 18.50
1,ta_diastolica,U Mann-Whitney,0.0000,G0vG1: 0.000,74.00 ± 13.00,79.00 ± 11.00
2,frec_cardiaca,Prueba T,0.5504,G0vG1: 0.529,78.81 ± 11.79,79.54 ± 12.01
3,right_1peak_systolic_velocity,U Mann-Whitney,0.9177,G0vG1: 0.918,31.20 ± 11.10,32.60 ± 13.35
4,right_2peak_systolic_velocity,U Mann-Whitney,0.1525,G0vG1: 0.152,21.00 ± 9.70,22.00 ± 11.55
5,right_pulsatility_index,U Mann-Whitney,0.0935,G0vG1: 0.094,1.77 ± 0.48,1.69 ± 0.53
6,right_psv_ratio,Prueba T,0.0002,G0vG1: 0.000,0.69 ± 0.12,0.73 ± 0.13
7,left_1peak_systolic_velocity,U Mann-Whitney,0.6982,G0vG1: 0.698,33.60 ± 10.23,32.75 ± 14.90
8,left_2peak_systolic_velocity,U Mann-Whitney,0.4818,G0vG1: 0.482,22.70 ± 8.88,23.55 ± 10.43
9,left_pulsatility_index,U Mann-Whitney,0.2588,G0vG1: 0.259,1.71 ± 0.52,1.68 ± 0.56
10,left_psv_ratio,U Mann-Whitney,0.0045,G0vG1: 0.004,0.69 ± 0.15,0.74 ± 0.17
11,right_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.51 ± 0.10,0.55 ± 0.11
12,left_mean,U Mann-Whitney,0.0000,G0vG1: 0.000,0.53 ± 0.11,0.57 ± 0.13

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,hemoglobina,U Mann-Whitney,0.3803,G0vG1: 0.380,130.00 ± 14.00,132.00 ± 12.50
1,hematocrito,U Mann-Whitney,0.5287,G0vG1: 0.529,0.39 ± 0.04,0.39 ± 0.03
2,leucocitos,U Mann-Whitney,0.8963,G0vG1: 0.896,6300.00 ± 1920.00,6310.00 ± 2150.00
3,plaquetas,U Mann-Whitney,0.2276,G0vG1: 0.228,261000.00 ± 81750.00,279000.00 ± 74000.00
4,glucosa,U Mann-Whitney,0.0988,G0vG1: 0.099,86.00 ± 9.00,88.00 ± 10.00
5,sodio,U Mann-Whitney,0.9685,G0vG1: 0.968,140.00 ± 3.00,140.00 ± 2.50
6,potasio,U Mann-Whitney,0.2004,G0vG1: 0.200,4.18 ± 0.31,4.26 ± 0.35
7,urato_acidourico,U Mann-Whitney,0.9312,G0vG1: 0.931,4.03 ± 1.11,4.09 ± 1.20
8,hemoglobina_glicada,U Mann-Whitney,0.0113,G0vG1: 0.011,5.30 ± 0.30,5.40 ± 0.30
9,ast,U Mann-Whitney,0.4128,G0vG1: 0.413,20.00 ± 6.00,20.00 ± 6.00
10,alt,U Mann-Whitney,0.1924,G0vG1: 0.192,15.00 ± 8.00,16.00 ± 10.00
11,bilirubina_total,U Mann-Whitney,0.1166,G0vG1: 0.117,0.60 ± 0.31,0.56 ± 0.24
12,ldh,U Mann-Whitney,0.1165,G0vG1: 0.116,161.00 ± 29.50,167.00 ± 32.00
13,vldl,U Mann-Whitney,0.0008,G0vG1: 0.001,11.06 ± 6.60,14.27 ± 11.41
14,ldl,U Mann-Whitney,0.3619,G0vG1: 0.362,110.29 ± 38.60,104.20 ± 34.42
15,hdl,U Mann-Whitney,0.0301,G0vG1: 0.030,59.80 ± 18.38,56.50 ± 17.42
16,colesterol_total,U Mann-Whitney,0.3301,G0vG1: 0.330,185.18 ± 42.75,180.73 ± 40.05
17,trigliceridos,U Mann-Whitney,0.0009,G0vG1: 0.001,54.87 ± 28.32,70.80 ± 55.31
18,prote_totales_orina,U Mann-Whitney,0.6018,G0vG1: 0.602,0.08 ± 0.05,0.08 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,Cat_Dieta,Chi-Square,0.5030,G0vG1: 0.503,Adherencia moderada: n=206 (63.2%) | Alta adherencia: n=19 (5.8%) | Baja adherencia: n=101 (31.0%),Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%)
1,Cat_Actividad,Chi-Square,0.3409,G0vG1: 0.325,Actividad física alta: n=293 (90.7%) | Actividad física baja: n=10 (3.1%) | Actividad física moderada: n=20 (6.2%),Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%)
2,Cat_Estres,Chi-Square,0.6488,G0vG1: 0.721,Nivel de estrés alto: n=112 (34.5%) | Nivel de estrés bajo: n=39 (12.0%) | Nivel de estrés moderado: n=165 (50.8%) | Nivel de estrés muy alto: n=9 (2.8%),Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%)
3,Cat_Memoria,Chi-Square,0.1246,G0vG1: 0.088,Deterioro leve: n=39 (12.0%) | Disfunción moderada-grave: n=29 (9.0%) | Función normal (lapsus leves): n=195 (60.2%) | Rendimiento de memoria óptimo: n=61 (18.8%),Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%)
4,Cat_SCL90R,Chi-Square,0.0284,G0vG1: 0.009,EN RIESGO: n=40 (12.4%) | Normal / Sin riesgo: n=74 (22.9%) | Patología severa: n=209 (64.7%),EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=326 (100.0%),1.0: n=132 (100.0%)
1,comp_placentaria,Chi-Square,0.0565,G0vG1: 0.056,0.0: n=284 (87.1%) | 1.0: n=42 (12.9%),0.0: n=105 (79.5%) | 1.0: n=27 (20.5%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000,0.0: n=323 (99.1%) | 1.0: n=3 (0.9%),0.0: n=94 (71.2%) | 1.0: n=38 (28.8%)
3,comp_metabolica,Chi-Square,1.0000,G0vG1: 1.000,0.0: n=292 (89.6%) | 1.0: n=34 (10.4%),0.0: n=118 (89.4%) | 1.0: n=14 (10.6%)
4,ant_obstetrico,Chi-Square,0.6062,G0vG1: 0.606,-1: n=237 (72.7%) | 1: n=72 (22.1%) | 3: n=14 (4.3%) | 4: n=3 (0.9%),-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%)
5,ant_medico,Chi-Square,0.1523,G0vG1: 0.152,-1: n=261 (80.1%) | 1: n=55 (16.9%) | 3: n=9 (2.8%) | 5: n=1 (0.3%),-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%)

####################################################################################################
ANÁLISIS DETALLADO: K=3 | Sil: 0.5471 | Tamaños: [104, 150, 204]
Variables: ['peso_ini_gest']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,86.00 ± 10.62,53.50 ± 5.38,65.25 ± 7.53
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,96.43 ± 11.35,64.00 ± 8.59,78.00 ± 9.62
2,aumento_peso_gest,Kruskal-Wallis,0.0433,G0vG1: 0.350 | G0vG2: 0.050 | G1vG2: 0.713,10.40 ± 7.20,11.00 ± 5.28,11.98 ± 5.43
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G1vG2: 0.000,165.00 ± 9.00,161.00 ± 7.00,165.00 ± 9.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,31.91 ± 5.77,20.34 ± 2.16,24.31 ± 3.22
5,edad_materna_gest,Kruskal-Wallis,0.2492,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.272,35.88 ± 6.91,35.30 ± 6.74,35.79 ± 6.06
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.267,119.29 ± 14.50,111.86 ± 14.00,113.00 ± 13.20
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.004 | G1vG2: 0.178,75.19 ± 9.00,71.64 ± 8.75,73.00 ± 9.00
8,eg_eco_1tri,Kruskal-Wallis,0.0619,G0vG1: 0.747 | G0vG2: 0.065 | G1vG2: 0.600,12.80 ± 0.70,12.80 ± 0.50,12.71 ± 0.70
9,eg_parto,Kruskal-Wallis,0.2259,G0vG1: 0.333 | G0vG2: 1.000 | G1vG2: 0.714,39.25 ± 2.30,39.60 ± 2.55,39.30 ± 2.00
10,peso_rn,Kruskal-Wallis,0.0725,G0vG1: 0.079 | G0vG2: 1.000 | G1vG2: 0.334,3160.00 ± 822.50,3035.00 ± 790.00,3120.00 ± 670.00
11,apgar_1min,Kruskal-Wallis,0.5223,G0vG1: 0.855 | G0vG2: 1.000 | G1vG2: 1.000,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.2188,G0vG1: 0.442 | G0vG2: 1.000 | G1vG2: 0.315,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.2274,G0vG1: 0.308 | G0vG2: 1.000 | G1vG2: 0.449,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.4366,G0vG1: 0.651 | G0vG2: 1.000 | G1vG2: 1.000,1.71 ± 2.92,1.65 ± 2.10,1.70 ± 2.10
15,sflt1_MoM,Kruskal-Wallis,0.6826,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.27 ± 1.16,1.26 ± 0.76,1.27 ± 0.57
16,plgf_MoM,Kruskal-Wallis,0.0014,G0vG1: 0.001 | G0vG2: 0.052 | G1vG2: 0.280,0.87 ± 0.91,1.27 ± 1.05,1.22 ± 1.02

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,48.00 ± 7.50,42.00 ± 6.00,45.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.003 | G1vG2: 0.071,32.00 ± 7.75,29.00 ± 5.00,29.00 ± 5.00
2,dtsvi_indexado,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.118 | G1vG2: 0.001,15.80 ± 3.38,18.04 ± 3.21,16.71 ± 3.01
3,septo_iv_diastole,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.003 | G1vG2: 0.015,9.00 ± 2.25,7.80 ± 2.40,8.00 ± 2.15
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0035,G0vG1: 0.002 | G0vG2: 0.253 | G1vG2: 0.134,8.00 ± 1.90,7.00 ± 2.00,7.50 ± 2.20
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,37.00 ± 3.25,30.00 ± 6.00,34.00 ± 5.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,42.85 ± 20.88,30.20 ± 12.02,36.05 ± 15.00
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.117 | G1vG2: 0.000,37.45 ± 19.85,25.40 ± 14.30,32.25 ± 14.10
8,tapse,Kruskal-Wallis,0.5357,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.845,24.20 ± 5.50,24.30 ± 5.00,25.00 ± 6.00
9,e_mitral,Kruskal-Wallis,0.0015,G0vG1: 0.003 | G0vG2: 0.477 | G1vG2: 0.020,72.00 ± 17.90,78.10 ± 21.80,74.00 ± 16.40
10,e_e,Kruskal-Wallis,0.6785,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,3.62 ± 1.19,3.84 ± 1.09,3.72 ± 1.23
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.134,6.50 ± 1.80,5.30 ± 1.40,5.60 ± 1.20
12,urato_acidourico,Kruskal-Wallis,0.0065,G0vG1: 0.006 | G0vG2: 0.026 | G1vG2: 1.000,4.31 ± 1.35,4.01 ± 0.98,3.91 ± 1.20

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.064,123.00 ± 16.00,109.00 ± 16.00,112.00 ± 16.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.063,81.00 ± 12.50,73.00 ± 10.00,75.00 ± 13.00
2,frec_cardiaca,ANOVA,0.0155,G0vG1: 0.005 | G0vG2: 0.067 | G1vG2: 1.000,81.80 ± 11.79,77.48 ± 11.26,78.75 ± 12.11
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.4339,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.665,31.25 ± 13.05,31.65 ± 11.70,31.25 ± 10.65
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.3842,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.508,21.25 ± 11.12,21.70 ± 10.18,20.95 ± 9.68
5,right_pulsatility_index,Kruskal-Wallis,0.9308,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.80 ± 0.47,1.71 ± 0.50,1.75 ± 0.50
6,right_psv_ratio,ANOVA,0.3547,G0vG1: 0.362 | G0vG2: 1.000 | G1vG2: 0.816,0.69 ± 0.12,0.71 ± 0.12,0.70 ± 0.13
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0047,G0vG1: 0.026 | G0vG2: 0.005 | G1vG2: 1.000,36.25 ± 13.52,32.55 ± 12.50,32.25 ± 10.93
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.0651,G0vG1: 0.569 | G0vG2: 0.060 | G1vG2: 0.885,25.10 ± 11.22,23.15 ± 9.50,22.40 ± 8.12
9,left_pulsatility_index,Kruskal-Wallis,0.9130,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.68 ± 0.59,1.67 ± 0.50,1.73 ± 0.54
10,left_psv_ratio,Kruskal-Wallis,0.3346,G0vG1: 0.601 | G0vG2: 1.000 | G1vG2: 0.611,0.70 ± 0.14,0.72 ± 0.15,0.69 ± 0.16
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.001 | G1vG2: 0.012,0.55 ± 0.15,0.50 ± 0.10,0.52 ± 0.11
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.021,0.58 ± 0.13,0.51 ± 0.10,0.54 ± 0.11

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.8396,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,131.00 ± 14.25,131.00 ± 14.00,131.00 ± 15.25
1,hematocrito,Kruskal-Wallis,0.8151,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.39 ± 0.04,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.0164,G0vG1: 0.012 | G0vG2: 0.169 | G1vG2: 0.675,6640.00 ± 1795.00,6100.00 ± 2065.00,6300.00 ± 2052.50
3,plaquetas,Kruskal-Wallis,0.3588,G0vG1: 1.000 | G0vG2: 0.427 | G1vG2: 1.000,274500.00 ± 73000.00,265000.00 ± 82500.00,260000.00 ± 90500.00
4,glucosa,Kruskal-Wallis,0.1010,G0vG1: 0.092 | G0vG2: 0.448 | G1vG2: 1.000,89.00 ± 10.25,86.00 ± 9.00,86.50 ± 9.50
5,sodio,Kruskal-Wallis,0.1812,G0vG1: 0.352 | G0vG2: 0.251 | G1vG2: 1.000,139.00 ± 2.25,140.00 ± 2.00,140.00 ± 3.00
6,potasio,Kruskal-Wallis,0.7791,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,4.23 ± 0.34,4.21 ± 0.33,4.21 ± 0.30
7,urato_acidourico,Kruskal-Wallis,0.0065,G0vG1: 0.006 | G0vG2: 0.026 | G1vG2: 1.000,4.31 ± 1.35,4.01 ± 0.98,3.91 ± 1.20
8,hemoglobina_glicada,Kruskal-Wallis,0.0024,G0vG1: 0.006 | G0vG2: 0.005 | G1vG2: 1.000,5.45 ± 0.42,5.30 ± 0.30,5.30 ± 0.27
9,ast,Kruskal-Wallis,0.3456,G0vG1: 0.524 | G0vG2: 0.608 | G1vG2: 1.000,19.00 ± 5.25,20.00 ± 5.00,20.00 ± 7.00
10,alt,Kruskal-Wallis,0.4411,G0vG1: 0.649 | G0vG2: 1.000 | G1vG2: 1.000,16.00 ± 12.25,14.00 ± 6.50,15.00 ± 8.25
11,bilirubina_total,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.049 | G1vG2: 0.004,0.52 ± 0.23,0.70 ± 0.30,0.56 ± 0.28
12,ldh,Kruskal-Wallis,0.0151,G0vG1: 0.017 | G0vG2: 0.044 | G1vG2: 1.000,169.00 ± 33.25,160.00 ± 28.00,159.00 ± 30.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.012 | G1vG2: 0.001,15.96 ± 14.40,9.81 ± 5.08,12.04 ± 7.44
14,ldl,Kruskal-Wallis,0.8925,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,109.47 ± 37.19,106.47 ± 36.29,111.35 ± 41.44
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.011 | G1vG2: 0.000,52.44 ± 14.80,66.56 ± 13.75,57.66 ± 17.80
16,colesterol_total,Kruskal-Wallis,0.7103,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,182.28 ± 35.22,185.37 ± 36.76,184.02 ± 45.00
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.017 | G1vG2: 0.000,79.21 ± 71.46,50.00 ± 21.68,59.74 ± 35.85
18,prote_totales_orina,Kruskal-Wallis,0.3434,G0vG1: 1.000 | G0vG2: 0.456 | G1vG2: 1.000,0.07 ± 0.03,0.07 ± 0.06,0.08 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.0011,G0vG1: 0.007 | G0vG2: 0.001 | G1vG2: 1.000,Adherencia moderada: n=51 (49.0%) | Alta adherencia: n=2 (1.9%) | Baja adherencia: n=51 (49.0%),Adherencia moderada: n=98 (65.3%) | Alta adherencia: n=9 (6.0%) | Baja adherencia: n=43 (28.7%),Adherencia moderada: n=135 (66.2%) | Alta adherencia: n=14 (6.9%) | Baja adherencia: n=55 (27.0%)
1,Cat_Actividad,Chi-Square,0.0564,G0vG1: 0.080 | G0vG2: 0.608 | G1vG2: 0.966,Actividad física alta: n=90 (86.5%) | Actividad física baja: n=2 (1.9%) | Actividad física moderada: n=12 (11.5%),Actividad física alta: n=136 (92.5%) | Actividad física baja: n=6 (4.1%) | Actividad física moderada: n=5 (3.4%),Actividad física alta: n=186 (92.5%) | Actividad física baja: n=3 (1.5%) | Actividad física moderada: n=12 (6.0%)
2,Cat_Estres,Chi-Square,0.1507,G0vG1: 0.298 | G0vG2: 0.399 | G1vG2: 1.000,Nivel de estrés alto: n=41 (39.8%) | Nivel de estrés bajo: n=13 (12.6%) | Nivel de estrés moderado: n=42 (40.8%) | Nivel de estrés muy alto: n=7 (6.8%),Nivel de estrés alto: n=46 (30.9%) | Nivel de estrés bajo: n=17 (11.4%) | Nivel de estrés moderado: n=83 (55.7%) | Nivel de estrés muy alto: n=3 (2.0%),Nivel de estrés alto: n=74 (36.3%) | Nivel de estrés bajo: n=22 (10.8%) | Nivel de estrés moderado: n=103 (50.5%) | Nivel de estrés muy alto: n=5 (2.5%)
3,Cat_Memoria,Chi-Square,0.7890,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,Deterioro leve: n=19 (18.4%) | Disfunción moderada-grave: n=11 (10.7%) | Función normal (lapsus leves): n=55 (53.4%) | Rendimiento de memoria óptimo: n=18 (17.5%),Deterioro leve: n=20 (13.5%) | Disfunción moderada-grave: n=13 (8.8%) | Función normal (lapsus leves): n=84 (56.8%) | Rendimiento de memoria óptimo: n=31 (20.9%),Deterioro leve: n=25 (12.4%) | Disfunción moderada-grave: n=20 (9.9%) | Función normal (lapsus leves): n=121 (59.9%) | Rendimiento de memoria óptimo: n=36 (17.8%)
4,Cat_SCL90R,Chi-Square,0.3889,G0vG1: 1.000 | G0vG2: 0.260 | G1vG2: 0.709,EN RIESGO: n=11 (10.9%) | Normal / Sin riesgo: n=15 (14.9%) | Patología severa: n=75 (74.3%),EN RIESGO: n=16 (11.0%) | Normal / Sin riesgo: n=30 (20.5%) | Patología severa: n=100 (68.5%),EN RIESGO: n=30 (14.8%) | Normal / Sin riesgo: n=44 (21.7%) | Patología severa: n=129 (63.5%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0022,G0vG1: 0.006 | G0vG2: 0.016 | G1vG2: 1.000,0.0: n=60 (57.7%) | 1.0: n=44 (42.3%),0.0: n=115 (76.7%) | 1.0: n=35 (23.3%),0.0: n=151 (74.0%) | 1.0: n=53 (26.0%)
1,comp_placentaria,Chi-Square,0.2015,G0vG1: 0.612 | G0vG2: 1.000 | G1vG2: 0.479,0.0: n=91 (87.5%) | 1.0: n=13 (12.5%),0.0: n=121 (80.7%) | 1.0: n=29 (19.3%),0.0: n=177 (86.8%) | 1.0: n=27 (13.2%)
2,comp_maternaGrave,Chi-Square,0.2865,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.500,0.0: n=94 (90.4%) | 1.0: n=10 (9.6%),0.0: n=141 (94.0%) | 1.0: n=9 (6.0%),0.0: n=182 (89.2%) | 1.0: n=22 (10.8%)
3,comp_metabolica,Chi-Square,0.0082,G0vG1: 0.259 | G0vG2: 0.012 | G1vG2: 1.000,0.0: n=85 (81.7%) | 1.0: n=19 (18.3%),0.0: n=135 (90.0%) | 1.0: n=15 (10.0%),0.0: n=190 (93.1%) | 1.0: n=14 (6.9%)
4,ant_obstetrico,Chi-Square,0.3003,G0vG1: 1.000 | G0vG2: 0.191 | G1vG2: 0.703,-1: n=76 (73.1%) | 1: n=19 (18.3%) | 3: n=6 (5.8%) | 4: n=3 (2.9%),-1: n=107 (71.3%) | 1: n=35 (23.3%) | 3: n=5 (3.3%) | 4: n=3 (2.0%),-1: n=152 (74.5%) | 1: n=45 (22.1%) | 3: n=7 (3.4%)
5,ant_medico,Chi-Square,0.0106,G0vG1: 0.003 | G0vG2: 0.302 | G1vG2: 0.385,-1: n=69 (66.3%) | 1: n=28 (26.9%) | 3: n=7 (6.7%),-1: n=129 (86.0%) | 1: n=17 (11.3%) | 3: n=4 (2.7%),-1: n=157 (77.0%) | 1: n=41 (20.1%) | 3: n=5 (2.5%) | 5: n=1 (0.5%)

####################################################################################################
ANÁLISIS DETALLADO: K=3 | Sil: 0.5458 | Tamaños: [197, 123, 138]
Variables: ['tas_1tri']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0002,G0vG1: 0.007 | G0vG2: 0.431 | G1vG2: 0.000,63.28 ± 17.90,67.00 ± 22.75,62.00 ± 13.00
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.006 | G0vG2: 0.184 | G1vG2: 0.000,76.00 ± 18.00,82.50 ± 22.05,74.00 ± 16.95
2,aumento_peso_gest,Kruskal-Wallis,0.4095,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.564,11.30 ± 5.40,12.00 ± 4.95,11.00 ± 5.10
3,talla,Kruskal-Wallis,0.5036,G0vG1: 0.723 | G0vG2: 1.000 | G1vG2: 1.000,164.00 ± 8.00,163.00 ± 9.00,163.00 ± 8.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 0.544 | G1vG2: 0.000,23.49 ± 6.53,25.51 ± 8.27,22.73 ± 4.70
5,edad_materna_gest,Kruskal-Wallis,0.8320,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,35.76 ± 6.67,35.61 ± 7.05,35.31 ± 5.66
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,114.00 ± 4.51,127.00 ± 7.50,103.00 ± 8.00
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,72.94 ± 6.00,78.00 ± 10.00,68.00 ± 10.00
8,eg_eco_1tri,Kruskal-Wallis,0.5764,G0vG1: 1.000 | G0vG2: 0.938 | G1vG2: 1.000,12.72 ± 0.50,12.80 ± 0.90,12.90 ± 0.65
9,eg_parto,Kruskal-Wallis,0.0651,G0vG1: 0.495 | G0vG2: 0.908 | G1vG2: 0.046,39.60 ± 2.80,39.20 ± 2.10,39.55 ± 1.70
10,peso_rn,Kruskal-Wallis,0.2310,G0vG1: 1.000 | G0vG2: 0.655 | G1vG2: 0.299,3120.00 ± 690.00,3070.00 ± 732.50,3165.00 ± 735.00
11,apgar_1min,Kruskal-Wallis,0.0572,G0vG1: 0.166 | G0vG2: 1.000 | G1vG2: 0.078,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0060,G0vG1: 0.239 | G0vG2: 0.235 | G1vG2: 0.004,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0441,G0vG1: 0.536 | G0vG2: 0.495 | G1vG2: 0.038,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.1244,G0vG1: 1.000 | G0vG2: 0.182 | G1vG2: 0.288,1.72 ± 2.76,1.69 ± 1.78,1.65 ± 1.75
15,sflt1_MoM,Kruskal-Wallis,0.0584,G0vG1: 1.000 | G0vG2: 0.135 | G1vG2: 0.092,1.28 ± 0.78,1.29 ± 0.72,1.25 ± 0.60
16,plgf_MoM,Kruskal-Wallis,0.0427,G0vG1: 1.000 | G0vG2: 0.073 | G1vG2: 0.100,1.09 ± 1.04,1.01 ± 0.97,1.29 ± 1.01

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0575,G0vG1: 0.061 | G0vG2: 0.461 | G1vG2: 1.000,44.00 ± 6.00,46.00 ± 5.50,45.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.3054,G0vG1: 0.401 | G0vG2: 1.000 | G1vG2: 0.718,29.00 ± 5.00,30.00 ± 5.00,30.00 ± 7.00
2,dtsvi_indexado,Kruskal-Wallis,0.9341,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,16.80 ± 3.41,17.00 ± 3.68,16.80 ± 3.47
3,septo_iv_diastole,Kruskal-Wallis,0.0151,G0vG1: 0.436 | G0vG2: 0.240 | G1vG2: 0.013,8.00 ± 2.33,8.40 ± 2.35,8.00 ± 2.10
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.1104,G0vG1: 1.000 | G0vG2: 0.157 | G1vG2: 0.281,7.50 ± 1.82,7.70 ± 1.55,7.00 ± 2.10
5,diam_ai,Kruskal-Wallis,0.0034,G0vG1: 0.426 | G0vG2: 0.122 | G1vG2: 0.002,34.00 ± 7.00,35.00 ± 6.00,33.00 ± 6.00
6,ai_volumen,Kruskal-Wallis,0.1557,G0vG1: 1.000 | G0vG2: 0.248 | G1vG2: 0.327,36.00 ± 15.70,35.00 ± 14.60,33.00 ± 16.80
7,ad_volumen,Kruskal-Wallis,0.3065,G0vG1: 1.000 | G0vG2: 0.392 | G1vG2: 0.945,32.00 ± 16.00,31.00 ± 16.50,28.10 ± 14.30
8,tapse,Kruskal-Wallis,0.2089,G0vG1: 0.272 | G0vG2: 0.841 | G1vG2: 1.000,25.00 ± 5.90,24.00 ± 5.45,25.00 ± 4.95
9,e_mitral,Kruskal-Wallis,0.1872,G0vG1: 0.435 | G0vG2: 1.000 | G1vG2: 0.246,74.00 ± 17.33,71.40 ± 15.58,75.70 ± 19.60
10,e_e,Kruskal-Wallis,0.8474,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,3.78 ± 1.25,3.65 ± 1.25,3.73 ± 0.87
11,gc_tsvi,Kruskal-Wallis,0.8520,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,5.70 ± 1.60,5.60 ± 1.63,5.60 ± 1.50
12,urato_acidourico,Kruskal-Wallis,0.2467,G0vG1: 1.000 | G0vG2: 0.315 | G1vG2: 0.724,4.09 ± 1.16,4.12 ± 1.01,3.91 ± 1.18

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,113.00 ± 20.25,122.00 ± 19.00,107.50 ± 15.75
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.003 | G0vG2: 0.000 | G1vG2: 0.000,76.00 ± 13.00,78.00 ± 11.25,72.00 ± 11.00
2,frec_cardiaca,ANOVA,0.2802,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.407,79.07 ± 11.54,80.24 ± 12.13,77.88 ± 12.00
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.2373,G0vG1: 0.332 | G0vG2: 0.717 | G1vG2: 1.000,30.15 ± 14.17,31.70 ± 8.78,32.15 ± 10.83
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.1266,G0vG1: 0.318 | G0vG2: 1.000 | G1vG2: 0.149,21.05 ± 11.15,22.15 ± 9.15,20.65 ± 9.80
5,right_pulsatility_index,Kruskal-Wallis,0.0898,G0vG1: 1.000 | G0vG2: 0.086 | G1vG2: 0.846,1.69 ± 0.46,1.76 ± 0.50,1.81 ± 0.49
6,right_psv_ratio,ANOVA,0.0028,G0vG1: 1.000 | G0vG2: 0.016 | G1vG2: 0.007,0.71 ± 0.12,0.72 ± 0.12,0.67 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.3554,G0vG1: 0.676 | G0vG2: 0.704 | G1vG2: 1.000,32.60 ± 10.95,33.90 ± 12.60,33.80 ± 11.60
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.5643,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.955,22.50 ± 8.35,23.25 ± 9.73,23.20 ± 9.30
9,left_pulsatility_index,Kruskal-Wallis,0.3708,G0vG1: 1.000 | G0vG2: 0.468 | G1vG2: 1.000,1.68 ± 0.47,1.67 ± 0.57,1.73 ± 0.59
10,left_psv_ratio,Kruskal-Wallis,0.1571,G0vG1: 1.000 | G0vG2: 0.258 | G1vG2: 0.307,0.71 ± 0.16,0.72 ± 0.16,0.69 ± 0.16
11,right_mean,Kruskal-Wallis,0.0846,G0vG1: 1.000 | G0vG2: 0.131 | G1vG2: 0.201,0.53 ± 0.11,0.52 ± 0.12,0.51 ± 0.08
12,left_mean,Kruskal-Wallis,0.0027,G0vG1: 1.000 | G0vG2: 0.014 | G1vG2: 0.006,0.55 ± 0.14,0.54 ± 0.15,0.52 ± 0.09

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.0286,G0vG1: 0.055 | G0vG2: 0.125 | G1vG2: 1.000,132.00 ± 15.00,128.00 ± 14.00,129.00 ± 13.00
1,hematocrito,Kruskal-Wallis,0.0254,G0vG1: 0.056 | G0vG2: 0.092 | G1vG2: 1.000,0.40 ± 0.04,0.39 ± 0.03,0.39 ± 0.03
2,leucocitos,Kruskal-Wallis,0.3892,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.560,6310.00 ± 1822.50,6530.00 ± 2110.00,6190.00 ± 2025.00
3,plaquetas,Kruskal-Wallis,0.1018,G0vG1: 0.212 | G0vG2: 1.000 | G1vG2: 0.156,263500.00 ± 78500.00,282000.00 ± 85000.00,260500.00 ± 85750.00
4,glucosa,Kruskal-Wallis,0.2231,G0vG1: 1.000 | G0vG2: 0.859 | G1vG2: 0.244,87.00 ± 10.75,88.00 ± 11.00,85.50 ± 8.50
5,sodio,Kruskal-Wallis,0.2804,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.304,140.00 ± 3.00,139.00 ± 1.00,140.00 ± 2.00
6,potasio,Kruskal-Wallis,0.6717,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,4.21 ± 0.34,4.19 ± 0.34,4.22 ± 0.31
7,urato_acidourico,Kruskal-Wallis,0.2467,G0vG1: 1.000 | G0vG2: 0.315 | G1vG2: 0.724,4.09 ± 1.16,4.12 ± 1.01,3.91 ± 1.18
8,hemoglobina_glicada,Kruskal-Wallis,0.0063,G0vG1: 1.000 | G0vG2: 0.049 | G1vG2: 0.007,5.40 ± 0.30,5.40 ± 0.20,5.30 ± 0.30
9,ast,Kruskal-Wallis,0.4884,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.662,20.00 ± 7.00,19.00 ± 6.00,21.00 ± 5.25
10,alt,Kruskal-Wallis,0.5787,G0vG1: 0.848 | G0vG2: 1.000 | G1vG2: 1.000,15.00 ± 8.00,15.00 ± 10.00,14.50 ± 8.00
11,bilirubina_total,Kruskal-Wallis,0.0100,G0vG1: 0.299 | G0vG2: 0.189 | G1vG2: 0.012,0.57 ± 0.24,0.53 ± 0.28,0.67 ± 0.32
12,ldh,Kruskal-Wallis,0.0565,G0vG1: 0.973 | G0vG2: 0.046 | G1vG2: 0.792,168.00 ± 28.00,160.00 ± 34.00,158.00 ± 29.00
13,vldl,Kruskal-Wallis,0.0922,G0vG1: 0.649 | G0vG2: 0.931 | G1vG2: 0.070,11.59 ± 9.27,12.66 ± 9.63,11.32 ± 5.75
14,ldl,Kruskal-Wallis,0.7025,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,106.69 ± 37.23,111.63 ± 37.94,106.83 ± 38.26
15,hdl,Kruskal-Wallis,0.0074,G0vG1: 0.136 | G0vG2: 0.460 | G1vG2: 0.006,58.44 ± 19.34,55.73 ± 19.35,61.15 ± 17.80
16,colesterol_total,Kruskal-Wallis,0.9261,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,183.44 ± 44.41,183.05 ± 33.67,184.60 ± 40.83
17,trigliceridos,Kruskal-Wallis,0.1174,G0vG1: 0.674 | G0vG2: 1.000 | G1vG2: 0.099,57.53 ± 42.92,62.84 ± 46.47,56.20 ± 21.35
18,prote_totales_orina,Kruskal-Wallis,0.1248,G0vG1: 1.000 | G0vG2: 0.140 | G1vG2: 0.471,0.08 ± 0.06,0.08 ± 0.06,0.07 ± 0.04

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.5900,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.868,Adherencia moderada: n=119 (60.4%) | Alta adherencia: n=11 (5.6%) | Baja adherencia: n=67 (34.0%),Adherencia moderada: n=74 (60.2%) | Alta adherencia: n=5 (4.1%) | Baja adherencia: n=44 (35.8%),Adherencia moderada: n=91 (65.9%) | Alta adherencia: n=9 (6.5%) | Baja adherencia: n=38 (27.5%)
1,Cat_Actividad,Chi-Square,0.0846,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.176,Actividad física alta: n=178 (91.8%) | Actividad física baja: n=4 (2.1%) | Actividad física moderada: n=12 (6.2%),Actividad física alta: n=112 (91.8%) | Actividad física moderada: n=10 (8.2%),Actividad física alta: n=122 (89.7%) | Actividad física baja: n=7 (5.1%) | Actividad física moderada: n=7 (5.1%)
2,Cat_Estres,Chi-Square,0.4366,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,Nivel de estrés alto: n=67 (34.2%) | Nivel de estrés bajo: n=21 (10.7%) | Nivel de estrés moderado: n=104 (53.1%) | Nivel de estrés muy alto: n=4 (2.0%),Nivel de estrés alto: n=40 (32.5%) | Nivel de estrés bajo: n=13 (10.6%) | Nivel de estrés moderado: n=63 (51.2%) | Nivel de estrés muy alto: n=7 (5.7%),Nivel de estrés alto: n=54 (39.4%) | Nivel de estrés bajo: n=18 (13.1%) | Nivel de estrés moderado: n=61 (44.5%) | Nivel de estrés muy alto: n=4 (2.9%)
3,Cat_Memoria,Chi-Square,0.1918,G0vG1: 1.000 | G0vG2: 0.278 | G1vG2: 1.000,Deterioro leve: n=23 (11.9%) | Disfunción moderada-grave: n=16 (8.2%) | Función normal (lapsus leves): n=110 (56.7%) | Rendimiento de memoria óptimo: n=45 (23.2%),Deterioro leve: n=20 (16.4%) | Disfunción moderada-grave: n=13 (10.7%) | Función normal (lapsus leves): n=65 (53.3%) | Rendimiento de memoria óptimo: n=24 (19.7%),Deterioro leve: n=21 (15.3%) | Disfunción moderada-grave: n=15 (10.9%) | Función normal (lapsus leves): n=85 (62.0%) | Rendimiento de memoria óptimo: n=16 (11.7%)
4,Cat_SCL90R,Chi-Square,0.5402,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,EN RIESGO: n=29 (15.0%) | Normal / Sin riesgo: n=38 (19.7%) | Patología severa: n=126 (65.3%),EN RIESGO: n=10 (8.3%) | Normal / Sin riesgo: n=24 (20.0%) | Patología severa: n=86 (71.7%),EN RIESGO: n=18 (13.1%) | Normal / Sin riesgo: n=27 (19.7%) | Patología severa: n=92 (67.2%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0013,G0vG1: 1.000 | G0vG2: 0.012 | G1vG2: 0.002,0.0: n=134 (68.0%) | 1.0: n=63 (32.0%),0.0: n=78 (63.4%) | 1.0: n=45 (36.6%),0.0: n=114 (82.6%) | 1.0: n=24 (17.4%)
1,comp_placentaria,Chi-Square,0.5401,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.0: n=164 (83.2%) | 1.0: n=33 (16.8%),0.0: n=108 (87.8%) | 1.0: n=15 (12.2%),0.0: n=117 (84.8%) | 1.0: n=21 (15.2%)
2,comp_maternaGrave,Chi-Square,0.1472,G0vG1: 1.000 | G0vG2: 0.238 | G1vG2: 0.673,0.0: n=175 (88.8%) | 1.0: n=22 (11.2%),0.0: n=111 (90.2%) | 1.0: n=12 (9.8%),0.0: n=131 (94.9%) | 1.0: n=7 (5.1%)
3,comp_metabolica,Chi-Square,0.1096,G0vG1: 0.270 | G0vG2: 1.000 | G1vG2: 0.408,0.0: n=180 (91.4%) | 1.0: n=17 (8.6%),0.0: n=104 (84.6%) | 1.0: n=19 (15.4%),0.0: n=126 (91.3%) | 1.0: n=12 (8.7%)
4,ant_obstetrico,Chi-Square,0.0756,G0vG1: 0.919 | G0vG2: 0.361 | G1vG2: 0.122,-1: n=150 (76.1%) | 1: n=36 (18.3%) | 3: n=9 (4.6%) | 4: n=2 (1.0%),-1: n=84 (68.3%) | 1: n=28 (22.8%) | 3: n=7 (5.7%) | 4: n=4 (3.3%),-1: n=101 (73.2%) | 1: n=35 (25.4%) | 3: n=2 (1.4%)
5,ant_medico,Chi-Square,0.2767,G0vG1: 1.000 | G0vG2: 0.931 | G1vG2: 0.724,-1: n=149 (75.6%) | 1: n=42 (21.3%) | 3: n=6 (3.0%),-1: n=92 (74.8%) | 1: n=23 (18.7%) | 3: n=7 (5.7%) | 5: n=1 (0.8%),-1: n=114 (82.6%) | 1: n=21 (15.2%) | 3: n=3 (2.2%)

####################################################################################################
ANÁLISIS DETALLADO: K=3 | Sil: 0.5363 | Tamaños: [125, 112, 221]
Variables: ['peso_fin_gest']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,83.00 ± 14.00,52.15 ± 5.00,64.00 ± 8.10
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,95.00 ± 13.00,62.00 ± 4.73,75.27 ± 8.30
2,aumento_peso_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.446 | G1vG2: 0.000,13.00 ± 7.00,10.00 ± 3.58,12.00 ± 5.10
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.218 | G1vG2: 0.000,165.00 ± 7.00,161.00 ± 7.00,164.00 ± 9.00
4,imc_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,30.68 ± 6.46,20.11 ± 2.35,23.67 ± 3.76
5,edad_materna_gest,Kruskal-Wallis,0.6792,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,35.77 ± 6.74,35.29 ± 6.42,35.68 ± 6.30
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 1.000,119.00 ± 16.00,112.02 ± 11.25,112.24 ± 14.76
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.002 | G1vG2: 0.456,75.00 ± 10.00,71.80 ± 9.00,72.27 ± 9.00
8,eg_eco_1tri,Kruskal-Wallis,0.0312,G0vG1: 0.990 | G0vG2: 0.032 | G1vG2: 0.453,12.80 ± 0.70,12.80 ± 0.70,12.71 ± 0.70
9,eg_parto,Kruskal-Wallis,0.4331,G0vG1: 1.000 | G0vG2: 0.556 | G1vG2: 1.000,39.30 ± 2.40,39.55 ± 2.62,39.30 ± 1.90
10,peso_rn,Kruskal-Wallis,0.0005,G0vG1: 0.001 | G0vG2: 0.437 | G1vG2: 0.011,3170.00 ± 860.00,2935.00 ± 785.00,3160.00 ± 630.00
11,apgar_1min,Kruskal-Wallis,0.8416,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.6662,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.5420,G0vG1: 0.992 | G0vG2: 1.000 | G1vG2: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.4795,G0vG1: 0.699 | G0vG2: 1.000 | G1vG2: 1.000,1.70 ± 2.89,1.60 ± 1.61,1.71 ± 2.05
15,sflt1_MoM,Kruskal-Wallis,0.6336,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,1.27 ± 1.10,1.27 ± 0.70,1.27 ± 0.67
16,plgf_MoM,Kruskal-Wallis,0.0016,G0vG1: 0.002 | G0vG2: 0.065 | G1vG2: 0.154,0.89 ± 0.98,1.40 ± 0.96,1.16 ± 0.91

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,diam_telediastolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,47.00 ± 7.25,42.00 ± 6.00,45.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.001 | G1vG2: 0.007,31.00 ± 7.50,28.00 ± 4.00,29.50 ± 5.00
2,dtsvi_indexado,Kruskal-Wallis,0.0017,G0vG1: 0.003 | G0vG2: 0.219 | G1vG2: 0.035,16.05 ± 3.90,17.69 ± 3.17,16.80 ± 3.16
3,septo_iv_diastole,Kruskal-Wallis,0.0001,G0vG1: 0.000 | G0vG2: 0.015 | G1vG2: 0.065,8.85 ± 2.53,7.80 ± 2.10,8.00 ± 2.00
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.0152,G0vG1: 0.008 | G0vG2: 0.564 | G1vG2: 0.202,8.00 ± 1.70,7.00 ± 1.80,7.50 ± 2.50
5,diam_ai,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,37.00 ± 5.00,30.00 ± 5.50,33.00 ± 6.00
6,ai_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.000,42.00 ± 18.10,28.75 ± 13.00,35.00 ± 14.00
7,ad_volumen,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.115 | G1vG2: 0.000,35.50 ± 18.48,24.00 ± 12.42,32.00 ± 15.00
8,tapse,Kruskal-Wallis,0.3740,G0vG1: 0.503 | G0vG2: 1.000 | G1vG2: 1.000,25.50 ± 6.17,24.70 ± 5.60,25.00 ± 6.00
9,e_mitral,Kruskal-Wallis,0.0144,G0vG1: 0.016 | G0vG2: 0.096 | G1vG2: 0.743,72.40 ± 18.90,76.25 ± 23.62,74.95 ± 17.17
10,e_e,Kruskal-Wallis,0.8941,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,3.70 ± 1.23,3.78 ± 0.95,3.72 ± 1.24
11,gc_tsvi,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.171,6.20 ± 1.73,5.30 ± 1.55,5.50 ± 1.40
12,urato_acidourico,Kruskal-Wallis,0.0054,G0vG1: 0.009 | G0vG2: 0.018 | G1vG2: 1.000,4.27 ± 1.44,3.99 ± 1.10,3.98 ± 1.06

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.044,121.00 ± 17.00,108.00 ± 15.50,112.00 ± 16.50
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.042,80.50 ± 12.00,72.00 ± 11.00,74.00 ± 11.50
2,frec_cardiaca,ANOVA,0.2074,G0vG1: 0.102 | G0vG2: 0.077 | G1vG2: 1.000,80.61 ± 11.41,78.19 ± 11.74,78.54 ± 12.11
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.9315,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,31.00 ± 12.40,30.80 ± 12.05,31.60 ± 11.28
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.4415,G0vG1: 0.916 | G0vG2: 0.700 | G1vG2: 1.000,20.80 ± 10.70,21.60 ± 10.00,21.20 ± 9.68
5,right_pulsatility_index,Kruskal-Wallis,0.1779,G0vG1: 1.000 | G0vG2: 0.211 | G1vG2: 0.891,1.81 ± 0.52,1.72 ± 0.52,1.72 ± 0.47
6,right_psv_ratio,ANOVA,0.3338,G0vG1: 0.627 | G0vG2: 0.417 | G1vG2: 1.000,0.68 ± 0.13,0.70 ± 0.12,0.70 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.0868,G0vG1: 0.398 | G0vG2: 0.088 | G1vG2: 1.000,35.40 ± 14.10,32.60 ± 12.70,32.45 ± 10.72
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.6646,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,23.20 ± 11.00,22.50 ± 8.80,22.95 ± 8.52
9,left_pulsatility_index,Kruskal-Wallis,0.4382,G0vG1: 1.000 | G0vG2: 0.827 | G1vG2: 0.932,1.72 ± 0.59,1.74 ± 0.52,1.68 ± 0.48
10,left_psv_ratio,Kruskal-Wallis,0.4827,G0vG1: 0.822 | G0vG2: 0.924 | G1vG2: 1.000,0.69 ± 0.14,0.72 ± 0.17,0.70 ± 0.16
11,right_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.119,0.55 ± 0.14,0.50 ± 0.10,0.51 ± 0.11
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.626,0.58 ± 0.14,0.52 ± 0.11,0.53 ± 0.10

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,hemoglobina,Kruskal-Wallis,0.5160,G0vG1: 0.731 | G0vG2: 1.000 | G1vG2: 1.000,131.50 ± 13.75,130.00 ± 13.50,131.00 ± 15.00
1,hematocrito,Kruskal-Wallis,0.5911,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.39 ± 0.04,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.1041,G0vG1: 0.101 | G0vG2: 0.727 | G1vG2: 0.622,6455.00 ± 1837.50,6050.00 ± 2320.00,6365.00 ± 1977.50
3,plaquetas,Kruskal-Wallis,0.4258,G0vG1: 1.000 | G0vG2: 0.559 | G1vG2: 1.000,273500.00 ± 70000.00,264000.00 ± 78000.00,258000.00 ± 90750.00
4,glucosa,Kruskal-Wallis,0.0565,G0vG1: 0.050 | G0vG2: 0.233 | G1vG2: 1.000,89.00 ± 8.75,87.00 ± 8.50,86.00 ± 10.75
5,sodio,Kruskal-Wallis,0.3597,G0vG1: 0.404 | G0vG2: 1.000 | G1vG2: 1.000,139.00 ± 2.75,140.00 ± 2.00,140.00 ± 3.00
6,potasio,Kruskal-Wallis,0.6023,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 0.936,4.20 ± 0.41,4.17 ± 0.33,4.23 ± 0.30
7,urato_acidourico,Kruskal-Wallis,0.0054,G0vG1: 0.009 | G0vG2: 0.018 | G1vG2: 1.000,4.27 ± 1.44,3.99 ± 1.10,3.98 ± 1.06
8,hemoglobina_glicada,Kruskal-Wallis,0.0001,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 1.000,5.50 ± 0.40,5.30 ± 0.40,5.30 ± 0.20
9,ast,Kruskal-Wallis,0.7919,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,20.00 ± 8.00,21.00 ± 5.50,20.00 ± 6.00
10,alt,Kruskal-Wallis,0.1843,G0vG1: 0.721 | G0vG2: 0.203 | G1vG2: 1.000,16.00 ± 12.00,15.00 ± 7.00,14.00 ± 7.00
11,bilirubina_total,Kruskal-Wallis,0.0016,G0vG1: 0.003 | G0vG2: 0.007 | G1vG2: 1.000,0.54 ± 0.24,0.64 ± 0.32,0.60 ± 0.27
12,ldh,Kruskal-Wallis,0.0004,G0vG1: 0.001 | G0vG2: 0.002 | G1vG2: 1.000,174.00 ± 29.00,159.00 ± 25.00,159.00 ± 30.00
13,vldl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.001 | G1vG2: 0.098,15.87 ± 13.37,10.34 ± 5.44,11.59 ± 6.60
14,ldl,Kruskal-Wallis,0.8869,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,109.90 ± 37.43,107.21 ± 37.24,109.47 ± 38.23
15,hdl,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G1vG2: 0.003,51.86 ± 14.22,66.95 ± 16.06,59.60 ± 16.46
16,colesterol_total,Kruskal-Wallis,0.8214,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,183.44 ± 35.89,188.47 ± 39.28,181.69 ± 44.31
17,trigliceridos,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.002 | G1vG2: 0.055,78.77 ± 66.38,51.33 ± 23.45,57.53 ± 29.87
18,prote_totales_orina,Kruskal-Wallis,0.9299,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.08 ± 0.05,0.07 ± 0.06,0.08 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,Cat_Dieta,Chi-Square,0.0010,G0vG1: 0.003 | G0vG2: 0.005 | G1vG2: 1.000,Adherencia moderada: n=62 (49.6%) | Alta adherencia: n=4 (3.2%) | Baja adherencia: n=59 (47.2%),Adherencia moderada: n=79 (70.5%) | Alta adherencia: n=6 (5.4%) | Baja adherencia: n=27 (24.1%),Adherencia moderada: n=143 (64.7%) | Alta adherencia: n=15 (6.8%) | Baja adherencia: n=63 (28.5%)
1,Cat_Actividad,Chi-Square,0.0038,G0vG1: 0.007 | G0vG2: 0.119 | G1vG2: 0.610,Actividad física alta: n=107 (85.6%) | Actividad física baja: n=2 (1.6%) | Actividad física moderada: n=16 (12.8%),Actividad física alta: n=102 (93.6%) | Actividad física baja: n=5 (4.6%) | Actividad física moderada: n=2 (1.8%),Actividad física alta: n=203 (93.1%) | Actividad física baja: n=4 (1.8%) | Actividad física moderada: n=11 (5.0%)
2,Cat_Estres,Chi-Square,0.3843,G0vG1: 0.823 | G0vG2: 0.879 | G1vG2: 1.000,Nivel de estrés alto: n=51 (41.1%) | Nivel de estrés bajo: n=13 (10.5%) | Nivel de estrés moderado: n=54 (43.5%) | Nivel de estrés muy alto: n=6 (4.8%),Nivel de estrés alto: n=38 (34.2%) | Nivel de estrés bajo: n=12 (10.8%) | Nivel de estrés moderado: n=60 (54.1%) | Nivel de estrés muy alto: n=1 (0.9%),Nivel de estrés alto: n=72 (32.6%) | Nivel de estrés bajo: n=27 (12.2%) | Nivel de estrés moderado: n=114 (51.6%) | Nivel de estrés muy alto: n=8 (3.6%)
3,Cat_Memoria,Chi-Square,0.3102,G0vG1: 1.000 | G0vG2: 0.046 | G1vG2: 0.591,Deterioro leve: n=18 (14.8%) | Disfunción moderada-grave: n=17 (13.9%) | Función normal (lapsus leves): n=61 (50.0%) | Rendimiento de memoria óptimo: n=26 (21.3%),Deterioro leve: n=15 (13.6%) | Disfunción moderada-grave: n=12 (10.9%) | Función normal (lapsus leves): n=62 (56.4%) | Rendimiento de memoria óptimo: n=21 (19.1%),Deterioro leve: n=31 (14.0%) | Disfunción moderada-grave: n=15 (6.8%) | Función normal (lapsus leves): n=137 (62.0%) | Rendimiento de memoria óptimo: n=38 (17.2%)
4,Cat_SCL90R,Chi-Square,0.8121,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,EN RIESGO: n=16 (13.1%) | Normal / Sin riesgo: n=20 (16.4%) | Patología severa: n=86 (70.5%),EN RIESGO: n=12 (11.0%) | Normal / Sin riesgo: n=24 (22.0%) | Patología severa: n=73 (67.0%),EN RIESGO: n=29 (13.2%) | Normal / Sin riesgo: n=45 (20.5%) | Patología severa: n=145 (66.2%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2
0,trastorno_hipertensivo,Chi-Square,0.0009,G0vG1: 0.048 | G0vG2: 0.001 | G1vG2: 1.000,0.0: n=73 (58.4%) | 1.0: n=52 (41.6%),0.0: n=83 (74.1%) | 1.0: n=29 (25.9%),0.0: n=170 (76.9%) | 1.0: n=51 (23.1%)
1,comp_placentaria,Chi-Square,0.0082,G0vG1: 0.043 | G0vG2: 1.000 | G1vG2: 0.037,0.0: n=111 (88.8%) | 1.0: n=14 (11.2%),0.0: n=85 (75.9%) | 1.0: n=27 (24.1%),0.0: n=193 (87.3%) | 1.0: n=28 (12.7%)
2,comp_maternaGrave,Chi-Square,0.5329,G0vG1: 1.000 | G0vG2: 1.000 | G1vG2: 1.000,0.0: n=111 (88.8%) | 1.0: n=14 (11.2%),0.0: n=104 (92.9%) | 1.0: n=8 (7.1%),0.0: n=202 (91.4%) | 1.0: n=19 (8.6%)
3,comp_metabolica,Chi-Square,0.1293,G0vG1: 0.610 | G0vG2: 0.263 | G1vG2: 1.000,0.0: n=106 (84.8%) | 1.0: n=19 (15.2%),0.0: n=102 (91.1%) | 1.0: n=10 (8.9%),0.0: n=202 (91.4%) | 1.0: n=19 (8.6%)
4,ant_obstetrico,Chi-Square,0.2690,G0vG1: 1.000 | G0vG2: 0.418 | G1vG2: 0.146,-1: n=90 (72.0%) | 1: n=27 (21.6%) | 3: n=5 (4.0%) | 4: n=3 (2.4%),-1: n=83 (74.1%) | 1: n=24 (21.4%) | 3: n=2 (1.8%) | 4: n=3 (2.7%),-1: n=162 (73.3%) | 1: n=48 (21.7%) | 3: n=11 (5.0%)
5,ant_medico,Chi-Square,0.0040,G0vG1: 0.002 | G0vG2: 0.076 | G1vG2: 0.735,-1: n=83 (66.4%) | 1: n=33 (26.4%) | 3: n=9 (7.2%),-1: n=98 (87.5%) | 1: n=12 (10.7%) | 3: n=2 (1.8%),-1: n=174 (78.7%) | 1: n=41 (18.6%) | 3: n=5 (2.3%) | 5: n=1 (0.5%)

####################################################################################################
ANÁLISIS DETALLADO: K=4 | Sil: 0.6136 | Tamaños: [132, 119, 106, 101]
Variables: ['trastorno_hipertensivo', 'talla']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.086 | G1vG2: 0.000 | G1vG3: 0.022 | G2vG3: 0.020,67.35 ± 21.25,66.50 ± 15.05,57.45 ± 16.45,63.00 ± 14.00
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.004 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 0.112,82.00 ± 22.25,80.00 ± 17.00,70.15 ± 15.75,74.07 ± 15.81
2,aumento_peso_gest,Kruskal-Wallis,0.0164,G0vG1: 1.000 | G0vG2: 0.648 | G0vG3: 0.072 | G1vG2: 0.375 | G1vG3: 0.046 | G2vG3: 1.000,12.00 ± 5.50,12.00 ± 6.00,11.00 ± 4.45,10.00 ± 4.70
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.576 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.000,163.00 ± 8.25,170.00 ± 4.00,159.00 ± 3.00,164.00 ± 2.00
4,imc_ini_gest,Kruskal-Wallis,0.0001,G0vG1: 0.001 | G0vG2: 0.003 | G0vG3: 0.004 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,25.70 ± 6.65,22.74 ± 4.37,23.27 ± 6.09,23.59 ± 5.54
5,edad_materna_gest,Kruskal-Wallis,0.0701,G0vG1: 0.588 | G0vG2: 0.076 | G0vG3: 0.451 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,36.88 ± 6.86,35.47 ± 5.97,35.25 ± 4.87,35.17 ± 7.69
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.025 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 0.274 | G2vG3: 1.000,116.04 ± 13.00,113.00 ± 14.00,112.20 ± 15.50,111.00 ± 17.00
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.020 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.631 | G1vG3: 0.103 | G2vG3: 1.000,75.63 ± 9.03,73.00 ± 10.50,71.64 ± 8.75,71.24 ± 10.00
8,eg_eco_1tri,Kruskal-Wallis,0.5676,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.73 ± 0.70,12.80 ± 0.50,12.72 ± 0.60,12.80 ± 0.70
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.134 | G1vG3: 0.977 | G2vG3: 1.000,38.30 ± 2.80,40.00 ± 1.80,39.30 ± 2.08,39.60 ± 1.70
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.016 | G0vG3: 0.000 | G1vG2: 0.021 | G1vG3: 1.000 | G2vG3: 0.400,2920.00 ± 748.75,3330.00 ± 635.00,3120.00 ± 787.50,3200.00 ± 740.00
11,apgar_1min,Kruskal-Wallis,0.0235,G0vG1: 0.103 | G0vG2: 0.172 | G0vG3: 0.176 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,9.00 ± 0.17,9.00 ± 0.00,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.015 | G0vG2: 0.003 | G0vG3: 0.001 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,10.00 ± 1.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.060 | G0vG2: 0.011 | G0vG3: 0.001 | G1vG2: 1.000 | G1vG3: 0.532 | G2vG3: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.72 ± 6.81,1.33 ± 1.10,1.34 ± 1.27,1.41 ± 1.16
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.229 | G1vG3: 1.000 | G2vG3: 1.000,1.79 ± 1.79,1.21 ± 0.41,1.26 ± 0.62,1.25 ± 0.54
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.64 ± 1.02,1.34 ± 0.85,1.32 ± 0.93,1.26 ± 0.85

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0011,G0vG1: 0.034 | G0vG2: 0.802 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.447 | G2vG3: 0.336,44.00 ± 5.00,46.50 ± 5.75,44.00 ± 6.00,45.00 ± 7.25
1,diam_telesistolico,Kruskal-Wallis,0.0529,G0vG1: 0.494 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.033 | G1vG3: 0.422 | G2vG3: 1.000,30.00 ± 6.00,31.00 ± 5.00,29.00 ± 4.25,29.00 ± 6.00
2,dtsvi_indexado,Kruskal-Wallis,0.1152,G0vG1: 1.000 | G0vG2: 0.208 | G0vG3: 1.000 | G1vG2: 0.204 | G1vG3: 1.000 | G2vG3: 1.000,16.82 ± 3.41,16.61 ± 2.72,17.49 ± 3.43,16.78 ± 3.83
3,septo_iv_diastole,Kruskal-Wallis,0.0380,G0vG1: 0.501 | G0vG2: 0.036 | G0vG3: 0.185 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,8.40 ± 2.60,8.00 ± 2.47,8.00 ± 2.00,8.00 ± 2.00
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.4251,G0vG1: 1.000 | G0vG2: 0.659 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,7.80 ± 1.70,7.10 ± 1.72,7.00 ± 2.20,7.20 ± 2.20
5,diam_ai,Kruskal-Wallis,0.0010,G0vG1: 0.141 | G0vG2: 0.001 | G0vG3: 0.009 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,36.00 ± 6.00,33.00 ± 7.00,33.50 ± 7.00,32.50 ± 6.00
6,ai_volumen,Kruskal-Wallis,0.1315,G0vG1: 1.000 | G0vG2: 0.926 | G0vG3: 1.000 | G1vG2: 0.192 | G1vG3: 0.494 | G2vG3: 1.000,36.00 ± 17.50,37.20 ± 16.07,33.90 ± 15.60,33.70 ± 14.93
7,ad_volumen,Kruskal-Wallis,0.0006,G0vG1: 1.000 | G0vG2: 0.002 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 1.000 | G2vG3: 0.015,35.00 ± 16.10,33.00 ± 15.55,27.00 ± 9.50,32.00 ± 16.15
8,tapse,Kruskal-Wallis,0.0000,G0vG1: 0.003 | G0vG2: 0.329 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.102 | G2vG3: 0.027,24.00 ± 5.00,27.00 ± 5.00,23.50 ± 5.00,25.50 ± 6.00
9,e_mitral,Kruskal-Wallis,0.6354,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,73.55 ± 21.20,74.70 ± 15.20,74.70 ± 21.70,74.00 ± 18.00
10,e_e,Kruskal-Wallis,0.3189,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.752,3.82 ± 1.15,3.65 ± 1.01,3.95 ± 1.08,3.60 ± 1.19
11,gc_tsvi,Kruskal-Wallis,0.0425,G0vG1: 1.000 | G0vG2: 0.121 | G0vG3: 1.000 | G1vG2: 0.115 | G1vG3: 1.000 | G2vG3: 0.124,5.70 ± 1.65,5.70 ± 1.20,5.40 ± 1.35,5.80 ± 1.70
12,urato_acidourico,Kruskal-Wallis,0.5571,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.839 | G2vG3: 1.000,4.09 ± 1.20,4.11 ± 1.11,4.16 ± 1.23,3.92 ± 0.97

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,121.00 ± 18.50,109.00 ± 14.50,113.00 ± 19.00,112.00 ± 16.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,79.00 ± 11.00,75.00 ± 12.00,74.00 ± 12.00,73.00 ± 12.00
2,frec_cardiaca,ANOVA,0.8007,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,79.54 ± 12.01,78.43 ± 13.04,78.49 ± 9.52,79.61 ± 12.46
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.3767,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.435,32.60 ± 13.35,31.20 ± 11.10,30.10 ± 10.00,32.00 ± 11.70
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.1444,G0vG1: 0.262 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.419 | G2vG3: 1.000,22.00 ± 11.55,20.70 ± 8.90,20.70 ± 8.70,22.20 ± 11.50
5,right_pulsatility_index,Kruskal-Wallis,0.0564,G0vG1: 0.137 | G0vG2: 0.694 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.186 | G2vG3: 0.867,1.69 ± 0.53,1.83 ± 0.42,1.81 ± 0.45,1.68 ± 0.55
6,right_psv_ratio,ANOVA,0.0002,G0vG1: 0.000 | G0vG2: 0.618 | G0vG3: 0.127 | G1vG2: 0.008 | G1vG3: 0.355 | G2vG3: 1.000,0.73 ± 0.13,0.66 ± 0.12,0.70 ± 0.11,0.69 ± 0.13
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.1718,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.167,32.75 ± 14.90,33.80 ± 7.45,32.40 ± 12.80,34.55 ± 11.85
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.2361,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.351 | G2vG3: 0.715,23.55 ± 10.43,22.50 ± 6.25,22.50 ± 11.70,24.10 ± 9.67
9,left_pulsatility_index,Kruskal-Wallis,0.4799,G0vG1: 0.917 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.68 ± 0.56,1.73 ± 0.51,1.72 ± 0.48,1.70 ± 0.59
10,left_psv_ratio,Kruskal-Wallis,0.0008,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 0.519 | G1vG2: 0.016 | G1vG3: 0.447 | G2vG3: 1.000,0.74 ± 0.17,0.67 ± 0.11,0.72 ± 0.14,0.70 ± 0.18
11,right_mean,Kruskal-Wallis,0.0002,G0vG1: 0.119 | G0vG2: 0.001 | G0vG3: 0.001 | G1vG2: 0.904 | G1vG3: 0.770 | G2vG3: 1.000,0.55 ± 0.11,0.52 ± 0.11,0.50 ± 0.10,0.50 ± 0.09
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.001 | G0vG2: 0.001 | G0vG3: 0.001 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.57 ± 0.13,0.53 ± 0.09,0.53 ± 0.11,0.52 ± 0.12

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.5274,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,132.00 ± 12.50,127.00 ± 14.50,131.00 ± 14.00,132.00 ± 15.00
1,hematocrito,Kruskal-Wallis,0.9023,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.03,0.39 ± 0.04,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.8791,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6310.00 ± 2150.00,6220.00 ± 1735.00,6460.00 ± 2360.00,6160.00 ± 1780.00
3,plaquetas,Kruskal-Wallis,0.0845,G0vG1: 0.475 | G0vG2: 1.000 | G0vG3: 0.785 | G1vG2: 0.195 | G1vG3: 1.000 | G2vG3: 0.465,279000.00 ± 74000.00,248000.00 ± 76000.00,278000.00 ± 68000.00,257000.00 ± 82500.00
4,glucosa,Kruskal-Wallis,0.2364,G0vG1: 1.000 | G0vG2: 0.338 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,88.00 ± 10.00,86.00 ± 8.00,86.00 ± 9.00,86.50 ± 8.00
5,sodio,Kruskal-Wallis,0.9925,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,140.00 ± 2.50,140.00 ± 3.00,140.00 ± 2.00,140.00 ± 3.00
6,potasio,Kruskal-Wallis,0.4750,G0vG1: 1.000 | G0vG2: 0.819 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.26 ± 0.35,4.20 ± 0.31,4.17 ± 0.27,4.19 ± 0.39
7,urato_acidourico,Kruskal-Wallis,0.5571,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.839 | G2vG3: 1.000,4.09 ± 1.20,4.11 ± 1.11,4.16 ± 1.23,3.92 ± 0.97
8,hemoglobina_glicada,Kruskal-Wallis,0.0675,G0vG1: 0.618 | G0vG2: 0.195 | G0vG3: 0.133 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,5.40 ± 0.30,5.30 ± 0.30,5.30 ± 0.40,5.30 ± 0.30
9,ast,Kruskal-Wallis,0.6001,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,20.00 ± 6.00,20.00 ± 6.00,20.00 ± 6.00,20.00 ± 6.00
10,alt,Kruskal-Wallis,0.5367,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.906 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,16.00 ± 10.00,15.00 ± 7.00,14.00 ± 9.00,14.00 ± 7.00
11,bilirubina_total,Kruskal-Wallis,0.3896,G0vG1: 1.000 | G0vG2: 0.588 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.56 ± 0.24,0.61 ± 0.27,0.62 ± 0.31,0.57 ± 0.30
12,ldh,Kruskal-Wallis,0.0698,G0vG1: 0.068 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.295 | G1vG3: 0.627 | G2vG3: 1.000,167.00 ± 32.00,157.50 ± 27.50,163.00 ± 25.00,162.00 ± 35.00
13,vldl,Kruskal-Wallis,0.0063,G0vG1: 0.008 | G0vG2: 0.268 | G0vG3: 0.031 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,14.27 ± 11.41,11.06 ± 5.17,12.13 ± 6.60,10.70 ± 6.82
14,ldl,Kruskal-Wallis,0.0422,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.099 | G1vG2: 1.000 | G1vG3: 0.073 | G2vG3: 0.196,104.20 ± 34.42,106.29 ± 36.03,105.76 ± 37.01,116.34 ± 41.80
15,hdl,Kruskal-Wallis,0.1674,G0vG1: 0.225 | G0vG2: 1.000 | G0vG3: 0.490 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,56.50 ± 17.42,60.76 ± 18.19,59.21 ± 19.35,60.56 ± 16.83
16,colesterol_total,Kruskal-Wallis,0.0841,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.179 | G1vG2: 1.000 | G1vG3: 0.115 | G2vG3: 0.481,180.73 ± 40.05,180.34 ± 36.19,183.05 ± 41.02,192.72 ± 38.41
17,trigliceridos,Kruskal-Wallis,0.0099,G0vG1: 0.013 | G0vG2: 0.218 | G0vG3: 0.043 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,70.80 ± 55.31,54.87 ± 21.68,60.18 ± 30.98,53.10 ± 28.54
18,prote_totales_orina,Kruskal-Wallis,0.3234,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.571 | G2vG3: 0.915,0.08 ± 0.05,0.07 ± 0.04,0.07 ± 0.05,0.09 ± 0.06

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.6391,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%),Adherencia moderada: n=78 (65.5%) | Alta adherencia: n=9 (7.6%) | Baja adherencia: n=32 (26.9%),Adherencia moderada: n=68 (64.2%) | Alta adherencia: n=4 (3.8%) | Baja adherencia: n=34 (32.1%),Adherencia moderada: n=60 (59.4%) | Alta adherencia: n=6 (5.9%) | Baja adherencia: n=35 (34.7%)
1,Cat_Actividad,Chi-Square,0.3632,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.702 | G1vG2: 0.698 | G1vG3: 1.000 | G2vG3: 1.000,Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%),Actividad física alta: n=106 (89.1%) | Actividad física baja: n=2 (1.7%) | Actividad física moderada: n=11 (9.2%),Actividad física alta: n=94 (91.3%) | Actividad física baja: n=4 (3.9%) | Actividad física moderada: n=5 (4.9%),Actividad física alta: n=93 (92.1%) | Actividad física baja: n=4 (4.0%) | Actividad física moderada: n=4 (4.0%)
2,Cat_Estres,Chi-Square,0.6822,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%),Nivel de estrés alto: n=36 (30.5%) | Nivel de estrés bajo: n=17 (14.4%) | Nivel de estrés moderado: n=61 (51.7%) | Nivel de estrés muy alto: n=4 (3.4%),Nivel de estrés alto: n=38 (35.8%) | Nivel de estrés bajo: n=8 (7.5%) | Nivel de estrés moderado: n=58 (54.7%) | Nivel de estrés muy alto: n=2 (1.9%),Nivel de estrés alto: n=38 (37.6%) | Nivel de estrés bajo: n=14 (13.9%) | Nivel de estrés moderado: n=46 (45.5%) | Nivel de estrés muy alto: n=3 (3.0%)
3,Cat_Memoria,Chi-Square,0.5260,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%),Deterioro leve: n=16 (13.6%) | Disfunción moderada-grave: n=9 (7.6%) | Función normal (lapsus leves): n=71 (60.2%) | Rendimiento de memoria óptimo: n=22 (18.6%),Deterioro leve: n=11 (10.5%) | Disfunción moderada-grave: n=12 (11.4%) | Función normal (lapsus leves): n=65 (61.9%) | Rendimiento de memoria óptimo: n=17 (16.2%),Deterioro leve: n=12 (11.9%) | Disfunción moderada-grave: n=8 (7.9%) | Función normal (lapsus leves): n=59 (58.4%) | Rendimiento de memoria óptimo: n=22 (21.8%)
4,Cat_SCL90R,Chi-Square,0.0244,G0vG1: 0.009 | G0vG2: 1.000 | G0vG3: 0.123 | G1vG2: 0.152 | G1vG3: 1.000 | G2vG3: 0.571,EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%),EN RIESGO: n=13 (10.9%) | Normal / Sin riesgo: n=34 (28.6%) | Patología severa: n=72 (60.5%),EN RIESGO: n=17 (16.5%) | Normal / Sin riesgo: n=16 (15.5%) | Patología severa: n=70 (68.0%),EN RIESGO: n=10 (9.9%) | Normal / Sin riesgo: n=24 (23.8%) | Patología severa: n=67 (66.3%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.0: n=132 (100.0%),0.0: n=119 (100.0%),0.0: n=106 (100.0%),0.0: n=101 (100.0%)
1,comp_placentaria,Chi-Square,0.1045,G0vG1: 0.129 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=105 (79.5%) | 1.0: n=27 (20.5%),0.0: n=108 (90.8%) | 1.0: n=11 (9.2%),0.0: n=90 (84.9%) | 1.0: n=16 (15.1%),0.0: n=86 (85.1%) | 1.0: n=15 (14.9%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=94 (71.2%) | 1.0: n=38 (28.8%),0.0: n=117 (98.3%) | 1.0: n=2 (1.7%),0.0: n=106 (100.0%),0.0: n=100 (99.0%) | 1.0: n=1 (1.0%)
3,comp_metabolica,Chi-Square,0.0637,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.170 | G1vG3: 1.000 | G2vG3: 0.474,0.0: n=118 (89.4%) | 1.0: n=14 (10.6%),0.0: n=111 (93.3%) | 1.0: n=8 (6.7%),0.0: n=88 (83.0%) | 1.0: n=18 (17.0%),0.0: n=93 (92.1%) | 1.0: n=8 (7.9%)
4,ant_obstetrico,Chi-Square,0.7367,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%),-1: n=93 (78.2%) | 1: n=21 (17.6%) | 3: n=5 (4.2%),-1: n=74 (69.8%) | 1: n=25 (23.6%) | 3: n=5 (4.7%) | 4: n=2 (1.9%),-1: n=70 (69.3%) | 1: n=26 (25.7%) | 3: n=4 (4.0%) | 4: n=1 (1.0%)
5,ant_medico,Chi-Square,0.3336,G0vG1: 1.000 | G0vG2: 0.528 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%),-1: n=93 (78.2%) | 1: n=22 (18.5%) | 3: n=4 (3.4%),-1: n=86 (81.1%) | 1: n=18 (17.0%) | 3: n=1 (0.9%) | 5: n=1 (0.9%),-1: n=82 (81.2%) | 1: n=15 (14.9%) | 3: n=4 (4.0%)

####################################################################################################
ANÁLISIS DETALLADO: K=4 | Sil: 0.5819 | Tamaños: [110, 132, 106, 110]
Variables: ['trastorno_hipertensivo', 'talla', 'ratio_MoM']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.020 | G1vG2: 0.000 | G1vG3: 0.109 | G2vG3: 0.010,66.75 ± 15.45,67.35 ± 21.25,57.45 ± 16.45,62.85 ± 14.00
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 0.001 | G1vG2: 0.000 | G1vG3: 0.006 | G2vG3: 0.062,80.00 ± 17.00,82.00 ± 22.25,70.15 ± 15.75,74.14 ± 15.73
2,aumento_peso_gest,Kruskal-Wallis,0.0230,G0vG1: 1.000 | G0vG2: 0.380 | G0vG3: 0.064 | G1vG2: 0.648 | G1vG3: 0.106 | G2vG3: 1.000,12.00 ± 6.00,12.00 ± 5.50,11.00 ± 4.45,10.05 ± 4.70
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.194 | G2vG3: 0.000,170.00 ± 4.00,163.00 ± 8.25,159.00 ± 3.00,164.00 ± 2.00
4,imc_ini_gest,Kruskal-Wallis,0.0001,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.003 | G1vG3: 0.003 | G2vG3: 1.000,22.79 ± 4.46,25.70 ± 6.65,23.27 ± 6.09,23.43 ± 5.52
5,edad_materna_gest,Kruskal-Wallis,0.0762,G0vG1: 0.370 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.076 | G1vG3: 0.716 | G2vG3: 1.000,35.33 ± 5.73,36.88 ± 6.86,35.25 ± 4.87,35.48 ± 7.55
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.027 | G0vG2: 1.000 | G0vG3: 0.477 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,113.00 ± 14.00,116.04 ± 13.00,112.20 ± 15.50,111.14 ± 16.50
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.042 | G0vG2: 0.470 | G0vG3: 0.065 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,73.00 ± 10.00,75.63 ± 9.03,71.64 ± 8.75,71.57 ± 10.00
8,eg_eco_1tri,Kruskal-Wallis,0.5729,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.80 ± 0.50,12.73 ± 0.70,12.72 ± 0.60,12.80 ± 0.70
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.063 | G0vG3: 0.293 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,40.20 ± 1.75,38.30 ± 2.80,39.30 ± 2.08,39.60 ± 1.80
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.005 | G0vG3: 0.309 | G1vG2: 0.016 | G1vG3: 0.000 | G2vG3: 0.827,3350.00 ± 630.00,2920.00 ± 748.75,3120.00 ± 787.50,3155.00 ± 691.25
11,apgar_1min,Kruskal-Wallis,0.0220,G0vG1: 0.088 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.172 | G1vG3: 0.197 | G2vG3: 1.000,9.00 ± 0.00,9.00 ± 0.17,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.020 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.003 | G1vG3: 0.000 | G2vG3: 1.000,10.00 ± 0.00,10.00 ± 1.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0001,G0vG1: 0.056 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.011 | G1vG3: 0.001 | G2vG3: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,1.21 ± 1.12,3.72 ± 6.81,1.34 ± 1.27,1.53 ± 1.16
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.092 | G0vG3: 0.395 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,1.17 ± 0.42,1.79 ± 1.79,1.26 ± 0.62,1.25 ± 0.56
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,1.36 ± 0.81,0.64 ± 1.02,1.32 ± 0.93,1.24 ± 0.89

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0007,G0vG1: 0.023 | G0vG2: 0.000 | G0vG3: 0.260 | G1vG2: 0.802 | G1vG3: 1.000 | G2vG3: 0.342,47.00 ± 6.00,44.00 ± 5.00,44.00 ± 6.00,45.00 ± 7.00
1,diam_telesistolico,Kruskal-Wallis,0.0503,G0vG1: 0.445 | G0vG2: 0.031 | G0vG3: 0.388 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,31.00 ± 5.00,30.00 ± 6.00,29.00 ± 4.25,29.00 ± 6.00
2,dtsvi_indexado,Kruskal-Wallis,0.1257,G0vG1: 1.000 | G0vG2: 0.242 | G0vG3: 1.000 | G1vG2: 0.208 | G1vG3: 1.000 | G2vG3: 1.000,16.58 ± 2.73,16.82 ± 3.41,17.49 ± 3.43,16.75 ± 3.71
3,septo_iv_diastole,Kruskal-Wallis,0.0407,G0vG1: 0.428 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.036 | G1vG3: 0.229 | G2vG3: 1.000,8.00 ± 2.40,8.40 ± 2.60,8.00 ± 2.00,8.00 ± 2.00
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.4289,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.659 | G1vG3: 1.000 | G2vG3: 1.000,7.10 ± 1.50,7.80 ± 1.70,7.00 ± 2.20,7.10 ± 2.20
5,diam_ai,Kruskal-Wallis,0.0009,G0vG1: 0.197 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.007 | G2vG3: 1.000,33.00 ± 5.50,36.00 ± 6.00,33.50 ± 7.00,32.00 ± 6.00
6,ai_volumen,Kruskal-Wallis,0.1537,G0vG1: 1.000 | G0vG2: 0.219 | G0vG3: 0.597 | G1vG2: 0.926 | G1vG3: 1.000 | G2vG3: 1.000,37.00 ± 15.75,36.00 ± 17.50,33.90 ± 15.60,33.80 ± 15.00
7,ad_volumen,Kruskal-Wallis,0.0004,G0vG1: 1.000 | G0vG2: 0.000 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 1.000 | G2vG3: 0.038,33.30 ± 15.20,35.00 ± 16.10,27.00 ± 9.50,30.50 ± 17.15
8,tapse,Kruskal-Wallis,0.0000,G0vG1: 0.004 | G0vG2: 0.000 | G0vG3: 0.157 | G1vG2: 0.329 | G1vG3: 1.000 | G2vG3: 0.015,27.00 ± 5.00,24.00 ± 5.00,23.50 ± 5.00,26.00 ± 6.00
9,e_mitral,Kruskal-Wallis,0.6378,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,74.70 ± 15.20,73.55 ± 21.20,74.70 ± 21.70,74.00 ± 18.00
10,e_e,Kruskal-Wallis,0.3304,G0vG1: 1.000 | G0vG2: 0.911 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.914,3.64 ± 1.04,3.82 ± 1.15,3.95 ± 1.08,3.63 ± 1.18
11,gc_tsvi,Kruskal-Wallis,0.0395,G0vG1: 1.000 | G0vG2: 0.060 | G0vG3: 1.000 | G1vG2: 0.121 | G1vG3: 1.000 | G2vG3: 0.224,5.85 ± 1.20,5.70 ± 1.65,5.40 ± 1.35,5.65 ± 1.60
12,urato_acidourico,Kruskal-Wallis,0.8253,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.09 ± 1.02,4.09 ± 1.20,4.16 ± 1.23,3.98 ± 0.96

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,109.00 ± 13.75,121.00 ± 18.50,113.00 ± 19.00,111.50 ± 17.25
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,74.00 ± 12.00,79.00 ± 11.00,74.00 ± 12.00,73.50 ± 13.00
2,frec_cardiaca,ANOVA,0.8474,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,78.50 ± 13.33,79.54 ± 12.01,78.49 ± 9.52,79.44 ± 12.19
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5150,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.961,31.30 ± 10.45,32.60 ± 13.35,30.10 ± 10.00,31.75 ± 11.30
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.2894,G0vG1: 0.450 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,20.95 ± 9.27,22.00 ± 11.55,20.70 ± 8.70,21.20 ± 10.85
5,right_pulsatility_index,Kruskal-Wallis,0.0945,G0vG1: 0.173 | G0vG2: 1.000 | G0vG3: 0.387 | G1vG2: 0.694 | G1vG3: 1.000 | G2vG3: 1.000,1.83 ± 0.42,1.69 ± 0.53,1.81 ± 0.45,1.69 ± 0.56
6,right_psv_ratio,ANOVA,0.0001,G0vG1: 0.000 | G0vG2: 0.006 | G0vG3: 0.236 | G1vG2: 0.618 | G1vG3: 0.092 | G2vG3: 1.000,0.66 ± 0.12,0.73 ± 0.13,0.70 ± 0.11,0.69 ± 0.12
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.2342,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.266,33.80 ± 7.05,32.75 ± 14.90,32.40 ± 12.80,34.50 ± 11.90
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.3441,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.703 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.961,22.50 ± 6.00,23.55 ± 10.43,22.50 ± 11.70,24.00 ± 10.40
9,left_pulsatility_index,Kruskal-Wallis,0.6460,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.73 ± 0.51,1.68 ± 0.56,1.72 ± 0.48,1.70 ± 0.55
10,left_psv_ratio,Kruskal-Wallis,0.0007,G0vG1: 0.001 | G0vG2: 0.014 | G0vG3: 0.368 | G1vG2: 1.000 | G1vG3: 0.395 | G2vG3: 1.000,0.67 ± 0.12,0.74 ± 0.17,0.72 ± 0.14,0.70 ± 0.16
11,right_mean,Kruskal-Wallis,0.0003,G0vG1: 0.107 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.001 | G2vG3: 1.000,0.52 ± 0.10,0.55 ± 0.11,0.50 ± 0.10,0.51 ± 0.09
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 0.001 | G2vG3: 1.000,0.53 ± 0.09,0.57 ± 0.13,0.53 ± 0.11,0.53 ± 0.11

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.3395,G0vG1: 0.712 | G0vG2: 1.000 | G0vG3: 0.801 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,127.00 ± 14.00,132.00 ± 12.50,131.00 ± 14.00,132.00 ± 15.25
1,hematocrito,Kruskal-Wallis,0.6701,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.04,0.39 ± 0.03,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.8810,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6220.00 ± 1735.00,6310.00 ± 2150.00,6460.00 ± 2360.00,6160.00 ± 1780.00
3,plaquetas,Kruskal-Wallis,0.0864,G0vG1: 0.667 | G0vG2: 0.265 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.557 | G2vG3: 0.340,249000.00 ± 75000.00,279000.00 ± 74000.00,278000.00 ± 68000.00,255000.00 ± 87000.00
4,glucosa,Kruskal-Wallis,0.2564,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.338 | G1vG3: 1.000 | G2vG3: 1.000,87.00 ± 8.00,88.00 ± 10.00,86.00 ± 9.00,86.00 ± 8.25
5,sodio,Kruskal-Wallis,0.9834,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,140.00 ± 3.00,140.00 ± 2.50,140.00 ± 2.00,140.00 ± 3.00
6,potasio,Kruskal-Wallis,0.5237,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.819 | G1vG3: 1.000 | G2vG3: 1.000,4.18 ± 0.33,4.26 ± 0.35,4.17 ± 0.27,4.22 ± 0.38
7,urato_acidourico,Kruskal-Wallis,0.8253,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,4.09 ± 1.02,4.09 ± 1.20,4.16 ± 1.23,3.98 ± 0.96
8,hemoglobina_glicada,Kruskal-Wallis,0.0482,G0vG1: 0.994 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.195 | G1vG3: 0.074 | G2vG3: 1.000,5.30 ± 0.30,5.40 ± 0.30,5.30 ± 0.40,5.30 ± 0.35
9,ast,Kruskal-Wallis,0.5968,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,20.00 ± 6.00,20.00 ± 6.00,20.00 ± 6.00,20.00 ± 5.25
10,alt,Kruskal-Wallis,0.5548,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.992 | G2vG3: 1.000,15.00 ± 8.00,16.00 ± 10.00,14.00 ± 9.00,14.50 ± 7.00
11,bilirubina_total,Kruskal-Wallis,0.3433,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.588 | G1vG3: 1.000 | G2vG3: 1.000,0.60 ± 0.28,0.56 ± 0.24,0.62 ± 0.31,0.58 ± 0.35
12,ldh,Kruskal-Wallis,0.0269,G0vG1: 0.027 | G0vG2: 0.143 | G0vG3: 0.176 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,156.50 ± 28.50,167.00 ± 32.00,163.00 ± 25.00,162.50 ± 35.00
13,vldl,Kruskal-Wallis,0.0061,G0vG1: 0.009 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.268 | G1vG3: 0.027 | G2vG3: 1.000,11.06 ± 4.63,14.27 ± 11.41,12.13 ± 6.60,10.79 ± 6.95
14,ldl,Kruskal-Wallis,0.0575,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.106 | G1vG2: 1.000 | G1vG3: 0.141 | G2vG3: 0.242,106.29 ± 36.12,104.20 ± 34.42,105.76 ± 37.01,115.49 ± 42.94
15,hdl,Kruskal-Wallis,0.1600,G0vG1: 0.500 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.214 | G2vG3: 1.000,59.99 ± 16.06,56.50 ± 17.42,59.21 ± 19.35,60.76 ± 15.66
16,colesterol_total,Kruskal-Wallis,0.0501,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.063 | G1vG2: 1.000 | G1vG3: 0.134 | G2vG3: 0.386,179.57 ± 37.54,180.73 ± 40.05,183.05 ± 41.02,192.72 ± 36.86
17,trigliceridos,Kruskal-Wallis,0.0098,G0vG1: 0.014 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.218 | G1vG3: 0.037 | G2vG3: 1.000,54.87 ± 19.03,70.80 ± 55.31,60.18 ± 30.98,53.54 ± 28.76
18,prote_totales_orina,Kruskal-Wallis,0.4994,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.07 ± 0.05,0.08 ± 0.05,0.07 ± 0.05,0.09 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.6467,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Adherencia moderada: n=71 (64.5%) | Alta adherencia: n=9 (8.2%) | Baja adherencia: n=30 (27.3%),Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%),Adherencia moderada: n=68 (64.2%) | Alta adherencia: n=4 (3.8%) | Baja adherencia: n=34 (32.1%),Adherencia moderada: n=67 (60.9%) | Alta adherencia: n=6 (5.5%) | Baja adherencia: n=37 (33.6%)
1,Cat_Actividad,Chi-Square,0.2933,G0vG1: 1.000 | G0vG2: 0.702 | G0vG3: 0.788 | G1vG2: 1.000 | G1vG3: 0.646 | G2vG3: 1.000,Actividad física alta: n=97 (88.2%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=11 (10.0%),Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%),Actividad física alta: n=94 (91.3%) | Actividad física baja: n=4 (3.9%) | Actividad física moderada: n=5 (4.9%),Actividad física alta: n=102 (92.7%) | Actividad física baja: n=4 (3.6%) | Actividad física moderada: n=4 (3.6%)
2,Cat_Estres,Chi-Square,0.4874,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Nivel de estrés alto: n=31 (28.4%) | Nivel de estrés bajo: n=15 (13.8%) | Nivel de estrés moderado: n=59 (54.1%) | Nivel de estrés muy alto: n=4 (3.7%),Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%),Nivel de estrés alto: n=38 (35.8%) | Nivel de estrés bajo: n=8 (7.5%) | Nivel de estrés moderado: n=58 (54.7%) | Nivel de estrés muy alto: n=2 (1.9%),Nivel de estrés alto: n=43 (39.1%) | Nivel de estrés bajo: n=16 (14.5%) | Nivel de estrés moderado: n=48 (43.6%) | Nivel de estrés muy alto: n=3 (2.7%)
3,Cat_Memoria,Chi-Square,0.4915,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.592 | G2vG3: 1.000,Deterioro leve: n=16 (14.7%) | Disfunción moderada-grave: n=9 (8.3%) | Función normal (lapsus leves): n=63 (57.8%) | Rendimiento de memoria óptimo: n=21 (19.3%),Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%),Deterioro leve: n=11 (10.5%) | Disfunción moderada-grave: n=12 (11.4%) | Función normal (lapsus leves): n=65 (61.9%) | Rendimiento de memoria óptimo: n=17 (16.2%),Deterioro leve: n=12 (10.9%) | Disfunción moderada-grave: n=8 (7.3%) | Función normal (lapsus leves): n=67 (60.9%) | Rendimiento de memoria óptimo: n=23 (20.9%)
4,Cat_SCL90R,Chi-Square,0.0239,G0vG1: 0.014 | G0vG2: 0.234 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.064 | G2vG3: 0.327,EN RIESGO: n=13 (11.8%) | Normal / Sin riesgo: n=31 (28.2%) | Patología severa: n=66 (60.0%),EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%),EN RIESGO: n=17 (16.5%) | Normal / Sin riesgo: n=16 (15.5%) | Patología severa: n=70 (68.0%),EN RIESGO: n=10 (9.1%) | Normal / Sin riesgo: n=27 (24.5%) | Patología severa: n=73 (66.4%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,0.0: n=110 (100.0%),1.0: n=132 (100.0%),0.0: n=106 (100.0%),0.0: n=110 (100.0%)
1,comp_placentaria,Chi-Square,0.0082,G0vG1: 0.008 | G0vG2: 0.206 | G0vG3: 0.040 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.0: n=104 (94.5%) | 1.0: n=6 (5.5%),0.0: n=105 (79.5%) | 1.0: n=27 (20.5%),0.0: n=90 (84.9%) | 1.0: n=16 (15.1%),0.0: n=90 (81.8%) | 1.0: n=20 (18.2%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,0.0: n=108 (98.2%) | 1.0: n=2 (1.8%),0.0: n=94 (71.2%) | 1.0: n=38 (28.8%),0.0: n=106 (100.0%),0.0: n=109 (99.1%) | 1.0: n=1 (0.9%)
3,comp_metabolica,Chi-Square,0.0661,G0vG1: 1.000 | G0vG2: 0.284 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.284,0.0: n=102 (92.7%) | 1.0: n=8 (7.3%),0.0: n=118 (89.4%) | 1.0: n=14 (10.6%),0.0: n=88 (83.0%) | 1.0: n=18 (17.0%),0.0: n=102 (92.7%) | 1.0: n=8 (7.3%)
4,ant_obstetrico,Chi-Square,0.8742,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=84 (76.4%) | 1: n=21 (19.1%) | 3: n=5 (4.5%),-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%),-1: n=74 (69.8%) | 1: n=25 (23.6%) | 3: n=5 (4.7%) | 4: n=2 (1.9%),-1: n=79 (71.8%) | 1: n=26 (23.6%) | 3: n=4 (3.6%) | 4: n=1 (0.9%)
5,ant_medico,Chi-Square,0.3153,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.528 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=87 (79.1%) | 1: n=20 (18.2%) | 3: n=3 (2.7%),-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%),-1: n=86 (81.1%) | 1: n=18 (17.0%) | 3: n=1 (0.9%) | 5: n=1 (0.9%),-1: n=88 (80.0%) | 1: n=17 (15.5%) | 3: n=5 (4.5%)

####################################################################################################
ANÁLISIS DETALLADO: K=4 | Sil: 0.5482 | Tamaños: [109, 132, 111, 106]
Variables: ['trastorno_hipertensivo', 'talla', 'sflt1_MoM']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,peso_ini_gest,Kruskal-Wallis,0.0000,G0vG1: 0.072 | G0vG2: 0.008 | G0vG3: 0.015 | G1vG2: 1.000 | G1vG3: 0.000 | G2vG3: 0.000,62.10 ± 14.00,67.35 ± 21.25,67.00 ± 15.90,57.45 ± 16.45
1,peso_fin_gest,Kruskal-Wallis,0.0000,G0vG1: 0.005 | G0vG2: 0.001 | G0vG3: 0.072 | G1vG2: 1.000 | G1vG3: 0.000 | G2vG3: 0.000,74.07 ± 15.81,82.00 ± 22.25,80.00 ± 17.50,70.15 ± 15.75
2,aumento_peso_gest,Kruskal-Wallis,0.0625,G0vG1: 0.196 | G0vG2: 0.217 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.648 | G2vG3: 0.637,10.80 ± 4.70,12.00 ± 5.50,12.00 ± 6.00,11.00 ± 4.45
3,talla,Kruskal-Wallis,0.0000,G0vG1: 0.220 | G0vG2: 0.000 | G0vG3: 0.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.000,164.00 ± 2.00,163.00 ± 8.25,170.00 ± 4.00,159.00 ± 3.00
4,imc_ini_gest,Kruskal-Wallis,0.0001,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.002 | G1vG3: 0.003 | G2vG3: 1.000,23.34 ± 5.54,25.70 ± 6.65,22.84 ± 4.71,23.27 ± 6.09
5,edad_materna_gest,Kruskal-Wallis,0.0766,G0vG1: 0.620 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.435 | G1vG3: 0.076 | G2vG3: 1.000,35.47 ± 7.55,36.88 ± 6.86,35.35 ± 5.91,35.25 ± 4.87
6,tas_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.299 | G0vG3: 1.000 | G1vG2: 0.039 | G1vG3: 0.000 | G2vG3: 1.000,111.07 ± 16.00,116.04 ± 13.00,113.00 ± 14.00,112.20 ± 15.50
7,tad_1tri,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.049 | G0vG3: 1.000 | G1vG2: 0.047 | G1vG3: 0.000 | G2vG3: 0.428,71.24 ± 10.00,75.63 ± 9.03,73.00 ± 10.00,71.64 ± 8.75
8,eg_eco_1tri,Kruskal-Wallis,0.6277,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,12.80 ± 0.70,12.73 ± 0.70,12.80 ± 0.50,12.72 ± 0.60
9,eg_parto,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.561 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.090,39.60 ± 1.80,38.30 ± 2.80,40.20 ± 1.80,39.30 ± 2.08
10,peso_rn,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.820 | G0vG3: 0.563 | G1vG2: 0.000 | G1vG3: 0.016 | G2vG3: 0.010,3200.00 ± 750.00,2920.00 ± 748.75,3330.00 ± 615.00,3120.00 ± 787.50
11,apgar_1min,Kruskal-Wallis,0.0223,G0vG1: 0.175 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.101 | G1vG3: 0.172 | G2vG3: 1.000,9.00 ± 0.00,9.00 ± 0.17,9.00 ± 0.00,9.00 ± 0.00
12,apgar_5min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.693 | G0vG3: 1.000 | G1vG2: 0.032 | G1vG3: 0.003 | G2vG3: 1.000,10.00 ± 0.00,10.00 ± 1.00,10.00 ± 0.00,10.00 ± 0.00
13,apgar_10min,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.321 | G0vG3: 1.000 | G1vG2: 0.103 | G1vG3: 0.011 | G2vG3: 1.000,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00,10.00 ± 0.00
14,ratio_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,1.57 ± 1.17,3.72 ± 6.81,1.22 ± 1.11,1.34 ± 1.27
15,sflt1_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 0.161 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 0.059,1.26 ± 0.56,1.79 ± 1.79,1.15 ± 0.44,1.26 ± 0.62
16,plgf_MoM,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,1.26 ± 0.87,0.64 ± 1.02,1.35 ± 0.82,1.32 ± 0.93

ECOCARDIOGRAFÍA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,diam_telediastolico,Kruskal-Wallis,0.0005,G0vG1: 1.000 | G0vG2: 0.162 | G0vG3: 0.435 | G1vG2: 0.016 | G1vG3: 0.802 | G2vG3: 0.000,45.00 ± 7.00,44.00 ± 5.00,47.00 ± 5.00,44.00 ± 6.00
1,diam_telesistolico,Kruskal-Wallis,0.0458,G0vG1: 1.000 | G0vG2: 0.335 | G0vG3: 1.000 | G1vG2: 0.427 | G1vG3: 1.000 | G2vG3: 0.029,29.00 ± 6.00,30.00 ± 6.00,31.00 ± 5.25,29.00 ± 4.25
2,dtsvi_indexado,Kruskal-Wallis,0.1018,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.208 | G2vG3: 0.178,16.83 ± 3.75,16.82 ± 3.41,16.49 ± 2.72,17.49 ± 3.43
3,septo_iv_diastole,Kruskal-Wallis,0.0410,G0vG1: 0.248 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.398 | G1vG3: 0.036 | G2vG3: 1.000,8.00 ± 2.00,8.40 ± 2.60,8.00 ± 2.40,8.00 ± 2.00
4,pared_posterior_vi_diastole,Kruskal-Wallis,0.4358,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.659 | G2vG3: 1.000,7.10 ± 2.20,7.80 ± 1.70,7.10 ± 1.50,7.00 ± 2.20
5,diam_ai,Kruskal-Wallis,0.0008,G0vG1: 0.005 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.234 | G1vG3: 0.001 | G2vG3: 1.000,32.00 ± 6.00,36.00 ± 6.00,33.00 ± 6.25,33.50 ± 7.00
6,ai_volumen,Kruskal-Wallis,0.1486,G0vG1: 1.000 | G0vG2: 0.571 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.926 | G2vG3: 0.212,33.80 ± 15.00,36.00 ± 17.50,37.00 ± 16.00,33.90 ± 15.60
7,ad_volumen,Kruskal-Wallis,0.0004,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.042 | G1vG2: 1.000 | G1vG3: 0.002 | G2vG3: 0.000,30.50 ± 17.35,35.00 ± 16.10,33.30 ± 15.20,27.00 ± 9.50
8,tapse,Kruskal-Wallis,0.0000,G0vG1: 1.000 | G0vG2: 0.099 | G0vG3: 0.019 | G1vG2: 0.003 | G1vG3: 0.329 | G2vG3: 0.000,25.00 ± 6.00,24.00 ± 5.00,27.00 ± 5.00,23.50 ± 5.00
9,e_mitral,Kruskal-Wallis,0.6163,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,73.70 ± 18.00,73.55 ± 21.20,75.00 ± 15.20,74.70 ± 21.70
10,e_e,Kruskal-Wallis,0.2978,G0vG1: 0.959 | G0vG2: 1.000 | G0vG3: 0.592 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.60 ± 1.09,3.82 ± 1.15,3.65 ± 1.02,3.95 ± 1.08
11,gc_tsvi,Kruskal-Wallis,0.0410,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.192 | G1vG2: 1.000 | G1vG3: 0.121 | G2vG3: 0.071,5.70 ± 1.60,5.70 ± 1.65,5.80 ± 1.20,5.40 ± 1.35
12,urato_acidourico,Kruskal-Wallis,0.8377,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.98 ± 0.98,4.09 ± 1.20,4.08 ± 1.01,4.16 ± 1.23

TA, CARÓTIDA Y OFTÁLMICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,ta_sistolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,111.00 ± 17.00,121.00 ± 18.50,109.00 ± 14.00,113.00 ± 19.00
1,ta_diastolica,Kruskal-Wallis,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,73.00 ± 12.50,79.00 ± 11.00,74.00 ± 12.00,74.00 ± 12.00
2,frec_cardiaca,Welch ANOVA,0.8581,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,79.36 ± 12.18,79.54 ± 12.01,78.59 ± 13.34,78.49 ± 9.52
3,right_1peak_systolic_velocity,Kruskal-Wallis,0.5112,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.934 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,31.90 ± 11.70,32.60 ± 13.35,31.30 ± 10.40,30.10 ± 10.00
4,right_2peak_systolic_velocity,Kruskal-Wallis,0.2681,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.417 | G1vG3: 1.000 | G2vG3: 1.000,21.20 ± 10.60,22.00 ± 11.55,20.90 ± 9.15,20.70 ± 8.70
5,right_pulsatility_index,Kruskal-Wallis,0.0822,G0vG1: 1.000 | G0vG2: 0.320 | G0vG3: 1.000 | G1vG2: 0.156 | G1vG3: 0.694 | G2vG3: 1.000,1.68 ± 0.57,1.69 ± 0.53,1.83 ± 0.41,1.81 ± 0.45
6,right_psv_ratio,ANOVA,0.0001,G0vG1: 0.105 | G0vG2: 0.212 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.618 | G2vG3: 0.005,0.69 ± 0.13,0.73 ± 0.13,0.66 ± 0.12,0.70 ± 0.11
7,left_1peak_systolic_velocity,Kruskal-Wallis,0.2248,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.249 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,34.55 ± 11.60,32.75 ± 14.90,33.80 ± 7.25,32.40 ± 12.80
8,left_2peak_systolic_velocity,Kruskal-Wallis,0.3498,G0vG1: 1.000 | G0vG2: 0.721 | G0vG3: 0.967 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,23.80 ± 9.43,23.55 ± 10.43,22.50 ± 6.15,22.50 ± 11.70
9,left_pulsatility_index,Kruskal-Wallis,0.6832,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,1.71 ± 0.56,1.68 ± 0.56,1.73 ± 0.50,1.72 ± 0.48
10,left_psv_ratio,Kruskal-Wallis,0.0009,G0vG1: 0.382 | G0vG2: 0.488 | G0vG3: 1.000 | G1vG2: 0.001 | G1vG3: 1.000 | G2vG3: 0.016,0.70 ± 0.17,0.74 ± 0.17,0.67 ± 0.12,0.72 ± 0.14
11,right_mean,Kruskal-Wallis,0.0003,G0vG1: 0.001 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.099 | G1vG3: 0.001 | G2vG3: 1.000,0.51 ± 0.09,0.55 ± 0.11,0.52 ± 0.11,0.50 ± 0.10
12,left_mean,Kruskal-Wallis,0.0000,G0vG1: 0.002 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.001 | G2vG3: 1.000,0.53 ± 0.11,0.57 ± 0.13,0.53 ± 0.10,0.53 ± 0.11

ANALÍTICA

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,hemoglobina,Kruskal-Wallis,0.4180,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.861 | G1vG3: 1.000 | G2vG3: 1.000,132.00 ± 15.00,132.00 ± 12.50,127.00 ± 14.00,131.00 ± 14.00
1,hematocrito,Kruskal-Wallis,0.7137,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.39 ± 0.04,0.39 ± 0.03,0.39 ± 0.04,0.39 ± 0.04
2,leucocitos,Kruskal-Wallis,0.8544,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,6160.00 ± 1810.00,6310.00 ± 2150.00,6215.00 ± 1750.00,6460.00 ± 2360.00
3,plaquetas,Kruskal-Wallis,0.0858,G0vG1: 0.700 | G0vG2: 1.000 | G0vG3: 0.414 | G1vG2: 0.529 | G1vG3: 1.000 | G2vG3: 0.215,257000.00 ± 84000.00,279000.00 ± 74000.00,248500.00 ± 75000.00,278000.00 ± 68000.00
4,glucosa,Kruskal-Wallis,0.2539,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.338 | G2vG3: 1.000,86.00 ± 8.50,88.00 ± 10.00,86.50 ± 8.00,86.00 ± 9.00
5,sodio,Kruskal-Wallis,0.9865,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,140.00 ± 3.00,140.00 ± 2.50,140.00 ± 3.00,140.00 ± 2.00
6,potasio,Kruskal-Wallis,0.5196,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.819 | G2vG3: 1.000,4.22 ± 0.38,4.26 ± 0.35,4.19 ± 0.32,4.17 ± 0.27
7,urato_acidourico,Kruskal-Wallis,0.8377,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,3.98 ± 0.98,4.09 ± 1.20,4.08 ± 1.01,4.16 ± 1.23
8,hemoglobina_glicada,Kruskal-Wallis,0.0592,G0vG1: 0.100 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.794 | G1vG3: 0.195 | G2vG3: 1.000,5.30 ± 0.30,5.40 ± 0.30,5.30 ± 0.30,5.30 ± 0.40
9,ast,Kruskal-Wallis,0.6055,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,20.00 ± 5.50,20.00 ± 6.00,20.00 ± 6.00,20.00 ± 6.00
10,alt,Kruskal-Wallis,0.5473,G0vG1: 0.941 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,14.00 ± 7.00,16.00 ± 10.00,15.50 ± 7.50,14.00 ± 9.00
11,bilirubina_total,Kruskal-Wallis,0.3738,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.588 | G2vG3: 1.000,0.58 ± 0.34,0.56 ± 0.24,0.60 ± 0.28,0.62 ± 0.31
12,ldh,Kruskal-Wallis,0.0227,G0vG1: 1.000 | G0vG2: 0.145 | G0vG3: 1.000 | G1vG2: 0.024 | G1vG3: 1.000 | G2vG3: 0.126,163.00 ± 35.00,167.00 ± 32.00,156.00 ± 28.00,163.00 ± 25.00
13,vldl,Kruskal-Wallis,0.0061,G0vG1: 0.030 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.008 | G1vG3: 0.268 | G2vG3: 1.000,10.70 ± 6.95,14.27 ± 11.41,10.97 ± 4.54,12.13 ± 6.60
14,ldl,Kruskal-Wallis,0.0574,G0vG1: 0.139 | G0vG2: 0.103 | G0vG3: 0.242 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,115.99 ± 43.06,104.20 ± 34.42,106.75 ± 35.70,105.76 ± 37.01
15,hdl,Kruskal-Wallis,0.1695,G0vG1: 0.287 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.382 | G1vG3: 1.000 | G2vG3: 1.000,60.76 ± 15.86,56.50 ± 17.42,60.38 ± 16.26,59.21 ± 19.35
16,colesterol_total,Kruskal-Wallis,0.0660,G0vG1: 0.157 | G0vG2: 0.089 | G0vG3: 0.438 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,191.95 ± 37.73,180.73 ± 40.05,179.95 ± 36.86,183.05 ± 41.02
17,trigliceridos,Kruskal-Wallis,0.0097,G0vG1: 0.041 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.013 | G1vG3: 0.218 | G2vG3: 1.000,53.10 ± 29.20,70.80 ± 55.31,54.43 ± 18.36,60.18 ± 30.98
18,prote_totales_orina,Kruskal-Wallis,0.4221,G0vG1: 1.000 | G0vG2: 0.884 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,0.09 ± 0.05,0.08 ± 0.05,0.07 ± 0.05,0.07 ± 0.05

SCORES CATEGÓRICOS

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,Cat_Dieta,Chi-Square,0.6325,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Adherencia moderada: n=66 (60.6%) | Alta adherencia: n=6 (5.5%) | Baja adherencia: n=37 (33.9%),Adherencia moderada: n=78 (59.1%) | Alta adherencia: n=6 (4.5%) | Baja adherencia: n=48 (36.4%),Adherencia moderada: n=72 (64.9%) | Alta adherencia: n=9 (8.1%) | Baja adherencia: n=30 (27.0%),Adherencia moderada: n=68 (64.2%) | Alta adherencia: n=4 (3.8%) | Baja adherencia: n=34 (32.1%)
1,Cat_Actividad,Chi-Square,0.3022,G0vG1: 0.654 | G0vG2: 0.828 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.703,Actividad física alta: n=101 (92.7%) | Actividad física baja: n=4 (3.7%) | Actividad física moderada: n=4 (3.7%),Actividad física alta: n=119 (92.2%) | Actividad física baja: n=1 (0.8%) | Actividad física moderada: n=9 (7.0%),Actividad física alta: n=98 (88.3%) | Actividad física baja: n=2 (1.8%) | Actividad física moderada: n=11 (9.9%),Actividad física alta: n=94 (91.3%) | Actividad física baja: n=4 (3.9%) | Actividad física moderada: n=5 (4.9%)
2,Cat_Estres,Chi-Square,0.5817,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Nivel de estrés alto: n=42 (38.5%) | Nivel de estrés bajo: n=15 (13.8%) | Nivel de estrés moderado: n=49 (45.0%) | Nivel de estrés muy alto: n=3 (2.8%),Nivel de estrés alto: n=49 (37.4%) | Nivel de estrés bajo: n=13 (9.9%) | Nivel de estrés moderado: n=63 (48.1%) | Nivel de estrés muy alto: n=6 (4.6%),Nivel de estrés alto: n=32 (29.1%) | Nivel de estrés bajo: n=16 (14.5%) | Nivel de estrés moderado: n=58 (52.7%) | Nivel de estrés muy alto: n=4 (3.6%),Nivel de estrés alto: n=38 (35.8%) | Nivel de estrés bajo: n=8 (7.5%) | Nivel de estrés moderado: n=58 (54.7%) | Nivel de estrés muy alto: n=2 (1.9%)
3,Cat_Memoria,Chi-Square,0.4740,G0vG1: 0.651 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,Deterioro leve: n=12 (11.0%) | Disfunción moderada-grave: n=8 (7.3%) | Función normal (lapsus leves): n=65 (59.6%) | Rendimiento de memoria óptimo: n=24 (22.0%),Deterioro leve: n=25 (19.4%) | Disfunción moderada-grave: n=15 (11.6%) | Función normal (lapsus leves): n=65 (50.4%) | Rendimiento de memoria óptimo: n=24 (18.6%),Deterioro leve: n=16 (14.5%) | Disfunción moderada-grave: n=9 (8.2%) | Función normal (lapsus leves): n=65 (59.1%) | Rendimiento de memoria óptimo: n=20 (18.2%),Deterioro leve: n=11 (10.5%) | Disfunción moderada-grave: n=12 (11.4%) | Función normal (lapsus leves): n=65 (61.9%) | Rendimiento de memoria óptimo: n=17 (16.2%)
4,Cat_SCL90R,Chi-Square,0.0257,G0vG1: 0.061 | G0vG2: 1.000 | G0vG3: 0.328 | G1vG2: 0.016 | G1vG3: 1.000 | G2vG3: 0.244,EN RIESGO: n=10 (9.2%) | Normal / Sin riesgo: n=27 (24.8%) | Patología severa: n=72 (66.1%),EN RIESGO: n=17 (13.4%) | Normal / Sin riesgo: n=15 (11.8%) | Patología severa: n=95 (74.8%),EN RIESGO: n=13 (11.7%) | Normal / Sin riesgo: n=31 (27.9%) | Patología severa: n=67 (60.4%),EN RIESGO: n=17 (16.5%) | Normal / Sin riesgo: n=16 (15.5%) | Patología severa: n=70 (68.0%)

ANTECEDENTES

,Variable,Test,p-valor (Total),p-valor (dos a dos),G0,G1,G2,G3
0,trastorno_hipertensivo,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,0.0: n=109 (100.0%),1.0: n=132 (100.0%),0.0: n=111 (100.0%),0.0: n=106 (100.0%)
1,comp_placentaria,Chi-Square,0.0362,G0vG1: 1.000 | G0vG2: 0.322 | G0vG3: 1.000 | G1vG2: 0.036 | G1vG3: 1.000 | G2vG3: 0.612,0.0: n=91 (83.5%) | 1.0: n=18 (16.5%),0.0: n=105 (79.5%) | 1.0: n=27 (20.5%),0.0: n=103 (92.8%) | 1.0: n=8 (7.2%),0.0: n=90 (84.9%) | 1.0: n=16 (15.1%)
2,comp_maternaGrave,Chi-Square,0.0000,G0vG1: 0.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 0.000 | G1vG3: 0.000 | G2vG3: 1.000,0.0: n=108 (99.1%) | 1.0: n=1 (0.9%),0.0: n=94 (71.2%) | 1.0: n=38 (28.8%),0.0: n=109 (98.2%) | 1.0: n=2 (1.8%),0.0: n=106 (100.0%)
3,comp_metabolica,Chi-Square,0.0661,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 0.301 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 0.268,0.0: n=101 (92.7%) | 1.0: n=8 (7.3%),0.0: n=118 (89.4%) | 1.0: n=14 (10.6%),0.0: n=103 (92.8%) | 1.0: n=8 (7.2%),0.0: n=88 (83.0%) | 1.0: n=18 (17.0%)
4,ant_obstetrico,Chi-Square,0.8041,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 1.000 | G2vG3: 1.000,-1: n=77 (70.6%) | 1: n=27 (24.8%) | 3: n=4 (3.7%) | 4: n=1 (0.9%),-1: n=98 (74.2%) | 1: n=27 (20.5%) | 3: n=4 (3.0%) | 4: n=3 (2.3%),-1: n=86 (77.5%) | 1: n=20 (18.0%) | 3: n=5 (4.5%),-1: n=74 (69.8%) | 1: n=25 (23.6%) | 3: n=5 (4.7%) | 4: n=2 (1.9%)
5,ant_medico,Chi-Square,0.3161,G0vG1: 1.000 | G0vG2: 1.000 | G0vG3: 1.000 | G1vG2: 1.000 | G1vG3: 0.528 | G2vG3: 1.000,-1: n=87 (79.8%) | 1: n=17 (15.6%) | 3: n=5 (4.6%),-1: n=94 (71.2%) | 1: n=31 (23.5%) | 3: n=7 (5.3%),-1: n=88 (79.3%) | 1: n=20 (18.0%) | 3: n=3 (2.7%),-1: n=86 (81.1%) | 1: n=18 (17.0%) | 3: n=1 (0.9%) | 5: n=1 (0.9%)

In [53]:
import os
import json

# ── EXPORTACIÓN DE LOS ÍNDICES 1 Y 2 DE top3_kmedoids ─────────────────────────
indices_exportar = [1, 2]   # posiciones en top3_kmedoids (0-based)

os.makedirs("exportaciones_kmedoids", exist_ok=True)

for idx in indices_exportar:

    row             = top3_kmedoids.iloc[idx]
    k_actual        = int(row['k'])
    vars_clustering = list(row['variables'])
    sil_score       = float(row['silhouette'])

    nombre_combo = f"combo_{idx}_k{k_actual}_sil{sil_score:.4f}"
    print(f"\n{'='*60}")
    print(f"EXPORTANDO POSICIÓN {idx}  |  K={k_actual}  |  Silhouette={sil_score:.4f}")
    print(f"Variables de clustering: {vars_clustering}")

    # ── 1. RE-EJECUTAR EL CLUSTERING ──────────────────────────────────────────
    sil, labels = evaluar_kmedoids(df_clean, vars_clustering, k_actual)

    # ── 2. ASIGNACIÓN DE CLUSTER A CADA PACIENTE ──────────────────────────────
    mapa = pd.DataFrame({'id': df_clean['id'].values, 'cluster': labels})

    df_base = df_maestro.loc[:, ~df_maestro.columns.duplicated()].copy()
    if 'cluster' in df_base.columns:
        df_base = df_base.drop(columns=['cluster'])
    df_pacientes = pd.merge(df_base, mapa, on='id', how='inner')

    # ── 3. METADATOS ───────────────────────────────────────────────────────────
    distribucion = df_pacientes['cluster'].value_counts().sort_index().to_dict()
    metadata = {
        "posicion_en_top3_kmedoids": idx,
        "modelo":                    "K-Medoids (PAM, distancia Gower)",
        "k":                         k_actual,
        "silhouette_score":          sil_score,
        "variables_clustering":      vars_clustering,
        "n_pacientes_total":         len(df_pacientes),
        "distribucion_clusters":     distribucion,
    }

    # ── 4. ORDENAR COLUMNAS ────────────────────────────────────────────────────
    cols_ordenadas = (
        ['id', 'cluster']
        + vars_clustering
        + [c for c in df_pacientes.columns
           if c not in ['id', 'cluster'] + vars_clustering]
    )
    cols_ordenadas = [c for c in cols_ordenadas if c in df_pacientes.columns]
    df_export = df_pacientes[cols_ordenadas].sort_values(['cluster', 'id']).reset_index(drop=True)

    # ── 5. GUARDAR ARCHIVOS ────────────────────────────────────────────────────

    # 5a. CSV con todos los pacientes
    ruta_csv = f"exportaciones_kmedoids/{nombre_combo}_pacientes.csv"
    df_export.to_csv(ruta_csv, index=False)
    print(f"  → Pacientes guardados: {ruta_csv}")

    # 5b. Excel: una hoja por cluster
    ruta_excel = f"exportaciones_kmedoids/{nombre_combo}_por_cluster.xlsx"
    with pd.ExcelWriter(ruta_excel, engine='openpyxl') as writer:

        df_export.to_excel(writer, sheet_name="TODOS", index=False)

        for g in sorted(df_export['cluster'].unique()):
            df_grupo = df_export[df_export['cluster'] == g].reset_index(drop=True)
            df_grupo.to_excel(writer, sheet_name=f"Cluster_{g}", index=False)

        pd.DataFrame([metadata]).T.reset_index().rename(
            columns={'index': 'campo', 0: 'valor'}
        ).to_excel(writer, sheet_name="METADATOS", index=False)

    print(f"  → Excel guardado:     {ruta_excel}")

    # 5c. JSON con metadatos
    ruta_json = f"exportaciones_kmedoids/{nombre_combo}_metadata.json"
    with open(ruta_json, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2, default=str)
    print(f"  → Metadata guardada:  {ruta_json}")

    # ── 6. RESUMEN EN PANTALLA ─────────────────────────────────────────────────
    print(f"\n  Distribución de clusters:")
    for g, n in distribucion.items():
        print(f"    Cluster {g}: {n} pacientes")

============================================================
EXPORTANDO POSICIÓN 1  |  K=2  |  Silhouette=0.9740
Variables de clustering: ['trastorno_hipertensivo', 'ratio_MoM']
  → Pacientes guardados: exportaciones_kmedoids/combo_1_k2_sil0.9740_pacientes.csv
  → Excel guardado:     exportaciones_kmedoids/combo_1_k2_sil0.9740_por_cluster.xlsx
  → Metadata guardada:  exportaciones_kmedoids/combo_1_k2_sil0.9740_metadata.json

  Distribución de clusters:
    Cluster 0: 132 pacientes
    Cluster 1: 326 pacientes

============================================================
EXPORTANDO POSICIÓN 2  |  K=2  |  Silhouette=0.9637
Variables de clustering: ['trastorno_hipertensivo', 'sflt1_MoM']
  → Pacientes guardados: exportaciones_kmedoids/combo_2_k2_sil0.9637_pacientes.csv
  → Excel guardado:     exportaciones_kmedoids/combo_2_k2_sil0.9637_por_cluster.xlsx
  → Metadata guardada:  exportaciones_kmedoids/combo_2_k2_sil0.9637_metadata.json

  Distribución de clusters:
    Cluster 0: 326 pacientes
    Cluster 1: 132 pacientes

# Clustering con HDBSCAN

Con HDBSCAN no se hacen k clusters, sino que se analiza la estructura de densidad de los datos y determina cuántos clusters existen de forma natural.

Como los clusters no tienen por qué tener forma circular en el espacio, no tiene sentido aplicar la métrica Silhouette, por lo que aplicarmos Estabilidad Media Relativa.

In [43]:
%pip install hdbscan gower
import hdbscan

Requirement already satisfied: hdbscan in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.8.42)
Requirement already satisfied: gower in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (0.1.2)
Requirement already satisfied: numpy<3,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan) (1.26.4)
Requirement already satisfied: scipy>=1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan) (1.7.2)
Requirement already satisfied: joblib>=1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from hdbscan) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn>=1.6->hdbscan) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

Este código tiene min_cluster_size = 25, 30, 40. Esto obliga a que cada grupo tenga al menos 25, 30 o 40 personas. De esta manera no salen muchísimos grupos. Si se quieren sacar más grupos hay que disminuir el tamaño de los clústeres. El código está preparado para disminuir el tamaño y mostrar los p-valores 2 a 2 fácilmente (porque al aumentar la cantidad de grupos aumentan también las combinaciones 2 a 2)

In [44]:
# 1. PREPARACIÓN Y LIMPIEZA
vars_clustering = [
    'peso_ini_gest', 'peso_fin_gest', 'aumento_peso_gest', 'talla', 'imc_ini_gest', 
    'peso_rn', 'apgar_1min', 'apgar_5min', 'apgar_10min', 'eg_parto', 
    'sflt1_MoM', 'tas_1tri', 'tad_1tri', 'edad_materna_gest', 'plgf_MoM', 'ratio_MoM', 
    'ant_obstetrico', 'ant_medico', 'trastorno_hipertensivo', 
    'comp_placentaria', 'comp_maternaGrave', 'comp_metabolica'
]

vars_disponibles = [v for v in vars_clustering if v in df_maestro.columns]
df_clean = df_maestro.dropna(subset=vars_disponibles).copy()
vars_finales = [v for v in vars_disponibles if df_clean[v].nunique() > 1]

# Forzar tipos numéricos para evitar conflictos en la matriz de Gower
for v in vars_finales:
    df_clean[v] = pd.to_numeric(df_clean[v], errors='coerce').fillna(0)

# 2. FUNCIÓN DE EVALUACIÓN (Métrica de Estabilidad)
def evaluar_hdbscan_estabilidad(df_input, vars_list, min_samples):
    X = df_input[vars_list].copy().astype(np.float64)
    cat_features = [v in variables_categoricas for v in vars_list]
    
    # Matriz de Gower
    dist_matrix = gower.gower_matrix(X, cat_features=cat_features).astype(np.float64)
    
    # HDBSCAN: min_cluster_size=100 asegura que los grupos detectados tengan >= 100 personas
    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_samples, 
        metric='precomputed', 
        gen_min_span_tree=True
    )
    labels = clusterer.fit_predict(dist_matrix)
    
    # Conteos de grupos (Cluster -1 = Ruido)
    counts = pd.Series(labels).value_counts().sort_index().to_dict()
    
    labels_sin_ruido = labels[labels != -1]
    if len(np.unique(labels_sin_ruido)) < 2:
        return 0.0, labels, counts
    
    # Métrica de estabilidad basada en la persistencia de los clusters
    score_estabilidad = np.mean(clusterer.cluster_persistence_)
    return score_estabilidad, labels, counts

# 3. BÚSQUEDA DE LAS TOP 3 COMBINACIONES
def buscar_top3_hdbscan(df_input, samples_range, candidate_vars):
    all_results = []
    for m in samples_range:
        print(f"\n> Explorando HDBSCAN (min_cluster_size={m})...")
        tested_combinations = []
        current_vars = []
        remaining = list(candidate_vars)
        
        while remaining:
            step_scores = []
            for var in remaining:
                temp_vars = current_vars + [var]
                try:
                    if len(temp_vars) < 2:
                        score, labels, counts = 0.0, [], {}
                    else:
                        score, labels, counts = evaluar_hdbscan_estabilidad(df_input, temp_vars, m)
                    
                    # Guardamos los resultados incluyendo Estabilidad y Conteos (n)
                    tested_combinations.append({
                        'min_samples': m, 
                        'estabilidad': score, 
                        'n_grupos': counts,
                        'num_vars': len(temp_vars),
                        'variables': list(temp_vars)
                    })
                    step_scores.append((score, var))
                except: continue
            
            if not step_scores: break
            step_scores.sort(key=lambda x: x[0], reverse=True)
            best_score, best_var = step_scores[0]
            
            if best_score <= 0 and len(current_vars) > 0: break # Evitar bucles infinitos si no hay estabilidad
            
            current_vars.append(best_var)
            remaining.remove(best_var)
            if len(current_vars) > 1:
                print(f"  Paso {len(current_vars)}: +{best_var:<25} | Estabilidad: {best_score:.4f}")

        # Top 3 de este rango
        df_m = pd.DataFrame(tested_combinations).sort_values('estabilidad', ascending=False).head(3)
        all_results.append(df_m)
        
    return pd.concat(all_results, ignore_index=True) if all_results else pd.DataFrame()

# EJECUCIÓN (Filtro n >= 100)
top3_hdbscan = buscar_top3_hdbscan(df_clean, [100], vars_finales)

# 4. ANÁLISIS ESTADÍSTICO DETALLADO
print("\n" + "="*70)
print("RESUMEN Y ANÁLISIS ESTADÍSTICO HDBSCAN (n_min >= 100)")
print("="*70)

if not top3_hdbscan.empty:
    pd.set_option('display.max_colwidth', None)
    # Mostramos la tabla resumen inicial con la Estabilidad
    display(top3_hdbscan[['min_samples', 'estabilidad', 'n_grupos', 'num_vars', 'variables']])

    for idx, row in top3_hdbscan.iterrows():
        m_val = int(row['min_samples'])
        vars_sel = row['variables']
        est_val = row['estabilidad']
        conteos = row['n_grupos']
        
        # Formatear el n de los grupos reales (excluyendo ruido -1)
        n_str = ", ".join([f"G{k}: n={v}" for k, v in conteos.items() if k != -1])
        n_ruido = conteos.get(-1, 0)
        
        print(f"\n\n{'#'*100}")
        print(f"HDBSCAN TOP {idx+1} | Estabilidad: {est_val:.4f} | Tamaños: [{n_str}] | Ruido: n={n_ruido}")
        print(f"Variables: {vars_sel}")
        print(f"{'#'*100}")
        
        # Obtener etiquetas y mergear
        _, labels, _ = evaluar_hdbscan_estabilidad(df_clean, vars_sel, m_val)
        mapa = pd.DataFrame({'id': df_clean['id'], 'cluster': labels})
        df_base = df_maestro.loc[:, ~df_maestro.columns.duplicated()].copy()
        if 'cluster' in df_base.columns: df_base = df_base.drop(columns=['cluster'])
        df_final = pd.merge(df_base, mapa, on='id', how='inner')
        
        # Solo analizamos clusters reales (n >= 100, no ruido)
        df_stats = df_final[df_final['cluster'] != -1].copy()
        clusters_reales = sorted(df_stats['cluster'].unique())
        
        if len(clusters_reales) < 2:
            print("No hay suficientes clusters válidos para análisis estadístico.")
            continue

        for nombre_bloque, vars_bloque in grupos_informe.items():
            v_existentes = [v for v in vars_bloque if v in df_stats.columns]
            data_stats = []
            for v in v_existentes:
                if v not in ['id', 'ID']:
                    try:
                        res = realizar_analisis_avanzado(df_stats, v, 'cluster')
                        if res: data_stats.append(res)
                    except: continue
            
            if data_stats:
                print(f"\n{nombre_bloque}")
                num_col_tot = len(data_stats[0])
                headers_fijos = ["Variable", "Test", "p-valor (Total)", "p-valor (dos a dos)"]
                headers_dinamicos = headers_fijos + [f"G{i}" for i in range(num_col_tot - len(headers_fijos))]
                
                df_res_completo = pd.DataFrame(data_stats, columns=headers_dinamicos)
                display(df_res_completo.drop(columns=["p-valor (dos a dos)"]).style.set_caption(f"Estadísticos: {nombre_bloque}"))
else:
    print("No se encontraron combinaciones que cumplan el requisito de 100 pacientes por grupo.")

> Explorando HDBSCAN (min_cluster_size=100)...
  Paso 2: +trastorno_hipertensivo    | Estabilidad: 0.4165
  Paso 3: +plgf_MoM                  | Estabilidad: 0.4299
  Paso 4: +comp_metabolica           | Estabilidad: 0.4151
  Paso 5: +sflt1_MoM                 | Estabilidad: 0.3837
  Paso 6: +ratio_MoM                 | Estabilidad: 0.3538
  Paso 7: +apgar_5min                | Estabilidad: 0.3279

======================================================================
RESUMEN Y ANÁLISIS ESTADÍSTICO HDBSCAN (n_min >= 100)
======================================================================

,min_samples,estabilidad,n_grupos,num_vars,variables
0,100,0.429904,"{0: 132, 1: 326}",3,"[peso_ini_gest, trastorno_hipertensivo, plgf_MoM]"
1,100,0.424115,"{0: 132, 1: 326}",3,"[peso_ini_gest, trastorno_hipertensivo, tad_1tri]"
2,100,0.416520,"{0: 132, 1: 326}",2,"[peso_ini_gest, trastorno_hipertensivo]"

####################################################################################################
HDBSCAN TOP 1 | Estabilidad: 0.4299 | Tamaños: [G0: n=132, G1: n=326] | Ruido: n=0
Variables: ['peso_ini_gest', 'trastorno_hipertensivo', 'plgf_MoM']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

ECOCARDIOGRAFÍA

TA, CARÓTIDA Y OFTÁLMICA

ANALÍTICA

SCORES CATEGÓRICOS

ANTECEDENTES

####################################################################################################
HDBSCAN TOP 2 | Estabilidad: 0.4241 | Tamaños: [G0: n=132, G1: n=326] | Ruido: n=0
Variables: ['peso_ini_gest', 'trastorno_hipertensivo', 'tad_1tri']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

ECOCARDIOGRAFÍA

TA, CARÓTIDA Y OFTÁLMICA

ANALÍTICA

SCORES CATEGÓRICOS

ANTECEDENTES

####################################################################################################
HDBSCAN TOP 3 | Estabilidad: 0.4165 | Tamaños: [G0: n=132, G1: n=326] | Ruido: n=0
Variables: ['peso_ini_gest', 'trastorno_hipertensivo']
####################################################################################################

GESTACIÓN Y BIOMARCADORES

ECOCARDIOGRAFÍA

TA, CARÓTIDA Y OFTÁLMICA

ANALÍTICA

SCORES CATEGÓRICOS

ANTECEDENTES